### ISSUE TITLE
System tray not rendering - fail with error

### ISSUE THREAD

**Issue by jagguli** [qtile/qtile#1009]
```
2017-02-14 14:46:50,164 libqtile manager.py:<lambda>():L261  Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/site-packages/libqtile/manager.py", line 1155, in f
    func(*args)
  File "/usr/lib/python3.6/site-packages/libqtile/bar.py", line 294, in _actual_draw
    i.draw()
  File "/usr/lib/python3.6/site-packages/libqtile/widget/systray.py", line 193, in draw
    None
  File "/usr/lib/python3.6/site-packages/libqtile/window.py", line 486, in place
    self.window.configure(**kwarg)
  File "/usr/lib/python3.6/site-packages/libqtile/xcbq.py", line 580, in configure
    return self.conn.conn.core.ConfigureWindow(self.wid, mask, values)
  File "/usr/lib/python3.6/site-packages/xcffib/xproto.py", line 2670, in ConfigureWindow
    buf.write(struct.pack("=i", y))
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

**Comment by flacjacket** [comment]
What versions of everything are you using? qtile master should work with xcffib 0.5.0, but the most recent qtile release probably needs 0.4.2 or earlier. I guess this is a good reason for me to actually get a release together :P

**Comment by jagguli** [comment]
this is on 0.10.6

xcbq.py:
```
    def configure(self, **kwargs):
        """
        Arguments can be: x, y, width, height, border, sibling, stackmode
        """
        mask, values = ConfigureMasks(**kwargs)
        # hack for negative numbers
        #values = [i & 0xffffffff for i in values]
        return self.conn.conn.core.ConfigureWindow(self.wid, mask, values)

```

the hack for negative numbers is the culprit,

**Comment by flacjacket** [comment]
Yep, that's been fixed in master eb519eacda710a4012fbcbf494956aa017cc036d I'll work on getting a new version out. For now, you can stay with xcffib 0.4 / xcb 1.11 and you'll be ok

**Comment by jagguli** [comment]
I'm on arch this broke after I did an update, anyways commenting out the hack works for me.

**Comment by flacjacket** [comment]
With everything up-to-date (xcb 1.12, xcffib 0.5.1, qtile 0.10.7), this should now be fixed.
