### ISSUE TITLE
Can't start qtile

### ISSUE THREAD

**Issue by Bonnee** [qtile/qtile#1037]
I have just installed qtile under Debian Jessie and I'm getting this error when trying to start it:
```
Traceback (most recent call last):
  File "/usr/local/bin/qtile", line 9, in <module>
    load_entry_point('qtile==0.10.7', 'console_scripts', 'qtile')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/qtile-0.10.7-py2.7.egg/libqtile/__init__.py", line 39, in <module>
    import asyncio  # noqa
  File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
```
I have followed and repeated the installation guide in the docs with no luck. I also tried installing the dev version from GH vs the pip version I originally installed.

**Comment by flacjacket** [comment]
On Python 2, I don't think you should have asyncio installed, try
uninstalling that and installing trollius

**Comment by Bonnee** [comment]
That fixed it, thanks for the quick reply! I thought that installing all the packages in the docs wouldn't hurt, but I was wrong..

**Comment by flacjacket** [comment]
Great, glad you have it working!
