### ISSUE TITLE
qtile-top format strings seem busted

### ISSUE THREAD

**Issue by tych0** [qtile/qtile#1050]
```
qtile-top
Traceback (most recent call last):
  File "/usr/local/bin/qtile-top", line 9, in <module>
    load_entry_point('qtile==0.10.7', 'console_scripts', 'qtile-top')()
  File "/usr/local/lib/python3.5/dist-packages/qtile-0.10.7-py3.5.egg/libqtile/scripts/qtile_top.py", line 162, in main
    force_start=force_start)
  File "/usr/lib/python3.5/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/qtile-0.10.7-py3.5.egg/libqtile/scripts/qtile_top.py", line 88, in get_stats
    scr.addstr(0, 0, "Qtile - Top {0:s} lines".format(limit))
ValueError: Unknown format code 's' for object of type 'int'
```

**Comment by frostidaho** [comment]
It should be fixed in the development branch
https://github.com/qtile/qtile/issues/1017

**Comment by tych0** [comment]
Oh, good call. Thanks!
