### ISSUE TITLE
Gentoo 9999 package is broken (SandboxViolation)

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#1093]
`x11-wm/qtile-9999` is broken for some time now. It still updates the sources, so it's not as bad as it looks.

Here is the emerge output:

```
ramnes@saiga :0 ~ sudo emerge -av qtile

 * IMPORTANT: 1 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


These are the packages that would be merged, in order:

Calculating dependencies                                 ... done!      
[ebuild   R   *] x11-wm/qtile-9999::gentoo  USE="{-test}" PYTHON_TARGETS="python2_7 python3_4 python3_5*" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

Would you like to merge these packages? [Yes/No] 
>>> Verifying ebuild manifests
>>> Emerging (1 of 1) x11-wm/qtile-9999::gentoo
>>> Failed to emerge x11-wm/qtile-9999, Log file:
>>>  '/var/tmp/portage/x11-wm/qtile-9999/temp/build.log'
>>> Jobs: 0 of 1 complete, 1 failed                 Load avg: 1.04, 1.01, 0.89
 * Package:    x11-wm/qtile-9999
 * Repository: gentoo
 * Maintainer: radhermit@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python2_7 python_targets_python3_4 python_targets_python3_5 userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
 * Fetching https://github.com/qtile/qtile.git ...
git fetch https://github.com/qtile/qtile.git +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/x11-wm/qtile/0/__main__ refs/git-r3/HEAD
 * Checking out https://github.com/qtile/qtile.git to /var/tmp/portage/x11-wm/qtile-9999/work/qtile-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://github.com/qtile/qtile.git
   at the commit:            dc7c43a80429b3096c685968586baa1f9e0db132
>>> Source unpacked in /var/tmp/portage/x11-wm/qtile-9999/work
>>> Preparing source in /var/tmp/portage/x11-wm/qtile-9999/work/qtile-9999 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/x11-wm/qtile-9999/work/qtile-9999 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/x11-wm/qtile-9999/work/qtile-9999 ...
 * python2_7: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python2.7 setup.py build
warning: no previously-included files found matching 'xcffib/_ffi.py'
Traceback (most recent call last):
  File "setup.py", line 160, in <module>
    'libqtile/ffi_build.py:xcursors_ffi',
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib64/python2.7/site-packages/setuptools/dist.py", line 335, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib64/python2.7/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 863, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1141, in best_match
    return self.obtain(req, installer)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1153, in obtain
    return installer(requirement)
  File "/usr/lib64/python2.7/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 698, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with error: SandboxViolation: mkdir('/var/tmp/portage/x11-wm/qtile-9999/work/qtile-9999-python2_7/lib/xcffib', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

 * ERROR: x11-wm/qtile-9999::gentoo failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called src_compile
 *   environment, line 3273:  Called distutils-r1_src_compile
 *   environment, line 1060:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
 *   environment, line  361:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2804:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2106:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2104:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line  790:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
 *   environment, line 1051:  Called distutils-r1_python_compile
 *   environment, line  926:  Called esetup.py 'build'
 *   environment, line 1319:  Called die
 * The specific snippet of code:
 *       "${@}" || die "${die_args[@]}";
 * 
 * If you need support, post the output of `emerge --info '=x11-wm/qtile-9999::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=x11-wm/qtile-9999::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/x11-wm/qtile-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/x11-wm/qtile-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/x11-wm/qtile-9999/work/qtile-9999'
 * S: '/var/tmp/portage/x11-wm/qtile-9999/work/qtile-9999'

 * Messages for package x11-wm/qtile-9999:

 * ERROR: x11-wm/qtile-9999::gentoo failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called src_compile
 *   environment, line 3273:  Called distutils-r1_src_compile
 *   environment, line 1060:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
 *   environment, line  361:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2804:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2106:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2104:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line  790:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
 *   environment, line 1051:  Called distutils-r1_python_compile
 *   environment, line  926:  Called esetup.py 'build'
 *   environment, line 1319:  Called die
 * The specific snippet of code:
 *       "${@}" || die "${die_args[@]}";
 * 
 * If you need support, post the output of `emerge --info '=x11-wm/qtile-9999::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=x11-wm/qtile-9999::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/x11-wm/qtile-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/x11-wm/qtile-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/x11-wm/qtile-9999/work/qtile-9999'
 * S: '/var/tmp/portage/x11-wm/qtile-9999/work/qtile-9999'
 * 
 * The following package has failed to build, install, or execute postinst:
 * 
 *  (x11-wm/qtile-9999:0/0::gentoo, ebuild scheduled for merge), Log file:
 *   '/var/tmp/portage/x11-wm/qtile-9999/temp/build.log'
 * 
```

**Comment by ramnes** [comment]
Ping @radhermit.

**Comment by flacjacket** [comment]
It looks like you need to be sure you have the required xcffib version `>=0.5.0`, and the latest version `0.5.1` is available in portage.

**Comment by ramnes** [comment]
Nice catch, thanks! It's there but it's keyworded as unstable; `x11-wm/qtile-9999` should require it.

**Comment by radhermit** [comment]
Thanks, it's now fixed in Gentoo.
