### ISSUE TITLE
Cannot import config file because of some dbus errors

### ISSUE THREAD

**Issue by Sweenu** [qtile/qtile#1115]
I'm facing a problem I never had and I have no idea how to fix it. I do realize it's not a Qtile problem but if anyone has any idea on what causes the problem, that would really help!

The two DBus errors are:
`dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name`
and
`dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files`

But here's the full log:
```
[0m[33m2018-01-07 08:49:21,415 [1m[33mlibqtile log_utils.py:init_log():L120 [0m Starting logging for Qtile[0m
[0m[31m2018-01-07 08:49:21,611 [1m[31mlibqtile confreader.py:from_file():L85 [0m Could not import config file '/home/sweenu/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtile-0.10.7-py3.6.egg/libqtile/confreader.py", line 81, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/sweenu/.config/qtile/config.py", line 13, in <module>
    notify2.init('myself')
  File "/usr/lib/python3.6/site-packages/notify2.py", line 103, in init
    '/org/freedesktop/Notifications')
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files[0m
[0m[31m2018-01-07 08:49:21,612 [1m[31mlibqtile qtile.py:make_qtile():L107 [0m Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtile-0.10.7-py3.6.egg/libqtile/confreader.py", line 81, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/sweenu/.config/qtile/config.py", line 13, in <module>
    notify2.init('myself')
  File "/usr/lib/python3.6/site-packages/notify2.py", line 103, in init
    '/org/freedesktop/Notifications')
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtile-0.10.7-py3.6.egg/libqtile/confreader.py", line 81, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/sweenu/.config/qtile/config.py", line 13, in <module>
    notify2.init('myself')
  File "/usr/lib/python3.6/site-packages/notify2.py", line 103, in init
    '/org/freedesktop/Notifications')
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtile-0.10.7-py3.6.egg/libqtile/scripts/qtile.py", line 105, in make_qtile
    config = confreader.Config.from_file(options.configfile)
  File "/usr/lib/python3.6/site-packages/qtile-0.10.7-py3.6.egg/libqtile/confreader.py", line 87, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtile-0.10.7-py3.6.egg/libqtile/confreader.py", line 81, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/sweenu/.config/qtile/config.py", line 13, in <module>
    notify2.init('myself')
  File "/usr/lib/python3.6/site-packages/notify2.py", line 103, in init
    '/org/freedesktop/Notifications')
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
[0m
```

**Comment by ramnes** [comment]
It may help to know which OS you're running on, as well as the versions of `python-dbus` and `dbus`.

**Comment by Sweenu** [comment]
Sorry, I'm using Arch with python-dbus 1.2.4 and dbus 1.12.2.
I've been using Qtile for more than a year without this problem. Rebooted my computer today and had that...

**Comment by Sweenu** [comment]
I feel pretty stupid...
I thought Qtile maybe needed the Notification DBus in order to import the config file for some reason. But it was actually because I use the notify2 library inside my config file and for some reason, my notification daemon (dunst) wasn't working anymore. 
Reinstalling dunst was the solution.
