### ISSUE TITLE
Exception in Max layout

### ISSUE THREAD

**Issue by nazar-pc** [qtile/qtile#1150]
Found this in my log, not really sure why this happened, but it did:

```
2018-03-02 14:56:35,928 ERROR libqtile group.py:layoutAll():L163 Exception in layout Max
Traceback (most recent call last):
  File "/web/github/qtile/libqtile/group.py", line 160, in layoutAll
    self.layout.layout(normal, screen)
  File "/web/github/qtile/libqtile/layout/base.py", line 57, in layout
    self.configure(i, screen)
  File "/web/github/qtile/libqtile/layout/max.py", line 57, in configure
    client.hide()
  File "/web/github/qtile/libqtile/window.py", line 417, in hide
    self.window.unmap()
  File "/web/github/qtile/libqtile/xcbq.py", line 741, in unmap
    self.conn.conn.core.UnmapWindowChecked(self.wid).check()
  File "/home/nazar-pc/.local/lib/python3.6/site-packages/xcffib/__init__.py", line 328, in check
    self.conn.request_check(self.sequence)
  File "/home/nazar-pc/.local/lib/python3.6/site-packages/xcffib/__init__.py", line 558, in wrapper
    return f(*args)
  File "/home/nazar-pc/.local/lib/python3.6/site-packages/xcffib/__init__.py", line 667, in request_check
    self._process_error(err)
  File "/home/nazar-pc/.local/lib/python3.6/site-packages/xcffib/__init__.py", line 635, in _process_error
    raise error(buf)
xcffib.xproto.WindowError
```

**Comment by jagguli** [comment]
@nazar-pc did you manage to fix or workaround this?

**Comment by nazar-pc** [comment]
No, I didn't

**Comment by tych0** [comment]
I think this basically means that a window was created, and then destroyed all before the configure() method completed; in this case (for the max layout), it looks basically harmless. We could wrap the hide/unhide() in max's configure() with a try/except, or perhaps we should switch unmap() to use the unchecked flavor to avoid the exception all together.

**Comment by tych0** [comment]
Gonna close this per the above fix.
