### ISSUE TITLE
VersionConflict - using qtile 0.10.7 but looking for 0.11.1

### ISSUE THREAD

**Issue by ricardovsilva** [qtile/qtile#1166]
I'm using ubuntu 17.10, tried to install qtile using apt install.
I tried to run qtile directly from terminal and it is throwing the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 972, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 863, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (qtile 0.10.7 (/usr/lib/python3/dist-packages), Requirement.parse('qtile==0.11.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/qtile", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 660, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 673, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 858, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'qtile==0.11.1' distribution was not found and is required by the application
```

**Comment by flacjacket** [comment]
It looks like you are running `qtile` from a locally installed version in `/usr/local/bin`, I would guess that the package installed version would be coming from `/usr/bin`. Did you install qtile from source or with pip before? The two installations may be conflicting. You could try running `/usr/bin/qtile` if it exists.

**Comment by ricardovsilva** [comment]
Yes, I was using ubuntu 16.04 and installed through pip, but I cannot get it to run. So I updated my ubuntu to 17.10 and installed through apt get.
I tried now to run from /usr/bin/qtile and got the exception below:
```
2018-04-06 10:49:07,543 libqtile manager.py:_xpoll():L758  Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/libqtile/manager.py", line 723, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3/dist-packages/xcffib/__init__.py", line 558, in wrapper
    return f(*args)
  File "/usr/lib/python3/dist-packages/xcffib/__init__.py", line 599, in poll_for_event
    return self.hoist_event(e)
  File "/usr/lib/python3/dist-packages/xcffib/__init__.py", line 672, in hoist_event
    return self._process_error(ffi.cast("xcb_generic_error_t *", e))
  File "/usr/lib/python3/dist-packages/xcffib/__init__.py", line 635, in _process_error
    raise error(buf)
xcffib.xproto.MatchError
```

**Comment by flacjacket** [comment]
Hmm, that's really interesting, what versions are you running of everything? Qtile and xcffib

**Comment by ricardovsilva** [comment]
@flacjacket can you please tell me the commands to get those versions?

**Comment by flacjacket** [comment]
You can look at the xcffib version by importing it and looking at `xcffib.__version__`. It doesn't look like qtile has a way to get the installed version...

**Comment by ricardovsilva** [comment]
@flacjacket on python 2.7 the xcffib version is **0.6.0** and on python 3.6.3 the xcffib version is *placeholder* (???)

**Comment by flacjacket** [comment]
Hmm, that leads me to think there is an issue with how xcffib was installed on Python 3. How did you install that? If you do `xcffib.__file__`, what does that give you?
