### ISSUE TITLE
fails to display after resume from suspend while monitor powered off

### ISSUE THREAD

**Issue by bdjnk** [qtile/qtile#1168]
**Steps to reproduce:**
1. Suspend your machine to RAM (I used `systemctl suspend`)
2. Power off the monitor (or perhaps monitors, but I'm only using one)
3. Resume from suspend, waiting for it to finish
4. Power back on the monitor

**Expectation:** The monitor displays Qtile in all its glory.

**Reality:** The monitor can't find any input and enters power saving mode.

**Additional information:**

- Qtile is still running and keyboard events are being listened to, since if I suspend from a terminal I can up-arrow and re-suspend
- I haven't discovered any way to re-establish the connection to the monitor, though I have tried:
  - re-suspending and re-resuming with the monitor powered on
  - mod-ctrl-r to restart Qtile
  - mucking about with qshell

The following possibly relevant error fills my `qtile.log`:

```
ERROR libqtile manager.py:_xpoll():L781 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/libqtile/manager.py", line 746, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.6/site-packages/xcffib/__init__.py", line 566, in wrapper
    return f(*args)
  File "/usr/lib/python3.6/site-packages/xcffib/__init__.py", line 607, in poll_for_event
    return self.hoist_event(e)
  File "/usr/lib/python3.6/site-packages/xcffib/__init__.py", line 680, in hoist_event
    return self._process_error(ffi.cast("xcb_generic_error_t *", e))
  File "/usr/lib/python3.6/site-packages/xcffib/__init__.py", line 643, in _process_error
    raise error(buf)
xcffib.xproto.MatchError
```

**Comment by ramnes** [comment]
Can you SSH to your computer and try to run something like `DISPLAY=:0 xrandr` when the monitor down?

**Comment by bdjnk** [comment]
`DISPLAY=:0 xrandr` with the abovementioned situation outputs:
```
Screen 0: minimum 8 x 8, current 3840 x 2160, maximum 16384 x 16384
DVI-I-0 disconnected primary (normal left inverted right x axis y axis)
DVI-I-1 disconnected (normal left inverted right x axis y axis)
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 connected (normal left inverted right x axis y axis)
   3840x2160     30.00 +
   2560x1440     59.95  
   1920x1080     60.00    59.94  
   1600x900      60.00  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00    59.94  
   1152x864      59.96  
   1024x768      60.00  
   800x600       60.32  
   720x480       59.94  
   640x480       59.94    59.93  
DP-1 disconnected (normal left inverted right x axis y axis)
DVI-D-0 disconnected (normal left inverted right x axis y axis)
```

It appears the error I mentioned does nor occur in conjunction with the situation in question.

**Comment by ramnes** [comment]
So it seems that your monitor is listed but no resolution is selected, right?

Is the resolution that you usually select in the list?

**Comment by bdjnk** [comment]
Yes, I usually used the preferred resolution, the highest.

Running `xrandr --output DP-0 --auto` blind in the terminal emulator causes Qtile to display again!

**Comment by ramnes** [comment]
With the correct resolution?

Anyway, could that be something wrong with DPMS and/or DisplayPort?
