### ISSUE TITLE
"Exception in poll loop" spamming my qtile log

### ISSUE THREAD

**Issue by TauPan** [qtile/qtile#1196]
I get a like 10 of these message every second, which causes my qtile log to grow and qtile uses around 80% cpu.

(Upon cursory check, this looks different than the other "Exception in poll loop" issues here.)

(Not sure what changed about my system configuration. We had a driver switch from nouveau to nvidia recently, no idea if that's relevant.)

I've updated to develop this morning and the problem persists.

Also xtrace is a bit hard to find these days. I managed to pull the tarball from https://alioth-archive.debian.org/git/xtrace/ , unpack it and then clone from there. (https://github.com/deepfire/xtrace doesn't seem current.)

I have a more extensive xtrace log, if needed. Below are just two examples.

```python
000:>:122aa: Event ConfigureRequest(23) parent=0x00000294 window=0x02400003 value-mask=x,y stack-mode=Above(0x00) sibling=None(0x00000000) x=2983 y=1710 width=57 height=52 border-width=0
000:<:122ab: 32: Request(12): ConfigureWindow window=0x02400003 values={x=4063 y=2254 width=0 height=0 border-width=0}
000:<:122ac: 44: Request(25): SendEvent propagate=false(0x00) destination=0x02400003 event-mask=StructureNotify ConfigureNotify(22) event=0x02400003 window=0x02400003 above-sibling=None(0x00000000) x=4063 y=2254 width=0 height=0 border-width=0 override-redirect=false(0x00)
000:>:22ab:Error 2=Value: major=12, minor=0, bad=0
000:>:122ac: Event (generated) ConfigureNotify(22) event=0x02400003 window=0x02400003 above-sibling=None(0x00000000) x=4063 y=2254 width=0 height=0 border-width=0 override-redirect=false(0x00)
[0m[31m2018-08-01 09:50:43,163 [1m[31mlibqtile manager.py:_xpoll():L752 [0m Got an exception in poll loop
Traceback (most recent call last):
  File "/home/taupan/nobackup/anon-vc/qtile/libqtile/manager.py", line 718, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/home/taupan/nobackup/virtualenvs/qtile/lib/python2.7/site-packages/xcffib/__init__.py", line 558, in wrapper
    return f(*args)
  File "/home/taupan/nobackup/virtualenvs/qtile/lib/python2.7/site-packages/xcffib/__init__.py", line 599, in poll_for_event
    return self.hoist_event(e)
  File "/home/taupan/nobackup/virtualenvs/qtile/lib/python2.7/site-packages/xcffib/__init__.py", line 672, in hoist_event
    return self._process_error(ffi.cast("xcb_generic_error_t *", e))
  File "/home/taupan/nobackup/virtualenvs/qtile/lib/python2.7/site-packages/xcffib/__init__.py", line 635, in _process_error
    raise error(buf)
ValueError[0m
000:>:122ac: Event ConfigureRequest(23) parent=0x00000294 window=0x02400003 value-mask=x,y stack-mode=Above(0x00) sibling=None(0x00000000) x=2983 y=1727 width=57 height=52 border-width=0
000:<:122ad: 32: Request(12): ConfigureWindow window=0x02400003 values={x=4063 y=2271 width=0 height=0 border-width=0}
000:<:122ae: 44: Request(25): SendEvent propagate=false(0x00) destination=0x02400003 event-mask=StructureNotify ConfigureNotify(22) event=0x02400003 window=0x02400003 above-sibling=None(0x00000000) x=4063 y=2271 width=0 height=0 border-width=0 override-redirect=false(0x00)
000:>:22ad:Error 2=Value: major=12, minor=0, bad=0
000:>:122ae: Event (generated) ConfigureNotify(22) event=0x02400003 window=0x02400003 above-sibling=None(0x00000000) x=4063 y=2271 width=0 height=0 border-width=0 override-redirect=false(0x00)
000:>:122ae: Event ConfigureRequest(23) parent=0x00000294 window=0x02400003 value-mask=x,y stack-mode=Above(0x00) sibling=None(0x00000000) x=2983 y=1710 width=57 height=52 border-width=0
[0m[31m2018-08-01 09:50:43,164 [1m[31mlibqtile manager.py:_xpoll():L752 [0m Got an exception in poll loop
Traceback (most recent call last):
  File "/home/taupan/nobackup/anon-vc/qtile/libqtile/manager.py", line 718, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/home/taupan/nobackup/virtualenvs/qtile/lib/python2.7/site-packages/xcffib/__init__.py", line 558, in wrapper
    return f(*args)
  File "/home/taupan/nobackup/virtualenvs/qtile/lib/python2.7/site-packages/xcffib/__init__.py", line 599, in poll_for_event
    return self.hoist_event(e)
  File "/home/taupan/nobackup/virtualenvs/qtile/lib/python2.7/site-packages/xcffib/__init__.py", line 672, in hoist_event
    return self._process_error(ffi.cast("xcb_generic_error_t *", e))
  File "/home/taupan/nobackup/virtualenvs/qtile/lib/python2.7/site-packages/xcffib/__init__.py", line 635, in _process_error
    raise error(buf)
ValueError[0m
000:<:122af: 32: Request(12): ConfigureWindow window=0x02400003 values={x=4063 y=2254 width=0 height=0 border-width=0}
000:<:122b0: 44: Request(25): SendEvent propagate=false(0x00) destination=0x02400003 event-mask=StructureNotify ConfigureNotify(22) event=0x02400003 window=0x02400003 above-sibling=None(0x00000000) x=4063 y=2254 width=0 height=0 border-width=0 override-redirect=false(0x00)
000:>:22af:Error 2=Value: major=12, minor=0, bad=0
000:>:122b0: Event (generated) ConfigureNotify(22) event=0x02400003 window=0x02400003 above-sibling=None(0x00000000) x=4063 y=2254 width=0 height=0 border-width=0 override-redirect=false(0x00)
000:>:122b0: Event ConfigureRequest(23) parent=0x00000294 window=0x02400003 value-mask=x,y stack-mode=Above(0x00) sibling=None(0x00000000) x=2983 y=1727 width=57 height=52 border-width=0
[0m[31m2018-08-01 09:50:43,164 [1m[31mlibqtile manager.py:_xpoll():L752 [0m Got an exception in poll loop
```

**Comment by TauPan** [comment]
This does not happen any more. Since this occured briefly after a package upgrade relating to X11 drivers and libraries, I assume something was botched in the installation on that day. Sorry for the noise.
