### ISSUE TITLE
from qtile 0.12.0 ModuleNotFoundError: No module named 'xcffib._ffi'

### ISSUE THREAD

**Issue by ericbsd** [qtile/qtile#1214]
xcffib is installed but _ffi is missing.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 161, in <module>
    'libqtile/ffi_build.py:xcursors_ffi',
  File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
    k: v for k, v in attrs.items()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
    ep.load()(self, ep.name, value)
  File "/usr/local/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 204, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/usr/local/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/usr/local/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 25, in execfile
    exec(code, glob, glob)
  File "libqtile/ffi_build.py", line 26, in <module>
    from cairocffi.ffi_build import ffi as cairocffi_ffi
  File "/usr/local/lib/python3.6/site-packages/cairocffi/__init__.py", line 18, in <module>
    from ._ffi import ffi
  File "/usr/local/lib/python3.6/site-packages/cairocffi/_ffi.py", line 3, in <module>
    from xcffib._ffi import ffi as _ffi0
ModuleNotFoundError: No module named 'xcffib._ffi'
```
```
 ! %  ~/P/f/p/x/qtile  python3.6 -c "import cairocffi"                                                                     787ms  Fri Oct 19 09:00:55 2018
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/cairocffi/__init__.py", line 18, in <module>
    from ._ffi import ffi
  File "/usr/local/lib/python3.6/site-packages/cairocffi/_ffi.py", line 3, in <module>
    from xcffib._ffi import ffi as _ffi0
ModuleNotFoundError: No module named 'xcffib._ffi'
```
```
 ! %  ~/P/f/p/x/qtile  python3.6 -c "import xcffib._ffi"                                                                   241ms  Fri Oct 19 09:03:46 2018
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'xcffib._ffi'
 ! %  ~/P/f/p/x/qtile  python3.6 -c "import xcffib"                                                                        220ms  Fri Oct 19 09:03:48 2018
 %  ~/P/f/p/x/qtile 

```

**Comment by ericbsd** [comment]
Ah install xcffib from pip fix the problem
