### ISSUE TITLE
Giving a list to Screen(top=...) makes Qtile hang

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#1230]
[The documentation says](http://docs.qtile.org/en/latest/manual/config/screens.html#screen) that we can give a list to `top`, `bottom`, `left` and `right` parameters of `Screen`, but in fact, `qtile` hangs and fail to complete its initialization if we do so.

**Comment by ramnes** [comment]
Related traceback, should be pretty easy to fix:

```
Traceback (most recent call last):
  File "/usr/bin/qtile", line 11, in <module>
    load_entry_point('qtile==0.10.7', 'console_scripts', 'qtile')()
  File "/usr/lib/python3/dist-packages/libqtile/scripts/qtile.py", line 127, in main
    q = make_qtile()
  File "/usr/lib/python3/dist-packages/libqtile/scripts/qtile.py", line 121, in make_qtile
    state=options.state,
  File "/usr/lib/python3/dist-packages/libqtile/manager.py", line 195, in __init__
    self._process_screens()
  File "/usr/lib/python3/dist-packages/libqtile/manager.py", line 406, in _process_screens
    self.groups[i],
  File "/usr/lib/python3/dist-packages/libqtile/config.py", line 270, in _configure
    self.setGroup(group)
  File "/usr/lib/python3/dist-packages/libqtile/config.py", line 338, in setGroup
    new_group._setScreen(self)
  File "/usr/lib/python3/dist-packages/libqtile/group.py", line 179, in _setScreen
    rect = self.screen.get_rect()
  File "/usr/lib/python3/dist-packages/libqtile/config.py", line 305, in get_rect
    return ScreenRect(self.dx, self.dy, self.dwidth, self.dheight)
  File "/usr/lib/python3/dist-packages/libqtile/config.py", line 284, in dy
    return self.y + self.top.size if self.top else self.y
AttributeError: 'list' object has no attribute 'size'
```

**Comment by ramnes** [comment]
Yeah, let's close this.

https://github.com/qtile/qtile/pull/1387#issuecomment-616213348
