### ISSUE TITLE
Clock: Required argument 'tz' (pos 1) not found

### ISSUE THREAD

**Issue by kamilchm** [qtile/qtile#1258]
I can't get working Clock after upgrade to 0.13. I use:
```
widget.Clock(format='%Y-%m-%d %a %H:%M'),
```
or
```
widget.Clock(format='%Y-%m-%d %a %H:%M', timezone='Europe/Warsaw'),
```
and I get the following error:
```
Traceback (most recent call last):
  File "/nix/store/vws161bihzlcxbiq17h63wdcdg12vrsc-python2.7-trollius-2.2/lib/python2.7/site-packages/trollius/events.py", line 136, in _run
    self._callback(*self._args)
  File "/nix/store/mpi5ibr3xajzqqsaiyb885pywl269bg9-qtile-0.13.0/lib/python2.7/site-packages/libqtile/manager.py", line 1197, in f
    func(*args)
  File "/nix/store/mpi5ibr3xajzqqsaiyb885pywl269bg9-qtile-0.13.0/lib/python2.7/site-packages/libqtile/widget/base.py", line 428, in timer_setup
    update_interval = self.tick()
  File "/nix/store/mpi5ibr3xajzqqsaiyb885pywl269bg9-qtile-0.13.0/lib/python2.7/site-packages/libqtile/widget/clock.py", line 76, in tick
    self.update(self.poll())
  File "/nix/store/mpi5ibr3xajzqqsaiyb885pywl269bg9-qtile-0.13.0/lib/python2.7/site-packages/libqtile/widget/clock.py", line 91, in poll
    return self._get_time()
  File "/nix/store/mpi5ibr3xajzqqsaiyb885pywl269bg9-qtile-0.13.0/lib/python2.7/site-packages/libqtile/widget/clock.py", line 83, in _get_time
    now = datetime.now(utc).astimezone()
TypeError: Required argument 'tz' (pos 1) not found
```

**Comment by bronsen** [comment]
I get the same error.

It appeared with version 0.13.0

**Comment by ramnes** [comment]
Argh, what a mess. This is due to 4a1cb18 (see #1170 for rationale), which I only tested against Python 3, relying on the test suite for Python 2. Apparently we clearly lack a proper test case here. Python 2 requires a `tz` argument for `astimezone` whereas Python 3 consider no argument as "use the local timezone".

**Comment by kamilchm** [comment]
Works fine with Python 3.

**Comment by ramnes** [comment]
Thanks for the bug report @kamilchm!
