### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#1273]
I follow the instructions and give me this error. Installed with the command sudo python3 setup.py install, if i want to install with sudo python setup.py install give me a  install error 

```
2019-01-28 20:58:45,173 libqtile confreader.py:from_file():L102  Could not import config file '/home/cr1ogen/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'
2019-01-28 20:58:45,173 libqtile qtile.py:make_qtile():L111  Error while reading config file (Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'
)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/scripts/qtile.py", line 109, in make_qtile
    config = confreader.Config.from_file(kore, options.configfile)
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 104, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'
```

**Comment by flacjacket** [comment]
This looks like a problem from running qtile, not installing it, right?

It looks like it is unable to find the `config.py` file, but it should then fall back to a default config. Is there any more context for this error? What is the command you used to get this error?

**Comment by cr1ogen** [comment]
I have it installed, but I do not know how to make an error file, I ran it in a command window. The configuration file in my home I do not have it and I tried it with the one that comes by default anyway it gives me configuration error in the bar below. Maybe it's a problem of compiling python in Debian

**Comment by flacjacket** [comment]
What command line did you run it in? Generally you need to run qtile through X, either using your display manager (such as GDM or SDDM) see [1] or you can put `exec qtile` in your `~/.xinitrc` and run `startx` from a tty screen.

[1] http://docs.qtile.org/en/latest/manual/config/index.html#starting-qtile

**Comment by flacjacket** [comment]
Oh that's interesting, we should try to get your log then, definitely. It
should be in `~/.local/share/qtile.log`.

**Comment by cr1ogen** [comment]
My file in ~/.local/share/qtile.log 

`2019-01-31 23:55:29,183 ERROR libqtile confreader.py:from_file():L102 Could not import config file '/home/cr1ogen/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'
2019-01-31 23:55:29,209 ERROR libqtile qtile.py:make_qtile():L111 Error while reading config file (Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'
)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/scripts/qtile.py", line 109, in make_qtile
    config = confreader.Config.from_file(kore, options.configfile)
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 104, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'

2019-01-31 23:55:29,817 WARNING libqtile utils.py:safe_import():L192 Unmet dependencies for optional Widget: '.widget.mpdwidget.Mpd', No module named 'mpd'
2019-01-31 23:55:29,854 WARNING libqtile utils.py:safe_import():L192 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2019-01-31 23:55:29,886 WARNING libqtile utils.py:safe_import():L192 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2019-01-31 23:55:59,145 ERROR libqtile manager.py:cmd_spawn():L1503 failed spawn: "xterm"
[Errno 2] No existe el fichero o el directorio
2019-01-31 23:56:08,099 ERROR libqtile manager.py:_xpoll():L758 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/core/manager.py", line 736, in _xpoll
    r = h(e)
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/core/manager.py", line 1017, in handle_ButtonPress
    if m.start:
AttributeError: 'Drag' object has no attribute 'start'
2019-01-31 23:58:54,471 WARNING libqtile manager.py:finalize():L347 Restarting Qtile with os.execv(...)
2019-01-31 23:58:54,634 ERROR libqtile confreader.py:from_file():L102 Could not import config file '/home/cr1ogen/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'
2019-01-31 23:58:54,634 ERROR libqtile qtile.py:make_qtile():L111 Error while reading config file (Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'
)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/scripts/qtile.py", line 109, in make_qtile
    config = confreader.Config.from_file(kore, options.configfile)
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 104, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'

2019-01-31 23:58:54,705 WARNING libqtile utils.py:safe_import():L192 Unmet dependencies for optional Widget: '.widget.mpdwidget.Mpd', No module named 'mpd'
2019-01-31 23:58:54,706 WARNING libqtile utils.py:safe_import():L192 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2019-01-31 23:58:54,708 WARNING libqtile utils.py:safe_import():L192 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2019-01-31 23:59:41,709 ERROR libqtile confreader.py:from_file():L102 Could not import config file '/home/cr1ogen/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'
2019-01-31 23:59:41,709 ERROR libqtile qtile.py:make_qtile():L111 Error while reading config file (Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'
)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/scripts/qtile.py", line 109, in make_qtile
    config = confreader.Config.from_file(kore, options.configfile)
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 104, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.13.0-py3.7.egg/libqtile/confreader.py", line 98, in from_file
    config = __import__(os.path.basename(path)[:-3])
ModuleNotFoundError: No module named 'config'

2019-01-31 23:59:41,784 WARNING libqtile utils.py:safe_import():L192 Unmet dependencies for optional Widget: '.widget.mpdwidget.Mpd', No module named 'mpd'
2019-01-31 23:59:41,787 WARNING libqtile utils.py:safe_import():L192 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2019-01-31 23:59:41,793 WARNING libqtile utils.py:safe_import():L192 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
`

**Comment by cr1ogen** [comment]
Screenshot say error in systray, if I use a configuration in ~ / .config / qtile the same desktop appears and error

![2019-01-31-235655_3840x2160_scrot](https://user-images.githubusercontent.com/9537788/52100449-4f867c00-25b6-11e9-8c21-33116bdaa77f.png)

**Comment by flacjacket** [comment]
Alright, that is expected when there is a bad config, or seemingly a
missing config (?). Do you have that config.py file? What is in it?

**Comment by cr1ogen** [comment]
I don't have a file config.py in ~/.config/qtile

**Comment by zordsdavini** [comment]
In Arch 1st time started Qtile it does not copy default config to home
right location. You should do that manually. ~/.config/qtile/config.py

2019 m. vas. 1 d., pn 06:02 cr1ogen <notifications@github.com rašė:

**Comment by cr1ogen** [comment]
i copy default config manually and works.
 I close the claim, thank you very much
