### ISSUE TITLE
CurrentLayoutIcon Not Working

### ISSUE THREAD

**Issue by dustinlacewell** [qtile/qtile#1291]
As of `0.13.0` I'm unable to utilize the `CurrentLayoutIcon` in any of my `Bar`s.

```python
bottom_bar = bar.Bar([
    TextBox("??"),
    CurrentLayoutIcon(foreground='#ff0000'),
    TextBox("!!"),
    CurrentLayout(foreground='#ff0000'),
    widgets.windowname,
    widgets.observers,
    widget.Pomodoro(
        num_pomodori=2,
        length_long_break=10,
        fmt="🍅%s",
        prefix_inactive="",
        prefix_paused="⏹️️",
        prefix_break="⏸",
        prefix_long_break="⏸",
    ),
    widgets.clock,
], bar_height)
```

You can see that Bar rendering ends after the `"??"` `TextBox`:

![2019-03-04-20-30-21](https://user-images.githubusercontent.com/53952/53761008-0f9f0700-3e8a-11e9-9a99-8b2da71ed8a7.png)

Removing the `CurrentLayoutIcon` you can see everything works as normal:

![2019-03-04-20-29-23](https://user-images.githubusercontent.com/53952/53760974-f5fdbf80-3e89-11e9-939e-56a5b9c21ae3.png)

The only stuff in the log that might be relevant is:

```
2019-03-04 14:30:48,487 ERROR libqtile manager.py:<lambda>():L282 Got an exception in poll loop
Traceback (most recent call last):
  File "/nix/store/yv4pzx3lxk3lscq0pw3hqzs7k4x76xsm-python3-3.7.2/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/nix/store/s2gxzwwgqpc8idnzrccgrm4h52g2l98j-qtile-0.13.0/lib/python3.7/site-packages/libqtile/manager.py", line 1197, in f
    func(*args)
  File "/nix/store/s2gxzwwgqpc8idnzrccgrm4h52g2l98j-qtile-0.13.0/lib/python3.7/site-packages/libqtile/bar.py", line 294, in _actual_draw
    i.draw()
  File "/nix/store/s2gxzwwgqpc8idnzrccgrm4h52g2l98j-qtile-0.13.0/lib/python3.7/site-packages/libqtile/widget/currentlayout.py", line 155, in draw
    self.drawer.draw(offsetx=self.offset, width=self.length)
  File "/nix/store/s2gxzwwgqpc8idnzrccgrm4h52g2l98j-qtile-0.13.0/lib/python3.7/site-packages/libqtile/drawer.py", line 315, in draw
    self.height if height is None else height
  File "/nix/store/pfp06k5lw156m7w1xa0f1qg3x3qkf12j-python3.7-xcffib-0.6.0/lib/python3.7/site-packages/xcffib/xproto.py", line 3034, in CopyArea
    buf.write(struct.pack("=xx2xIIIhhhhHH", src_drawable, dst_drawable, gc, src_x, src_y, dst_x, dst_y, width, height))
struct.error: required argument is not an integer
```

**Comment by flacjacket** [comment]
This seems to be working fine on the current master. Can you try with that? I know we dropped old Python support. If that is an issue, what version are you running?

**Comment by osimplex** [comment]
Working fine on my end: Qtile 0.13 - Arch package.

```python
CurrentLayoutIcon(
	padding = 0,
	scale = 0.6
)
```
