### ISSUE TITLE
Freezing qtile 

### ISSUE THREAD

**Issue by zarMarco** [qtile/qtile#1318]
Hi all, I'm using qtile from two days, on my arch and my gentoo installation. I use videocard integrate Intel 620. 
When I opened qtile and I opened some programs, especially with vscode, I have freezing as I can't move from one workspace to another, and I only can stop qtile if I go in tty and stopped qtile service. 
This is output in .local/share/qtile/qtile.log 

```
2019-05-06 09:18:12,376 ERROR libqtile manager.py:_xpoll():L749 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 719, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2019-05-06 09:18:12,376 ERROR libqtile manager.py:<lambda>():L282 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 719, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 750, in _xpoll
    self.stop()
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 800, in stop
    self.graceful_shutdown()
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 770, in graceful_shutdown
    pids = list(filter(lambda x: x is not None, pids))
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 768, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.7/site-packages/libqtile/xcbq.py", line 607, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.7/site-packages/libqtile/xcbq.py", line 714, in get_property
    0, (2 ** 32) - 1
  File "/usr/lib/python3.7/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 390, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2019-05-06 09:18:12,377 ERROR libqtile manager.py:_xpoll():L749 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 719, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2019-05-06 09:18:12,377 ERROR libqtile manager.py:<lambda>():L282 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 719, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 750, in _xpoll
    self.stop()
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 800, in stop
    self.graceful_shutdown()
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 770, in graceful_shutdown
    pids = list(filter(lambda x: x is not None, pids))
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 768, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.7/site-packages/libqtile/xcbq.py", line 607, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.7/site-packages/libqtile/xcbq.py", line 714, in get_property
    0, (2 ** 32) - 1
  File "/usr/lib/python3.7/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 390, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2019-05-06 09:18:12,378 ERROR libqtile manager.py:_xpoll():L749 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 719, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2019-05-06 09:18:12,378 ERROR libqtile manager.py:<lambda>():L282 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 719, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 750, in _xpoll
    self.stop()
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 800, in stop
    self.graceful_shutdown()
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 770, in graceful_shutdown
    pids = list(filter(lambda x: x is not None, pids))
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 768, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.7/site-packages/libqtile/xcbq.py", line 607, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.7/site-packages/libqtile/xcbq.py", line 714, in get_property
    0, (2 ** 32) - 1
  File "/usr/lib/python3.7/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 390, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2019-05-06 09:18:12,379 ERROR libqtile manager.py:_xpoll():L749 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 719, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2019-05-06 09:18:12,379 ERROR libqtile manager.py:<lambda>():L282 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 719, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 750, in _xpoll
    self.stop()
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 800, in stop
    self.graceful_shutdown()
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 770, in graceful_shutdown
    pids = list(filter(lambda x: x is not None, pids))
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 768, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.7/site-packages/libqtile/xcbq.py", line 607, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.7/site-packages/libqtile/xcbq.py", line 714, in get_property
    0, (2 ** 32) - 1
  File "/usr/lib/python3.7/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 390, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2019-05-06 09:18:12,380 ERROR libqtile manager.py:_xpoll():L749 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 719, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2019-05-06 09:18:12,380 ERROR libqtile manager.py:<lambda>():L282 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 719, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 750, in _xpoll
    self.stop()
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 800, in stop
    self.graceful_shutdown()
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 770, in graceful_shutdown
    pids = list(filter(lambda x: x is not None, pids))
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 768, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.7/site-packages/libqtile/xcbq.py", line 607, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.7/site-packages/libqtile/xcbq.py", line 714, in get_property
    0, (2 ** 32) - 1
  File "/usr/lib/python3.7/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 390, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2019-05-06 09:18:12,380 ERROR libqtile manager.py:_xpoll():L749 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 719, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 558, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
```

**Comment by zordsdavini** [comment]
it looks like https://github.com/qtile/qtile/issues/1326 , too. Have you solved the issue?

**Comment by zarMarco** [comment]
Yes, I had had a problem with two layout . When I erased those layouts I hadn't had problems

**Comment by ramnes** [comment]
Glad to know you got this fixed, @zarMarco! Can you give more details? Like which layouts where causing this?

**Comment by tych0** [comment]
I'll go ahead and close this for now; if you could let us know which layouts were that would be great :)
