### ISSUE TITLE
closing windows seems to be broken with xcffib.xproto.WindowError

### ISSUE THREAD

**Issue by jagguli** [qtile/qtile#1325]
Closing an window also throws errors 

my env is broken right now, I was using the git version on arch, switched to the release version issue still exists. So I'm guessing its something related to xcffib? 

I'm on archlinux tried upgrading also.

```
File "/home/steven/.config/qtile/extra.py", line 179, in __call__
    qtile.current_screen.cmd_toggle_group(self.name)
  File "/usr/lib/python3.7/site-packages/libqtile/config.py", line 406, in cmd_toggle_group
    self.set_group(group)
  File "/usr/lib/python3.7/site-packages/libqtile/config.py", line 324, in set_group
    old_group._set_screen(None)
  File "/usr/lib/python3.7/site-packages/libqtile/group.py", line 183, in _set_screen
    self.hide()
  File "/usr/lib/python3.7/site-packages/libqtile/group.py", line 191, in hide
    i.hide()
  File "/usr/lib/python3.7/site-packages/libqtile/window.py", line 422, in hide
    self.window.unmap()
  File "/usr/lib/python3.7/site-packages/libqtile/core/xcbq.py", line 744, in unmap
    self.conn.conn.core.UnmapWindowChecked(self.wid).check()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 338, in check
    self.conn.request_check(self.sequence)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 570, in wrapper
    return f(*args)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 679, in request_check
    self._process_error(err)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 647, in _process_error
    raise error(buf)
xcffib.xproto.WindowError
```

**Comment by jagguli** [comment]
```
2019-06-01 02:22:08,031 libqtile group.py:layout_all():L163  Exception in layout max
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/group.py", line 160, in layout_all
    self.layout.layout(normal, screen)
  File "/usr/lib/python3.7/site-packages/libqtile/layout/base.py", line 57, in layout
    self.configure(i, screen)
  File "/usr/lib/python3.7/site-packages/libqtile/layout/max.py", line 58, in configure
    client.hide()
  File "/usr/lib/python3.7/site-packages/libqtile/window.py", line 422, in hide
    self.window.unmap()
  File "/usr/lib/python3.7/site-packages/libqtile/core/xcbq.py", line 744, in unmap
    self.conn.conn.core.UnmapWindowChecked(self.wid).check()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 338, in check
    self.conn.request_check(self.sequence)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 570, in wrapper
    return f(*args)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 679, in request_check
    self._process_error(err)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 647, in _process_error
    raise error(buf)
xcffib.xproto.WindowError
```

**Comment by jagguli** [comment]
Can someone please help me with this, my config completely broken by this

**Comment by jagguli** [comment]
related: https://github.com/qtile/qtile/issues/1150

**Comment by jagguli** [comment]
downgrading to 'xcffib<0.8.0' fixes the issue

**Comment by ramnes** [comment]
Good to know, thanks for the debug @jagguli. @tych0, any idea on what could cause this?

**Comment by tych0** [comment]
I commented on the other bug, but I think the second one is mostly harmless.

As for the first, it again seems like a race, unless it always happens with the same kind of window?

**Comment by tych0** [comment]
xcffib 0.8.0 only has a few small changes on top of 0.7.0. However, they could result in fairly large speedups, and so we may end up surfacing more races like this. They're mostly benign, and perhaps we should just go through and switch to unchecked calls everywhere it makes sense to dodge this sort of thing.

**Comment by jagguli** [comment]
ok try catch in the unmap solves the issue.

**Comment by jagguli** [comment]
Unfortunately this is still an issue, I think the error message was unrelated to the actual bug which is window still hangs around after closing.

**Comment by jagguli** [comment]
the issue here is the window is not being removed from the group.

this is because the removed window is coming through as `Static` instead of `Window`.

**Comment by jagguli** [comment]
ok found the issue it was related to an issue in one of my hooks that set the window as static. not sure what changed to cause that to break, I'll update this if I find it. thx.
