### ISSUE TITLE
Improvement : overview of keyboard shortcuts

### ISSUE THREAD

**Issue by erikdubois** [qtile/qtile#1329]
I was wondering if something like this already exists and if not ...
Will you consider in making this available?
An overview of all keyboard shortcuts from the config.py.

Something like this on Awesome
![arcolinux-awesome-keyboard-shortcuts](https://user-images.githubusercontent.com/10594806/58653122-554a5f00-8315-11e9-86c8-3cc9475cc154.jpg)

or 

something like this on Ubuntu
![ubuntu](https://user-images.githubusercontent.com/10594806/58653141-5f6c5d80-8315-11e9-953c-94563116267e.jpg)

That would be just great.

**Comment by ramnes** [comment]
Hey @erikdubois :wave: 

That would be very nice, indeed. Contributions welcome!

**Comment by erikdubois** [comment]
Indeed - if someone can contribute that would be great... Not me though. All my time goes into the development of ArcoLinux ;-)

**Comment by krive001** [comment]
Update suggestion from manager.py
cmd_display_kb function.
![ArcoLinuxD_2019_06_01_13_37_51](https://user-images.githubusercontent.com/24889940/58749258-17b81400-8484-11e9-902b-46ce044466f4.jpg)

manager.py lines
def cmd_display_kb(self, *args):
        """Display table of key bindings"""
        class FormatTable(object):
            def __init__(self):
                self.max_col_size = []
                self.rows = []

            def add(self, row):
                n = len(row) - len(self.max_col_size)
                if n > 0:
                    self.max_col_size += [0] * n
                for i, f in enumerate(row):
                    if len(f) > self.max_col_size[i]:
                        self.max_col_size[i] = len(f)
                self.rows.append(row)

            def getformat(self):
                format_string = (" | ".join(
                                 "%-{0:d}s".format(max_col_size)
                                 for max_col_size in self.max_col_size))
                return format_string + "\n", len(self.max_col_size)

            def expandlist(self, list, n):
                if not list:
                    return ["+" * max_col_size
                            for max_col_size in self.max_col_size]
                n -= len(list)
                if n > 0:
                    list += [""] * n
                return list

            def __str__(self):
                format, n = self.getformat()
                return ("".join([format % tuple(self.expandlist(row, n))
                                 for row in self.rows]))

        result = FormatTable()
        result.add(["Mod+" + "KeySym", "Description"])
        result.add([])
        rows = []
        for (ks, kmm), k in self.keyMap.items():
            if not k.commands:
                continue
            name = "".join(xcbq.rkeysyms.get(ks, ("<unknown>", )))
            modifiers = "+".join(utils.translate_modifiers(kmm))
            if modifiers == "":
                sas = name
            else:
                sas = modifiers + "+" + name
            desc = k.desc
            rows.append((sas, desc))
        rows.sort()
        for row in rows:
            result.add(row)
        return str(result)

    def cmd_list_widgets(self):
        """List of all addressible widget names"""
        return list(self.widgetMap.keys())

**Comment by m-col** [comment]
I started working on this. This is where I'm at. This window is toggled with a keybinding:
![200417-104734](https://user-images.githubusercontent.com/44536113/79556473-a7f94a80-8090-11ea-8597-74826e842dd2.png)
I just need to format keybinding text nicely into the window (mostly inspired by that Ubuntu one).

**Comment by zordsdavini** [comment]
for me it would be the best way terminal output and then `spawn('st -e qtile --keybindings')` bind to <M-S-/> (M-?)

**Comment by pawamoy** [comment]
The terminal way would be the easiest one: just echo the keybindings nicely, and spawn a "frozen" terminal with the command echoing them, though I like the idea of having a native Qtile window showing up. What kind of window is this @m-col?

**Comment by m-col** [comment]
> What kind of window is this @m-col?

It's one of [these](https://github.com/m-col/qtools/blob/master/qtools/__init__.py#L109). A terminal would work too (and would be possible anyway) but IMO the ubuntu window is the most professional looking and it's not that much code to create the windows.

**Comment by lh0n** [comment]
How far along is this implementation? I can't wait for it to land. :-)

I keep opening my config file just to check keybindings I forgot. :-D

How could I use the new Popup class for a quick-hack type of solution? I know a bit of python but I'm not familiar with qtile's codebase.

**Comment by m-col** [comment]
TBH I got bored of working on it and stopped. IIRC 'all' it needs is robust formatting of the binding information within the window. Here is some code if anyone wants to work on it:

```
from libqtile import configurable, hook, images, pangocffi, utils, popup, qtile
from libqtile.lazy import lazy
from libqtile.log_utils import logger
from libqtile.notify import notifier
from libqtile.backend.x11 import xcbq

class KbdOverview(configurable.Configurable):
    defaults = [
        ('x', None, 'x position. Defaults to centering on screen.'),
        ('y', None, 'y position. Defaults to centering on screen.'),
        ('width', None, 'Width in pixels. Defaults to 75% screen width.'),
        ('height', None, 'Height in pixels. Defaults to 75% screen height.'),
        ('foreground', '#ffffff', 'Text colour.',),
        ('background', '#111111', 'Background colour.',),
        ('border', '#111111', 'Border colours. Or None for none.',),
        ('border_width', 4, 'Line width of borders.'),
        ('opacity', 1.0, 'Window opacity. Requires compositor.'),
        ('corner_radius', None, 'Corner radius for round corners, or None.'),
        ('font', 'sans', 'Font.'),
        ('font_size', 14, 'Size of font.'),
        ('font_shadow', None, 'Color for text shadows, or None for no shadows.'),
    ]

    def __init__(self, **config):
        configurable.Configurable.__init__(self, **config)
        self.add_defaults(KbdOverview.defaults)
        self._window = None
        self._shown = False
        hook.subscribe.startup_complete(self.configure)

    def configure(self):
        if self.border_width:
            self.border = qtile.color_pixel(self.border)  # this will need updating
        if self.width is None:
            self.width = int(qtile.screens[0].width * 6/8)
        if self.height is None:
            self.height = int(qtile.screens[0].height * 6/8)
        if self.x is None:
            self.x = int(qtile.current_screen.width * 1/8)
        if self.y is None:
            self.y = int(qtile.current_screen.height * 1/8)

        popup_config = {}
        for opt in popup.Popup.defaults:
            key = opt[0]
            if hasattr(self, key):
                popup_config[key] = getattr(self, key)

        self._window = popup.Popup(
            qtile, **popup_config, x=self.x, y=self.y, width=self.width, height=self.height
        )
        self._window.win.handle_ButtonPress = self._button_press
        self._window.clear()

        # title
        self._window.layout.font_size = 24
        self._window.text = 'Keyboard Shortcuts'        
        self._window.draw_text(y=28, x=(self._window.width / 2) - (self._window.layout.width / 2))
        self._window.drawer.draw_hbar(
            self.foreground + '.5', self.width * 1/8, self.width * 7/8, 76
        )

        # binding information should go here
        self._window.layout.font_size = self.font_size
        self._text = 'one\ntwo\nthree'
        for num, line in enumerate(self._text.split('\n')):
            self._window.text = line
            y = 72 + num * self._window.layout.height
            self._window.draw_text(y=y)

    def _button_press(self, event):
        if event.detail == 1:
            self.hide()

    def toggle(self):
        if self._shown:
            self.hide()
        else:
            self.show()

    def hide(self):
        self._window.hide()
        self._shown = False

    def show(self, qtile=None):
        self._window.unhide()
        self._window.draw()
        self._shown = True
```

I would import this from a file or something, then do `kbdoverview = KbvOverview()` and bind a key to `lazy.function(kbdoverview.toggle)`, for example.

**Comment by m-col** [comment]
Note that I wrote that with an older version of qtile so it will need changes.

**Comment by ramnes** [comment]
For those who use rofI, I ended up doing this, which is super ugly but works:

```python
Key([mod], "k", lazy.spawn('python -c "print(`qtile cmd-obj -o cmd -f display_kb`)" | rofi -dmenu', shell=True)),
```

And user NaBaCo on IRC did this, to make things look better:

```python
def show_keys():
    key_help = ""
    for k in keys:
        mods = ""

        for m in k.modifiers:
            if m == "mod4":
                mods += "Super + "
            else:
                mods += m.capitalize() + " + "

        if len(k.key) > 1:
            mods += k.key.capitalize()
        else:
            mods += k.key

        key_help += "{:<30} {}".format(mods, k.desc + "\n")

    return key_help

keys.extend([Key([mod], "F1", lazy.spawn("sh -c 'echo \"" + show_keys() + "\" | rofi -dmenu -i -mesg \"Keyboard shortcuts\"'"), desc="Print keyboard bindings"),])
```

Which gives this (their picture):

![d43af704-f4ec-48f8-80d6-e4981cd24205](https://user-images.githubusercontent.com/835072/104315145-cb93d900-54da-11eb-88ee-a76eadd1e347.jpg)

**Comment by Barbarossa93** [comment]
Unfortunately the solution by NaBaCo doesn't work for me. I think this is the relevant error message in the logs:
```
2021-01-13 12:49:38,933 ERROR libqtile manager.py:process_key_event():L311 KB command error spawn: Traceback (most recent call last):
   File "/usr/lib/python3.9/site-packages/libqtile/command/interface.py", line 312, in call
     return SUCCESS, cmd(*args, **kwargs)
   File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 1102, in cmd_spawn
     args = shlex.split(cmd)
   File "/usr/lib/python3.9/shlex.py", line 315, in split
     return list(lex)
   File "/usr/lib/python3.9/shlex.py", line 300, in __next__
     token = self.get_token()
   File "/usr/lib/python3.9/shlex.py", line 109, in get_token
     raw = self.read_token()
   File "/usr/lib/python3.9/shlex.py", line 191, in read_token
     raise ValueError("No closing quotation")
 ValueError: No closing quotation
```

Quotations all look good to me. I am running the latest qtile-git, so maybe that code only works for the last release?

**Comment by pawamoy** [comment]
Could there be a single or double quote in one of your keys description?

**Comment by Barbarossa93** [comment]
Oof, yes, there was one single quote out of all of my keybindings. Thanks for pointing that out!

**Comment by nixfu** [comment]
When I run this on 0.17.1.dev
`qtile cmd-obj -o cmd -f d`

I get this errori:
`error: Sorry cannot run function 'display_kb' with arguments []`

Any ideas?

**Comment by ep12** [comment]
> When I run this on 0.17.1.dev
> `qtile cmd-obj -o cmd -f display_kb`
> 
> I get this errori:
> `error: Sorry cannot run function 'display_kb' with arguments []`
> 
> Any ideas? Does the command require arguments now?

@nixfu That is #2247 which could be fixed soon via #2308.

**Comment by LaurentOngaro** [comment]
For those who are interested, this is an improved version of the code by @ramnes that shows keybindings printed in a rofi/dmenu window. 

You could add some keys to ignore and some texts to replace. 

```python
def show_keys(keys):
  """
  print current keybindings in a pretty way for a rofi/dmenu window.
  """
  key_help = ""
  keys_ignored = (
      "XF86AudioMute",  #
      "XF86AudioLowerVolume",  #
      "XF86AudioRaiseVolume",  #
      "XF86AudioPlay",  #
      "XF86AudioNext",  #
      "XF86AudioPrev",  #
      "XF86AudioStop",
  )
  text_replaced = {
      "mod4": "[S]",  #
      "control": "[Ctl]",  #
      "mod1": "[Alt]",  #
      "shift": "[Shf]",  #
      "twosuperior": "²",  #
      "less": "<",  #
      "ampersand": "&",  #
      "Escape": "Esc",  #
      "Return": "Enter",  #
  }
  for k in keys:
    if k.key in keys_ignored:
      continue

    mods = ""
    key = ""
    desc = k.desc.title()
    for m in k.modifiers:
      if m in text_replaced.keys():
        mods += text_replaced[m] + " + "
      else:
        mods += m.capitalize() + " + "

    if len(k.key) > 1:
      if k.key in text_replaced.keys():
        key = text_replaced[k.key]
      else:
        key = k.key.title()
    else:
      key = k.key

    key_line = "{:<30} {}".format(mods + key, desc + "\n")
    key_help += key_line

    # debug_print(key_line)  # debug only

  return key_help
```
and this function is mapped to a key by adding the following line in config.py

```python
# this must be done AFTER all the keys have been defined
keys.extend(
    [Key([mod], "F1", lazy.spawn("sh -c 'echo \"" + show_keys(keys) + "\" | rofi -dmenu -i -mesg \"Keyboard shortcuts\"'"), desc="Print keyboard bindings")]
)
```
My next work will be to parse the keys definition to generate a conky file that could be displayed when qtile starts (for an arcolinux distro , it will generate the ~.config/qtile/scripts/system-overview file automatically)

You can find the whole qtile config I use and where this code come from in my [dotfile repo](https://gitlab.com/linuxdev_gameamea/dotfiles/-/tree/BigDaddyArco_ArcoLinux_Qtile/.config/qtile)

**Comment by pushp1997** [comment]
Hey everyone!

I have extended @m-col's [work](https://github.com/qtile/qtile/issues/1329#issuecomment-742868703)  till here:

![Screenshot-2021-06-15-23_42_01](https://user-images.githubusercontent.com/19623154/122103219-ff7d7c80-ce33-11eb-9de7-f4ad1670e2a1.jpg)

The keybindings which are missing the `desc` do not have description displayed!

More work that is to be done:
- [ ]  Better formatting (ofc!)
- [ ]  Add ability to scroll

Please, feel free to tell me if I should add something to the list. Peace ✌🏽

**Comment by pushp1997** [comment]
Hey @m-col can you point me to a doc on how to enable scrolling on popups? I searched on Qtile docs but couldn't find anything!

**Comment by m-col** [comment]
The popups are very basic windows without any functionality built on top of them, including input handling, so if you want to do something when there is a scroll event then you'll have to manually implement. This isn't actually as involved as it sounds, though.

Check out what `Popup` is doing here: https://github.com/qtile/qtile/blob/master/libqtile/popup.py#L71. When the underlying `Internal` window receives a mouse button (incl. scrolling) it will call `self.process_button_click`. By default this does nothing, it's there to be overriden like `Popup` is doing here, allowing `Popup` to catch those events and do what it wants with them. So if you replace that method with your own thing:
```py
popup.win.process_button_click = your_method_here
```
then you can get the coordinates and button code.

From there you'd need to update the contents and re-draw the window/text e.g. if each keybinding is an entry in a big list then you'd just slide along the slice that you take from it and render those lines.

I hope this helps!

**Comment by wulfalpha** [comment]
It's not much but you can try my shell script. you just need to add Yad to the floating class.


```
#!/bin/bash

sed -n '/#HKeys/,/#HKeys-End/p' .config/qtile/sxhkd/sxhkdrc | grep -v '##'| grep -v '#-' | yad --text-info --back=#282c34 --fore=#46d9ff --geometry=1200x800
```

**Comment by Sidmaz666** [comment]
If this helps anyone https://github.com/Sidmaz666/qtile-rofi-keybindings.git
![preview](https://raw.githubusercontent.com/Sidmaz666/qtile-rofi-keybindings/main/qtile_keybinding_rofi_preview.gif)

**Comment by a2n-s** [comment]
I think I might have cracked this actually, using only `dmenu`.
At least it is a script that:

1. parses the output of `qtile cmd-obj -o cmd -f display_kb`
2. shows the keymap to the user through `dmenu`
3. let the user choose and execute one action

Fully FOS, so feel free to do whatever you want with that if you find it usefull!

Very inspiring thread, thanks guys, cheers :wave: :yum:

**Comment by elParaguayo** [comment]
> I'm just working on this if anyone is interested let me know and ping me, I'm hoping i can group commands but at the moment its in the order that they are in the config
> 
> ![image](https://user-images.githubusercontent.com/9284733/196229492-b237f8af-f172-493f-aca6-79906f9ff4ab.png)
> 
> PS. If anyone does want it if you use Key Chords then you would need to move them out of the main `keys = []` or it will not work :) I just add them instead of `keys.extend([])` instead of `keys = []`

FYI I've opened a pull request to add a `desc` attribute to KeyChords (#3900). The idea was that it would be useful for scripts like this.

**Comment by The-Repo-Club** [comment]
> > PS. If anyone does want it if you use Key Chords then you would need to move them out of the main `keys = []` or it will not work :) I just add them instead of `keys.extend([])` instead of `keys = []`
> 
> FYI I've opened a pull request to add a `desc` attribute to KeyChords (#3900). The idea was that it would be useful for scripts like this.

awesome that would be good :)

**Comment by The-Repo-Club** [comment]
> ```
> #!/bin/bash
> 
> sed -n '/#HKeys/,/#HKeys-End/p' .config/qtile/sxhkd/sxhkdrc | grep -v '##'| grep -v '#-' | yad --text-info --back=#282c34 --fore=#46d9ff --geometry=1200x800
> ```

[wm-cheat](https://github.com/The-Repo-Club/wm-cheat) this works well with i3 or sxhkd and can group the keybinds without using yad :) [image too big](https://user-images.githubusercontent.com/9284733/196264846-6a53e5ae-9189-42c9-9792-18dbdef82000.png) to put here. i would like to do the same thing with qtile and make qtile-cheat but need groups first

**Comment by The-Repo-Club** [comment]
I made the above function `show_keys(keys)` also save the output to a json then i made a 2nd script that can be ran that will then read the said json file and create a gtk app out of it.

I have worked hard after adding groups to my config.py inside the libqtile folder and now i can do some thing like this each tab at the top is a group

![1666109894](https://user-images.githubusercontent.com/9284733/196487516-85d1f3b1-5754-4e3e-a341-1741b761d79d.png)

**Comment by The-Repo-Club** [comment]
[`show_keys(keys)`](https://github.com/The-Repo-Club/DotFiles/blob/main/qtile/.config/qtile/config.py#L148) Function

[`qtile-cheat`](https://github.com/The-Repo-Club/DotFiles/blob/main/qtile/.config/qtile/scripts/qtile-cheat) GTK App

**Comment by jwijenbergh** [comment]
Here is my simple and short solution:

```python

# Add help key
keys_str = ""
for key in keys:
    keypress = key.modifiers + [key.key]
    keypress_str = "-".join(keypress)
    keys_str += keypress_str + ": " + key.desc + "\n"

help_desc = "Show qtile keys in rofi"
help_key = "slash"
keys_str += f"{mod}-{help_key}: {help_desc}"


def get_launcher_command(s, prompt, launcher):
    return {
        "shell": True,
        "cmd": f"echo -en '{s}' | {launcher} -dmenu -p '{prompt}'",
    }


keys.extend(
    [
        Key(
            [mod],
            help_key,
            lazy.spawn(**get_launcher_command(keys_str, "Qtile keys", launcher)),
            desc=help_desc,
        ),
    ]
)
```

![image](https://github.com/qtile/qtile/assets/46386452/92cac077-b4d1-4c03-8140-7db6e34b77bd)

**Comment by cben** [comment]
Seeing qtile already ships a "[Keybindings in images](https://docs.qtile.org/en/latest/manual/commands/keybindings.html) renderer, I wanted to try how well it works as cheatsheet.
```py
generated = False  # Reset at each reload.
@lazy.function
def display_kb_img(qtile):
    global generated
    if not generated:
        # Must NOT do this at top level, cause `gen-keybinding-img` evals this config.
        subprocess.check_call("~/WM/qtile/scripts/gen-keybinding-img --config ~/.config/qtile/config.py --output-dir ~/.config/qtile/", shell=True)
        generated = True

    images = "~/.config/qtile/{mod4,mod4-shift,mod4-control,mod4-mod1}.png" # pick your subset & order
    w, h = qtile.current_screen.width, qtile.current_screen.height
    if qtile.core.name == "wayland":
        # Kludge: cover 100% of screen to ensure keyboard focus
        qtile.spawn(f"swayimg --class=qtile-help --scale=fit --size={w},{h} {images}", shell=True)
    else:
        # On X, can size bit smaller to peek at window layout underneath (and figure what action I want), gets focus anyway
        qtile.spawn(f"feh --class=qtile-help --auto-zoom --geometry={w*80//100}x{h*80//100}+{w*10//100}+{h*10//100} {images}", shell=True)

...

    Key([mod], "slash", display_kb_img, desc="Help"),
    Key([mod, "shift"], "slash", display_kb_img, desc="Help"),

...

floating_layout = layout.Floating(
    float_rules=[
        ...
        Match(wm_class="qtile-help"),
```
First time it takes ~3sec to generate but later <kbd>Win+?</kbd> presses give me a near-instanteneous overlay (tried several viewers, swayimg opens _fast_), and I can <kbd>PgDn</kbd>/<kbd>PgUp</kbd> to switch images for different modifiers, <kbd>Esc</kbd> or <kbd>q</kbd> to close.  
floating allows it to pop up without disturbing existing layout — no matter which I had!

Well, I dunno.  The keyboard layout is pretty, but having to page makes it less information-dense than some thematically-grouped text solutions above. 🤷 🤔 

P.S. Shelling out to `gen-keybinding-img` just to have it re-import and parse the config is silly.  Ideally I'd would import and pass the in-process `qtile.config`, right now the script (even its file name) is not friendly to that 👀 

<img width="3840" height="2163" alt="Image" src="https://github.com/user-attachments/assets/8df7183b-cbb5-4f18-be28-3f6d7d6eacf6" />

**Comment by erikdubois** [comment]
we will write something - for now use the keybindings.txt
