### ISSUE TITLE
Qtile crash at startup

### ISSUE THREAD

**Issue by max-k** [qtile/qtile#1346]
Qtile crash almost every time I restart my computer.

If I restart only Qtile, everything is working properly.

System informations:

* Os: Archlinux
* Qtile : 0.13.0  - also tested with latest git version [commit a83257b7](https://github.com/qtile/qtile/commit/a83257b77af2aad1c263ae177e735ac9798b3938) -
* Python: 3.7.3
* Kernel: 5.1.10-hardened

Here is the log output:
```
2019-06-17 21:43:18,422 libqtile hook.py:fire():L371  Internal event: startup((), {})
2019-06-17 21:43:18,429 libqtile hook.py:fire():L371  Internal event: startup_complete((), {})
2019-06-17 21:43:18,430 libqtile ipc.py:start():L247  Starting server
2019-06-17 21:43:18,506 libqtile qtile.py:main():L131  Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/scripts/qtile.py", line 129, in main
    q.loop()
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 806, in loop
    self.server.start()
  File "/usr/lib/python3.7/site-packages/libqtile/ipc.py", line 248, in start
    self.server = self.loop.run_until_complete(server_coroutine)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 582, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
2019-06-17 21:43:18,509 libqtile qtile.py:main():L132  Exiting...
```

Symptoms are always the same, I get my screen layout but Qtile isn't responding.

**Comment by zordsdavini** [comment]
it looks the same as in https://github.com/qtile/qtile/issues/1326

**Comment by max-k** [comment]
I'll investigate a few days more but it seems fixed in Qtile 0.14.0.

**Comment by max-k** [comment]
In fact it's still not working.

**Comment by zordsdavini** [comment]
does it crash with default config?

**Comment by max-k** [comment]
Hi, I found where was the problem.

It came from an old hook (still documented [here](http://docs.qtile.org/en/latest/manual/ref/hooks.html#libqtile.hook.subscribe.screen_change)) I took from official documentation.

I think it was triggered at startup preventing Qtile to start properly.

I disabled it and everything is working again.

**Comment by max-k** [comment]
I'm sorry but in fact, the problem didn't come from here.

Here is a new debug output log:

```
2019-07-10 18:36:43,239 libqtile log_utils.py:init_log():L120  Starting logging for Qtile
2019-07-10 18:36:44,352 libqtile hook.py:fire():L368  Internal event: addgroup((<libqtile.core.manager.Qtile object at 0x63155d7d17f0>, '1'), {})
2019-07-10 18:36:44,352 libqtile hook.py:fire():L368  Internal event: changegroup((), {})
2019-07-10 18:36:44,353 libqtile hook.py:fire():L368  Internal event: addgroup((<libqtile.core.manager.Qtile object at 0x63155d7d17f0>, '2'), {})
2019-07-10 18:36:44,353 libqtile hook.py:fire():L368  Internal event: changegroup((), {})
2019-07-10 18:36:44,354 libqtile hook.py:fire():L368  Internal event: addgroup((<libqtile.core.manager.Qtile object at 0x63155d7d17f0>, '3'), {})
2019-07-10 18:36:44,354 libqtile hook.py:fire():L368  Internal event: changegroup((), {})
2019-07-10 18:36:44,355 libqtile hook.py:fire():L368  Internal event: addgroup((<libqtile.core.manager.Qtile object at 0x63155d7d17f0>, '4'), {})
2019-07-10 18:36:44,355 libqtile hook.py:fire():L368  Internal event: changegroup((), {})
2019-07-10 18:36:44,356 libqtile hook.py:fire():L368  Internal event: addgroup((<libqtile.core.manager.Qtile object at 0x63155d7d17f0>, '5'), {})
2019-07-10 18:36:44,356 libqtile hook.py:fire():L368  Internal event: changegroup((), {})
2019-07-10 18:36:44,357 libqtile hook.py:fire():L368  Internal event: addgroup((<libqtile.core.manager.Qtile object at 0x63155d7d17f0>, '6'), {})
2019-07-10 18:36:44,357 libqtile hook.py:fire():L368  Internal event: changegroup((), {})
2019-07-10 18:36:44,358 libqtile hook.py:fire():L368  Internal event: addgroup((<libqtile.core.manager.Qtile object at 0x63155d7d17f0>, '7'), {})
2019-07-10 18:36:44,358 libqtile hook.py:fire():L368  Internal event: changegroup((), {})
2019-07-10 18:36:44,359 libqtile hook.py:fire():L368  Internal event: addgroup((<libqtile.core.manager.Qtile object at 0x63155d7d17f0>, '8'), {})
2019-07-10 18:36:44,360 libqtile hook.py:fire():L368  Internal event: changegroup((), {})
2019-07-10 18:36:44,361 libqtile hook.py:fire():L368  Internal event: addgroup((<libqtile.core.manager.Qtile object at 0x63155d7d17f0>, '9'), {})
2019-07-10 18:36:44,361 libqtile hook.py:fire():L368  Internal event: changegroup((), {})
2019-07-10 18:36:44,362 libqtile manager.py:setup_eventloop():L277  Adding io watch
2019-07-10 18:36:44,432 libqtile hook.py:fire():L368  Internal event: setgroup((), {})
2019-07-10 18:36:44,432 libqtile hook.py:fire():L368  Internal event: focus_change((), {})
2019-07-10 18:36:44,432 libqtile hook.py:fire():L368  Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x63155ab74198>, <group.Group ('1')>), {})
2019-07-10 18:36:44,863 libqtile manager.py:_xpoll():L733  ScreenChangeNotify
2019-07-10 18:36:44,864 libqtile manager.py:_xpoll():L735  Handling: ScreenChangeNotify
2019-07-10 18:36:44,864 libqtile hook.py:fire():L368  Internal event: screen_change((<libqtile.core.manager.Qtile object at 0x63155d7d17f0>, <xcffib.randr.ScreenChangeNotifyEvent object at 0x63155aa34da0>), {})
2019-07-10 18:36:44,864 libqtile manager.py:stop():L807  Stopping eventloop
2019-07-10 18:36:44,864 libqtile manager.py:_xpoll():L733  ConfigureNotify
2019-07-10 18:36:44,865 libqtile manager.py:_xpoll():L735  Handling: ConfigureNotify
2019-07-10 18:36:44,865 libqtile manager.py:_xpoll():L733  PropertyNotify
2019-07-10 18:36:44,865 libqtile manager.py:_xpoll():L735  Handling: PropertyNotify
2019-07-10 18:36:44,865 libqtile manager.py:_xpoll():L733  ConfigureNotify
2019-07-10 18:36:44,865 libqtile manager.py:_xpoll():L735  Handling: ConfigureNotify
2019-07-10 18:36:44,866 libqtile manager.py:_xpoll():L733  PropertyNotify
2019-07-10 18:36:44,866 libqtile manager.py:_xpoll():L735  Handling: PropertyNotify
2019-07-10 18:36:44,866 libqtile manager.py:_xpoll():L733  Expose
2019-07-10 18:36:44,866 libqtile manager.py:_xpoll():L735  Handling: Expose
2019-07-10 18:36:44,866 libqtile manager.py:_xpoll():L733  PropertyNotify
2019-07-10 18:36:44,867 libqtile manager.py:_xpoll():L735  Handling: PropertyNotify
2019-07-10 18:36:44,867 libqtile manager.py:_xpoll():L733  ClientMessage
2019-07-10 18:36:44,867 libqtile manager.py:_xpoll():L735  Handling: ClientMessage
2019-07-10 18:36:44,871 libqtile hook.py:fire():L368  Internal event: startup_once((), {})
[...] # Logs of external tools runned by autostart.sh
2019-07-10 18:36:45,299 libqtile hook.py:fire():L368  Internal event: startup((), {})
2019-07-10 18:36:45,308 libqtile hook.py:fire():L368  Internal event: startup_complete((), {})
2019-07-10 18:36:45,308 libqtile ipc.py:start():L309  Starting server
2019-07-10 18:36:45,414 libqtile qtile.py:main():L134  Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/scripts/qtile.py", line 132, in main
    q.loop()
  File "/usr/lib/python3.7/site-packages/libqtile/core/manager.py", line 811, in loop
    self.server.start()
  File "/usr/lib/python3.7/site-packages/libqtile/ipc.py", line 310, in start
    self.server = self.loop.run_until_complete(server_coroutine)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 582, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
2019-07-10 18:36:45,417 libqtile qtile.py:main():L135  Exiting...
```

**Comment by max-k** [comment]
Okay, sorry again, it clearly was the problem but, in my multi-file configuration, not importing it wasn't sufficient to disable it, I have to completely comment it out.

Maybe the following example has be removed from the documentation:

```
@libqtile.hook.subscribe.screen_change
def restart_on_randr(qtile, ev):
    qtile.cmd_restart()
```

**Comment by danmilon** [comment]
I'm randomly hitting the same error too.

**Comment by max-k** [comment]
@danmilon Do you have the screen_change hook enabled ? If yes, could you try to comment it out from your configuration ?

**Comment by danmilon** [comment]
@max-k yeah, I do. The crash happens every other time when running this xrandr command:
```
xrandr --output HDMI-1 --mode 2560x1440 --primary --output eDP-1 --off
```
to switch to an external monitor.

If I take out the hook it doesn't crash.

**Comment by jagguli** [comment]
I'm having the same issue, is there an alternative to restarting on screen change event ?

**Comment by danmilon** [comment]
Remove the hook, and do a manual qtile restart after xrandr.
You should have a key like that already if you follow the default config:
```
Key("M-C-r", lazy.restart())
```

**Comment by tych0** [comment]
Seems like we're probably not quite shutting down the event loop properly on restart. Let me look into it.

**Comment by xtalax** [comment]
> Seems like we're probably not quite shutting down the event loop properly on restart. Let me look into it.

This appears to still be the case, I have the following error:
```
2022-03-21 19:06:13,176 ERROR libqtile hook.py:fire():L392 Error in hook screen_change
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 390, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 359, in cmd_reconfigure_screens
    self._process_screens()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 340, in _process_screens
    scr._configure(self, i, x, y, w, h, grp, reconfigure_gaps=reconfigure_gaps)
  File "/usr/lib/python3.10/site-packages/libqtile/config.py", line 302, in _configure
    self.set_group(group)
  File "/usr/lib/python3.10/site-packages/libqtile/config.py", line 364, in set_group
    g1 = self.group
AttributeError: 'Screen' object has no attribute 'group'
```

Which persists after deleting the `@screen_change` hook and reloading the config

**Comment by elParaguayo** [comment]
I don't think your issue is in any way related to this thread. Can you start a new issue and provide a link to your config.
