### ISSUE TITLE
QTile Bad Config

### ISSUE THREAD

**Issue by dk0104** [qtile/qtile#1483]
QTile Config error with default config.py .Config file location ~/.config/qtile/config.py
QTile installed  on fedora 30 dnf. QTile version : 0.13.0
qtile.log:
```
2019-10-22 23:10:55,246 WARNING libqtile log_utils.py:init_log():L120 Starting logging for Qtile
2019-10-22 23:10:55,260 ERROR libqtile confreader.py:from_file():L87 Could not import config file '/home/dk/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
2019-10-22 23:10:55,260 ERROR libqtile qtile.py:make_qtile():L109 Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/scripts/qtile.py", line 107, in make_qtile
    config = confreader.Config.from_file(options.configfile)
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 89, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

2019-10-22 23:10:55,313 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpdwidget.Mpd', No module named 'mpd'
2019-10-22 23:10:55,314 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2019-10-22 23:10:55,317 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2019-10-22 23:10:55,323 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
2019-10-22 23:10:55,329 WARNING libqtile xcursors.py:_setup_xcursor_binding():L117 xcb-cursor not found, fallback to font pointer
2019-10-22 23:10:55,896 WARNING libqtile manager.py:finalize():L355 Restarting Qtile with os.execv(...)
2019-10-22 23:10:56,071 WARNING libqtile log_utils.py:init_log():L120 Starting logging for Qtile
2019-10-22 23:10:56,084 ERROR libqtile confreader.py:from_file():L87 Could not import config file '/home/dk/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
2019-10-22 23:10:56,085 ERROR libqtile qtile.py:make_qtile():L109 Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/scripts/qtile.py", line 107, in make_qtile
    config = confreader.Config.from_file(options.configfile)
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 89, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

2019-10-22 23:10:56,138 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpdwidget.Mpd', No module named 'mpd'
2019-10-22 23:10:56,139 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2019-10-22 23:10:56,142 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2019-10-22 23:10:56,148 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
2019-10-22 23:10:56,155 WARNING libqtile xcursors.py:_setup_xcursor_binding():L117 xcb-cursor not found, fallback to font pointer
2019-10-22 23:10:56,617 WARNING libqtile manager.py:finalize():L355 Restarting Qtile with os.execv(...)
2019-10-22 23:10:56,794 WARNING libqtile log_utils.py:init_log():L120 Starting logging for Qtile
2019-10-22 23:10:56,809 ERROR libqtile confreader.py:from_file():L87 Could not import config file '/home/dk/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
2019-10-22 23:10:56,809 ERROR libqtile qtile.py:make_qtile():L109 Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/scripts/qtile.py", line 107, in make_qtile
    config = confreader.Config.from_file(options.configfile)
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 89, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

2019-10-22 23:10:56,864 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpdwidget.Mpd', No module named 'mpd'
2019-10-22 23:10:56,865 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2019-10-22 23:10:56,868 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2019-10-22 23:10:56,874 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
2019-10-22 23:10:56,881 WARNING libqtile xcursors.py:_setup_xcursor_binding():L117 xcb-cursor not found, fallback to font pointer
2019-10-22 23:23:31,090 ERROR libqtile manager.py:_xpoll():L753 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 719, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 566, in wrapper
    return f(*args)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 607, in poll_for_event
    return self.hoist_event(e)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 680, in hoist_event
    return self._process_error(ffi.cast("xcb_generic_error_t *", e))
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 643, in _process_error
    raise error(buf)
xcffib.xproto.MatchError
2019-10-22 23:32:34,356 WARNING libqtile manager.py:finalize():L355 Restarting Qtile with os.execv(...)
2019-10-22 23:32:34,505 WARNING libqtile log_utils.py:init_log():L120 Starting logging for Qtile
2019-10-22 23:32:34,518 ERROR libqtile confreader.py:from_file():L87 Could not import config file '/home/dk/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
2019-10-22 23:32:34,519 ERROR libqtile qtile.py:make_qtile():L109 Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/scripts/qtile.py", line 107, in make_qtile
    config = confreader.Config.from_file(options.configfile)
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 89, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

2019-10-22 23:32:34,570 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpdwidget.Mpd', No module named 'mpd'
2019-10-22 23:32:34,571 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2019-10-22 23:32:34,574 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2019-10-22 23:32:34,580 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
2019-10-22 23:32:34,586 WARNING libqtile xcursors.py:_setup_xcursor_binding():L117 xcb-cursor not found, fallback to font pointer
2019-10-22 23:32:35,618 WARNING libqtile manager.py:finalize():L355 Restarting Qtile with os.execv(...)
2019-10-22 23:32:35,775 WARNING libqtile log_utils.py:init_log():L120 Starting logging for Qtile
2019-10-22 23:32:35,788 ERROR libqtile confreader.py:from_file():L87 Could not import config file '/home/dk/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
2019-10-22 23:32:35,788 ERROR libqtile qtile.py:make_qtile():L109 Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/scripts/qtile.py", line 107, in make_qtile
    config = confreader.Config.from_file(options.configfile)
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 89, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

2019-10-22 23:32:35,841 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpdwidget.Mpd', No module named 'mpd'
2019-10-22 23:32:35,841 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2019-10-22 23:32:35,844 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2019-10-22 23:32:35,850 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
2019-10-22 23:32:35,857 WARNING libqtile xcursors.py:_setup_xcursor_binding():L117 xcb-cursor not found, fallback to font pointer
2019-10-22 23:32:36,520 WARNING libqtile manager.py:finalize():L355 Restarting Qtile with os.execv(...)
2019-10-22 23:32:36,675 WARNING libqtile log_utils.py:init_log():L120 Starting logging for Qtile
2019-10-22 23:32:36,689 ERROR libqtile confreader.py:from_file():L87 Could not import config file '/home/dk/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
2019-10-22 23:32:36,689 ERROR libqtile qtile.py:make_qtile():L109 Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/scripts/qtile.py", line 107, in make_qtile
    config = confreader.Config.from_file(options.configfile)
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 89, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

2019-10-22 23:32:36,743 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpdwidget.Mpd', No module named 'mpd'
2019-10-22 23:32:36,744 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2019-10-22 23:32:36,747 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2019-10-22 23:32:36,753 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
2019-10-22 23:32:36,759 WARNING libqtile xcursors.py:_setup_xcursor_binding():L117 xcb-cursor not found, fallback to font pointer
2019-10-22 23:35:09,311 WARNING libqtile manager.py:finalize():L355 Restarting Qtile with os.execv(...)
2019-10-22 23:35:09,462 WARNING libqtile log_utils.py:init_log():L120 Starting logging for Qtile
2019-10-22 23:35:09,477 ERROR libqtile confreader.py:from_file():L87 Could not import config file '/home/dk/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
2019-10-22 23:35:09,478 ERROR libqtile qtile.py:make_qtile():L109 Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/scripts/qtile.py", line 107, in make_qtile
    config = confreader.Config.from_file(options.configfile)
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 89, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

2019-10-22 23:35:09,531 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpdwidget.Mpd', No module named 'mpd'
2019-10-22 23:35:09,531 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2019-10-22 23:35:09,535 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2019-10-22 23:35:09,541 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
2019-10-22 23:35:09,547 WARNING libqtile xcursors.py:_setup_xcursor_binding():L117 xcb-cursor not found, fallback to font pointer
2019-10-22 23:35:10,115 WARNING libqtile manager.py:finalize():L355 Restarting Qtile with os.execv(...)
2019-10-22 23:35:10,292 WARNING libqtile log_utils.py:init_log():L120 Starting logging for Qtile
2019-10-22 23:35:10,306 ERROR libqtile confreader.py:from_file():L87 Could not import config file '/home/dk/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
2019-10-22 23:35:10,306 ERROR libqtile qtile.py:make_qtile():L109 Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/scripts/qtile.py", line 107, in make_qtile
    config = confreader.Config.from_file(options.configfile)
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 89, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

2019-10-22 23:35:10,361 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpdwidget.Mpd', No module named 'mpd'
2019-10-22 23:35:10,362 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2019-10-22 23:35:10,365 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2019-10-22 23:35:10,371 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
2019-10-22 23:35:10,378 WARNING libqtile xcursors.py:_setup_xcursor_binding():L117 xcb-cursor not found, fallback to font pointer
2019-10-22 23:35:10,808 WARNING libqtile manager.py:finalize():L355 Restarting Qtile with os.execv(...)
2019-10-22 23:35:10,957 WARNING libqtile log_utils.py:init_log():L120 Starting logging for Qtile
2019-10-22 23:35:10,971 ERROR libqtile confreader.py:from_file():L87 Could not import config file '/home/dk/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
2019-10-22 23:35:10,972 ERROR libqtile qtile.py:make_qtile():L109 Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/scripts/qtile.py", line 107, in make_qtile
    config = confreader.Config.from_file(options.configfile)
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 89, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

2019-10-22 23:35:11,027 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpdwidget.Mpd', No module named 'mpd'
2019-10-22 23:35:11,028 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2019-10-22 23:35:11,031 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2019-10-22 23:35:11,037 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
2019-10-22 23:35:11,046 WARNING libqtile xcursors.py:_setup_xcursor_binding():L117 xcb-cursor not found, fallback to font pointer
2019-10-22 23:35:11,700 WARNING libqtile manager.py:finalize():L355 Restarting Qtile with os.execv(...)
2019-10-22 23:35:11,864 WARNING libqtile log_utils.py:init_log():L120 Starting logging for Qtile
2019-10-22 23:35:11,880 ERROR libqtile confreader.py:from_file():L87 Could not import config file '/home/dk/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
2019-10-22 23:35:11,881 ERROR libqtile qtile.py:make_qtile():L109 Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'
)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/scripts/qtile.py", line 107, in make_qtile
    config = confreader.Config.from_file(options.configfile)
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 89, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/confreader.py", line 83, in from_file
    config = __import__(os.path.basename(path)[:-3])
  File "/home/dk/.config/qtile/config.py", line 2, in <module>
    from libqtile.lazy import lazy
ModuleNotFoundError: No module named 'libqtile.lazy'

2019-10-22 23:35:11,940 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpdwidget.Mpd', No module named 'mpd'
2019-10-22 23:35:11,941 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2019-10-22 23:35:11,944 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2019-10-22 23:35:11,950 WARNING libqtile utils.py:safe_import():L268 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
2019-10-22 23:35:11,958 WARNING libqtile xcursors.py:_setup_xcursor_binding():L117 xcb-cursor not found, fallback to font pointer
2019-10-22 23:51:58,845 ERROR libqtile manager.py:_xpoll():L749 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 566, in wrapper
    return f(*args)
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 605, in poll_for_event
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 554, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libqtile/manager.py", line 719, in _xpoll
    e = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 568, in wrapper
    self.invalid()
  File "/usr/lib/python3.7/site-packages/xcffib/__init__.py", line 554, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
```

**Comment by pawamoy** [comment]
I'm also thinking it's a compatibility problem. There's `ModuleNotFoundError: No module named 'libqtile.lazy'` throughout the whole log, and `lazy` has recently been moved into `libqtile.commands` (though this change has not been released yet).

**Comment by dk0104** [comment]
Yes it was a compatibility issue. I was able fix that by building the actual head . 
```
git clone git://github.com/qtile/qtile.git
cd qtile
pip3 install . 
```
But i think the [doc Installation part](http://docs.qtile.org/en/latest/manual/install/fedora.html) should be changed, because the OS Repository is not up to date . 

Thanks for support.

**Comment by whatacold** [comment]
Glad that helps, and welcome :)

---

Since this compatibility issue happens occasionally(e.g. this issue and #1479 ), how about adding an option to `qtile` command, say `--generate-default-config`, so that running `qtile --generate-default-config` will copy the `default_config.py` of that exact version to `~/.config/qtile/config.py` and exit? @flacjacket @ramnes

**Comment by ramnes** [comment]
I'd rather be in favor of automatically writing the file when qtile loads if it doesn't exist yet. What annoys me is that I thought we were doing this already, but apparently not.

**Comment by pawamoy** [comment]
Yes I also thought the default config was loaded if ~/.config/qtile/config.py didn't exist, but I actually had to manually create it the first time I installed qtile. Are there tests for this case?

**Comment by whatacold** [comment]
@ramnes I was also thinking this after I posted the above comment, and it is more user friendly.

**Comment by whatacold** [comment]
@pawamoy The default config actually is loaded if there is no config.py as in [confreader.py](https://github.com/qtile/qtile/blob/master/libqtile/confreader.py#L67), and an additional textbox labelled "Config Err!" is added.
