### ISSUE TITLE
Expected config error after update to 0.15.0

### ISSUE THREAD

**Issue by zeluu** [qtile/qtile#1610]
# Issue description
After update qtile to latest version I have config error as expected according to info in Release Notes however I can't identify what change in config in order to make it working.

# Qtile version
 0.15.0

# Stack traces
* `~/.local/share/qtile/qtile.log`

2020-04-13 12:54:15,806 ERROR libqtile manager.py:<lambda>():L274 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/core/manager.py", line 724, in _xpoll
    continue
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/site-packages/libqtile/core/manager.py", line 755, in _xpoll
    self.core.grab_pointer()
  File "/usr/lib/python3.8/site-packages/libqtile/core/manager.py", line 805, in stop
    if self.current_window and group:
  File "/usr/lib/python3.8/site-packages/libqtile/core/manager.py", line 775, in graceful_shutdown
    dx = x - ox
  File "/usr/lib/python3.8/site-packages/libqtile/core/manager.py", line 773, in get_interesting_pid
    return
  File "/usr/lib/python3.8/site-packages/libqtile/core/xcbq.py", line 610, in get_net_wm_pid
  File "/usr/lib/python3.8/site-packages/libqtile/core/xcbq.py", line 703, in get_property
  File "/usr/lib/python3.8/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2020-04-13 12:54:15,808 ERROR libqtile manager.py:_xpoll():L754 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/core/manager.py", line 724, in _xpoll
    continue
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2020-04-13 12:54:15,809 ERROR libqtile manager.py:<lambda>():L274 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/core/manager.py", line 724, in _xpoll
    continue
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
[qtile.log](https://github.com/qtile/qtile/files/4469610/qtile.log)

Full 8MB log in attachment

*No logs in `~/.xsession-errors`

# Configuration

https://gist.github.com/zeluu/bfec52a0d04f4bc983c7f56e33738508

**Comment by arcolinuxz** [comment]
For future readers 
we changed this in our code 
 from libqtile.command import lazy, Client
to
 from libqtile.command import lazy

And commented out one of our self created widgets

**Comment by ramnes** [comment]
Yeah, the relevant part in your logs is this:

```
ImportError: cannot import name 'Client' from 'libqtile.command' (/usr/lib/python3.8/site-packages/libqtile/command.py)
```

`libqtile.command.Client` does not exist anymore. We need to mention this in the CHANGELOG.

**Comment by ramnes** [comment]
Related to #1555

**Comment by ramnes** [comment]
Related to #1409

**Comment by arcolinuxz** [comment]
can be closed for @arcolinuxz

**Comment by ramnes** [comment]
Closing in favor of the two mentioned issues.

**Comment by zeluu** [comment]
Changing
from libqtile.command import lazy, Client
to
from libqtile.command import lazy

and commenting arco battery widget in config.py helped.
