### ISSUE TITLE
qtile-top crash 'Client' object has no attribute 'tracemalloc_dump'

### ISSUE THREAD

**Issue by zordsdavini** [qtile/qtile#1656]
# Issue description

Tried to run `qtile-top` and it crashed. I'm not sure should be done before that script  - no documentation.
Tried 
```
 arnas@zordmachine  ~  qtile-cmd -o cmd -f tracemalloc_dump
[False, 'Trace not started']
 arnas@zordmachine  ~  qtile-cmd -o cmd -f tracemalloc_toggle
 arnas@zordmachine  ~  qtile-cmd -o cmd -f tracemalloc_dump
[True, '/home/arnas/.cache/qtile/qtile_tracemalloc.dump']
```
but this didn't helped

# Qtile version

5bd8e57f78b72ed9de4d10bf51af6db51561d794 (latest git version)

# Stack traces

Traceback (most recent call last):
  File "/usr/bin/qtile-top", line 11, in <module>
    load_entry_point('qtile==0.15.0', 'console_scripts', 'qtile-top')()
  File "/usr/lib/python3.8/site-packages/libqtile/scripts/qtile_top.py", line 164, in main
    curses.wrapper(get_stats, client, limit=lines, seconds=seconds,
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3.8/site-packages/libqtile/scripts/qtile_top.py", line 91, in get_stats
    snapshot = get_trace(client, force_start)
  File "/usr/lib/python3.8/site-packages/libqtile/scripts/qtile_top.py", line 63, in get_trace
    (started, path) = client.tracemalloc_dump()
AttributeError: 'Client' object has no attribute 'tracemalloc_dump'

# Configuration

https://github.com/zordsdavini/qtile-config
Arch

**Comment by ep12** [comment]
Same error with 0.15.1 from the arch repo.
