### ISSUE TITLE
Maximized videos freeze in Firefox

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1658]
# Issue description

Sometimes when I maximize a YouTube or Plex video in Firefox, the window freezes. It's responsive, but the screen freezes on the last frame. Not especially the video frame, but the whole screen frame (with potential play/pause buttons and stuff over the video).

It happens with both Qtile's maximization (`lazy.window.toggle_maximize()`) and video maximization (the common "maximize" buttons in videos).

I can still unmaximize, and everything works fine. As soon as I maximize again, window freezes again.

- Qtile version: 0.14.2
- Firefox version: 75.0

# Stack traces

I'll update the post with minimal stack traces where the issue happens.

# Configuration

```python
import logging
import os
import platform
import sys
import traceback
import importlib
import subprocess

from libqtile.confreader import Config, ConfigError
from libqtile.config import Key, Screen, Group, Drag, Click
from libqtile.command import lazy
from libqtile.xkeysyms import keysyms
from libqtile import layout, bar, widget, hook

from Xlib import display as xdisplay

# TODO: check out great pieces of code at
# https://github.com/zordsdavini/dotfiles/blob/master/.config/qtile/config.py


os.environ["MPD_HOST"] = "192.168.0.34"


logging.basicConfig(
    filename="qtile.log",
    filemode="a",
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)


class KeysHolder:
    def __init__(self):
        for key in keysyms.keys():
            self_key = key.upper()
            if key[0] in range(0, 9):
                self_key = "K" + self_key
            setattr(self, self_key, key)
        self.ALT = self.MOD1 = "mod1"
        self.HYPER = self.MOD3 = "mod3"
        self.SUPER = self.MOD4 = "mod4"
        self.SHIFT = "shift"
        self.CONTROL = "control"
        self.EXCLAMATION = self.EXCLAM
        self.DOUBLE_QUOTE = self.QUOTEDBL


class MouseButtons:
    LEFT = BUTTON1 = "Button1"
    MIDDLE = BUTTON2 = "Button2"
    RIGHT = BUTTON3 = "Button3"
    WHEEL_UP = BUTTON4 = "Button4"
    WHEEL_DOWN = BUTTON5 = "Button5"
    WHEEL_LEFT = BUTTON6 = "Button6"
    WHEEL_RIGHT = BUTTON7 = "Button7"
    PREVIOUS = BUTTON8 = "Button8"
    NEXT = BUTTON9 = "Button9"


# ------------------------------------------------------------------------------
# LAZY FUNCTIONS ---------------------------------------------------------------
# ------------------------------------------------------------------------------
@lazy.function
def float_to_front(qtile):
    logging.info("bring floating windows to front")
    for group in qtile.groups:
        for window in group.windows:
            if window.floating:
                window.cmd_bring_to_front()


def resize(qtile, direction):
    layout = qtile.current_layout
    child = layout.current
    parent = child.parent

    while parent:
        if child in parent.children:
            layout_all = False

            if (direction == "left" and parent.split_horizontal) or (
                direction == "up" and not parent.split_horizontal
            ):
                parent.split_ratio = max(5, parent.split_ratio - layout.grow_amount)
                layout_all = True
            elif (direction == "right" and parent.split_horizontal) or (
                direction == "down" and not parent.split_horizontal
            ):
                parent.split_ratio = min(95, parent.split_ratio + layout.grow_amount)
                layout_all = True

            if layout_all:
                layout.group.layout_all()
                break

        child = parent
        parent = child.parent


@lazy.function
def resize_left(qtile):
    resize(qtile, "left")


@lazy.function
def resize_right(qtile):
    resize(qtile, "right")


@lazy.function
def resize_up(qtile):
    resize(qtile, "up")


@lazy.function
def resize_down(qtile):
    resize(qtile, "down")


# @lazy.function
# def validate_and_restart(qtile):
#     logging.info("validating config before restart")
#     try:
#         validate_config()
#     except ConfigError as error:
#         logging.warning("prevented restart because of error:\n" + str(error))
#         notifier = Notify.Notification.new('Configuration error', str(error))
#         notifier.set_timeout(10000)
#         notifier.show()
#         # subprocess.call(["notify-send", "-t", "10000", str(error)])
#     else:
#         qtile.cmd_restart()


# TODO: lazy function to cycle through groups, not currently
# displayed on any other screen, and to bring them into the current
# screen.


# ------------------------------------------------------------------------------
# HOOKS FUNCTIONS --------------------------------------------------------------
# ------------------------------------------------------------------------------
@hook.subscribe.client_new
def floating_windows(window):
    wm_class = window.window.get_wm_class()
    w_name = window.window.get_name()
    if (
        (
            (
                wm_class == ("jetbrains-pycharm-ce", "jetbrains-pycharm-ce")
                and w_name in (" ", "win0")
            )
            or (
                wm_class == ("java-lang-Thread", "java-lang-Thread")
                and w_name == "win0"
            )
        )
        or (
            wm_class == ("Steam", "Steam")
            and (
                w_name != "Steam"
                # w_name == "Friends List"
                # or w_name == "Screenshot Uploader"
                # or w_name.startswith("Steam - News")
                or "PMaxSize" in window.window.get_wm_normal_hints().get("flags", ())
            )
        )
        or (wm_class == ("Places", "firefox") and w_name == "Library")
    ):
        window.floating = True


# ------------------------------------------------------------------------------
# EXTRA FUNCTIONS --------------------------------------------------------------
# ------------------------------------------------------------------------------
def get_ip_location(data):
    return "IP: {}".format(data.get("query", "-"))


# ------------------------------------------------------------------------------
# KEYBINDINGS ------------------------------------------------------------------
# ------------------------------------------------------------------------------
k = KeysHolder()
m = MouseButtons()

keys = [
    # Change focus between windows in current stack pane
    Key([k.HYPER], "k", lazy.layout.left()),
    Key([k.HYPER], "o", lazy.layout.up()),
    Key([k.HYPER], "l", lazy.layout.down()),
    Key([k.HYPER], "m", lazy.layout.right()),
    Key([k.HYPER], k.LEFT, lazy.layout.left()),
    Key([k.HYPER], k.UP, lazy.layout.up()),
    Key([k.HYPER], k.DOWN, lazy.layout.down()),
    Key([k.HYPER], k.RIGHT, lazy.layout.right()),
    # Move windows up or down in current stack
    Key([k.HYPER, k.SHIFT], "k", lazy.layout.shuffle_left()),
    Key([k.HYPER, k.SHIFT], "o", lazy.layout.shuffle_up()),
    Key([k.HYPER, k.SHIFT], "l", lazy.layout.shuffle_down()),
    Key([k.HYPER, k.SHIFT], "m", lazy.layout.shuffle_right()),
    Key([k.HYPER, k.SHIFT], k.LEFT, lazy.layout.shuffle_left()),
    Key([k.HYPER, k.SHIFT], k.UP, lazy.layout.shuffle_up()),
    Key([k.HYPER, k.SHIFT], k.DOWN, lazy.layout.shuffle_down()),
    Key([k.HYPER, k.SHIFT], k.RIGHT, lazy.layout.shuffle_right()),
    # Flip windows?
    Key([k.HYPER, k.CONTROL], "k", lazy.layout.flip_left()),
    Key([k.HYPER, k.CONTROL], "o", lazy.layout.flip_up()),
    Key([k.HYPER, k.CONTROL], "l", lazy.layout.flip_down()),
    Key([k.HYPER, k.CONTROL], "m", lazy.layout.flip_right()),
    Key([k.HYPER, k.CONTROL], k.LEFT, lazy.layout.flip_left()),
    Key([k.HYPER, k.CONTROL], k.UP, lazy.layout.flip_up()),
    Key([k.HYPER, k.CONTROL], k.DOWN, lazy.layout.flip_down()),
    Key([k.HYPER, k.CONTROL], k.RIGHT, lazy.layout.flip_right()),
    # Resize windows
    Key([k.HYPER, k.ALT], "k", resize_left),
    Key([k.HYPER, k.ALT], "o", resize_up),
    Key([k.HYPER, k.ALT], "l", resize_down),
    Key([k.HYPER, k.ALT], "m", resize_right),
    Key([k.HYPER, k.ALT], k.LEFT, resize_left),
    Key([k.HYPER, k.ALT], k.UP, resize_up),
    Key([k.HYPER, k.ALT], k.DOWN, resize_down),
    Key([k.HYPER, k.ALT], k.RIGHT, resize_right),
    # Grow windows
    Key([k.HYPER, k.SHIFT, k.ALT], "k", lazy.layout.grow_left()),
    Key([k.HYPER, k.SHIFT, k.ALT], "o", lazy.layout.grow_up()),
    Key([k.HYPER, k.SHIFT, k.ALT], "l", lazy.layout.grow_down()),
    Key([k.HYPER, k.SHIFT, k.ALT], "m", lazy.layout.grow_right()),
    Key([k.HYPER, k.SHIFT, k.ALT], k.LEFT, lazy.layout.grow_left()),
    Key([k.HYPER, k.SHIFT, k.ALT], k.UP, lazy.layout.grow_up()),
    Key([k.HYPER, k.SHIFT, k.ALT], k.DOWN, lazy.layout.grow_down()),
    Key([k.HYPER, k.SHIFT, k.ALT], k.RIGHT, lazy.layout.grow_right()),
    # Cycle through current layout (and therefore screen and group)'s windows
    Key([k.ALT], k.TAB, lazy.layout.next()),
    Key([k.ALT, k.SHIFT], k.TAB, lazy.layout.previous()),
    # Cycle through layouts
    Key([k.HYPER], k.TAB, lazy.next_layout()),
    Key([k.HYPER, k.SHIFT], k.TAB, lazy.previous_layout()),
    # Cycle focus through screens
    Key([k.SUPER], k.TAB, lazy.next_screen()),
    Key([k.SUPER, k.SHIFT], k.TAB, lazy.previous_screen()),
    # Windows
    Key([k.HYPER, k.SHIFT], k.SPACE, lazy.layout.rotate()),
    Key([k.HYPER, k.SHIFT], k.RETURN, lazy.layout.toggle_split()),
    Key([k.HYPER], "w", lazy.window.kill()),
    Key([k.HYPER], "f", lazy.window.toggle_floating()),
    Key([k.HYPER], "x", lazy.window.toggle_fullscreen()),
    Key([k.HYPER], "d", lazy.window.toggle_maximize()),
    Key([k.HYPER], "b", float_to_front),
    # Launchers
    Key([k.HYPER], k.RETURN, lazy.spawn("terminator")),
    Key([k.SUPER], k.RETURN, lazy.spawn("terminator")),  # For safety
    Key([k.HYPER], "r", lazy.spawncmd()),
    Key([k.HYPER], "c", lazy.spawn("terminator -x vim {}".format(__file__))),
    Key([k.SUPER], "x", lazy.spawn("xterm -hold +ls -e xmodmap")),
    Key([k.ALT], "F2", lazy.spawn("gmrun")),
    Key([], k.PRINT, lazy.spawn("xfce4-screenshooter")),
    Key([k.SHIFT], k.PRINT, lazy.spawn("xfce4-screenshooter -r")),
    # QTile
    Key([k.HYPER, k.CONTROL], "r", lazy.restart()),
    Key([k.SUPER, k.CONTROL], "r", lazy.restart()),  # For safety
    Key([k.HYPER, k.CONTROL], "q", lazy.shutdown()),
    # Special keys
    Key([], k.SCROLL_LOCK, lazy.spawn("toggle-kb-led")),
    # Multimedia keys
    Key([], k.XF86AUDIORAISEVOLUME, lazy.spawn("amixer -c 0 -q set Master 2dB+")),
    Key([], k.XF86AUDIOLOWERVOLUME, lazy.spawn("amixer -c 0 -q set Master 2dB-")),
    Key([k.HYPER], k.XF86AUDIORAISEVOLUME, lazy.spawn("mpc volume +5")),
    Key([k.HYPER], k.XF86AUDIOLOWERVOLUME, lazy.spawn("mpc volume -5")),
    Key([], k.XF86AUDIONEXT, lazy.spawn("mpc next")),
    Key([], k.XF86AUDIOPREV, lazy.spawn("mpc prev")),
    Key([], k.XF86AUDIOPLAY, lazy.spawn("mpc toggle")),
    Key([], k.XF86AUDIOSTOP, lazy.spawn("mpc stop")),
    Key([], k.XF86MONBRIGHTNESSUP, lazy.spawn("brightnessctl set +10%")),
    Key([], k.XF86MONBRIGHTNESSDOWN, lazy.spawn("brightnessctl set 10%-")),
]

mouse = [
    Drag(
        [k.ALT],
        m.LEFT,
        lazy.window.set_position_floating(),
        start=lazy.window.get_position(),
    ),
    Drag(
        [k.HYPER, k.ALT],
        m.LEFT,
        lazy.window.set_position(),
        start=lazy.window.get_position(),
    ),
    Drag(
        [k.ALT], m.RIGHT, lazy.window.set_size_floating(), start=lazy.window.get_size()
    ),
    Click([k.HYPER], m.LEFT, lazy.window.bring_to_front()),
    Click([k.HYPER], m.MIDDLE, lazy.window.kill()),
]


# ------------------------------------------------------------------------------
# GROUPS -----------------------------------------------------------------------
# ------------------------------------------------------------------------------
groups_def = [("1", k.COMMA), ("2", k.SEMICOLON), ("3", k.COLON), ("4", k.EXCLAMATION)]
groups = [Group(name) for name, char in groups_def]

for name, char in groups_def:
    keys.extend(
        [
            # bring group to current screen
            Key([k.HYPER, k.CONTROL], char, lazy.group[name].toscreen()),
            # move focused window to group and switch to group
            Key([k.HYPER, k.SHIFT], char, lazy.window.togroup(name)),
        ]
    )


# ------------------------------------------------------------------------------
# LAYOUTS ----------------------------------------------------------------------
# ------------------------------------------------------------------------------
layouts = [
    layout.Max(),
    layout.Bsp(
        border_normal="#000000",
        border_focus="#ffffff",
        border_width=1,
        fair=False,
        lower_right=False,
        margin=20,
        grow_amount=1,
    ),
]

floating_layout = layout.Floating(
    border_normal="#000000",
    border_focus="#ffffff",
    float_rules=[
        {"wmclass": "confirm"},
        {"wmclass": "dialog"},
        {"wmclass": "download"},
        {"wmclass": "error"},
        {"wmclass": "file_progress"},
        {"wmclass": "notification"},
        {"wmclass": "splash"},
        {"wmclass": "toolbar"},
        {"wmclass": "confirmreset"},  # gitk
        {"wmclass": "makebranch"},  # gitk
        {"wmclass": "maketag"},  # gitk
        {"wname": "branchdialog"},  # gitk
        {"wname": "pinentry"},  # GPG key password entry
        {"wmclass": "ssh-askpass"},  # ssh-askpass
        {"wmclass": "gcr-prompter"},  # tomb pinentry
        {"wname": "Terminator Preferences"},
        {"wmclass": "feh"},
        {"wmclass": "Pinentry-gtk-2"},
        {"wmclass": "sun-awt-X11-XWindowPeer"},  # pycharm popups
    ],
)


# ------------------------------------------------------------------------------
# SCREENS AND BARS -------------------------------------------------------------
# ------------------------------------------------------------------------------
widget_defaults = dict(font="sans", fontsize=12, padding=3)
extension_defaults = widget_defaults.copy()

bar_size = 24
bar_opacity = 0.6

net_interface = "enp3s0"
graph_config = dict(
    width=50, type="linefill", samples=20, line_width=2, interace=net_interface
)

separator_config = dict(linewidth=2, size_percent=50, padding=10)

hostname = platform.node()

def get_num_monitors():
    num_monitors = 0
    try:
        display = xdisplay.Display()
        screen = display.screen()
        resources = screen.root.xrandr_get_screen_resources()

        for output in resources.outputs:
            monitor = display.xrandr_get_output_info(output, resources.config_timestamp)
            preferred = False
            if hasattr(monitor, "preferred"):
                preferred = monitor.preferred
            elif hasattr(monitor, "num_preferred"):
                preferred = monitor.num_preferred
            if preferred:
                num_monitors += 1
    except Exception as e:
        # always setup at least one monitor
        logging.error(str(e))
        return 1
    else:
        return num_monitors

num_monitors = get_num_monitors()

logging.info("monitors number: %d" % num_monitors)

screens = [
    Screen(
        top=bar.Bar(
            [
                widget.CurrentScreen(
                    active_color="#0000ff",
                    active_text="■",
                    inactive_color="#333333",
                    inactive_text="■",
                ),
                widget.GroupBox(rounded=False),
                # widget.LaunchBar(progs=[
                #     ("terminator", "terminator", "terminator"),
                # ]),
                widget.WindowName(),
                widget.Prompt(),
                widget.Systray(padding=10),
                widget.Battery(discharge_char="↓", charge_char="↑", format="{percent:2.0%}{char}"),
                widget.TextBox(text="Layout:"),
                widget.CurrentLayout(),
                widget.CurrentLayoutIcon(scale=0.6),
                widget.Sep(**separator_config),
                widget.Clock(format="%Y.%m.%d %a %H:%M"),
            ],
            bar_size,
            opacity=bar_opacity,
        ),
    )
]

if num_monitors > 1:
    for m in range(num_monitors - 1):
        screens.append(
            Screen(
                top=bar.Bar(
                    [
                        widget.CurrentScreen(
                            active_color="#0000ff",
                            active_text="■",
                            inactive_color="#333333",
                            inactive_text="■",
                        ),
                        widget.GroupBox(rounded=False),
                        widget.WindowName(),
                        # widget.TaskList(),
                    ],
                    bar_size,
                    opacity=bar_opacity,
                )
            )
        )


# ------------------------------------------------------------------------------
# WINDOWN MANAGER NAME ---------------------------------------------------------
# ------------------------------------------------------------------------------
wmname = "qtile"


# ------------------------------------------------------------------------------
# VALIDATION -------------------------------------------------------------------
# ------------------------------------------------------------------------------
def find_similar_keys(key):
    import regex

    regexp = regex.compile(r"({}{{e<{}}})".format(key, len(key)), regex.IGNORECASE)
    similar_keys = []
    for qtile_key in keysyms.keys():
        if regexp.match(qtile_key):
            similar_keys.append(qtile_key)
    if not similar_keys:
        return "No key similar to '{}' could be found in libqtile.xkeysyms.keysyms :/".format(
            key
        )
    if len(similar_keys) == 1:
        return "Maybe you meant '{}'?".format(similar_keys[0])
    return "Maybe you meant '{}', or '{}'?".format(
        "', '".join(similar_keys[:-1]), similar_keys[-1]
    )


def validate_config(reload=True):
    from libqtile.core.xcore import XCore

    output = [
        "The configuration file '",
        __file__,
        "' generated the following error:\n\n",
    ]

    try:
        if reload:
            importlib.reload(sys.modules[__name__])
        Config.from_file(XCore(), __file__)
    except ConfigError as error:
        output.append(str(error))

        if str(error).startswith("No such key"):
            output.append("\n\n")
            key = str(error).replace("No such key: ", "")
            try:
                similar_keys = find_similar_keys(key)
            except ImportError:
                output.append("Install 'regex' if you want to see valid similar keys")
            else:
                output.append(similar_keys)
        raise ConfigError("".join(output))
    except Exception as error:
        output.append("{}: {}".format(sys.exc_info()[0].__name__, str(error)))
        raise ConfigError("".join(output))


if __name__ == "__main__":
    try:
        validate_config(reload=False)
    except ConfigError as error:
        print(str(error), file=sys.stderr)
        sys.exit(1)
    else:
        print("OK!")
        sys.exit(0)
```

**Comment by ramnes** [comment]
Is the issue happening with 0.15.x also? Do you have a composite manager running, and if so, does it happens without?

**Comment by cr1ogen** [comment]
will have something to do with #1446 bug?

**Comment by tych0** [comment]
I don't think it's related to #1446, this config doesn't have the KeyboardLayout widget in it.

**Comment by pawamoy** [comment]
I don't think either! So I just ran tests:
- issue only happens when compton (window compositor) is running
- even with compton running, it doesn't always happen, seems to be a bit random
- I collected some logs, will clean them a bit and update the post

**Comment by pawamoy** [comment]
Still happens on 0.15.1 but less often.

**Comment by pawamoy** [comment]
## Attempts to maximize

The first four attempts worked correctly, then you can see some differences

```
2020-04-27 17:24:01,169 - libqtile - DEBUG - Internal event: client_mouse_enter((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:01,173 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:01,174 - libqtile - DEBUG - Internal event: focus_change((), {})
2020-04-27 17:24:01,178 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:01,186 - libqtile - DEBUG - PropertyNotifyEvent: WM_HINTS
2020-04-27 17:24:01,191 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:02,969 - libqtile - INFO - Ignoring unknown button: 1
2020-04-27 17:24:02,969 - libqtile - INFO - Ignoring unknown button: 1
2020-04-27 17:24:02,969 - libqtile - INFO - Ignoring unknown button: 1
2020-04-27 17:24:02,969 - libqtile - DEBUG - Command: function((<function Qtile.__init__.<locals>.noop at 0x7fbd02a2c040>,), {})
2020-04-27 17:24:02,974 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:02,975 - libqtile - DEBUG - Internal event: focus_change((), {})
2020-04-27 17:24:02,980 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:02,982 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:02,996 - libqtile - DEBUG - Internal event: client_mouse_enter((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:04,217 - libqtile - INFO - Ignoring unknown button: 1
2020-04-27 17:24:04,217 - libqtile - INFO - Ignoring unknown button: 1
2020-04-27 17:24:04,217 - libqtile - INFO - Ignoring unknown button: 1
2020-04-27 17:24:04,218 - libqtile - DEBUG - Command: function((<function Qtile.__init__.<locals>.noop at 0x7fbd02a2c040>,), {})
2020-04-27 17:24:04,222 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:04,222 - libqtile - DEBUG - Internal event: focus_change((), {})
2020-04-27 17:24:04,225 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:04,230 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:04,239 - libqtile - DEBUG - Internal event: client_mouse_enter((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:06,559 - libqtile - INFO - Ignoring unknown button: 1
2020-04-27 17:24:06,559 - libqtile - INFO - Ignoring unknown button: 1
2020-04-27 17:24:06,559 - libqtile - INFO - Ignoring unknown button: 1
2020-04-27 17:24:06,560 - libqtile - DEBUG - Command: function((<function Qtile.__init__.<locals>.noop at 0x7fbd02a2c040>,), {})
2020-04-27 17:24:06,564 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:06,565 - libqtile - DEBUG - Internal event: focus_change((), {})
2020-04-27 17:24:06,568 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:06,570 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:06,579 - libqtile - DEBUG - Internal event: client_mouse_enter((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:09,090 - libqtile - INFO - Ignoring unknown button: 1
2020-04-27 17:24:09,090 - libqtile - INFO - Ignoring unknown button: 1
2020-04-27 17:24:09,090 - libqtile - INFO - Ignoring unknown button: 1
2020-04-27 17:24:09,091 - libqtile - DEBUG - Command: function((<function Qtile.__init__.<locals>.noop at 0x7fbd02a2c040>,), {})
2020-04-27 17:24:09,092 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:09,093 - libqtile - DEBUG - Internal event: focus_change((), {})
2020-04-27 17:24:09,094 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:09,095 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:09,098 - libqtile - DEBUG - Internal event: client_mouse_enter((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:09,298 - libqtile - DEBUG - PropertyNotifyEvent: _NET_WM_STATE
2020-04-27 17:24:09,299 - libqtile - DEBUG - _NET_WM_STATE: ['fullscreen', '_NET_WM_STATE_MAXIMIZED_VERT', '_NET_WM_STATE_MAXIMIZED_HORZ']
2020-04-27 17:24:09,304 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:09,304 - libqtile - DEBUG - Internal event: float_change((), {})
2020-04-27 17:24:09,324 - libqtile - DEBUG - PropertyNotifyEvent: _NET_WM_OPAQUE_REGION
2020-04-27 17:24:09,324 - libqtile - INFO - Unknown window property: _NET_WM_OPAQUE_REGION
2020-04-27 17:24:09,346 - libqtile - DEBUG - PropertyNotifyEvent: _NET_WM_OPAQUE_REGION
2020-04-27 17:24:09,346 - libqtile - INFO - Unknown window property: _NET_WM_OPAQUE_REGION
2020-04-27 17:24:17,401 - libqtile - INFO - Ignoring unknown button: 1
2020-04-27 17:24:17,401 - libqtile - INFO - Ignoring unknown button: 1
2020-04-27 17:24:17,402 - libqtile - INFO - Ignoring unknown button: 1
2020-04-27 17:24:17,402 - libqtile - DEBUG - Command: function((<function Qtile.__init__.<locals>.noop at 0x7fbd02a2c040>,), {})
2020-04-27 17:24:17,402 - libqtile - DEBUG - Internal event: focus_change((), {})
2020-04-27 17:24:17,403 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:17,403 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:17,405 - libqtile - DEBUG - Internal event: client_mouse_enter((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:17,539 - libqtile - DEBUG - PropertyNotifyEvent: _NET_WM_STATE
2020-04-27 17:24:17,540 - libqtile - DEBUG - _NET_WM_STATE: ['_NET_WM_STATE_MAXIMIZED_VERT', '_NET_WM_STATE_MAXIMIZED_HORZ']
2020-04-27 17:24:17,542 - libqtile - ERROR - Exception in layout bsp
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/group.py", line 160, in layout_all
    self.layout.layout(normal, screen)
  File "/usr/lib/python3.8/site-packages/libqtile/layout/base.py", line 57, in layout
    self.configure(i, screen)
  File "/usr/lib/python3.8/site-packages/libqtile/layout/bsp.py", line 209, in configure
    node.x,
AttributeError: 'NoneType' object has no attribute 'x'
2020-04-27 17:24:17,554 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:17,559 - libqtile - DEBUG - Internal event: client_focus((Window('Casually Explained: Levels of Wealth - YouTube - Mozilla Firefox'),), {})
2020-04-27 17:24:17,559 - libqtile - DEBUG - Internal event: float_change((), {})
2020-04-27 17:24:17,561 - libqtile - DEBUG - Expose
2020-04-27 17:24:17,561 - libqtile - DEBUG - Handling: Expose
2020-04-27 17:24:17,561 - libqtile - DEBUG - Expose
2020-04-27 17:24:17,561 - libqtile - DEBUG - Handling: Expose
2020-04-27 17:24:17,561 - libqtile - DEBUG - Expose
2020-04-27 17:24:17,561 - libqtile - DEBUG - Handling: Expose
2020-04-27 17:24:17,562 - libqtile - DEBUG - Expose
2020-04-27 17:24:17,562 - libqtile - DEBUG - Handling: Expose
2020-04-27 17:24:17,562 - libqtile - DEBUG - Expose
2020-04-27 17:24:17,562 - libqtile - INFO - Unhandled event: 'Expose'
```

Variants

```
2020-04-27 17:24:21,522 - libqtile - DEBUG - _NET_WM_STATE: ['fullscreen', '_NET_WM_STATE_MAXIMIZED_VERT', '_NET_WM_STATE_MAXIMIZED_HORZ']
```

```
2020-04-27 17:24:32,962 - libqtile - DEBUG - _NET_WM_STATE: ['_NET_WM_STATE_MAXIMIZED_VERT', '_NET_WM_STATE_MAXIMIZED_HORZ']
```

**Comment by pawamoy** [comment]
Here are the logs when the issue happens (0.15.1, with compton) and the same one when compton is not running:
[qtile-1658-compton.log](https://github.com/qtile/qtile/files/4540934/qtile-1658-compton.log)
[qtile-1658-no-compton.log](https://github.com/qtile/qtile/files/4540936/qtile-1658-no-compton.log)

Unfortunately, they look quite similar...
