### ISSUE TITLE
Some BSP errors in the logs

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1684]
```
2020-04-27 17:24:32,963 - libqtile - ERROR - Exception in layout bsp
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/group.py", line 160, in layout_all
    self.layout.layout(normal, screen)
  File "/usr/lib/python3.8/site-packages/libqtile/layout/base.py", line 57, in layout
    self.configure(i, screen)
  File "/usr/lib/python3.8/site-packages/libqtile/layout/bsp.py", line 209, in configure
    node.x,
AttributeError: 'NoneType' object has no attribute 'x'
```

```python
layouts = [
    layout.Max(),
    layout.Bsp(
        border_normal="#000000",
        border_focus="#ffffff",
        border_width=1,
        fair=False,
        lower_right=False,
        margin=20,
        grow_amount=1,
    ),
]
```

**Comment by tych0** [comment]
#1800 fixes this
