### ISSUE TITLE
Ampersands need to be escaped in WindowName widget

### ISSUE THREAD

**Issue by sffjunkie** [qtile/qtile#1685]
# Issue description
Ampersands in window names need to be changed in WindowName widget to "&amp;" before being passed to Pango/Cairo

# Qtile version
0.15.1

# Stack traces
Exception: parse_markup() failed for b'Seth Lakeman - King & Country'
2020-04-27 19:12:00,744 ERROR libqtile hook.py:fire():L373 Error in hook focus_change
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/hook.py", line 371, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/windowname.py", line 67, in update
    self.text = "%s%s" % (state, w.name if w and w.name else " ")
  File "/usr/lib/python3.8/site-packages/libqtile/widget/base.py", line 323, in text
    self.layout.text = self.formatted_text
  File "/usr/lib/python3.8/site-packages/libqtile/drawer.py", line 70, in text
    attrlist, value, accel_char = pangocffi.parse_markup(value)
  File "/usr/lib/python3.8/site-packages/libqtile/pangocffi.py", line 173, in parse_markup
    raise Exception("parse_markup() failed for %s" % value)
Exception: parse_markup() failed for b'Seth Lakeman - King & Country'

# Configuration
N/A

**Comment by ramnes** [comment]
Fixed, thanks for raising this issue!
