### ISSUE TITLE
Volume Widget: FileNotFoundError: [Errno 2] No such file or directory: 'amixer'

### ISSUE THREAD

**Issue by 20jam** [qtile/qtile#1711]
# Issue description
The default volume widget doesn't work with me. 
I have pamixer installed and not amixer, and no matter how I play with the variables. it wont work and spit the following error:

```
2020-05-08 08:25:38,036 libqtile base.py:_wrapper():L284  got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/widget/base.py", line 282, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/volume.py", line 132, in update
    vol = self.get_volume()
  File "/usr/lib/python3.8/site-packages/libqtile/widget/volume.py", line 194, in get_volume
    mixer_out = self.call_process(get_volume_cmd)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/base.py", line 276, in call_process
    output = subprocess.check_output(command, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'amixer'
^[;^[;

```

# Qtile version
0.15.1-1

# Stack traces

```
2020-05-08 08:25:35,594 ERROR libqtile xcore.py:_xpoll():L270 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/backend/x11/xcore.py", line 231, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2020-05-08 08:25:35,595 INFO libqtile qtile.py:main():L154 Exiting...
2020-05-08 08:25:35,598 WARNING libqtile xcbq.py:set_property():L687 X error in SetProperty (wid=62914561, prop='WM_STATE'), ignoring
2020-05-08 08:25:37,498 WARNING libqtile xcursors.py:_setup_xcursor_binding():L112 xcb-cursor not found, fallback to font pointer
2020-05-08 08:25:37,734 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.launchbar.LaunchBar', No module named 'xdg'
2020-05-08 08:25:37,738 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2020-05-08 08:25:37,748 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.khal_calendar.KhalCalendar', No module named 'dateutil'
2020-05-08 08:25:37,750 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
2020-05-08 08:25:37,765 INFO libqtile clock.py:__init__():L60 Defaulting to the system local timezone.
2020-05-08 08:25:37,769 INFO libqtile clock.py:__init__():L60 Defaulting to the system local timezone.
2020-05-08 08:25:38,036 ERROR libqtile base.py:_wrapper():L284 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/widget/base.py", line 282, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/volume.py", line 132, in update
    vol = self.get_volume()
  File "/usr/lib/python3.8/site-packages/libqtile/widget/volume.py", line 194, in get_volume
    mixer_out = self.call_process(get_volume_cmd)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/base.py", line 276, in call_process
    output = subprocess.check_output(command, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'amixer'
2020-05-08 08:26:30,285 WARNING libqtile xcbq.py:set_property():L687 X error in SetProperty (wid=25203987, prop='WM_STATE'), ignoring
2020-05-08 08:28:55,842 WARNING libqtile xcbq.py:set_property():L687 X error in SetProperty (wid=98566150, prop='WM_STATE'), ignoring

```
# Configuration
                widget.Volume(
                    volume_app="pamixer",
                    get_volume_command="pamixer --get-volume-human",
                    theme_path=home+'/.config/qtile/icons',
                    ),

**Comment by 20jam** [comment]
Oh my bad, there's actually a widget just for pulse, okay, never mind, however, does the same setting apply? the theme_path and everything.

THANKSSSSS

**Comment by 20jam** [comment]
Just as I expected for everything to work nicely, 

The following error occurred with setting the theme_path:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/site-packages/libqtile/core/manager.py", line 855, in f
    func(*args)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/pulse_volume.py", line 261, in timer_setup
    self.poll()
  File "/usr/lib/python3.8/site-packages/libqtile/widget/pulse_volume.py", line 234, in poll
    self.update()
  File "/usr/lib/python3.8/site-packages/libqtile/widget/pulse_volume.py", line 246, in update
    self._update_drawer()
  File "/usr/lib/python3.8/site-packages/libqtile/widget/volume.py", line 153, in _update_drawer
    self.drawer.ctx.set_source(self.surfaces[img_name])
KeyError: 'audio-volume-muted'
```
I have audio-volume-muted in my path.

**Comment by ramnes** [comment]
Can you please make a dedicated issue for that theme_path problem?
