### ISSUE TITLE
CommandClient not working in config file?

### ISSUE THREAD

**Issue by aMOPel** [qtile/qtile#1752]
# Issue description

so i wanted to script some windows to always open on startup, the hook works fine, however since there is no qtile object given with the hook i need to make an InteractiveCommandClient instance to interact with the current qtile instance. at least thats how i understood things.
Instanciation works fine, however as soon as i call something of the commandclient i get an error in the asynchio lib:
```
File "/usr/lib/python3.7/asyncio/base_events.py", line 521, in run_forever
    raise RuntimeError('This event loop is already running')
```

and if i dont reload it but restart it then i get another error from the ipc module:
```
libqtile.ipc.IPCError: Could not open /home/momo/.cache/qtile/qtilesocket.:0.0
```

so basically i dont understand how to use the commandclient, espacially because if i go into the actual qtile directory and start an python interpreter, it actually works, but i dont understand how  to put it in script.

```
+ ~/local/qtile  % python                                                                                                                                                         
Python 3.7.5 (default, Apr 19 2020, 20:18:17)
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from libqtile.command_client import InteractiveCommandClient
>>> c = InteractiveCommandClient()
>>> c.status()
'OK'
>>>
```
# Qtile version
0.15.1 (venv)

commit hash
db0f044f8968f4bccad006fb001a87a98742c9a0
# Stack traces
## from restart (lazy.cmd_restart or smth):
```
2020-05-25 18:26:53,818 ERROR libqtile confreader.py:load():L103 Could not import config file '/home/momo/.config/qtile/config.py'
Traceback (most recent call last):
  File "/home/momo/local/qtile/libqtile/confreader.py", line 99, in load
    config = __import__(name)  # noqa: F811
  File "/home/momo/.config/qtile/config.py", line 286, in <module>
    logger.error(c.status())
  File "/home/momo/local/qtile/libqtile/command_client.py", line 211, in __getattr__
    if not self._command.has_command(self._current_node, name):
  File "/home/momo/local/qtile/libqtile/command_interface.py", line 258, in has_command
    commands = self.execute(cmd_call, (), {})
  File "/home/momo/local/qtile/libqtile/command_interface.py", line 231, in execute
    call.parent.selectors, call.name, args, kwargs
  File "/home/momo/local/qtile/libqtile/ipc.py", line 206, in send
    _, client_proto = self.loop.run_until_complete(client_coroutine)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 566, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 521, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2020-05-25 18:26:53,820 ERROR libqtile manager.py:cmd_restart():L1118 Preventing restart because of a configuration error: Traceback (most recent call last):
  File "/home/momo/local/qtile/libqtile/confreader.py", line 99, in load
    config = __import__(name)  # noqa: F811
  File "/home/momo/.config/qtile/config.py", line 286, in <module>
    logger.error(c.status())
  File "/home/momo/local/qtile/libqtile/command_client.py", line 211, in __getattr__
    if not self._command.has_command(self._current_node, name):
  File "/home/momo/local/qtile/libqtile/command_interface.py", line 258, in has_command
    commands = self.execute(cmd_call, (), {})
  File "/home/momo/local/qtile/libqtile/command_interface.py", line 231, in execute
    call.parent.selectors, call.name, args, kwargs
  File "/home/momo/local/qtile/libqtile/ipc.py", line 206, in send
    _, client_proto = self.loop.run_until_complete(client_coroutine)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 566, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 521, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```
## when quiting and coming back in:
```
2020-05-25 18:46:12,236 ERROR libqtile confreader.py:load():L103 Could not import config file '/home/momo/.config/qtile/config.py'
Traceback (most recent call last):
  File "/home/momo/local/qtile/libqtile/ipc.py", line 206, in send
    _, client_proto = self.loop.run_until_complete(client_coroutine)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 232, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 469, in _sock_connect
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/momo/local/qtile/libqtile/confreader.py", line 99, in load
    config = __import__(name)  # noqa: F811
  File "/home/momo/.config/qtile/config.py", line 285, in <module>
    logger.error(c.status())
  File "/home/momo/local/qtile/libqtile/command_client.py", line 211, in __getattr__
    if not self._command.has_command(self._current_node, name):
  File "/home/momo/local/qtile/libqtile/command_interface.py", line 258, in has_command
    commands = self.execute(cmd_call, (), {})
  File "/home/momo/local/qtile/libqtile/command_interface.py", line 231, in execute
    call.parent.selectors, call.name, args, kwargs
  File "/home/momo/local/qtile/libqtile/ipc.py", line 208, in send
    raise IPCError("Could not open %s" % self.fname)
libqtile.ipc.IPCError: Could not open /home/momo/.cache/qtile/qtilesocket.:0.0
2020-05-25 18:46:12,238 ERROR libqtile qtile.py:make_qtile():L129 Error while reading config file (Traceback (most recent call last):
  File "/home/momo/local/qtile/libqtile/ipc.py", line 206, in send
    _, client_proto = self.loop.run_until_complete(client_coroutine)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 232, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 469, in _sock_connect
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/momo/local/qtile/libqtile/confreader.py", line 99, in load
    config = __import__(name)  # noqa: F811
  File "/home/momo/.config/qtile/config.py", line 285, in <module>
    logger.error(c.status())
  File "/home/momo/local/qtile/libqtile/command_client.py", line 211, in __getattr__
    if not self._command.has_command(self._current_node, name):
  File "/home/momo/local/qtile/libqtile/command_interface.py", line 258, in has_command
    commands = self.execute(cmd_call, (), {})
  File "/home/momo/local/qtile/libqtile/command_interface.py", line 231, in execute
    call.parent.selectors, call.name, args, kwargs
  File "/home/momo/local/qtile/libqtile/ipc.py", line 208, in send
    raise IPCError("Could not open %s" % self.fname)
libqtile.ipc.IPCError: Could not open /home/momo/.cache/qtile/qtilesocket.:0.0
)
Traceback (most recent call last):
  File "/home/momo/local/qtile/libqtile/ipc.py", line 206, in send
    _, client_proto = self.loop.run_until_complete(client_coroutine)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 232, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 469, in _sock_connect
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/momo/local/qtile/libqtile/confreader.py", line 99, in load
    config = __import__(name)  # noqa: F811
  File "/home/momo/.config/qtile/config.py", line 285, in <module>
    logger.error(c.status())
  File "/home/momo/local/qtile/libqtile/command_client.py", line 211, in __getattr__
    if not self._command.has_command(self._current_node, name):
  File "/home/momo/local/qtile/libqtile/command_interface.py", line 258, in has_command
    commands = self.execute(cmd_call, (), {})
  File "/home/momo/local/qtile/libqtile/command_interface.py", line 231, in execute
    call.parent.selectors, call.name, args, kwargs
  File "/home/momo/local/qtile/libqtile/ipc.py", line 208, in send
    raise IPCError("Could not open %s" % self.fname)
libqtile.ipc.IPCError: Could not open /home/momo/.cache/qtile/qtilesocket.:0.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/momo/local/qtile/libqtile/scripts/qtile.py", line 127, in make_qtile
    config = confreader.Config.from_file(options.configfile, kore=kore)
  File "/home/momo/local/qtile/libqtile/confreader.py", line 85, in from_file
    cnf.load()
  File "/home/momo/local/qtile/libqtile/confreader.py", line 105, in load
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/home/momo/local/qtile/libqtile/ipc.py", line 206, in send
    _, client_proto = self.loop.run_until_complete(client_coroutine)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 232, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 469, in _sock_connect
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/momo/local/qtile/libqtile/confreader.py", line 99, in load
    config = __import__(name)  # noqa: F811
  File "/home/momo/.config/qtile/config.py", line 285, in <module>
    logger.error(c.status())
  File "/home/momo/local/qtile/libqtile/command_client.py", line 211, in __getattr__
    if not self._command.has_command(self._current_node, name):
  File "/home/momo/local/qtile/libqtile/command_interface.py", line 258, in has_command
    commands = self.execute(cmd_call, (), {})
  File "/home/momo/local/qtile/libqtile/command_interface.py", line 231, in execute
    call.parent.selectors, call.name, args, kwargs
  File "/home/momo/local/qtile/libqtile/ipc.py", line 208, in send
    raise IPCError("Could not open %s" % self.fname)
libqtile.ipc.IPCError: Could not open /home/momo/.cache/qtile/qtilesocket.:0.0
```

# Configuration

```
from libqtile.command_client import InteractiveCommandClient
c = InteractiveCommandClient()

logger.error(c.status())
```

**Comment by ramnes** [comment]
Did you try using the `main` function? It receives an instance of the manager.

For example: https://github.com/ramnes/qtile-config/blob/master/config.py#L282-L289

**Comment by aMOPel** [comment]
yes this works for me, however thats not the way its supposed to be done is it?

is the command client in the config working for you?

**Comment by ramnes** [comment]
The command clients are meant for remote scriptability, I'm not surprised if they do not work in the configuration. @flacjacket @tych0 do you want to support this?

**Comment by aMOPel** [comment]
what do you mean with remote scriptability? what would be a working setup? where should i put my script and how should i call it to make use of the command client?

**Comment by tych0** [comment]
No, I don't want to support IPC to the same process. Just use the various hooks.

The config file is a special file, read in the qtile process as it's starting up. There's no need to use the IPC client to interact with the qtile object there, you can do it directly (modulo issues like #1719).

**Comment by flacjacket** [comment]
I agree, running the IPC client out of the config seems very odd.

In a hook that receives a `qtile` instance or in the config `main`, it is possible to wrap that in an interactive command client, like:
```
q = InteractiveCommandClient(QtileCommandInterface(qtile))
q.status()
```
This would give some easier access to the `cmd_` functions if you wanted to run several of them or apply some additional logic to them that couldn't be handled by a simple `lazy` command. But this is something that you wouldn't want to run when the config is loaded, as you need to have the `qtile` instance to wrap.
