### ISSUE TITLE
startup error: no module, syntax error

### ISSUE THREAD

**Issue by sirakai-pc** [qtile/qtile#1802]
# Qtile failed to start, here's the qtile log:
`2020-07-04 05:52:58,255 ERROR libqtile confreader.py:from_file():L91 Could not import config file '/home/sirakai/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 87, in from_file
    config = __import__(os.path.basename(path)[:-3])  # noqa: F811
  File "/home/sirakai/.config/qtile/config.py", line 31
    Key([mod, "mod1"], "s", lazy.spawn("systemctl reboot") #Reboot
    ^
SyntaxError: invalid syntax
2020-07-04 05:52:58,255 ERROR libqtile qtile.py:make_qtile():L129 Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 87, in from_file
    config = __import__(os.path.basename(path)[:-3])  # noqa: F811
  File "/home/sirakai/.config/qtile/config.py", line 31
    Key([mod, "mod1"], "s", lazy.spawn("systemctl reboot") #Reboot
    ^
SyntaxError: invalid syntax
)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 87, in from_file
    config = __import__(os.path.basename(path)[:-3])  # noqa: F811
  File "/home/sirakai/.config/qtile/config.py", line 31
    Key([mod, "mod1"], "s", lazy.spawn("systemctl reboot") #Reboot
    ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/scripts/qtile.py", line 127, in make_qtile
    config = confreader.Config.from_file(kore, options.configfile)
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 93, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 87, in from_file
    config = __import__(os.path.basename(path)[:-3])  # noqa: F811
  File "/home/sirakai/.config/qtile/config.py", line 31
    Key([mod, "mod1"], "s", lazy.spawn("systemctl reboot") #Reboot
    ^
SyntaxError: invalid syntax

2020-07-04 05:52:58,461 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2020-07-04 05:52:58,466 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2020-07-04 05:52:58,467 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.khal_calendar.KhalCalendar', No module named 'dateutil'
2020-07-04 05:52:58,468 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
`

I found some possible solutions for "No module named x" issue, **they didn't work**. I don't know what could be the syntax error.

# Qtile version

# Stack traces

# Configuration
[config.py](https://pastebin.com/QUL9hTvu)

**Comment by tych0** [comment]
Looks like you need a close paren in the line before in your config file.

**Comment by sirakai-pc** [comment]
@tych0 I don't understan where I need to put this "close paren", what line before?
) -> is this a close paren?

**Comment by sirakai-pc** [comment]
I kind of resolved that SyntaxError, now I don't understand this new crash log:
`2020-07-04 20:54:46,541 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2020-07-04 20:54:46,546 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2020-07-04 20:54:46,547 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.khal_calendar.KhalCalendar', No module named 'dateutil'
2020-07-04 20:54:46,548 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
2020-07-04 20:54:46,555 ERROR libqtile confreader.py:from_file():L91 Could not import config file '/home/sirakai/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 87, in from_file
    config = __import__(os.path.basename(path)[:-3])  # noqa: F811
  File "/home/sirakai/.config/qtile/config.py", line 58, in <module>
    Key([mod], "space", lazy.layouALTt.next()),  # Switch window focus to other pane(s) of stack
  File "/usr/lib/python3.8/site-packages/libqtile/command.py", line 35, in __getattr__
    return super().__getattr__(name)
  File "/usr/lib/python3.8/site-packages/libqtile/command_client.py", line 200, in __getattr__
    raise SelectError("Cannot select children of call", name, self._current_node.selectors)
libqtile.command_object.SelectError: Cannot select children of call, name: next, selectors: []
2020-07-04 20:54:46,556 ERROR libqtile qtile.py:make_qtile():L129 Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 87, in from_file
    config = __import__(os.path.basename(path)[:-3])  # noqa: F811
  File "/home/sirakai/.config/qtile/config.py", line 58, in <module>
    Key([mod], "space", lazy.layouALTt.next()),  # Switch window focus to other pane(s) of stack
  File "/usr/lib/python3.8/site-packages/libqtile/command.py", line 35, in __getattr__
    return super().__getattr__(name)
  File "/usr/lib/python3.8/site-packages/libqtile/command_client.py", line 200, in __getattr__
    raise SelectError("Cannot select children of call", name, self._current_node.selectors)
libqtile.command_object.SelectError: Cannot select children of call, name: next, selectors: []
)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 87, in from_file
    config = __import__(os.path.basename(path)[:-3])  # noqa: F811
  File "/home/sirakai/.config/qtile/config.py", line 58, in <module>
    Key([mod], "space", lazy.layouALTt.next()),  # Switch window focus to other pane(s) of stack
  File "/usr/lib/python3.8/site-packages/libqtile/command.py", line 35, in __getattr__
    return super().__getattr__(name)
  File "/usr/lib/python3.8/site-packages/libqtile/command_client.py", line 200, in __getattr__
    raise SelectError("Cannot select children of call", name, self._current_node.selectors)
libqtile.command_object.SelectError: Cannot select children of call, name: next, selectors: []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/scripts/qtile.py", line 127, in make_qtile
    config = confreader.Config.from_file(kore, options.configfile)
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 93, in from_file
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 87, in from_file
    config = __import__(os.path.basename(path)[:-3])  # noqa: F811
  File "/home/sirakai/.config/qtile/config.py", line 58, in <module>
    Key([mod], "space", lazy.layouALTt.next()),  # Switch window focus to other pane(s) of stack
  File "/usr/lib/python3.8/site-packages/libqtile/command.py", line 35, in __getattr__
    return super().__getattr__(name)
  File "/usr/lib/python3.8/site-packages/libqtile/command_client.py", line 200, in __getattr__
    raise SelectError("Cannot select children of call", name, self._current_node.selectors)
libqtile.command_object.SelectError: Cannot select children of call, name: next, selectors: []

`

**Comment by sirakai-pc** [comment]
Resolved other errors.. Here is the last(I wish):
`2020-07-04 21:07:39,774 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.mpd2widget.Mpd2', No module named 'mpd'
2020-07-04 21:07:39,779 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.wlan.Wlan', No module named 'iwlib'
2020-07-04 21:07:39,780 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.khal_calendar.KhalCalendar', No module named 'dateutil'
2020-07-04 21:07:39,780 WARNING libqtile utils.py:safe_import():L191 Unmet dependencies for optional Widget: '.widget.imapwidget.ImapWidget', No module named 'keyring'
2020-07-04 21:07:39,792 ERROR libqtile qtile.py:make_qtile():L129 Error while reading config file (No such key: <libqtile.lazy.LazyCall object at 0x7f997dcab4f0>)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/scripts/qtile.py", line 127, in make_qtile
    config = confreader.Config.from_file(kore, options.configfile)
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 95, in from_file
    cnf.validate(kore)
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 109, in validate
    raise ConfigError("No such key: %s" % k.key)
libqtile.confreader.ConfigError: No such key: <libqtile.lazy.LazyCall object at 0x7f997dcab4f0>
2020-07-04 21:16:08,251 ERROR libqtile qtile.py:make_qtile():L129 Error while reading config file (No such key: <libqtile.lazy.LazyCall object at 0x7f5387df62b0>)
Traceback (most recent call last):
  File "/home/sirakai/.local/lib/python3.8/site-packages/libqtile/scripts/qtile.py", line 127, in make_qtile
    config = confreader.Config.from_file(options.configfile, kore=kore)
  File "/home/sirakai/.local/lib/python3.8/site-packages/libqtile/confreader.py", line 85, in from_file
    cnf.load()
  File "/home/sirakai/.local/lib/python3.8/site-packages/libqtile/confreader.py", line 109, in load
    self.validate()
  File "/home/sirakai/.local/lib/python3.8/site-packages/libqtile/confreader.py", line 122, in validate
    raise ConfigError("No such key: %s" % k.key)
libqtile.confreader.ConfigError: No such key: <libqtile.lazy.LazyCall object at 0x7f5387df62b0>
`

**Comment by sirakai-pc** [comment]
Do I need to open a new issue for this error?

**Comment by tych0** [comment]
Sure, the lazy call stuff was done by @ramnes, maybe he has some idea?
