### ISSUE TITLE
 TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType

### ISSUE THREAD

**Issue by deliciouslytyped** [qtile/qtile#1844]
I get the following traceback when I start qtile 0.16.0, and launch some applications in it, from a script.
Only MonadTall is enabled and otherwise I use the default config, I'm not actually sure at what point of execution / shutdown the error happens.
```
2020-07-25 04:00:49,282 libqtile hook.py:fire():L376  Error in hook focus_change
Traceback (most recent call last):
  File "/nix/store/0njfdkjw85bb685fbklm84v5j9blqm4c-qtile-0.16.0/lib/python3.7/site-packages/libqtile/hook.py", line 374, in fire
    i(*args, **kwargs)
  File "/nix/store/0njfdkjw85bb685fbklm84v5j9blqm4c-qtile-0.16.0/lib/python3.7/site-packages/libqtile/widget/windowname.py", line 68, in update
    self.text = pangocffi.markup_escape_text(unescaped)
  File "/nix/store/0njfdkjw85bb685fbklm84v5j9blqm4c-qtile-0.16.0/lib/python3.7/site-packages/libqtile/widget/base.py", line 336, in text
    self.layout.text = self.formatted_text
  File "/nix/store/0njfdkjw85bb685fbklm84v5j9blqm4c-qtile-0.16.0/lib/python3.7/site-packages/libqtile/drawer.py", line 71, in text
    self.layout.set_attributes(attrlist)
  File "/nix/store/0njfdkjw85bb685fbklm84v5j9blqm4c-qtile-0.16.0/lib/python3.7/site-packages/libqtile/pangocffi.py", line 111, in set_attributes
    pango.pango_layout_set_attributes(self._pointer, attrs)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
Exception in callback Qtile.call_soon.<locals>.f() at /nix/store/0njfdkjw85bb685fbklm84v5j9blqm4c-qtile-0.16.0/lib/python3.7/site-packages/libqtile/core/manager.py:912
handle: <Handle Qtile.call_soon.<locals>.f() at /nix/store/0njfdkjw85bb685fbklm84v5j9blqm4c-qtile-0.16.0/lib/python3.7/site-packages/libqtile/core/manager.py:912>
Traceback (most recent call last):
  File "/nix/store/k2w1idz2vdag50xl88113845mr74z823-python3-3.7.7/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/nix/store/0njfdkjw85bb685fbklm84v5j9blqm4c-qtile-0.16.0/lib/python3.7/site-packages/libqtile/core/manager.py", line 913, in f
    func(*args)
  File "/nix/store/0njfdkjw85bb685fbklm84v5j9blqm4c-qtile-0.16.0/lib/python3.7/site-packages/libqtile/bar.py", line 332, in _actual_draw
    self._resize(self.length, self.widgets)
  File "/nix/store/0njfdkjw85bb685fbklm84v5j9blqm4c-qtile-0.16.0/lib/python3.7/site-packages/libqtile/bar.py", line 235, in _resize
    [i.length for i in widgets if i.length_type != STRETCH]
  File "/nix/store/0njfdkjw85bb685fbklm84v5j9blqm4c-qtile-0.16.0/lib/python3.7/site-packages/libqtile/bar.py", line 235, in <listcomp>
    [i.length for i in widgets if i.length_type != STRETCH]
  File "/nix/store/0njfdkjw85bb685fbklm84v5j9blqm4c-qtile-0.16.0/lib/python3.7/site-packages/libqtile/widget/base.py", line 143, in length
    return int(self.calculate_length())
  File "/nix/store/0njfdkjw85bb685fbklm84v5j9blqm4c-qtile-0.16.0/lib/python3.7/site-packages/libqtile/widget/base.py", line 395, in calculate_length
    self.layout.width,
  File "/nix/store/0njfdkjw85bb685fbklm84v5j9blqm4c-qtile-0.16.0/lib/python3.7/site-packages/libqtile/drawer.py", line 79, in width
    return self.layout.get_pixel_size()[0]
  File "/nix/store/0njfdkjw85bb685fbklm84v5j9blqm4c-qtile-0.16.0/lib/python3.7/site-packages/libqtile/pangocffi.py", line 131, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
```

**Comment by tych0** [comment]
Seems like this has to happen during shutdown, right?

**Comment by ramnes** [comment]
I just had that very same issue in a fail of the test suite because of a bug I introduced to Qtile's code. Looks like we're doing something wrong somewhere with our error handling.

**Comment by ramnes** [comment]
@tych0 If you want to run the buggy branch that triggers this, it's here: https://github.com/ramnes/qtile/tree/1844-demo

Just run `pytest test/test_manager.py -x` and should have the same errors.

**Comment by tych0** [comment]
I think we should blame @flacjacket for this one actually :)

**Comment by deliciouslytyped** [comment]
Sigh stale bots, so is this fixed yet?

**Comment by jagguli** [comment]
I'm having the same issue on restart

**Comment by elParaguayo** [comment]
jagguli, can you share your config and the full error from your logfile? I've seen this with some widgets but I'll need that info to track this one down.

**Comment by Bart97** [comment]
I've encountered the same issue when trying to reload config when subscribe.screen_change hook is called. Here's the full log:

```
2021-12-31 23:08:17,683 ERROR libqtile loop.py:_handle_exception():L64 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 833, in f
    func(*args)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 564, in timer_setup
    update_interval = self.tick()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/clock.py", line 72, in tick
    self.update(self.poll())
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 535, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 135, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2021-12-31 23:08:17,862 ERROR libqtile loop.py:_handle_exception():L64 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 833, in f
    func(*args)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 564, in timer_setup
    update_interval = self.tick()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/clock.py", line 72, in tick
    self.update(self.poll())
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 535, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 135, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2021-12-31 23:08:17,887 ERROR libqtile loop.py:_handle_exception():L64 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 833, in f
    func(*args)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 564, in timer_setup
    update_interval = self.tick()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/clock.py", line 72, in tick
    self.update(self.poll())
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 535, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 135, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2021-12-31 23:08:17,901 ERROR libqtile loop.py:_handle_exception():L64 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 833, in f
    func(*args)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 564, in timer_setup
    update_interval = self.tick()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/clock.py", line 72, in tick
    self.update(self.poll())
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 535, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 135, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2021-12-31 23:08:17,961 ERROR libqtile base.py:on_done():L632 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 624, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 535, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 135, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2021-12-31 23:08:17,971 ERROR libqtile base.py:_wrapper():L347 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 345, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/volume.py", line 117, in update
    self._update_drawer()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/volume.py", line 146, in _update_drawer
    self.text = 'M'
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 401, in text
    self.layout.text = self.formatted_text
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 72, in text
    self.layout.set_attributes(attrlist)
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 115, in set_attributes
    pango.pango_layout_set_attributes(self._pointer, attrs)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2021-12-31 23:08:17,990 ERROR libqtile base.py:on_done():L632 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 624, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 535, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 135, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2021-12-31 23:08:17,990 ERROR libqtile base.py:on_done():L632 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 624, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 535, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 135, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2021-12-31 23:08:17,991 ERROR libqtile base.py:on_done():L632 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 624, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 535, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 135, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2021-12-31 23:08:18,079 ERROR libqtile base.py:_wrapper():L347 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 345, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/volume.py", line 117, in update
    self._update_drawer()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/volume.py", line 146, in _update_drawer
    self.text = 'M'
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 401, in text
    self.layout.text = self.formatted_text
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 72, in text
    self.layout.set_attributes(attrlist)
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 115, in set_attributes
    pango.pango_layout_set_attributes(self._pointer, attrs)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2021-12-31 23:08:18,114 ERROR libqtile base.py:_wrapper():L347 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 345, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/volume.py", line 117, in update
    self._update_drawer()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/volume.py", line 146, in _update_drawer
    self.text = 'M'
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 401, in text
    self.layout.text = self.formatted_text
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 72, in text
    self.layout.set_attributes(attrlist)
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 115, in set_attributes
    pango.pango_layout_set_attributes(self._pointer, attrs)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2021-12-31 23:08:18,144 ERROR libqtile base.py:_wrapper():L347 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 345, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/volume.py", line 117, in update
    self._update_drawer()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/volume.py", line 146, in _update_drawer
    self.text = 'M'
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 401, in text
    self.layout.text = self.formatted_text
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 72, in text
    self.layout.set_attributes(attrlist)
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 115, in set_attributes
    pango.pango_layout_set_attributes(self._pointer, attrs)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2021-12-31 23:08:18,273 ERROR libqtile loop.py:_handle_exception():L64 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
NoneType: None
2021-12-31 23:08:18,277 ERROR libqtile loop.py:_handle_exception():L64 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
NoneType: None
2021-12-31 23:08:18,278 ERROR libqtile loop.py:_handle_exception():L64 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
NoneType: None
2021-12-31 23:08:18,280 ERROR libqtile loop.py:_handle_exception():L64 initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
NoneType: None
```
This is how my hook looks like:
```
@hook.subscribe.screen_change
def on_screens_reconfigured(_):
   qtile.cmd_reload_config()
```

I've also tried hooking to screens_reconfigured, but the result is the same.

**Comment by m-col** [comment]
@Bart97 we just changed when `screens_reconfigured` fires. Perhaps try using that again (if running from the git version) and seeing if it persists?

**Comment by elParaguayo** [comment]
If we can find a reliable way to recreate this I'm happy to work on a fix.

**Comment by Riazzor** [comment]
Hello.

I am having the same issue with this function : <br>
```py
@libqtile.hook.subscribe.startup_once
def command_at_startup():
    subprocess.run(['xscreensaver', '-nosplash'])
```
It doesn't work even with default_config.py<br>

I would like to point out that the screensaver does actually work if I wait long enough.<br>
But the rest doesn't. Feel free to ask if you need more information.

**Comment by m-col** [comment]
@Riazzor you're getting the same issue as in you're getting the above log output? If so, are you sure it's that function that's causing it?
