### ISSUE TITLE
Qtile creshes after unlocking session (light-locker)

### ISSUE THREAD

**Issue by LongerHV** [qtile/qtile#1886]
# Issue description
After I lock a screen with light-locker and unlock it again, every other time qtile crashes.

# Qtile version
0.16.1

# OS
Distro: Arch linux
Kernel: 5.8.5-zen1
(same result on 5.4.61-1-lts)

# Stack traces
2020-08-27 21:57:49,037 ERROR libqtile xcore.py:_xpoll():L269 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 610, in poll_for_event
    self.invalid()
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/backend/x11/xcore.py", line 230, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2020-08-27 21:57:49,039 ERROR libqtile manager.py:finalize():L320 exception during finalize
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/core/manager.py", line 310, in finalize
    widget.finalize()
  File "/usr/lib/python3.8/site-packages/libqtile/widget/base.py", line 208, in finalize
    self.drawer.finalize()
  File "/usr/lib/python3.8/site-packages/libqtile/drawer.py", line 247, in finalize
    self.qtile.conn.conn.core.FreeGC(self.gc)
  File "/usr/lib/python3.8/site-packages/xcffib/xproto.py", line 3027, in FreeGC
    return self.send_request(60, buf, is_checked=is_checked)
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2020-08-27 21:57:49,040 ERROR libqtile xcbq.py:disconnect():L894 Failed to disconnect, connection already failed?

# Configuration
https://gitlab.com/LongerHV/.dotfiles/-/tree/master/.config/qtile

**Comment by Caduser2020** [comment]
I have the same issue. I would like to help with this bug as my computer goes to sleep frequently.
Qtile: 0.16.1

**Comment by ramnes** [comment]
Best way to help with a bug is always to bisect the faulty commit. :)

**Comment by Caduser2020** [comment]
This appears to be an Xorg issue as the same problem appears on spectrwm.

**Comment by ramnes** [comment]
I'll close by assuming it's not on our side as it seems indeed much more likely that it's a Xorg problem. Feel free to comment, I'll reopen if needed.

**Comment by jjrugui** [comment]
I am experiencing the exact same error only with my particular config file. If I use the default config file I can execute qtile without any problem. I'm going to try and see if downgrading Xorg helps but otherwise, any tips on how to debug it?

**Comment by ramnes** [comment]
Can you share your config file @jjrugui ?

**Comment by jjrugui** [comment]
I started from scratch since I didn't have much in my config file and it works without an issue.  If I have any issue while configuring it from scratch while iterating over the file, I'll report here (in case it has to do with a widget, bar, etc).
For reference I'm using Arch, kernel 5.9.1 and I installed from the git repo in a python env with this packages:

```
cairocffi==1.1.0
cffi==1.14.3
dbus-python==1.2.16
iwlib==1.7.0
psutil==5.7.3
pycairo==1.20.0
pycparser==2.20
PyGObject==3.38.0
qtile==0.16.1
six==1.15.0
xcffib==0.10.1
```
Here's the old config file though:

```from typing import List  # noqa: F401

from libqtile import bar, layout, widget
from libqtile.config import Click, Drag, Group, Key, Screen
from libqtile.lazy import lazy
from libqtile.utils import guess_terminal
import os
import subprocess
from libqtile import hook

# Consts
mod = "mod4"
terminal = guess_terminal()
MARGIN = 10
BORDER_WIDTH = 3
COLORS = {
        'nord0': "#2E3440",
        'nord1': "#3B4252",
        'nord2': "#434C5E",
        'nord3': "#4C566A",
        'nord4': "#D8DEE9",
        'nord5': "#E5E9F0",
        'nord6': "#ECEFF4",
        'nord7': "#8FBCBB",
        'nord8': "#88C0D0",
        'nord9': "#81A1C1",
        'nord10': "#5E81AC",
        'nord11': "#BF616A",
        'nord12': "#D08770",
        'nord13': "#EBCB8B",
        'nord14': "#A3BE8C",
        'nord15': "#B48EAD",
        }

FONTS = {
        "font":  "sans",
        "fontsize": 20
        }


# Autostart scripts
@hook.subscribe.startup_once
def autostart():
    home = os.path.expanduser('~/.config/qtile/autostart.sh')
    subprocess.call([home])
    # Dunst for notification
    subprocess.call(["dunst"])

#########
#KEYBINDS
#########

keys = [
    # Switch between windows in current stack pane
    #Key([mod], "k", lazy.layout.down(),
    #    desc="Move focus down in stack pane"),
    #Key([mod], "j", lazy.layout.up(),
    #    desc="Move focus up in stack pane"),

    ## Move windows up or down in current stack
    #Key([mod, "control"], "k", lazy.layout.shuffle_down(),
    #    desc="Move window down in current stack "),
    #Key([mod, "control"], "j", lazy.layout.shuffle_up(),
    #    desc="Move window up in current stack "),

    # Switch window focus to other pane(s) of stack
    Key([mod], "space", lazy.layout.next(),
        desc="Switch window focus to other pane(s) of stack"),

    # Swap panes of split stack
    Key([mod, "shift"], "space", lazy.layout.rotate(),
        desc="Swap panes of split stack"),

    # Monad specific

    Key([mod], "h", lazy.layout.left()),
    Key([mod], "l", lazy.layout.right()),
    Key([mod], "j", lazy.layout.down()),
    Key([mod], "k", lazy.layout.up()),
    Key([mod, "shift"], "h", lazy.layout.swap_left()),
    Key([mod, "shift"], "l", lazy.layout.swap_right()),
    Key([mod, "shift"], "j", lazy.layout.shuffle_down()),
    Key([mod, "shift"], "k", lazy.layout.shuffle_up()),
    Key([mod], "i", lazy.layout.grow()),
    Key([mod], "m", lazy.layout.shrink()),
    Key([mod], "n", lazy.layout.normalize()),
    Key([mod], "o", lazy.layout.maximize()),
    Key([mod, "shift"], "space", lazy.layout.flip()),

    # Toggle between split and unsplit sides of stack.
    # Split = all windows displayed
    # Unsplit = 1 window displayed, like Max layout, but still with
    # multiple stack panes
    Key([mod, "shift"], "Return", lazy.layout.toggle_split(),
        desc="Toggle between split and unsplit sides of stack"),
    Key([mod], "Return", lazy.spawn(terminal), desc="Launch terminal"),

    # Toggle between different layouts as defined below
    Key([mod], "Tab", lazy.next_layout(), desc="Toggle between layouts"),
    Key([mod], "w", lazy.window.kill(), desc="Kill focused window"),

    Key([mod, "control"], "r", lazy.restart(), desc="Restart qtile"),
    Key([mod, "control"], "q", lazy.shutdown(), desc="Shutdown qtile"),
    Key([mod], "r", lazy.spawncmd(),
        desc="Spawn a command using a prompt widget"),
    Key([mod], "d", lazy.spawn("dmenu_run"), desc="Spawn rofi"),
]


groups = [Group(str(i)) for i in range(0,10)]

for i in groups:
    keys.extend([
        # mod1 + letter of group = switch to group
        Key([mod], i.name, lazy.group[i.name].toscreen(),
            desc="Switch to group {}".format(i.name)),

        # mod1 + shift + letter of group = switch to & move focused window to group
        Key([mod, "shift"], i.name, lazy.window.togroup(i.name, switch_group=True),
            desc="Switch to & move focused window to group {}".format(i.name)),
        # Or, use below if you prefer not to switch to that group.
        # # mod1 + shift + letter of group = move focused window to group
        # Key([mod, "shift"], i.name, lazy.window.togroup(i.name),
        #     desc="move focused window to group {}".format(i.name)),
    ])

layouts = [
    layout.Max(),
    layout.Stack(num_stacks=2, margin=MARGIN),
    # Try more layouts by unleashing below layouts.
    # layout.Bsp(),
    # layout.Columns(),
    # layout.Matrix(),
    layout.MonadTall(margin=MARGIN),
    layout.MonadWide(margin=MARGIN),
    layout.Floating(),
    # layout.RatioTile(),
    # layout.Tile(),
    # layout.TreeTab(),
    # layout.VerticalTile(),
    # layout.Zoomy(),
]

widget_defaults = dict(
    font='sans',
    fontsize=12,
    padding=3,
)
extension_defaults = widget_defaults.copy()

screens = [
    Screen(
        bottom=top.Bar(
            [
                widget.CurrentLayout(**FONTS),
                widget.Sep(),
                widget.GroupBox(**FONTS),
                widget.Sep(),
                widget.Prompt(),
                widget.Sep(),
                widget.WindowName(**FONTS),
                widget.Sep(),
                widget.Chord(
                    chords_colors={
                        'launch': ("#ff0000", "#ffffff"),
                    },
                    name_transform=lambda name: name.upper(),
                ),
                widget.Clock(format='%Y-%m-%d %a %I:%M %p', **FONTS),
                widget.Sep(),
                widget.TextBox('CPU'),
                widget.CPUGraph(),
                widget.Sep(),
                widget.TextBox('Net'),
                widget.Wlan(interface="wlan0"),
                widget.NetGraph(graph_color=COLORS['nord14'], fill_color=COLORS['nord15']),
                widget.Sep(),
                widget.Battery(**FONTS),
                widget.Sep(),
                widget.Volume(emoji=True),
                widget.Systray(),
                widget.QuickExit(**FONTS),
            ],
            48,
            opacity=1,
            background=[COLORS['nord3'], COLORS['nord0']],
        ),
    ),
]

# Drag floating layouts.
mouse = [
    Drag([mod], "Button1", lazy.window.set_position_floating(),
         start=lazy.window.get_position()),
    Drag([mod], "Button3", lazy.window.set_size_floating(),
         start=lazy.window.get_size()),
    Click([mod], "Button2", lazy.window.bring_to_front())
]

dgroups_key_binder = None
dgroups_app_rules = []  # type: List
main = None
follow_mouse_focus = True
bring_front_click = False
cursor_warp = False
floating_layout = layout.Floating(float_rules=[
    # Run the utility of `xprop` to see the wm class and name of an X client.
    {'wmclass': 'confirm'},
    {'wmclass': 'dialog'},
    {'wmclass': 'download'},
    {'wmclass': 'error'},
    {'wmclass': 'file_progress'},
    {'wmclass': 'notification'},
    {'wmclass': 'splash'},
    {'wmclass': 'toolbar'},
    {'wmclass': 'confirmreset'},  # gitk
    {'wmclass': 'makebranch'},  # gitk
    {'wmclass': 'maketag'},  # gitk
    {'wname': 'branchdialog'},  # gitk
    {'wname': 'pinentry'},  # GPG key password entry
    {'wmclass': 'ssh-askpass'},  # ssh-askpass
])
auto_fullscreen = True
focus_on_window_activation = "smart"

# XXX: Gasp! We're lying here. In fact, nobody really uses or cares about this
# string besides java UI toolkits; you can see several discussions on the
# mailing lists, GitHub issues, and other WM documentation that suggest setting
# this string if your java app doesn't work correctly. We may as well just lie
# and say that we're a working one by default.
#
# We choose LG3D to maximize irony: it is a 3D non-reparenting WM written in
# java that happens to be on java's whitelist.
wmname = "LG3D"```

**Comment by jjrugui** [comment]
The weird thing is that I get the same error as OP in the logs but nothing more informative than that and just checking `python config.py` does not throw any error.
