### ISSUE TITLE
lazy.restart() fails when a group has a non-ASCII name

### ISSUE THREAD

**Issue by Bauthe** [qtile/qtile#1888]
# Issue description

After adding middle-dots in my group names, lazy.restart() fails. It does the same with a set of non-ASCII characters I tested: "àç".

# Qtile version

0.16.2.dev21+ge71fae80

Using qtile-git from the AUR.

# Stack traces

Here is the error that seems relevant to the issue

```
2020-08-29 02:09:05,707 ERROR libqtile manager.py:process_key_event():L374 KB command error restart: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/command_interface.py", line 312, in call
    return SUCCESS, cmd(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/core/manager.py", line 1147, in cmd_restart
    self.restart()
  File "/usr/lib/python3.8/site-packages/libqtile/core/manager.py", line 290, in restart
    argv.append('--with-state=' + buf.getvalue().decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 163: invalid continuation byte
```

And the entire log : [qtile.log](https://github.com/qtile/qtile/files/5144542/qtile.log)

# Configuration

A 1-line config is sufficient to produce the issue on my laptop

```python
from libqtile.config import Group

groups = [Group(i) for i in "azà"]
```

**Comment by m-col** [comment]
Could you confirm whether https://github.com/qtile/qtile/pull/1898 fixes the problem?

**Comment by Bauthe** [comment]
It fixes it. Well done :+1:
