### ISSUE TITLE
subscribe.startup_once not working?

### ISSUE THREAD

**Issue by Jamesdawg1977** [qtile/qtile#1909]
I freshly installed Qtile and used a config from someone else, with my own personal modification. At the end of that [config](https://github.com/qtile/qtile/files/5215380/config.txt), there's this:

@hook.subscribe.startup_once
def start_once():
    home = os.path.expanduser('~')
    subprocess.call([home + '/.config/qtile/autostart.sh'])

autostart.sh looks like this:
#! /bin/bash 
picom &
nitrogen --restore &
steam -silent &
lxqt-policy-agent &
dunst &

Yet when I start Qtile, none of that starts. I've had similar issues before with .desktop files and some others I think, so it may not be a solely Qtile related issued, but I'm not sure. I have the most recent version of Qtile. I found these lines in /home/james/.local/share/qtile/qtile.log:

2020-09-13 17:45:51,875 ERROR libqtile hook.py:fire():L367 Error in hook startup_once
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/hook.py", line 365, in fire
    i(*args, **kwargs)
  File "/home/james/.config/qtile/config.py", line 463, in start_once
    subprocess.call([home + '/.config/qtile/autostart.sh'])
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/james/.config/qtile/autostart.sh'

I have no clue why it doesn't have permission. That is my home directory, and I started Qtile. I even changed the permissions to give anyone complete access and it still won't work. I'm pretty new to all of this, so this could be a really stupid mistak, but I'd appreciate anyone's help!

**Comment by Jamesdawg1977** [comment]
Nevermind, I'm just an idiot and forgot to reboot after changing the permissions.
