### ISSUE TITLE
qtile config error

### ISSUE THREAD

**Issue by supermindsv1** [qtile/qtile#1922]
I have a Qtile config which runs perfectly on my Manjaro install. But when I run the save config in ArcoLinux, it crashes... I am a fairly new Qtile user and this is the output when I check the error message, this is what pops up... P.S. it is not my config... I am planning to build my own one... Till the I am using this config which is on Derek Taylor's gitlab repo and using my own custom keybindings...
`020-10-02 23:07:35,300 libqtile confreader.py:load():L96  Could not import config file '/home/jg/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 138, in wrapper
    return_value = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/sensors.py", line 99, in get_temp_sensors
    sensors_out = self.call_process(command)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/base.py", line 286, in call_process
    output = subprocess.check_output(command, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sensors']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 92, in load
    config = __import__(name)  # noqa: F811
  File "/home/jg/.config/qtile/config.py", line 461, in <module>
    screens = init_screens()
  File "/home/jg/.config/qtile/config.py", line 455, in init_screens
    return [Screen(top=bar.Bar(widgets=init_widgets_screen1(), opacity=1.0, size=20)),
  File "/home/jg/.config/qtile/config.py", line 445, in init_widgets_screen1
    widgets_screen1 = init_widgets_list()
  File "/home/jg/.config/qtile/config.py", line 356, in init_widgets_list
    widget.ThermalSensor(
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 213, in class_proxy
    return cls(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/sensors.py", line 76, in __init__
    temp_values = self.get_temp_sensors()
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 138, in wrapper
    return_value = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 140, in wrapper
    logger.warning(err.strerror)
AttributeError: 'CalledProcessError' object has no attribute 'strerror'
2020-10-02 23:07:35,301 libqtile manager.py:__init__():L113  Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 138, in wrapper
    return_value = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/sensors.py", line 99, in get_temp_sensors
    sensors_out = self.call_process(command)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/base.py", line 286, in call_process
    output = subprocess.check_output(command, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sensors']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 92, in load
    config = __import__(name)  # noqa: F811
  File "/home/jg/.config/qtile/config.py", line 461, in <module>
    screens = init_screens()
  File "/home/jg/.config/qtile/config.py", line 455, in init_screens
    return [Screen(top=bar.Bar(widgets=init_widgets_screen1(), opacity=1.0, size=20)),
  File "/home/jg/.config/qtile/config.py", line 445, in init_widgets_screen1
    widgets_screen1 = init_widgets_list()
  File "/home/jg/.config/qtile/config.py", line 356, in init_widgets_list
    widget.ThermalSensor(
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 213, in class_proxy
    return cls(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/sensors.py", line 76, in __init__
    temp_values = self.get_temp_sensors()
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 138, in wrapper
    return_value = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 140, in wrapper
    logger.warning(err.strerror)
AttributeError: 'CalledProcessError' object has no attribute 'strerror'
)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 138, in wrapper
    return_value = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/sensors.py", line 99, in get_temp_sensors
    sensors_out = self.call_process(command)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/base.py", line 286, in call_process
    output = subprocess.check_output(command, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sensors']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 92, in load
    config = __import__(name)  # noqa: F811
  File "/home/jg/.config/qtile/config.py", line 461, in <module>
    screens = init_screens()
  File "/home/jg/.config/qtile/config.py", line 455, in init_screens
    return [Screen(top=bar.Bar(widgets=init_widgets_screen1(), opacity=1.0, size=20)),
  File "/home/jg/.config/qtile/config.py", line 445, in init_widgets_screen1
    widgets_screen1 = init_widgets_list()
  File "/home/jg/.config/qtile/config.py", line 356, in init_widgets_list
    widget.ThermalSensor(
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 213, in class_proxy
    return cls(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/sensors.py", line 76, in __init__
    temp_values = self.get_temp_sensors()
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 138, in wrapper
    return_value = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 140, in wrapper
    logger.warning(err.strerror)
AttributeError: 'CalledProcessError' object has no attribute 'strerror'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/core/manager.py", line 111, in __init__
    self.config.load()
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 98, in load
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 138, in wrapper
    return_value = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/sensors.py", line 99, in get_temp_sensors
    sensors_out = self.call_process(command)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/base.py", line 286, in call_process
    output = subprocess.check_output(command, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sensors']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/confreader.py", line 92, in load
    config = __import__(name)  # noqa: F811
  File "/home/jg/.config/qtile/config.py", line 461, in <module>
    screens = init_screens()
  File "/home/jg/.config/qtile/config.py", line 455, in init_screens
    return [Screen(top=bar.Bar(widgets=init_widgets_screen1(), opacity=1.0, size=20)),
  File "/home/jg/.config/qtile/config.py", line 445, in init_widgets_screen1
    widgets_screen1 = init_widgets_list()
  File "/home/jg/.config/qtile/config.py", line 356, in init_widgets_list
    widget.ThermalSensor(
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 213, in class_proxy
    return cls(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/widget/sensors.py", line 76, in __init__
    temp_values = self.get_temp_sensors()
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 138, in wrapper
    return_value = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/libqtile/utils.py", line 140, in wrapper
    logger.warning(err.strerror)
AttributeError: 'CalledProcessError' object has no attribute 'strerror'`

**Comment by m-col** [comment]
>  subprocess.CalledProcessError: Command '['sensors']' returned non-zero exit status 1.

This means what it says: the `sensors` command is returning a non-zero status. Try running it in a terminal and seeing what the error is that it is saying.

**Comment by supermindsv1** [comment]
I did a sensors-detect as it said and this is what it returned...
`# sensors-detect version 3.6.0
# System: innotek GmbH VirtualBox [1.2]
# Board: Oracle Corporation VirtualBox
# Kernel: 5.4.68-1-lts x86_64
# Processor: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6/158/10)

This program will help you determine which kernel modules you need
to load to use lm_sensors most effectively. It is generally safe
and recommended to accept the default answers to all questions,
unless you know what you're doing.

Some south bridges, CPUs or memory controllers contain embedded sensors.
Do you want to scan for them? This is totally safe. (YES/no): yes
Module cpuid loaded successfully.
Silicon Integrated Systems SIS5595...                       No
VIA VT82C686 Integrated Sensors...                          No
VIA VT8231 Integrated Sensors...                            No
AMD K8 thermal sensors...                                   No
AMD Family 10h thermal sensors...                           No
AMD Family 11h thermal sensors...                           No
AMD Family 12h and 14h thermal sensors...                   No
AMD Family 15h thermal sensors...                           No
AMD Family 16h thermal sensors...                           No
AMD Family 17h thermal sensors...                           No
AMD Family 15h power sensors...                             No
AMD Family 16h power sensors...                             No
Hygon Family 18h thermal sensors...                         No
Intel digital thermal sensor...                             No
Intel AMB FB-DIMM thermal sensor...                         No
Intel 5500/5520/X58 thermal sensor...                       No
VIA C7 thermal sensor...                                    No
VIA Nano thermal sensor...                                  No

Some Super I/O chips contain embedded sensors. We have to write to
standard I/O ports to probe them. This is usually safe.
Do you want to scan for Super I/O sensors? (YES/no): yes
Probing for Super-I/O at 0x2e/0x2f
Trying family `National Semiconductor/ITE'...               No
Trying family `SMSC'...                                     No
Trying family `VIA/Winbond/Nuvoton/Fintek'...               No
Trying family `ITE'...                                      No
Probing for Super-I/O at 0x4e/0x4f
Trying family `National Semiconductor/ITE'...               No
Trying family `SMSC'...                                     No
Trying family `VIA/Winbond/Nuvoton/Fintek'...               No
Trying family `ITE'...                                      No

Some systems (mainly servers) implement IPMI, a set of common interfaces
through which system health data may be retrieved, amongst other things.
We first try to get the information from SMBIOS. If we don't find it
there, we have to read from arbitrary I/O ports to probe for such
interfaces. This is normally safe. Do you want to scan for IPMI
interfaces? (YES/no): yes
Probing for `IPMI BMC KCS' at 0xca0...                      No
Probing for `IPMI BMC SMIC' at 0xca8...                     No

Some hardware monitoring chips are accessible through the ISA I/O ports.
We have to write to arbitrary I/O ports to probe them. This is usually
safe though. Yes, you do have ISA I/O ports even if you do not have any
ISA slots! Do you want to scan the ISA I/O ports? (YES/no): yes
Probing for `National Semiconductor LM78' at 0x290...       No
Probing for `National Semiconductor LM79' at 0x290...       No
Probing for `Winbond W83781D' at 0x290...                   No
Probing for `Winbond W83782D' at 0x290...                   No

Lastly, we can probe the I2C/SMBus adapters for connected hardware
monitoring devices. This is the most risky part, and while it works
reasonably well on most systems, it has been reported to cause trouble
on some systems.
Do you want to probe the I2C/SMBus adapters now? (YES/no): yes
Using driver `i2c-piix4' for device 0000:00:07.0: Intel 82371AB PIIX4 ACPI
Module i2c-dev loaded successfully.

Next adapter: SMBus PIIX4 adapter at 4100 (i2c-0)
Do you want to scan it? (YES/no/selectively): yes

Sorry, no sensors were detected.
Either your system has no sensors, or they are not supported, or
they are connected to an I2C or SMBus adapter that is not
supported. If you find out what chips are on your board, check
https://hwmon.wiki.kernel.org/device_support_status for driver status.
`

**Comment by m-col** [comment]
This is unrelated to Qtile. It seems `sensors` is doing one thing on Manjaro and another on `ArcoLinux`. I suggest bringing this up with the ArcoLinux people.

**Comment by tcld** [comment]
I have been having the same issues when using VMs, `sensors` usually doesn't return anything and thus my config breaks. So for testing purposes, I just remove the sensor-widgets inside VMs.

**Comment by supermindsv1** [comment]
Alright, I think this is what might have happened...I am closing this issue... Thanks for the help...
