### ISSUE TITLE
Error with adding border to Popup

### ISSUE THREAD

**Issue by elParaguayo** [qtile/qtile#1954]
# Issue description

I am unable to add a border > 0 pixels to a Popup window. Doing so causes an Exception which prevents the window being drawn.

# Qtile version

0.16.1

I note there's a new commit (e71fae802da55ebedb49ec04abb94b65b3ce0136) that makes some changes to how borders are painted so this may fix it but it hasn't made the next official release so I haven't tested.

If you're already aware of this then please just close the issue and I'll wait for the next version bump in the Arch repos.

# Stack traces

```
2020-11-07 08:49:21,325 WARNING libqtile manager.py:maybe_restart():L269 Restarting Qtile with os.execv(...)
2020-11-07 08:49:24,978 ERROR libqtile command_object.py:cmd_function():L206 Exception calling "<function poptest at 0x7fd7d4b9c790>":
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/command_object.py", line 203, in cmd_function
    function(self, *args, **kwargs)
  File "/home/elpara/.config/qtile/config.py", line 93, in poptest
    p.place()
  File "/usr/lib/python3.8/site-packages/libqtile/popup.py", line 146, in place
    self.win.place(
  File "/usr/lib/python3.8/site-packages/libqtile/window.py", line 498, in place
    self.window.set_attribute(borderpixel=bordercolor)
  File "/usr/lib/python3.8/site-packages/libqtile/backend/x11/xcbq.py", line 629, in set_attribute
    self.conn.conn.core.ChangeWindowAttributesChecked(
  File "/usr/lib/python3.8/site-packages/xcffib/xproto.py", line 2591, in ChangeWindowAttributes
    buf.write(struct.pack("=I", border_pixel))
struct.error: required argument is not an integer
```

# Configuration

The following function is triggered by a key press:

```
def poptest(q):
    p = Popup(q, opacity=0.7, border="#ff0000", border_width=2)
    p.place()
    p.unhide()
```

**Comment by m-col** [comment]
Yep you're right, that commit should fix the issue you're having and make it work as expected. The git version is _usually_ stable so if you want the changes you could check out installing the `qtile-git` package from the AUR. Otherwise, you'll get them at the next release. Please let us know if you have further issues when that release does get out :)

**Comment by elParaguayo** [comment]
Thanks.

I assume this is unconnected to the other issue I have of being unable to get a popup to respond to events.

I posted it in the dev group (https://groups.google.com/g/qtile-dev/c/5v6NKNc53E0/m/qIJGqAF9CAAJ) as I don't know if it's a bug or not!

**Comment by m-col** [comment]
I also noticed this recently, with a more recent version that the last release,
and it did used to work in the past. I'll bisect the changes and try to find out
what broke it. Thanks for reminding me :)

**Comment by elParaguayo** [comment]
I have installed the repo into a virtual environment (at least I hope I
have) so I can test different commits.

I haven't yet found one where the popup works though...
