### ISSUE TITLE
gen-keybinding-img script not working

### ISSUE THREAD

**Issue by RohitSingh107** [qtile/qtile#2019]
# gen-keybinding-img script not working
-->

# 0.16.1

**Comment by tych0** [comment]
Please post an actual error.

**Comment by RAprogramm** [comment]
python /home/user/.config/qtile/qtile-master/scripts/gen-keybinding-img -c /home/ra/.config/qtile/con
fig.py -o /home/user/Pictures
Traceback (most recent call last):
  File "/home/ra/.config/qtile/qtile-master/scripts/gen-keybinding-img", line 429, in <module>
    f.render(output_file)
  File "/home/ra/.config/qtile/qtile-master/scripts/gen-keybinding-img", line 192, in render
    self.draw_button(context, i.key, i.x, i.y, i.width, i.height)
  File "/home/ra/.config/qtile/qtile-master/scripts/gen-keybinding-img", line 243, in draw_button
    self.show_multiline(context, x + COMMAND_X, y + COMMAND_Y, k)
  File "/home/ra/.config/qtile/qtile-master/scripts/gen-keybinding-img", line 268, in show_multiline
    words = key.command.split(' ')
AttributeError: 'tuple' object has no attribute 'split'

**Comment by m-col** [comment]
Does that happen as a result of having more than one command as part of a keybinding?

**Comment by RAprogramm** [comment]
i think no

**Comment by RAprogramm** [comment]
https://github.com/qtile/qtile/issues/3567
