### ISSUE TITLE
Tray icons dissappeared

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#2070]
# Issue description
Update Qtile to version 0.16.2.dev145 + gab78c0cc and the widgets from the Qtile bar disappeared and it gives me the following error

# Qtile version
0.16.2.dev145 + gab78c0cc 

# Stack traces
2021-01-04 21:39:09,496 ERROR libqtile manager.py:handle_exception():L64 'Drawer' object has no attribute 'pixmap'
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/dist-packages/qtile-0.16.2.dev145+gab78c0cc-py3.9.egg/libqtile/core/manager.py", line 905, in f
    func(*args)
  File "/usr/local/lib/python3.9/dist-packages/qtile-0.16.2.dev145+gab78c0cc-py3.9.egg/libqtile/bar.py", line 376, in _actual_draw
    i.draw()
  File "/usr/local/lib/python3.9/dist-packages/qtile-0.16.2.dev145+gab78c0cc-py3.9.egg/libqtile/widget/systray.py", line 189, in draw
    icon.window.set_attribute(backpixmap=self.drawer.pixmap)
AttributeError: 'Drawer' object has no attribute 'pixmap'
2021-01-04 21:39:11,029 ERROR libqtile manager.py:handle_exception():L64 'Drawer' object has no attribute 'pixmap'
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/dist-packages/qtile-0.16.2.dev145+gab78c0cc-py3.9.egg/libqtile/core/manager.py", line 905, in f
    func(*args)
  File "/usr/local/lib/python3.9/dist-packages/qtile-0.16.2.dev145+gab78c0cc-py3.9.egg/libqtile/bar.py", line 376, in _actual_draw
    i.draw()
  File "/usr/local/lib/python3.9/dist-packages/qtile-0.16.2.dev145+gab78c0cc-py3.9.egg/libqtile/widget/systray.py", line 189, in draw
    icon.window.set_attribute(backpixmap=self.drawer.pixmap)
AttributeError: 'Drawer' object has no attribute 'pixmap'

# Configuration Screen and Bar

screens = [
    Screen(
        top=bar.Bar(
            [
                widget.GroupBox(this_current_screen_border=COLORS[0],highlight_method="block", active="#FFFFFF", inactive="#9c9d9e"),
                widget.TaskList(border=COLORS[0], highlight_method="block"),
                widget.Systray(icon_size=32, padding=9),
		        widget.KeyboardLayout(background=COLORS[0], padding=10, configured_keyboards = ['us','es']),
		        widget.CurrentLayout(background=COLORS[0]),
                widget.CurrentLayoutIcon(background=COLORS[0]),
                widget.Clock(format='%B %d %H:%M %p', background=COLORS[0], padding=10),
            ],
        46,
	    background=COLORS[2]),
        ),
        ]

**Comment by ramnes** [comment]
Yep. Fixed in 242780176c8f3172000afa33dcc07ffd2d793843. Thanks!
