### ISSUE TITLE
Saving state for restarts fails when scratchpad windows are used during the session

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#2087]
# Issue description

^ the title

I get this in my log:
```
2021-01-09 21:13:46,884 ERROR libqtile manager.py:dump_state():L147 Unable to pickle qtile state
Traceback (most recent call last):
  File "/home/mcol/git/qtile/libqtile/core/manager.py", line 145, in dump_state
    pickle.dump(QtileState(self), buf, protocol=0)
  File "/home/mcol/git/qtile/libqtile/state.py", line 44, in __init__
    self.scratchpads[group.name] = group.get_state()
  File "/home/mcol/git/qtile/libqtile/scratchpad.py", line 336, in get_state
    pid = dd.window.window.get_net_wm_pid()
  File "/home/mcol/git/qtile/libqtile/backend/x11/xcbq.py", line 615, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/home/mcol/git/qtile/libqtile/backend/x11/xcbq.py", line 708, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.9/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 556, in invalid
    raise XcffibException("Invalid connection.")
xcffib.XcffibException: Invalid connection.
2021-01-09 21:13:46,891 WARNING libqtile lifecycle.py:_atexit():L34 Restarting Qtile with os.execv(...)
2021-01-09 21:13:48,139 ERROR libqtile manager.py:_configure():L186 failed restoring state
Traceback (most recent call last):
  File "/home/mcol/git/qtile/libqtile/core/manager.py", line 183, in _configure
    st = pickle.load(f)
EOFError: Ran out of input
```

Note that the second exception is just because the state can't be restored, because it wasn't saved.

# Qtile version

Current HEAD which is f0a67e8bd4ebda97f310de6c235f1cbd72a0dc7d.

# Configuration

Anything with a ScratchPad and DropDowns.

# To reproduce:

1. Configure a ScratchPad group with a Dropdown.
2. don't use it
3. restart
4. note no error
5. use the dropdown (spawns the window)
6. restart
7. note the error

**Comment by m-col** [comment]
Fixing this may fix https://github.com/qtile/qtile/issues/1942 too

**Comment by DorianGray** [comment]
This should now be fixed, can you confirm?

**Comment by m-col** [comment]
Oh apologies, I didn't confirm it fixed it. Yeah, guess it did!
