### ISSUE TITLE
Dgroups broken in current master

### ISSUE THREAD

**Issue by dequis** [qtile/qtile#2089]
# Issue description

I tried git master to see if another thing is already fixed there, but i found that dgroups doesn't work anymore. It just sends everything to the current group and doesn't create new ones.

v0.16.1 works, master doesn't. Did bisect, fce22e59fceb23310ea03feaa13a0aa5b4f802a9 is the first bad commit

# Qtile version

fce22e59fceb23310ea03feaa13a0aa5b4f802a9 (first bad commit)
33ef59f88fe9655b82b4b3b232ae1f8252f2cd65 (current master)

# Stack traces

 It shows this when starting a client with rules (gimp in this case)

```
2021-01-10 21:20:07,198 libqtile hook.py:fire():L385  Error in hook client_new
Traceback (most recent call last):
  File "/home/dx/test/gits/qtile/libqtile/hook.py", line 383, in fire
    i(*args, **kwargs)
  File "/home/dx/test/gits/qtile/libqtile/dgroups.py", line 169, in _add
    if rule.matches(client):
  File "/home/dx/test/gits/qtile/libqtile/config.py", line 672, in matches
    return self.match.compare(w)
  File "/home/dx/test/gits/qtile/libqtile/config.py", line 631, in compare
    if not match(rule_value):
  File "/home/dx/test/gits/qtile/libqtile/config.py", line 603, in predicate
    return value and any(match(v) for v in value)
  File "/home/dx/test/gits/qtile/libqtile/config.py", line 603, in <genexpr>
    return value and any(match(v) for v in value)
  File "/home/dx/test/gits/qtile/libqtile/config.py", line 602, in <lambda>
    match = getattr(other, 'match', lambda v: other in v)
TypeError: 'in <string>' requires string as left operand, not list
```

# Configuration

```
dgroups_app_rules = [
    Rule(Match(
        wm_class=['MPlayer', 'Exe', 'feh', 'Pinentry', 'Plugin-container',
                  'Gtk-recordMyDesktop', 'Beep.py']),
        float=True, intrusive=True, break_on_match=False),
    Rule(Match(title=['Event Tester', 'Firefox Preferences']),
        float=True, intrusive=True),
    Rule(Match(wm_class=['Gnome-terminal', 'st-256color', 'st']), group='term'),
    Rule(Match(wm_class=['fontforge']), group='fontforge', float=True),
    Rule(Match(wm_class=['Gimp', 'gimp']), group='gimp', float=True),
    Rule(Match(wm_class=['anki', 'Anki']), group='anki'),
    Rule(Match(wm_class=['chromium', 'Chromium']), group='chrome'),
    Rule(Match(wm_class=['Firefox', 'Aurora', 'Nightly', 'firefox-bin'],
        role=['browser']), group='www'),
    Rule(Match(wm_class=['Wine']), float=True, group='wine'),
    Rule(Match(wm_class=['Steam']), float=True, group='steam'),
    Rule(Match(wm_class=['zoom']), float=True, group='zoom'),
    Rule(Match(title=['QEMU']), float=True, group='qemu'),
]
```

[config_sanitized.txt](https://github.com/qtile/qtile/files/5793266/config_sanitized.txt)

**Comment by DorianGray** [comment]
Can you confirm that https://github.com/qtile/qtile/pull/2094 fixes this for me? Thanks!

**Comment by jagguli** [comment]
I'm still experiencing this issue on latest version

```
2021-03-04 19:00:35,152 ERROR libqtile hooks.py:set_groups():L146 error setting rules
Traceback (most recent call last):
  File "/home/steven/.config/qtile/hooks.py", line 106, in set_groups
    if rule.matches(client):
  File "/home/steven/.local/lib/python3.9/site-packages/qtile-0.17.1.dev73+g569c4d9a-py3.9-linux-x86_64.egg/libqtile/config.py", line 6
83, in matches
    return any(w.match(m) for m in self.matchlist)
  File "/home/steven/.local/lib/python3.9/site-packages/qtile-0.17.1.dev73+g569c4d9a-py3.9-linux-x86_64.egg/libqtile/config.py", line 6
83, in <genexpr>
    return any(w.match(m) for m in self.matchlist)
  File "/home/steven/.local/lib/python3.9/site-packages/qtile-0.17.1.dev73+g569c4d9a-py3.9-linux-x86_64.egg/libqtile/window.py", line 1
056, in match
    return match.compare(self)
  File "/home/steven/.local/lib/python3.9/site-packages/qtile-0.17.1.dev73+g569c4d9a-py3.9-linux-x86_64.egg/libqtile/config.py", line 6
39, in compare
    if not match(rule_value):
  File "/home/steven/.local/lib/python3.9/site-packages/qtile-0.17.1.dev73+g569c4d9a-py3.9-linux-x86_64.egg/libqtile/config.py", line 6
15, in predicate
    return match(value)
  File "/home/steven/.local/lib/python3.9/site-packages/qtile-0.17.1.dev73+g569c4d9a-py3.9-linux-x86_64.egg/libqtile/config.py", line 6
14, in <lambda>
    match = getattr(other, 'match', lambda v: other in v)
```

**Comment by ramnes** [comment]
Is it linked to #1805?

**Comment by Fabien-Bernard** [comment]
/pull/2094 fix a simple logic error, but only for match with wm_class, 
the same problem still exists if you try to match a title for example.

The same modification 6 lines below will fix it.

**Comment by tych0** [comment]
Can you send a pull request?

**Comment by Fabien-Bernard** [comment]
I have time so yes I could, but the last reply of DorianGray in [/pull/2094](https://github.com/qtile/qtile/pull/2094) may indicate that this problem is already fix - with tests ;)

**Comment by jagguli** [comment]
Yea I saw that PR but was not sure if it was intentional, thank for the info, I'll push the fix.
