### ISSUE TITLE
test_qtile_cmd appears to be flaky

### ISSUE THREAD

**Issue by vrusinov** [qtile/qtile#2103]
# Issue description

test_qtile_cmd.py seems to be flaky. Once in a while I get an error when running `pytest . -x` from the fresh checkout. The issue pops randomly and non-determenistically. I attempted to reproduce it running `while pytest test/test_qtile_cmd.py ; do :; done` but it never failed after 10-15 minutes of running.

# Qtile version

commit cae69ccb9dd572abf5c3fe41a32c23ead36a7089
Date:   Tue Jan 12 14:06:08 2021 -0500

```
$ python3 --version
Python 3.8.6
```

xorg-server 1.20.10

# Stack traces

```
<...>
test/test_popup.py::test_popup_focus[BareConfig] PASSED       [ 45%]
test/test_qtile_cmd.py::test_qtile_cmd[ServerConfig] Fatal Python error: Aborted

Thread 0x00007f5accdf3640 (most recent call first):
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 507 in iteration
  File "/home/rvs/workspace/qtile/libqtile/core/loop.py", line 68 in gobject_thread
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57 in run
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 80 in _worker
  File "/usr/lib/python3.8/threading.py", line 870 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007f5ad6601740 (most recent call first):
  File "/usr/lib/python3.8/site-packages/cairocffi/xcb.py", line 37 in __init__
  File "/home/rvs/workspace/qtile/libqtile/drawer.py", line 236 in __init__
  File "/home/rvs/workspace/qtile/libqtile/bar.py", line 214 in _configure
  File "/home/rvs/workspace/qtile/libqtile/config.py", line 289 in _configure
  File "/home/rvs/workspace/qtile/libqtile/core/manager.py", line 288 in _process_screens
  File "/home/rvs/workspace/qtile/libqtile/core/manager.py", line 152 in _configure
  File "/home/rvs/workspace/qtile/libqtile/core/manager.py", line 217 in async_loop
  File "/home/rvs/workspace/qtile/libqtile/core/session_manager.py", line 75 in async_loop
  File "/usr/lib/python3.8/asyncio/events.py", line 81 in _run
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859 in _run_once
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570 in run_forever
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603 in run_until_complete
  File "/usr/lib/python3.8/asyncio/runners.py", line 44 in run
  File "/home/rvs/workspace/qtile/libqtile/core/session_manager.py", line 68 in loop
  File "/home/rvs/workspace/qtile/test/conftest.py", line 287 in run_qtile
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108 in run
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315 in _bootstrap
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 75 in _launch
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19 in __init__
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277 in _Popen
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224 in _Popen
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121 in start
  File "/home/rvs/workspace/qtile/test/conftest.py", line 292 in start
  File "/home/rvs/workspace/qtile/test/conftest.py", line 499 in manager
  File "/usr/lib/python3.8/site-packages/_pytest/fixtures.py", line 921 in call_fixture_func
  File "/usr/lib/python3.8/site-packages/_pytest/fixtures.py", line 1124 in pytest_fixture_setup
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/fixtures.py", line 1070 in execute
  File "/usr/lib/python3.8/site-packages/_pytest/fixtures.py", line 689 in _compute_fixture_value
  File "/usr/lib/python3.8/site-packages/_pytest/fixtures.py", line 605 in _get_active_fixturedef
  File "/usr/lib/python3.8/site-packages/_pytest/fixtures.py", line 585 in getfixturevalue
  File "/usr/lib/python3.8/site-packages/_pytest/fixtures.py", line 572 in _fillfixtures
  File "/usr/lib/python3.8/site-packages/_pytest/python.py", line 1633 in setup
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 448 in prepare
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 151 in pytest_runtest_setup
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 256 in <lambda>
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 310 in from_call
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 255 in call_runtest_hook
  File "/usr/lib/python3.8/site-packages/flaky/flaky_pytest_plugin.py", line 138 in call_and_report
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 121 in runtestprotocol
  File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 110 in pytest_runtest_protocol
  File "/usr/lib/python3.8/site-packages/flaky/flaky_pytest_plugin.py", line 94 in pytest_runtest_protocol
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 338 in pytest_runtestloop
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 313 in _main
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 257 in wrap_session
  File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 306 in pytest_cmdline_main
  File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 164 in main
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 187 in console_main
  File "/usr/lib/python-exec/python3.8/pytest", line 33 in <module>
ERROR    [ 46%]

============================== ERRORS ===============================
__________ ERROR at setup of test_qtile_cmd[ServerConfig] ___________

request = <SubRequest 'manager' for <Function test_qtile_cmd[ServerConfig]>>
xephyr = <test.conftest.Xephyr object at 0x7f5ad24b41c0>

    @pytest.fixture(scope="function")
    def manager(request, xephyr):
        config = getattr(request, "param", BareConfig)
    
        for attr in dir(default_config):
            if not hasattr(config, attr):
                setattr(config, attr, getattr(default_config, attr))
    
        with tempfile.NamedTemporaryFile() as f:
            sockfile = f.name
            try:
                manager = TestManager(sockfile, xephyr.display, request.config.getoption("--debuglog"))
>               manager.start(config)

test/conftest.py:499: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/conftest.py:295: in start
    if can_connect_qtile(self.sockfile, ok=lambda: not rpipe.poll()):
test/conftest.py:82: in wrapper
    return fn(*args, **kwargs)
test/conftest.py:114: in can_connect_qtile
    val = client.status()
libqtile/command/client.py:211: in __getattr__
    if not self._command.has_command(self._current_node, name):
libqtile/command/interface.py:258: in has_command
    commands = self.execute(cmd_call, (), {})
libqtile/command/interface.py:230: in execute
    status, result = self._client.send((
libqtile/ipc.py:133: in send
    return asyncio.run(self.async_send(msg))
/usr/lib/python3.8/asyncio/runners.py:44: in run
    return loop.run_until_complete(main)
/usr/lib/python3.8/asyncio/base_events.py:616: in run_until_complete
    return future.result()
libqtile/ipc.py:159: in async_send
    await writer.wait_closed()
/usr/lib/python3.8/asyncio/streams.py:359: in wait_closed
    await self._protocol._get_close_waiter(self)
libqtile/ipc.py:153: in async_send
    read_data = await asyncio.wait_for(reader.read(), timeout=10)
/usr/lib/python3.8/asyncio/tasks.py:491: in wait_for
    return fut.result()
/usr/lib/python3.8/asyncio/streams.py:677: in read
    block = await self.read(self._limit)
/usr/lib/python3.8/asyncio/streams.py:684: in read
    await self._wait_for_data('read')
/usr/lib/python3.8/asyncio/streams.py:517: in _wait_for_data
    await self._waiter
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_SelectorSocketTransport closed fd=26>

    def _read_ready__data_received(self):
        if self._conn_lost:
            return
        try:
>           data = self._sock.recv(self.max_size)
E           ConnectionResetError: [Errno 104] Connection reset by peer                                                                    

/usr/lib/python3.8/asyncio/selector_events.py:848: ConnectionResetError
----------------------- Captured stderr setup -----------------------
python3.8: /tmp/portage/x11-libs/cairo-1.16.0-r4/work/cairo-1.16.0/src/cairo-xcb-screen.c:219: int _get_screen_index(cairo_xcb_connection_t *, xcb_screen_t *): Assertion `!"reached"' failed.
qtile exited with exitcode: -6
====================== short test summary info ======================
ERROR test/test_qtile_cmd.py::test_qtile_cmd[ServerConfig] - Conne...
!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!
=================== 194 passed, 1 error in 52.64s ===================
```

# Configuration

n/a

**Comment by vrusinov** [comment]
It actually fails relatively frequently when running `pytest . -x` as opposed to running just a single `pytest test/test_qtile_cmd.py`. Perhaps some cleanup from previous test does not manage to complete in time?

**Comment by vrusinov** [comment]
Right, so it's reasonably well reproducible when my machine's CPU usage is high-ish.

If I peg all cores, `pytest . -x` fails even sooner with this:

```
test/test_bar.py::test_prompt[GBConfig] ERROR                                                                                                                                                               [  0%]

===================================================================================================== ERRORS ======================================================================================================
_____________________________________________________________________________________ ERROR at setup of test_prompt[GBConfig] _____________________________________________________________________________________

request = <SubRequest 'manager' for <Function test_prompt[GBConfig]>>, xephyr = <test.conftest.Xephyr object at 0x7f3dfec65a30>

    @pytest.fixture(scope="function")
    def manager(request, xephyr):
        config = getattr(request, "param", BareConfig)
    
        for attr in dir(default_config):
            if not hasattr(config, attr):
                setattr(config, attr, getattr(default_config, attr))
    
        with tempfile.NamedTemporaryFile() as f:
            sockfile = f.name
            try:
                manager = TestManager(sockfile, xephyr.display, request.config.getoption("--debuglog"))
>               manager.start(config)

test/conftest.py:499: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test.conftest.TestManager object at 0x7f3dfebc3490>, config_class = <class 'test.test_bar.GBConfig'>

    def start(self, config_class):
        rpipe, wpipe = multiprocessing.Pipe()
    
        def run_qtile():
            try:
                kore = Core(display_name=self.display)
                init_log(self.log_level, log_path=None, log_color=False)
                q = SessionManager(kore, config_class(), socket_path=self.sockfile)
                q.loop()
            except Exception:
                wpipe.send(traceback.format_exc())
    
        self.proc = multiprocessing.Process(target=run_qtile)
        self.proc.start()
    
        # First, wait for socket to appear
        if can_connect_qtile(self.sockfile, ok=lambda: not rpipe.poll()):
            ipc_client = ipc.Client(self.sockfile)
            ipc_command = command.interface.IPCCommandInterface(ipc_client)
            self.c = command.client.InteractiveCommandClient(ipc_command)
            return
        if rpipe.poll(sleep_time):
            error = rpipe.recv()
>           raise AssertionError("Error launching qtile, traceback:\n%s" % error)
E           AssertionError: Error launching qtile, traceback:
E           Traceback (most recent call last):
E             File "/home/rvs/workspace/qtile/test/conftest.py", line 284, in run_qtile
E               kore = Core(display_name=self.display)
E             File "/home/rvs/workspace/qtile/libqtile/backend/x11/core.py", line 71, in __init__
E               self.conn = xcbq.Connection(display_name)
E             File "/home/rvs/workspace/qtile/libqtile/backend/x11/xcbq.py", line 775, in __init__
E               self.conn = xcffib.connect(display=display)
E             File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 527, in __init__
E               self.invalid()
E             File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 559, in invalid
E               raise ConnectionException(err)
E           xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
```

Searching for this error pointed me to https://github.com/qtile/qtile/issues/1634, so perhaps that issue can be extended and this closed as a dupe?

My system has xcffib 0.11.1 since it seem to be relevant.

**Comment by tych0** [comment]
If you apply https://github.com/qtile/qtile/pull/2072 can you reproduce? I think some of the seg faults are due to that.

The timeouts when CPU usage is high is probably just due to our crappy test suite: we use sleep wait instead of a more principled approach to detect when qtile has spawned.

**Comment by DorianGray** [comment]
#2072 is now in master

**Comment by vrusinov** [comment]
Yes, still reproducible at 7489b44d12af55d1a86ce219a0436e404002478c

**Comment by vrusinov** [comment]
> The timeouts when CPU usage is high is probably just due to our crappy test suite: we use sleep wait instead of a more principled approach to detect when qtile has spawned.

I looked into this, and here are some things I found.

I wasn't able to see "ConnectionResetError" anymore, possibly because xcb errors seem to be much more prevalent.

They are easily reproducible for me on two different machines (different CPUs with different numbers of cores) when running test suite together with some CPU load. `stress-ng -c 0 -l 30` - does the job of reliably triggering `xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors`. It is more frequent the higher the load number is. Running with `stress-ng -c 0 -l 80` makes test suite fail almost immediately.

It is not reproducible when I run 100% load on some of my cores and leave at least one for tests. I.e. on 4-core / 8 thread intel machine with HT tests run fine under `stress-ng -c 3 -l 100` (100% load on 3 threads) but start failing with `-c 4`.

Digging further - I don't believe this is due to sleeps & waits - this part seems to actually work fine (for this problem anyway). The exception does not come from a test suite - it's actually produced by a spawned qtile process, and the test suite only reads it from the `rpipe` and re-raises as an `AssertionError`. We could add `Retry` to `run_qtile` but it may mask actual exceptions and startup flakiness in non-test Qtile code.

I've also noticed that the first test always passes, it the 2nd or later ones that fail. I will look into how test turndown/cleanup is done next. I suspect the 2nd and subsequent tests may have a chance of stomping on the socket or DISPLAY of the previous test invocation.

**Comment by vrusinov** [comment]
PS: once again this looks very similar to #1634, but I'll keep this issue separate as it may be easier to fix for non-parallel case by adding some locks.

**Comment by vrusinov** [comment]
> I've also noticed that the first test always passes, it the 2nd or later ones that fail.

That is not true. I just had a test failure when running a single test:

```
$ pytest-3 -v -x 'test/test_bar.py::test_incompatible_widget'             
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.8.7, pytest-4.6.11, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/vrusinov/workspace/qtile, inifile: setup.cfg
collected 1 item                                                                                                                                                                                                  

test/test_bar.py::test_incompatible_widget FAILED                                                                                                                                                           [100%]

==================================================================================================== FAILURES =====================================================================================================
____________________________________________________________________________________________ test_incompatible_widget _____________________________________________________________________________________________

manager_nospawn = <test.conftest.TestManager object at 0x7f703180ca60>

    def test_incompatible_widget(manager_nospawn):
        config = IncompatibleWidgetConf
    
        # Ensure that adding a widget that doesn't support the orientation of the
        # bar raises ConfigError
        with pytest.raises(libqtile.confreader.ConfigError):
>           m = manager_nospawn.create_manager(config)

test/test_bar.py:339: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/conftest.py:319: in create_manager
    kore = Core(display_name=self.display)
libqtile/backend/x11/core.py:71: in __init__
    self.conn = xcbq.Connection(display_name)
libqtile/backend/x11/xcbq.py:779: in __init__
    self.conn = xcffib.connect(display=display)
../../.local/lib/python3.8/site-packages/xcffib/__init__.py:527: in __init__
    self.invalid()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <xcffib.Connection object at 0x7f7031824250>

    def invalid(self):
        if self._conn is None:
            raise XcffibException("Invalid connection.")
        err = lib.xcb_connection_has_error(self._conn)
        if err > 0:
>           raise ConnectionException(err)
E           xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

../../.local/lib/python3.8/site-packages/xcffib/__init__.py:559: ConnectionException
-------------------------------------------------------------------------------------------- Captured stderr teardown ---------------------------------------------------------------------------------------------
qtile is not alive
============================================================================================ 1 failed in 0.89 seconds =============================================================================================

```

**Comment by vrusinov** [comment]
The next thing I suspected that `can_connect_x11` returns early, or there is something weird happens that causes test manager fixture finish before xephyr fixture. So I started playing with this idea in a new file and found out that under load `xcffib.connect` is unreliable. So this does not seem like a qtile bug - it is xcffib or Xorg's one!

Here's the reproduction:

```python
import time
import subprocess
import xcffib
import xcffib.testing
import xcffib.xproto

print("xcffib version is %s" % xcffib.__version__)

# Load all CPU cores to 80%. Requires stress-ng installed, e.g. via `apt install strress-ng`
stress_args = [
    "stress-ng",
    "-c",
    "0",
    "-l",
    "80"
]
stress_proc = subprocess.Popen(stress_args)
time.sleep(0.1)

display, display_file = xcffib.testing.find_display()
display = ":{}".format(display)
args = [
    "Xephyr",
    "-name",
    "qtile_test",
    display,
    "-ac",
    "-screen",
    "{}x{}".format(800, 800),
]
xephyr_proc = subprocess.Popen(args)

try:
    for i in range(1000):
        try:
            conn = xcffib.connect(display=display)
            conn.disconnect()
            print("connected")
        except xcffib.ConnectionException:
            print("failed")
finally:
    stress_proc.terminate()
    xephyr_proc.terminate()

```

If you run it you may see something like this:

```
$ python3 repro.py
xcffib version is 0.10.1
stress-ng: info:  [1984659] defaulting to a 86400 second (1 day, 0.00 secs) run per stressor
stress-ng: info:  [1984659] dispatching hogs: 8 cpu
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
connected
failed
connected
connected
failed
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
failed
connected
connected
connected
connected
failed
connected
connected
connected
connected
failed
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
failed
connected
connected
connected
failed
connected
failed
connected
connected
connected
connected
connected
connected
connected
failed
connected
failed
connected
connected
connected
connected
connected
connected
connected
^CTraceback (most recent call last):
  File "repro.py", line 36, in <module>
    conn = xcffib.connect(display=display)
  File "/home/vrusinov/.local/lib/python3.8/site-packages/xcffib/__init__.py", line 525, in __init__
    self._conn = lib.xcb_connect(display, i)
KeyboardInterrupt

stress-ng: info:  [1984659] successful run completed in 4.76s
```

Initial failures are totally expected. What is unexpected that it fails once in a while after it managed to connect once!

**Comment by vrusinov** [comment]
> xcffib version is 0.10.1

I tried with 0.11.1 and see the same problem.

**Comment by vrusinov** [comment]
A few other tests:

1) looks Xephyr specific, does not reproduces with already running X server:

```python
import time
import subprocess
import xcffib
import xcffib.testing
import xcffib.xproto

print("xcffib version is %s" % xcffib.__version__)

# Load all CPU cores to 80%. Requires stress-ng installed, e.g. via `apt install strress-ng`
stress_args = [
    "stress-ng",
    "-c",
    "0",
    "-l",
    "80"
]
stress_proc = subprocess.Popen(stress_args)
time.sleep(0.1)

display=":0"

connected = 0
failed = 0

try:
    for i in range(10_000):
        try:
            conn = xcffib.connect(display=display)
            conn.disconnect()
            connected += 1
        except xcffib.ConnectionException:
            failed += 1
finally:
    stress_proc.terminate()

print("success: %d, fail: %d" % (connected, failed))
```

```
$ python3 repro.py
xcffib version is 0.11.1
stress-ng: info:  [1992782] defaulting to a 86400 second (1 day, 0.00 secs) run per stressor
stress-ng: info:  [1992782] dispatching hogs: 8 cpu
success: 10000, fail: 0
stress-ng: info:  [1992782] successful run completed in 6.23s
```

Letting Xephyr run for a while does not help:

```
import time
import subprocess
import xcffib
import xcffib.testing
import xcffib.xproto

print("xcffib version is %s" % xcffib.__version__)

display, display_file = xcffib.testing.find_display()
display = ":{}".format(display)
args = [
    "Xephyr",
    "-name",
    "qtile_test",
    display,
    "-ac",
    "-screen",
    "{}x{}".format(800, 800),
]
xephyr_proc = subprocess.Popen(args)
time.sleep(5.0)

# Load all CPU cores to 80%. Requires stress-ng installed, e.g. via `apt install strress-ng`
stress_args = [
    "stress-ng",
    "-c",
    "0",
    "-l",
    "80"
]
stress_proc = subprocess.Popen(stress_args)
time.sleep(0.1)

connected = 0
failed = 0

try:
    for i in range(1000):
        try:
            conn = xcffib.connect(display=display)
            conn.disconnect()
            print("connected")
            connected += 1
        except xcffib.ConnectionException:
            print("failed")
            failed += 1
finally:
    stress_proc.terminate()
    xephyr_proc.terminate()

print("success: %d, fail: %d" % (connected, failed))
```

```
xcffib version is 0.11.1
stress-ng: info:  [1996122] defaulting to a 86400 second (1 day, 0.00 secs) run per stressor
stress-ng: info:  [1996122] dispatching hogs: 8 cpu
connected
connected
connected
connected
failed
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
failed
connected
failed
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
connected
failed
<...>
```


Thus, I conclude this is likely Xephyr issue.

```
$ dpkg -l xserver-xephyr
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  xserver-xephyr 2:1.20.10-2  amd64        nested X server
```

I'll test on a few other versions and will try to report this to xorg folks.

Any ideas for mitigations on qtile side? Adding retries to all `xcffib.connect` invocations seems dirty.

**Comment by DorianGray** [comment]
I think the linked PR mitigates it pretty totally...could use some logic to the xephyr fixture I guess to ensure it's actually ready.

**Comment by vrusinov** [comment]
@DorianGray it seems to make xcb errors much less likely indeed! However it does not fix the problem completely - I still can't get all of the tests succeed with 80% cpu load (using `stress-ng -c 0 -l 80` - this time on 8 core/16 thread AMD machine):

```
===================================================================================================== ERRORS ======================================================================================================
________________________________________________________________________ ERROR at setup of test_too_few_groups[xephyr0-TooFewGroupsConfig] ________________________________________________________________________

request = <SubRequest 'manager' for <Function test_too_few_groups[xephyr0-TooFewGroupsConfig]>>, xephyr = <test.conftest.Xephyr object at 0x7f55f655f400>

    @pytest.fixture(scope="function")
    def manager(request, xephyr):
        config = getattr(request, "param", BareConfig)
    
        for attr in dir(default_config):
            if not hasattr(config, attr):
                setattr(config, attr, getattr(default_config, attr))
    
        with tempfile.NamedTemporaryFile() as f:
            sockfile = f.name
            try:
                manager = TestManager(sockfile, xephyr.display, request.config.getoption("--debuglog"))
>               manager.start(config)

test/conftest.py:502: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test.conftest.TestManager object at 0x7f55f6550820>, config_class = <class 'test.test_manager.TooFewGroupsConfig'>, no_spawn = False

    def start(self, config_class, no_spawn=False):
        rpipe, wpipe = multiprocessing.Pipe()
    
        def run_qtile():
            try:
                kore = Core(display_name=self.display)
                init_log(self.log_level, log_path=None, log_color=False)
                Qtile(
                    kore,
                    config_class(),
                    socket_path=self.sockfile,
                    no_spawn=no_spawn,
                ).loop()
            except Exception:
                wpipe.send(traceback.format_exc())
    
        self.proc = multiprocessing.Process(target=run_qtile)
        self.proc.start()
    
        # First, wait for socket to appear
        if can_connect_qtile(self.sockfile, ok=lambda: not rpipe.poll()):
            ipc_client = ipc.Client(self.sockfile)
            ipc_command = command.interface.IPCCommandInterface(ipc_client)
            self.c = command.client.InteractiveCommandClient(ipc_command)
            return
        if rpipe.poll(sleep_time):
            error = rpipe.recv()
>           raise AssertionError("Error launching qtile, traceback:\n%s" % error)
E           AssertionError: Error launching qtile, traceback:
E           Traceback (most recent call last):
E             File "/home/rvs/workspace/qtile/test/conftest.py", line 285, in run_qtile
E               kore = Core(display_name=self.display)
E             File "/home/rvs/workspace/qtile/libqtile/backend/x11/core.py", line 70, in __init__
E               self.conn = xcbq.Connection(display_name)
E             File "/home/rvs/workspace/qtile/libqtile/backend/x11/xcbq.py", line 778, in __init__
E               self.conn = xcffib.connect(display=display)
E             File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 527, in __init__
E               self.invalid()
E             File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 559, in invalid
E               raise ConnectionException(err)
E           xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

test/conftest.py:307: AssertionError
============================================================================================= short test summary info =============================================================================================
ERROR test/test_manager.py::test_too_few_groups[xephyr0-TooFewGroupsConfig] - AssertionError: Error launching qtile, traceback:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================================== 116 passed, 1 error in 24.23s ==========================================================================================
```

**Comment by vrusinov** [comment]
> Remove stale label or comment or this will be closed in 30 days.

This is still relevant as this (and other) tests are still flaky. I didn't had time to debug it further though.

**Comment by vrusinov** [comment]
Ok, I'm fairly sure it's an Xorg (or maybe libxcb) bug as it's also reproducable in non-python code.

Thus, it has nothing to do with qtile. I've opened https://gitlab.freedesktop.org/xorg/xserver/-/issues/1177 and closing this issue here.

**Comment by ramnes** [comment]
Thanks for your thorough investigation!
