### ISSUE TITLE
Shutdown hook is missing

### ISSUE THREAD

**Issue by KIC** [qtile/qtile#2124]
# Issue description

I have tried to use the [documented shutdown hook](http://docs.qtile.org/en/latest/manual/ref/hooks.html#libqtile.hook.subscribe.shutdown):
```
@hook.subscribe.shutdown
def save_session():
    pass
```
unfortunate hook does not provide such a hook
# Qtile version
pypi 0.16.1

# Stack traces
```
2021-01-19 18:10:45,878 ERROR libqtile confreader.py:load():L96 Could not import config file '/home/kic/.config/qtile/config.py'
Traceback (most recent call last):
  File "/home/kic/.local/lib/python3.8/site-packages/libqtile/confreader.py", line 92, in load
    config = __import__(name)  # noqa: F811
  File "/home/kic/.config/qtile/config.py", line 149, in <module>
    @hook.subscribe.shutdown
AttributeError: 'Subscribe' object has no attribute 'shutdown'
2021-01-19 18:10:45,878 ERROR libqtile manager.py:cmd_restart():L1150 Preventing restart because of a configuration error: Traceback (most recent call last):
  File "/home/kic/.local/lib/python3.8/site-packages/libqtile/confreader.py", line 92, in load
    config = __import__(name)  # noqa: F811
  File "/home/kic/.config/qtile/config.py", line 149, in <module>
    @hook.subscribe.shutdown
AttributeError: 'Subscribe' object has no attribute 'shutdown'
```

I want to save all screen and group information of all windows before shutdown. such that when I restart any app I will find the corresponding windows where I have left.

**Comment by tych0** [comment]
The hook is in an unreleased version of qtile, you'll have to install
from git master if you want to use it.

**Comment by elParaguayo** [comment]
@KIC  I've been caught out by things like this before. If you're not on the git version, make sure you select the correct release version when looking at the docs. 

Here's the hooks page for 0.16.1: http://docs.qtile.org/en/v0.16.1/manual/ref/hooks.html

**Comment by ramnes** [comment]
Closing because it has been answered.

Now should we make 0.16.1 the default page on the docs? We have this kind of questions quite regularly.
