### ISSUE TITLE
Zoomy layout has significant CPU usage

### ISSUE THREAD

**Issue by Barbarossa93** [qtile/qtile#2125]
# Issue description
I decided to try some new layouts and one of which I think I'd like to use is the zoomy layout. However, once I switch to the zoomy layout, there is some SIGNIFICANT system slowdown. Checking bpytop, I can see qtile is at 80%+ cpu usage on a single core. At this point, I have no choice but to restart the machine

# Qtile version
0.16.2 commit 7489b44

# Stack traces

I *think* this is the most relevant log output. There's quite a few iterations of this:
```
2021-01-19 14:46:57,031 ERROR libqtile core.py:_xpoll():L295 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 248, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 612, in poll_for_event
    return self.hoist_event(e)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 686, in hoist_event
    return self._process_error(ffi.cast("xcb_generic_error_t *", e))
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 649, in _process_error
    raise error(buf)
xcffib.xproto.ValueError
```

# Configuration

https://github.com/Barbarossa93/Genome/blob/69123891c01528812bafad6172da7bed6e4b9ae0/.config/qtile/config.py#L534

**Comment by Barbarossa93** [comment]
I investigated a little further and realized (by deleting the logs and then reproducing this problem, THEN check the logs) I found that nothing is written to the logs when this event occurs. However, I did notice a memory leak when switching to the zoomy layout. Every 2 seconds, the total memory usage increases by 10-20mb.

**Comment by Barbarossa93** [comment]
Tested at one more layer! Using a xephyr session, switching to the zoomy layout causes a flood of these messages in the terminal starting the xephyr session:
```
2021-01-21 11:11:49,955 libqtile core.py:_get_target_chain():L338 Unhandled event: ConfigureNotify
```
This is probably completely incorrect, but could it be as simple as adding ConfigureNotify to [this](https://github.com/qtile/qtile/blob/35a3cfe5a1097233dc425a400c45863d8622b957/libqtile/backend/x11/core.py#L313) list?

**Comment by Barbarossa93** [comment]
Applying this [commit](https://github.com/qtile/qtile/commit/99c944e3f3b0e7062ed0d6e59aff95a06bbc7d29) fixed it! I guess we'll have to wait until there is a better implementation

**Comment by Barbarossa93** [comment]
Not sure what commit fixed it, but I no longer have this problem. Closing.
