### ISSUE TITLE
qtile error on startup : pkg_souces has no attribute 'require'

### ISSUE THREAD

**Issue by lapingenieur** [qtile/qtile#2182]
## Description

I usually start qtile from sddm but this time it didn't launch and sddm froze. I went to htop and no `qtile` process was running even after several tries.

I then tried to execute `qtile` on the command line and I got this :

```
$ qtile
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/qtile.py", line 40, in <module>
    VERSION = pkg_resources.require("qtile")[0].version
AttributeError: module 'pkg_resources' has no attribute 'require'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/qtile", line 33, in <module>
    sys.exit(load_entry_point('qtile==0.16.1', 'console_scripts', 'qtile')())
  File "/usr/bin/qtile", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/qtile.py", line 41, in <module>
    except (pkg_resources.DistributionNotFound, ImportError):
AttributeError: module 'pkg_resources' has no attribute 'DistributionNotFound'
$
```

Python doesn't find pkg_resources.require and pkg_resources.DistributionNotFound

I installed qtile via `pacman` and it work fine until now.

## version

I can't get `qtile --version` because of this error, `pacman -Si qtile` says version is `0.16.1-2` and `python` is linked to `python3.9` version 3.9.1

## log files

I don't have any `~/.xsession-errors` and `~/.local/share/qtile/qtile.log` has no logs of today's runs.

## PS

Sorry for the messed up issue, first (and last) try opening an issue with gh-cli

**Comment by lapingenieur** [comment]
Does qutebrowser or the qtwebengine or any subprocess use python ?

**Comment by ramnes** [comment]
setuptools does have `pkg_resources.DistributionNotFound` up to 53.0.0. What distribution are you using? Your Python setup is probably broken, maybe you should try reinstalling it, or Python entirely?

**Comment by ramnes** [comment]
Especially if it used to work before and do not work anymore. Sounds like a system update that went wrong.

**Comment by DorianGray** [comment]
Definitely a python environment issue, not a qtile one. https://stackoverflow.com/questions/39925227/attributeerror-module-pkg-resources-has-no-attribute-safe-name-oauthlib-ins

**Comment by lapingenieur** [comment]
After trying to reinstall a package named like `python-ressources` with pacman (I'm on manjaro) it is in fact an i/o error : 4 files cannot be listed/read/edited or even removed

Maybe it's a filesystem error.

I'll close this issue because it's no more a qtile issue but a general python and io error.
