### ISSUE TITLE
dialog windows suddenly not floating anymore

### ISSUE THREAD

**Issue by Zemrod** [qtile/qtile#2221]
# Issue description
less of a problem and more of a pesky bug

with the recent update on archlinux some dialog windows are no longer floating
affected are: dialog windows to pick a download location, the windows to pick the file to upload and the dialogwindows of nextcloud (those are the ones i am aware of at least)

not affected: lxpolkit (part of lxsession)

# Qtile version
0.17.0

# Stack traces

```
2021-02-18 08:13:46,174 ERROR libqtile start.py:start():L91 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/start.py", line 89, in start
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 225, in loop
    logger.debug('Adding io watch')
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 247, in async_loop
    except Exception:
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 286, in finalize
    try:
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 157, in finalize
  File "/usr/lib/python3.9/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-02-18 08:13:46,175 WARNING libqtile lifecycle.py:_atexit():L34 Restarting Qtile with os.execv(...)
2021-02-18 08:20:19,606 WARNING libqtile floating.py:__init__():L109 Non-config.Match objects in float_rules are deprecated
2021-02-18 08:23:55,632 ERROR libqtile core.py:_xpoll():L305 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 273, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 304, in handle_ButtonPress
    widget.button_press(
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 233, in button_press
    self.mouse_callbacks[name]()
TypeError: <lambda>() missing 1 required positional argument: 'qtile'
2021-02-18 08:27:09,542 ERROR libqtile manager.py:get_interesting_pid():L598 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 658, in wait_for_reply
    self._process_error(error_p[0])
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 645, in _process_error
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 596, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/xcbq.py", line 610, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/xcbq.py", line 703, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 332, in reply
    data = self.conn.wait_for_reply(self.sequence)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-02-18 08:27:09,548 ERROR libqtile core.py:_xpoll():L297 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 258, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-02-18 08:27:09,549 ERROR libqtile manager.py:get_interesting_pid():L598 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 258, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 596, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/xcbq.py", line 610, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/xcbq.py", line 703, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.9/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-02-18 08:27:09,551 ERROR libqtile manager.py:finalize():L283 exception during finalize
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 273, in finalize
    widget.finalize()
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 209, in finalize
    self.drawer.finalize()
  File "/usr/lib/python3.9/site-packages/libqtile/drawer.py", line 235, in finalize
    self._free_pixmap()
  File "/usr/lib/python3.9/site-packages/libqtile/drawer.py", line 302, in _free_pixmap
    self.qtile.conn.conn.core.FreePixmap(self._pixmap)
  File "/usr/lib/python3.9/site-packages/xcffib/xproto.py", line 2863, in FreePixmap
    return self.send_request(54, buf, is_checked=is_checked)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-02-18 08:27:09,554 ERROR libqtile start.py:start():L91 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/start.py", line 89, in start
    q.loop()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 225, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 247, in async_loop
    self.finalize()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 286, in finalize
    self.core.finalize()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 157, in finalize
    self.conn.conn.core.DeletePropertyChecked(
  File "/usr/lib/python3.9/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-02-18 08:27:09,556 WARNING libqtile lifecycle.py:_atexit():L34 Restarting Qtile with os.execv(...)
2021-02-18 08:27:40,729 WARNING libqtile floating.py:__init__():L109 Non-config.Match objects in float_rules are deprecated
2021-02-18 08:35:35,425 WARNING libqtile window.py:handle_ClientMessage():L1177 Invalid value for focus_on_window_activation: smart
```

# Configuration

https://gitlab.com/Zemrod/dotfiles/-/blob/admin/.config/qtile/config.py

**Comment by Zemrod** [comment]
Addedum: the pssword dialog of trojita (mail client on qt-base) is affected as well

**Comment by ramnes** [comment]
What if you remove this chunk? https://gitlab.com/Zemrod/dotfiles/-/blob/admin/.config/qtile/config.py#L258-275

**Comment by Zemrod** [comment]
removing the entire floating rule fixed the entire issue
