### ISSUE TITLE
mouse callback for the image widget requires already passed argument

### ISSUE THREAD

**Issue by Zemrod** [qtile/qtile#2222]
# Issue description
while applying a solution for a different issue i noticed that my shortcut to my config file, doesn't work
i linked the exact line in the configuration down below

# Qtile version
0.17.0

# Stack traces

```
2021-02-18 12:13:32,896 ERROR libqtile core.py:_xpoll():L305 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 273, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 304, in handle_ButtonPress
    widget.button_press(
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 233, in button_press
    self.mouse_callbacks[name]()
TypeError: <lambda>() missing 1 required positional argument: 'qtile'
```
# Configuration

https://gitlab.com/Zemrod/dotfiles/-/blob/admin/.config/qtile/config.py#L166

**Comment by tych0** [comment]
Yes, mouse_callbacks no longer take any arguments, see #2220
