### ISSUE TITLE
Qtile loggin with default config

### ISSUE THREAD

**Issue by marcostrejo2644** [qtile/qtile#2244]
Hi today when i loggin in my arch linux with qtile, opened with default config. i see another post with similar problem but dont work. This is the log of qtile:

```
2021-02-22 13:35:55,667 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
2021-02-22 13:36:01,032 WARNING libqtile floating.py:__init__():L109 Non-config.Match objects in float_rules are deprecated
2021-02-22 13:36:01,032 ERROR libqtile confreader.py:load():L106 Could not import config file '/home/sailentk/.config/qtile/config.py'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/confreader.py", line 101, in load
    config = __import__(name)  # noqa: F811
  File "/home/sailentk/.config/qtile/config.py", line 9, in <module>
    from settings.widgets import widget_defaults, extension_defaults
  File "/home/sailentk/.config/qtile/settings/widgets.py", line 64, in <module>
    widget.Pacman(**base(bg='color4'), update_interval=1800),
  File "/usr/lib/python3.9/site-packages/libqtile/utils.py", line 226, in __getattr__
    raise AttributeError
AttributeError
2021-02-22 13:36:01,033 ERROR libqtile manager.py:load_config():L107 Error while reading config file (Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/confreader.py", line 101, in load
    config = __import__(name)  # noqa: F811
  File "/home/sailentk/.config/qtile/config.py", line 9, in <module>
    from settings.widgets import widget_defaults, extension_defaults
  File "/home/sailentk/.config/qtile/settings/widgets.py", line 64, in <module>
    widget.Pacman(**base(bg='color4'), update_interval=1800),
  File "/usr/lib/python3.9/site-packages/libqtile/utils.py", line 226, in __getattr__
    raise AttributeError
AttributeError
)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/confreader.py", line 101, in load
    config = __import__(name)  # noqa: F811
  File "/home/sailentk/.config/qtile/config.py", line 9, in <module>
    from settings.widgets import widget_defaults, extension_defaults
  File "/home/sailentk/.config/qtile/settings/widgets.py", line 64, in <module>
    widget.Pacman(**base(bg='color4'), update_interval=1800),
  File "/usr/lib/python3.9/site-packages/libqtile/utils.py", line 226, in __getattr__
    raise AttributeError
AttributeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 104, in load_config
    self.config.load()
  File "/usr/lib/python3.9/site-packages/libqtile/confreader.py", line 108, in load
    raise ConfigError(tb)
libqtile.confreader.ConfigError: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/confreader.py", line 101, in load
    config = __import__(name)  # noqa: F811
  File "/home/sailentk/.config/qtile/config.py", line 9, in <module>
    from settings.widgets import widget_defaults, extension_defaults
  File "/home/sailentk/.config/qtile/settings/widgets.py", line 64, in <module>
    widget.Pacman(**base(bg='color4'), update_interval=1800),
  File "/usr/lib/python3.9/site-packages/libqtile/utils.py", line 226, in __getattr__
    raise AttributeError
AttributeError
```

**Comment by m-col** [comment]
Hi @marcostrejo2644 

It doesn't look like you are using the default config. There is no longer a `widget.Pacman`, instead please use `widget.CheckUpdates` which does the same thing.

@tych0 perhaps another API breakage that we can add to `qtile merge`?

**Comment by marcostrejo2644** [comment]
> Hi @marcostrejo2644
> 
> It doesn't look like you are using the default config. There is no longer a `widget.Pacman`, instead please use `widget.CheckUpdates` which does the same thing.
> 
> @tych0 perhaps another API breakage that we can add to `qtile merge`?

widget.CheckUpdates fixed the error. Thank you man!

**Comment by tych0** [comment]
Yes, although migrate doesn't automatically migrate stuff right now. We should add that at some point once it lands.
