### ISSUE TITLE
Mouse callback in widgets not working

### ISSUE THREAD

**Issue by redBaron23** [qtile/qtile#2280]
# Issue description
I make this config like 8 month ago, and now since 1 month or 2 it's not working the mouse callback (it doesn't execute nothing). I tried with Button1 ,2,3,4,5 and doesn't work. 

# Qtile version
0.17.0

In  ~/.local/share/qtile/qtile.log i got this. And in xsessions there isn't a related error
`
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 273, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 304, in handle_ButtonPress
    widget.button_press(
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 233, in button_press
    self.mouse_callbacks[name]()
TypeError: changeSoundOutput() missing 1 required positional argument: 'qtile'
2021-03-07 22:40:52,238 ERROR libqtile core.py:_xpoll():L305 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 273, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 304, in handle_ButtonPress
    widget.button_press(
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 233, in button_press
    self.mouse_callbacks[name]()
TypeError: changeSoundOutput() missing 1 required positional argument: 'qtile'
2021-03-07 22:40:53,757 ERROR libqtile core.py:_xpoll():L305 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 273, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 304, in handle_ButtonPress
    widget.button_press(
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 233, in button_press
    self.mouse_callbacks[name]()
TypeError: changeSoundOutput() missing 1 required positional argument: 'qtile'
2021-03-07 22:40:53,961 ERROR libqtile core.py:_xpoll():L305 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 273, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 304, in handle_ButtonPress
    widget.button_press(
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 233, in button_press
    self.mouse_callbacks[name]()
TypeError: changeSoundOutput() missing 1 required positional argument: 'qtile'
`
# Configuration

https://pastebin.com/Sm1XNJQC

**Comment by tych0** [comment]
Yes, mouse_callbacks no longer take a qtile argument. See https://github.com/qtile/qtile/issues/2008 and https://github.com/qtile/qtile/commit/6feca1c187d689b418fb3680bde02f37387cdb3a
