### ISSUE TITLE
PangoLayout error happens very often

### ISSUE THREAD

**Issue by diego-rapoport** [qtile/qtile#2307]
# Issue description

I get this log quite often:
2021-03-18 09:05:57,675 ERROR libqtile base.py:on_done():L542 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 534, in on_done
    self.update(result)
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 550, in update
    old_width = self.layout.width
  File "/usr/lib/python3.9/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.9/site-packages/libqtile/pangocffi.py", line 132, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType

This makes my qtile freeze when I try to reload it, at least directly from binding. I usually do it because I can't make it automatically with the startup_complete hook for my monitors work with xrandr command. Tried a couple of times, failed it, and now I do it manually.

# Qtile version

0.17.0

**Comment by tych0** [comment]
git master has a bunch of fixes for this, might be worth a try.

**Comment by diego-rapoport** [comment]
Thanks, I'll check it out!

**Comment by m-col** [comment]
Is this still an issue?

**Comment by m-col** [comment]
https://github.com/qtile/qtile/issues/2557 appears to be a duplicate, with the error also appearing on recent master
