### ISSUE TITLE
[qtile shell] cd without arguments creates an error

### ISSUE THREAD

**Issue by lapingenieur** [qtile/qtile#2309]
This is a minor bug

# Issue description

When inside the `qtile shell`, `cd` permits to select an object to work. But if we don't give it any arguments instead of printing an error message it makes the qtile shell exit on an error. The rest of qtile isn't affected at all.

# Qtile version

`0.17.0` (installed from the manjaro repos, pacman says `0.17.0-1`...)

# Stack traces

What I get when `cd`-ing to no where : 

```
$ qtile shell
 > ls
bar/     group/   layout/  screen/  widget/  window/
 > cd screen/
screen
screen > ls
layout/  window/  bar/     0/       1/     
screen > cd ..
/
 > cd window/
window
window > cd /
/
 > cd
Traceback (most recent call last):
  File "/usr/bin/qtile", line 33, in <module>
    sys.exit(load_entry_point('qtile==0.17.0', 'console_scripts', 'qtile')())
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/main.py", line 59, in main
    options.func(options)
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/shell.py", line 36, in qshell
    qsh.loop()
  File "/usr/lib/python3.9/site-packages/libqtile/sh.py", line 344, in loop
    val = self.process_line(line)
  File "/usr/lib/python3.9/site-packages/libqtile/sh.py", line 304, in process_line
    val = builtin(args)
  File "/usr/lib/python3.9/site-packages/libqtile/sh.py", line 205, in do_cd
    next_node = self._find_path(arg)
  File "/usr/lib/python3.9/site-packages/libqtile/sh.py", line 152, in _find_path
    root = graph.CommandGraphRoot() if path.startswith("/") else self._current_node
AttributeError: 'NoneType' object has no attribute 'startswith'
$ echo $?
1
$
```

`cd` without arguments could be kinda like the bash `cd` (aka go to `~/` directory) but instead of going to the home, go to `/` (root of list objects).

**Comment by m-col** [comment]
A PR actually did implement this, 6 days ago in fact! https://github.com/qtile/qtile/pull/2297
