### ISSUE TITLE
Error in startup hook

### ISSUE THREAD

**Issue by vicrdguez** [qtile/qtile#2335]
# Issue description
Hello!
I'm having problems executing my autostart script with qtile. I've been searching about this problem (I'm aware of #1169) but I can't find how to get this to work. 
The script has execution permissions, in fact my workaround now is executing the script manually.

Thanks for your amazing work!

# Qtile version
0.17.0

# Stack traces
```
2021-03-30 12:36:18,870 WARNING libqtile lifecycle.py:_atexit():L34 Restarting Qtile with os.execv(...)
2021-03-30 12:36:19,354 ERROR libqtile hook.py:fire():L391 Error in hook startup
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/hook.py", line 389, in fire
    i(*args, **kwargs)
  File "/home/vrodriguez/.config/qtile/config.py", line 476, in start_once
    subprocess.call([home])
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/vrodriguez/.config/qtile/autostart.sh'
```

# Configuration
My hook:
```python
@hook.subscribe.startup
def start_once():
    home = os.path.expanduser('~/.config/qtile/autostart.sh')
    subprocess.call([home])
```

My autostart script:
```shell
##!/usr/bin/env bash

lxsession &
picom --experimental-backends --config ./picom.conf &
#nitrogen --restore &
xfce4-power-manager &
feh --randomize --bg-fill ~/.wallpapers/* &
volumeicon &
nm-applet &
variety &
```

**Comment by elParaguayo** [comment]
Change your shebang line. It should be:
```
#!/usr/bin/env bash
```
i.e. one `#` not two.

**Comment by vicrdguez** [comment]
Can't feel more stupid now. I'm blind.. haha
Thank you for your time, I'll close the issue
