### ISSUE TITLE
[Wayland] [Minor] Hitting button of QuickExit widget generates TypeError exception.

### ISSUE THREAD

**Issue by Fabien-Bernard** [qtile/qtile#2509]
# Issue description

When I shutdown qtile via the QuickExit widget, the error pasted below is generated.
This error does not prevent the shutdown.
I don't see this error with x11.

# Qtile version

6799b6ae

# Stack traces
```

2021-06-04 11:08:53,547 DEBUG libqtile hook.py:fire():L370 Internal event: shutdown((), {})
2021-06-04 11:08:54,548 DEBUG libqtile manager.py:_stop():L253 Stopping qtile
2021-06-04 11:08:54,548 DEBUG libqtile ipc.py:close():L262 Stopping server on close
2021-06-04 11:08:54,550 DEBUG libqtile keyboard.py:_on_destroy():L69 Signal: keyboard destroy
2021-06-04 11:08:54,581 DEBUG libqtile core.py:remove_listener():L450 Removing io watch
2021-06-04 11:08:54,597 ERROR libqtile base.py:_wrapper():L304 got exception from widget timer
Traceback (most recent call last):
  File "[...]/libqtile/widget/base.py", line 302, in _wrapper method(*method_args)
  File "[...]/libqtile/widget/quick_exit.py", line 61, in update self.text = self.countdown_format.format(self.countdown)
  File "[...]/libqtile/widget/base.py", line 355, in text self.layout.text = self.formatted_text
  File "[...]/libqtile/drawer.py", line 72, in text self.layout.set_attributes(attrlist)
  File "[...]/libqtile/pangocffi.py", line 115, in set_attributes pango.pango_layout_set_attributes(self._pointer, attrs)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2021-06-04 11:08:54,624 INFO libqtile start.py:start():L93 Exiting...
2021-06-04 11:08:54,628 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
```

# Configuration

Any configuration with the QuickExit widget I think.

# Proposition
This error could be avoided by optimising the update method of the widget if we do not recall the update method once the shutdown is effectively launched.

**Comment by m-col** [comment]
I see something I think is related just when I shutdown with a key-bound `lazy.shutdown`:
```
2021-06-04 11:14:20,597 libqtile dgroups.py:_del():L248  Add dgroup timer with delay 1s
2021-06-04 11:14:21,613 libqtile base.py:_wrapper():L304  got exception from widget timer
Traceback (most recent call last):
  File "/home/mcol/git/qtile/libqtile/widget/base.py", line 302, in _wrapper
    method(*method_args)
  File "/home/mcol/git/qtile/libqtile/widget/graph.py", line 200, in update
    self.update_graph()
  File "/home/mcol/git/qtile/libqtile/widget/graph.py", line 254, in update_graph
    self.push(push_value)
  File "/home/mcol/git/qtile/libqtile/widget/graph.py", line 192, in push
    self.draw()
  File "/home/mcol/git/qtile/libqtile/widget/graph.py", line 150, in draw
    self.drawer.clear(self.background or self.bar.background)
  File "/home/mcol/git/qtile/libqtile/backend/base.py", line 535, in clear
    self.set_source_rgb(colour)
  File "/home/mcol/git/qtile/libqtile/backend/base.py", line 532, in set_source_rgb
    self.ctx.set_source_rgba(*utils.rgb(colour))
AttributeError: 'NoneType' object has no attribute 'set_source_rgba'
2021-06-04 11:14:21,618 libqtile start.py:start():L93  Exiting...
2021-06-04 11:14:21,618 libqtile lifecycle.py:_atexit():L38  Qtile will now terminate
```
This happens no matter which way I run it: TTY, nested X, nested Wayland.

> This error could be avoided by optimising the update method of the widget if we do not recall the update method once the shutdown is effectively launched.

My interpretation was the same :) Gotta clean up these timers a bit more nicely.

**Comment by elParaguayo** [comment]
`asyncio.call_soon` and `asyncio.call_later` both return handles which can be used to cancel scheduled tasks. Could be an option?

**Comment by m-col** [comment]
I believe this will be fixed by #2360
