### ISSUE TITLE
systray crash on Wayland

### ISSUE THREAD

**Issue by RohitSingh107** [qtile/qtile#2615]
# Issue description
widget systray crashed on Qtile on Wayland. Here are qtile logs:

2021-07-09 12:41:12,212 WARNING libqtile floating.py:__init__():L114 Non-config.Match objects in float_rules are deprecated
2021-07-09 12:41:12,226 WARNING libqtile tasklist.py:_configure():L306 TaskList icons not supported in Wayland.
2021-07-09 12:41:12,232 ERROR libqtile bar.py:_configure_widget():L273 Systray widget crashed during _configure with error: AttributeError("'Core' object has no attribute 'conn'")
2021-07-09 12:41:12,378 ERROR libqtile hook.py:fire():L382 Error in hook client_new
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/hook.py", line 380, in fire
    i(*args, **kwargs)
  File "/home/rohit/.config/qtile/config.py", line 605, in set_floating
    if (window.window.get_wm_transient_for()
AttributeError: 'Static' object has no attribute 'window'
2021-07-09 12:41:26,238 ERROR libqtile hook.py:fire():L382 Error in hook client_new
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/hook.py", line 380, in fire
    i(*args, **kwargs)
  File "/home/rohit/.config/qtile/config.py", line 605, in set_floating
    if (window.window.get_wm_transient_for()
AttributeError: 'Window' object has no attribute 'window'
2021-07-09 12:41:48,383 ERROR libqtile hook.py:fire():L382 Error in hook client_new
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/hook.py", line 380, in fire
    i(*args, **kwargs)
  File "/home/rohit/.config/qtile/config.py", line 605, in set_floating
    if (window.window.get_wm_transient_for()
AttributeError: 'Static' object has no attribute 'window'

# Qtile version
0.18 (using qtile-git from Arch AUR)

# Stack traces

**Comment by m-col** [comment]
The Systray widget uses a X11-specific spec so it cannot be supported 
on Wayland. We plan on adding a check to stop it from being used by 
default when running under Wayland 
(<https://github.com/qtile/qtile/pull/2576>). The replacement will be 
the StatusNotifier widget, which is currently a work in progress: 
<https://github.com/qtile/qtile/pull/2601>
