### ISSUE TITLE
Volume widget control with pamixer fails

### ISSUE THREAD

**Issue by leybodv** [qtile/qtile#2616]
# Issue description

I try to use pamixer for displaying/controlling volume level in Volume widget. In config.py I add 
`widget.Volume(volume_app = "pamixer", get_volume_command = "pamixer --get-volume-human", volume_down_command = "pamixer --decrease 1", volume_up_command = "pamixer --increase 1", mute_command = "pamixer --toggle-mute")`
However widget displays "0" instead of actual volume level.

The possible problem is in `widget.base.call_process` method which invokes `subprocess.check_output` without `shell=True` parameter.
call_process method is invoked in volume.py on 174th line to get volume from environment.

Invoking `subprocess.check_output("pamixer --get-volume-human")` in python shell causes:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/d/git/qtile/libqtile/widget/volume.py", line 174, in get_volume
    mixer_out = self.call_process(get_volume_cmd)
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 292, in call_process
    output = subprocess.check_output(command, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pamixer --get-volume-human'

# Qtile version
0.17.0

# Stack traces

2021-07-10 17:41:18,935 ERROR libqtile base.py:_wrapper():L300 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 298, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.9/site-packages/libqtile/widget/volume.py", line 112, in update
    vol = self.get_volume()
  File "/usr/lib/python3.9/site-packages/libqtile/widget/volume.py", line 174, in get_volume
    mixer_out = self.call_process(get_volume_cmd)
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 292, in call_process
    output = subprocess.check_output(command, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pamixer --get-volume-human'

# Configuration

[config.py.txt](https://github.com/qtile/qtile/files/6795550/config.py.txt)

**Comment by Fabien-Bernard** [comment]
I think the python error could be avoided with `get_volume_command=["pamixer", "--get-volume-human"]`.

But I don't think it will be sufficient to get the volume right due to the difference of outputs between pamixer `46%` and amixer `[46%]`. The Volume widget regex is unable to catch the volume if the brackets are missing.

Different options were suggested on a similar issue (https://groups.google.com/g/qtile-dev/c/1ykdOEpsziw) : 
- the PulseVolume widget,
- the GenPollText widget with your pamixer command,
- the Volume widget with a script that uses your pamixer command and adds the brackets aroud the result.

**Comment by leybodv** [comment]
@Fabien-Bernard Thank you for the suggestion, `get_volume_command=["pamixer", "--get-volume-human"]` works without traceback (should have read python docs more carefully). I know that I should modify output of pamixer to match the regexp, thanks.
