### ISSUE TITLE
qtile autostart not working

### ISSUE THREAD

**Issue by ussak12** [qtile/qtile#2665]
# Issue description

qtile autostart doesnt work

qtile check in the terminal give me this:

```
checking qtile config file /home/muhammad/.config/qtile/config.py
Success: no issues found in 1 source file
config file type checking succeeded
config file can be loaded by qtile
```

# Qtile version

0.18.1.dev0+g8e7ecc0a.d20210719

# Stack traces

```
2021-07-30 10:14:09,444 ERROR libqtile hook.py:fire():L381 Error in hook startup
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/hook.py", line 379, in fire
    i(*args, **kwargs)
  File "/home/muhammad/.config/qtile/config.py", line 199, in autostart
    subprocess.call([home])
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/muhammad/.config/qtile/autostart.sh'
```

# Configuration

autostart.sh:
```
#!/usr/bin/env bash

setxkbmap dk
picom &
nitrogen --restore &
```
config.py:
```
from typing import List  # noqa: F401

from libqtile import bar, layout, widget, hook
from libqtile.config import Click, Drag, Group, Key, Match, Screen
from libqtile.lazy import lazy
from libqtile.utils import guess_terminal

import os
import subprocess
@hook.subscribe.startup
def autostart():
    home = os.path.expanduser('/home/muhammad/.config/qtile/autostart.sh') # path to my script, under my user directory
    subprocess.call([home])

```

**Comment by elParaguayo** [comment]
You're getting a permission error. Have you done `chmod +x` on your startup script?

**Comment by ussak12** [comment]
no i chmod -x it, thats why it didnt work
