### ISSUE TITLE
Qtile cmd-obj can't find objects it suggests

### ISSUE THREAD

**Issue by LamprosPitsillos** [qtile/qtile#2684]
# Issue description

Am i missing something? Because it is suggested by the shell I  imagine it should be possible to find that object.

# Qtile version

`0.18.1.dev0+g8e7ecc0a.d20210719`

# Stack traces
```
$ qtile cmd-obj   
Specify an object on which to execute command
-o cmd
-o bar
-o group
-o layout
-o screen
-o widget
-o window
$ qtile cmd-obj -o bar
Traceback (most recent call last):
  File "/usr/bin/qtile", line 33, in <module>
    sys.exit(load_entry_point('qtile==0.18.1.dev0+g8e7ecc0a.d20210719', 'console_scripts', 'qtile')())
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/main.py", line 55, in main
    options.func(options)
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/cmd_obj.py", line 165, in cmd_obj
    print_commands("-o " + " ".join(args.obj_spec), obj)
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/cmd_obj.py", line 74, in print_commands
    cmds = obj.call("commands")
  File "/usr/lib/python3.9/site-packages/libqtile/command/client.py", line 118, in call
    if name not in self.commands:
  File "/usr/lib/python3.9/site-packages/libqtile/command/client.py", line 138, in commands
    return self._command.execute(command_call, (), {})
  File "/usr/lib/python3.9/site-packages/libqtile/command/interface.py", line 237, in execute
    raise CommandError(result)
libqtile.command.base.CommandError: No object bar in path 'bar'
$ qtile cmd-obj -o widget
Traceback (most recent call last):
  File "/usr/bin/qtile", line 33, in <module>
    sys.exit(load_entry_point('qtile==0.18.1.dev0+g8e7ecc0a.d20210719', 'console_scripts', 'qtile')())
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/main.py", line 55, in main
    options.func(options)
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/cmd_obj.py", line 165, in cmd_obj
    print_commands("-o " + " ".join(args.obj_spec), obj)
  File "/usr/lib/python3.9/site-packages/libqtile/scripts/cmd_obj.py", line 74, in print_commands
    cmds = obj.call("commands")
  File "/usr/lib/python3.9/site-packages/libqtile/command/client.py", line 118, in call
    if name not in self.commands:
  File "/usr/lib/python3.9/site-packages/libqtile/command/client.py", line 138, in commands
    return self._command.execute(command_call, (), {})
  File "/usr/lib/python3.9/site-packages/libqtile/command/interface.py", line 237, in execute
    raise CommandError(result)
libqtile.command.base.CommandError: No object widget in path 'widget'
```
# Configuration

**Comment by elParaguayo** [comment]
That's only part of the command, you need to give the object identifier (e.g. widget name). You can find the names by looking at the bar `qtile cmd-obj -o bar top -f info` (assuming your bar is on the top).

After that, you can see what commands are available for a widget by doing `qtile cmd-obj -o widget <widgetname> -f help`

**Comment by elParaguayo** [comment]
I've created #2686 to provide more clarity here.

**Comment by elParaguayo** [comment]
#2686 was merged so I'm closing this.
