### ISSUE TITLE
CryptoTicker migration is incomplete

### ISSUE THREAD

**Issue by tych0** [qtile/qtile#2736]
I previously had:

```
widget.CryptoTicker(format="BTC: {avg}", **widget_defaults)
```

but it seems avg is not an allowed key any more per:

```
2021-09-01 14:42:17,968 ERROR libqtile generic_poll_text.py:poll():L90 got exception polling widget
Traceback (most recent call last):
  File "/home/tycho/.local/lib/python3.9/site-packages/libqtile/widget/generic_poll_text.py", line 88, in poll
    text = self.parse(body)
  File "/home/tycho/.local/lib/python3.9/site-packages/libqtile/widget/crypto_ticker.py", line 90, in parse
    return self.format.format(**variables)
```

/cc @Graeme22

**Comment by Graeme22** [comment]
Is migration supposed to cover this kind of thing? I wasn't aware.

**Comment by tych0** [comment]
I'd like us to at least try, it doesn't make much sense to fix some parts of peoples' configs but not others.

**Comment by tych0** [comment]
I'd say prevent breakage is all that's required.
