### ISSUE TITLE
GroupBox widget shows error at startup

### ISSUE THREAD

**Issue by addy419** [qtile/qtile#2749]
# Issue description
GroupBox widget throws error and does not show groupbox, after restart of wm with a keybinding, everything works as expected. This means GroupBox is started before qtile has properly setup.

# Qtile version

0.16.0 from nixpkgs 21.05

# Stack traces

```
2021-09-04 12:10:16,670 ERROR libqtile xcore.py:_xpoll():L272 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 610, in poll_for_event
    self.invalid()
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/s95fvw5nk7xf4ia4vg3bs3l3zsq0q4p3-qtile-0.16.0/lib/python3.7/site-packages/libqtile/backend/x11/xcore.py", line 231, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-09-04 12:10:16,679 ERROR libqtile manager.py:get_interesting_pid():L631 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 610, in poll_for_event
    self.invalid()
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/s95fvw5nk7xf4ia4vg3bs3l3zsq0q4p3-qtile-0.16.0/lib/python3.7/site-packages/libqtile/backend/x11/xcore.py", line 231, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/s95fvw5nk7xf4ia4vg3bs3l3zsq0q4p3-qtile-0.16.0/lib/python3.7/site-packages/libqtile/core/manager.py", line 629, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/nix/store/s95fvw5nk7xf4ia4vg3bs3l3zsq0q4p3-qtile-0.16.0/lib/python3.7/site-packages/libqtile/backend/x11/xcbq.py", line 612, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/nix/store/s95fvw5nk7xf4ia4vg3bs3l3zsq0q4p3-qtile-0.16.0/lib/python3.7/site-packages/libqtile/backend/x11/xcbq.py", line 713, in get_property
    0, (2 ** 32) - 1
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-09-04 12:10:16,696 ERROR libqtile manager.py:finalize():L309 exception during finalize
Traceback (most recent call last):
  File "/nix/store/s95fvw5nk7xf4ia4vg3bs3l3zsq0q4p3-qtile-0.16.0/lib/python3.7/site-packages/libqtile/core/manager.py", line 299, in finalize
    widget.finalize()
  File "/nix/store/s95fvw5nk7xf4ia4vg3bs3l3zsq0q4p3-qtile-0.16.0/lib/python3.7/site-packages/libqtile/widget/base.py", line 208, in finalize
    self.drawer.finalize()
  File "/nix/store/s95fvw5nk7xf4ia4vg3bs3l3zsq0q4p3-qtile-0.16.0/lib/python3.7/site-packages/libqtile/drawer.py", line 247, in finalize
    self.qtile.conn.conn.core.FreeGC(self.gc)
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/xproto.py", line 3027, in FreeGC
    return self.send_request(60, buf, is_checked=is_checked)
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/nix/store/y31dgf7qsb722jsmsqxjx8p997bn3q86-python3.7-xcffib-0.11.1/lib/python3.7/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
```

# Configuration

```python
from typing import List  # noqa: F401
from libqtile import bar, layout, widget
from libqtile.config import Click, Drag, Group, Key, Screen, KeyChord
from libqtile.lazy import lazy
from libqtile.utils import guess_terminal


mod = "mod4"
terminal = f"urxvt"

keys = []

# Drag floating layouts.
mouse = [
    Drag([mod], "Button1", lazy.window.set_position_floating(),
         start=lazy.window.get_position()),
    Drag([mod], "Button3", lazy.window.set_size_floating(),
         start=lazy.window.get_size()),
    Click([mod], "Button2", lazy.window.bring_to_front())
]

dgroups_key_binder = None
dgroups_app_rules = []  # type: List
main = None
follow_mouse_focus = True
bring_front_click = False
cursor_warp = False
floating_layout = layout.Floating(float_rules=[
    # Run the utility of `xprop` to see the wm class and name of an X client.
    {'wmclass': 'confirm'},
    {'wmclass': 'dialog'},
    {'wmclass': 'download'},
    {'wmclass': 'error'},
    {'wmclass': 'file_progress'},
    {'wmclass': 'notification'},
    {'wmclass': 'splash'},
    {'wmclass': 'toolbar'},
    {'wmclass': 'confirmreset'},  # gitk
    {'wmclass': 'makebranch'},  # gitk
    {'wmclass': 'maketag'},  # gitk
    {'wname': 'branchdialog'},  # gitk
    {'wname': 'pinentry'},  # GPG key password entry
    {'wmclass': 'ssh-askpass'},  # ssh-askpass
])
auto_fullscreen = True
focus_on_window_activation = "smart"

# XXX: Gasp! We're lying here. In fact, nobody really uses or cares about this
# string besides java UI toolkits; you can see several discussions on the
# mailing lists, GitHub issues, and other WM documentation that suggest setting
# this string if your java app doesn't work correctly. We may as well just lie
# and say that we're a working one by default.
#
# We choose LG3D to maximize irony: it is a 3D non-reparenting WM written in
# java that happens to be on java's whitelist.
wmname = "LG3D"

# extra config
from libqtile import hook

# groups
groups = [Group(str(i+1),label="") for i in range(9)]
for i in groups:
    keys.extend([
        Key([mod], i.name, lazy.group[i.name].toscreen(toggle=False),
            desc="Switch to group {}".format(i.name)),
        Key([mod, "shift"], i.name, lazy.window.togroup(i.name, switch_group=True),
            desc="Switch to & move focused window to group {}".format(i.name)),
    ])

# layouts
layouts = [layout.MonadTall()]

# bar
widget_defaults = dict(font="Iosevka Nerdfont",fontsize=12,padding=3)
extension_defaults = widget_defaults.copy()

workspace = widget.GroupBox(font="Font Awesome 5 Free Regular",fontsize=16,highlight_method="text")
status_bar = bar.Bar([workspace],32)

# screens
maxScreens = 1
screens = [Screen(bottom=status_bar) for i in range(maxScreens)]

def monad_stack_size(qtile):
    info = qtile.current_layout.info()
    return len(info["secondary"])

def grow_master(qtile):
    if monad_stack_size(qtile) != 0:
        qtile.current_layout.cmd_grow_main()

def shrink_master(qtile):
    if monad_stack_size(qtile) != 0:
        qtile.current_layout.cmd_shrink_main()

def grow_window(qtile):
    if monad_stack_size(qtile) > 1:
        qtile.current_layout.cmd_grow()

def shrink_window(qtile):
    if monad_stack_size(qtile) > 1:
        qtile.current_layout.cmd_shrink()

# Reset ratio : will work in 0.18.0
# @hook.subscribe.client_killed
# def on_client_kill(window):
#     if monad_stack_size(qtile) == 0:

# keybindings
keys.extend([
    # keybindings
    Key([mod], "Return", lazy.spawn(terminal)),
    Key([mod, "control"], "h", lazy.function(shrink_master)),
    Key([mod, "control"], "j", lazy.function(shrink_window)),
    Key([mod, "control"], "k", lazy.function(grow_window)),
    Key([mod, "control"], "l", lazy.function(grow_master)),
    Key([mod], "h", lazy.layout.left()),
    Key([mod], "j", lazy.layout.down()),
    Key([mod], "k", lazy.layout.up()),
    Key([mod], "l", lazy.layout.right()),
    Key([mod, "mod1"], "r", lazy.restart()),
    Key([mod, "shift"], "h", lazy.layout.swap_left()),
    Key([mod, "shift"], "j", lazy.layout.shuffle_down()),
    Key([mod, "shift"], "k", lazy.layout.shuffle_up()),
    Key([mod, "shift"], "l", lazy.layout.swap_right()),
])
```

**Comment by addy419** [comment]
After upgrade to 0.18.0, I still receive this error sometimes, but the groupbox shows correctly. So I'm closing this issue
