### ISSUE TITLE
Multiple borders not drawn on Firefox in X

### ISSUE THREAD

**Issue by m-col** [qtile/qtile#2781]
# Issue description

Using the x11 backend, multiple borders fail to get drawn on Firefox windows, instead keeping whatever borders they had before or no borders.

# Qtile version

Current master add6e136ce5d7f046d560979bd58a7f3b085e4d2

# Stack traces

`MatchError`s get logged when the border drawing is attempted e.g. when moving focus to a FF window. This makes me suspect it's a mismatch between window and border depth/visual or one of those other X things (haven't looked deeper).

```
2021-09-08 23:02:21,385 ERROR libqtile core.py:_xpoll():L330 Got an exception in poll loop
Traceback (most recent call last):
  File "/home/mcol/git/qtile/libqtile/backend/x11/core.py", line 284, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 612, in poll_for_event
    return self.hoist_event(e)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 686, in hoist_event
    return self._process_error(ffi.cast("xcb_generic_error_t *", e))
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 649, in _process_error
    raise error(buf)
xcffib.xproto.MatchError
2021-09-08 23:02:21,402 ERROR libqtile core.py:_xpoll():L330 Got an exception in poll loop
Traceback (most recent call last):
  File "/home/mcol/git/qtile/libqtile/backend/x11/core.py", line 284, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 612, in poll_for_event
    return self.hoist_event(e)
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 686, in hoist_event
    return self._process_error(ffi.cast("xcb_generic_error_t *", e))
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 649, in _process_error
    raise error(buf)
xcffib.xproto.MatchError
```

# Configuration

Default config, just open up firefox and either switch the `Column`s column to stack mode, or just rename the default `border_focus_stack` option to `border_focus`.

**Comment by jwijenbergh** [comment]
Put up a pr to fix this issue
