### ISSUE TITLE
MPD widget won't update

### ISSUE THREAD

**Issue by yl11283** [qtile/qtile#2803]
# Issue description

MPD2 widget sometimes won't update.  [Screenshot](https://i.imgur.com/vuLaOd4.png) 

# Qtile version

0.18.0-2

# Stack traces

Today's qtile.log errors (this only happened today):

```
2021-09-18 11:34:45,970 ERROR libqtile core.py:_xpoll():L330 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 298, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1038, in handle_KeyPress
    self.process_key_press(keysym)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 407, in process_key_press
    if self.has_keyboard:
  File "/usr/lib/python3.9/site-packages/libqtile/configurable.py", line 51, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: Bar has no attribute: has_keyboard
2021-09-18 11:35:00,863 ERROR libqtile core.py:_xpoll():L330 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 298, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1038, in handle_KeyPress
    self.process_key_press(keysym)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 407, in process_key_press
    if self.has_keyboard:
  File "/usr/lib/python3.9/site-packages/libqtile/configurable.py", line 51, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: Bar has no attribute: has_keyboard
2021-09-18 11:35:33,457 ERROR libqtile core.py:_xpoll():L330 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 298, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1038, in handle_KeyPress
    self.process_key_press(keysym)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 407, in process_key_press
    if self.has_keyboard:
  File "/usr/lib/python3.9/site-packages/libqtile/configurable.py", line 51, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: Bar has no attribute: has_keyboard
2021-09-18 12:24:40,968 ERROR libqtile base.py:on_done():L563 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 555, in on_done
    self.update(result)
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 467, in update
    self.text = text
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 359, in text
    self.layout.text = self.formatted_text
  File "/usr/lib/python3.9/site-packages/libqtile/drawer.py", line 71, in text
    attrlist, value, accel_char = pangocffi.parse_markup(value)
  File "/usr/lib/python3.9/site-packages/libqtile/pangocffi.py", line 183, in parse_markup
    raise Exception("parse_markup() failed for %s" % value)
Exception: parse_markup() failed for b'<span size="large">\xef\x85\x84</span> Pictures at an Exhibition: F. The Great Gates of Kiev - Emerson, Lake &amp\xe2\x80\xa6'
```
-->

# Configuration

https://pastebin.com/zrmW3LWv

**Comment by elParaguayo** [comment]
That looks like it's just an error with the text to be displayed. The `&amp` is causing this to fail.

I _think_ we've seen this before so let me check past issues/qtile-dev conversations.

**Comment by elParaguayo** [comment]
Yup - looks like same bug as #2649

**Comment by yl11283** [comment]
> That looks like it's just an error with the text to be displayed. The `&amp` is causing this to fail.
> 
> I _think_ we've seen this before so let me check past issues/qtile-dev conversations.

I can play other songs that have ''&" in it and they will work just fine though, it's just this one song that bugs the widget for some reason.

**Comment by elParaguayo** [comment]
Well, that's weird!

I took the string from your debug log, removed the &amp and `parse_markup`
worked ok. So it does seem to be the issue here.

**Comment by elParaguayo** [comment]
Are you able to change the metadata for that file to see if it is the ampersand that's causing the problem?

**Comment by yl11283** [comment]
> Are you able to change the metadata for that file to see if it is the ampersand that's causing the problem?

Yes, I just did and that seems to be it, but I have no idea why it only happens with that one particular song, since all other songs by "Emerson, Lake & Palmer" will work just fine, it's just this one that does that.

**Comment by m-col** [comment]
Please could you check if https://github.com/qtile/qtile/pull/2906 fixes this issue?

**Comment by alethiophile** [comment]
I am also having this issue, though I can't yet pin down what song is causing it.
