### ISSUE TITLE
run-cmd -f doesn't float window

### ISSUE THREAD

**Issue by LamprosPitsillos** [qtile/qtile#2806]
# Issue description

https://user-images.githubusercontent.com/61395246/133945613-ce778b5b-504e-4e3d-89c1-ec1633aa8c00.mp4

# Qtile version
```
❯ qtile -v
0.18.1
```

# Stack traces
```python
2021-09-20 01:48:46,440 ERROR libqtile hook.py:fire():L382 Error in hook client_new
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/hook.py", line 380, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/libqtile/dgroups.py", line 198, in _add
    client.enablefloating()
AttributeError: 'Window' object has no attribute 'enablefloating'

```

# Configuration

[MyConfig](https://gist.github.com/LamprosPitsillos/28e8e9d8984972e49f3671776114a2b3)

**Comment by elParaguayo** [comment]
Yes. Looks like that's changed. I think it should be `client.cmd_enable_floating()` now.

Will take a look later unless you can test and submit a PR if it works.
