### ISSUE TITLE
Windows do not appear when application is started

### ISSUE THREAD

**Issue by leybodv** [qtile/qtile#2807]
# Issue description

When I use lazy.spawn(application) its window does not appear on screen. Application is started, its name is in the TaskList widget and it appears as inactive (no border around its name). Window appear when I click on its name 3 times.

# Qtile version

qtile --version -> 0.18.1

# Stack traces

in ~/.local/share/qtile/qtile.log:

2021-09-20 11:51:47,298 ERROR libqtile hook.py:fire():L382 Error in hook client_new
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/hook.py", line 380, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/libqtile/dgroups.py", line 181, in _add
    client.togroup(rule.group)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1502, in togroup
    group.add(self)
  File "/usr/lib/python3.9/site-packages/libqtile/group.py", line 243, in add
    elif self.floating_layout.match(win):
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in match
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in <genexpr>
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1526, in match
    return match.compare(self)
AttributeError: 'dict' object has no attribute 'compare'
2021-09-20 11:51:47,505 ERROR libqtile hook.py:fire():L382 Error in hook client_new
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/hook.py", line 380, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/libqtile/dgroups.py", line 181, in _add
    client.togroup(rule.group)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1502, in togroup
    group.add(self)
  File "/usr/lib/python3.9/site-packages/libqtile/group.py", line 243, in add
    elif self.floating_layout.match(win):
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in match
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in <genexpr>
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1526, in match
    return match.compare(self)
AttributeError: 'dict' object has no attribute 'compare'
2021-09-20 11:51:52,692 ERROR libqtile core.py:_xpoll():L329 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 297, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 679, in handle_MapRequest
    self.qtile.manage(win)
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 576, in manage
    self.current_screen.group.add(win, focus=win.can_steal_focus)
  File "/usr/lib/python3.9/site-packages/libqtile/group.py", line 243, in add
    elif self.floating_layout.match(win):
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in match
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in <genexpr>
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1526, in match
    return match.compare(self)
AttributeError: 'dict' object has no attribute 'compare'
2021-09-20 11:51:57,713 ERROR libqtile core.py:_xpoll():L329 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 297, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1108, in handle_ButtonPress
    self.process_button_click(e.event_x, e.event_y, e.detail)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 378, in process_button_click
    widget.button_press(
  File "/usr/lib/python3.9/site-packages/libqtile/widget/tasklist.py", line 403, in button_press
    base._Widget.button_press(self, x, y, button)
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 237, in button_press
    self.mouse_callbacks[name]()
  File "/usr/lib/python3.9/site-packages/libqtile/widget/tasklist.py", line 410, in select_window
    window.group.focus(window, False)
  File "/usr/lib/python3.9/site-packages/libqtile/group.py", line 219, in focus
    layout.focus(win)
  File "/usr/lib/python3.9/site-packages/libqtile/layout/base.py", line 466, in focus
    self.clients.current_client = client
  File "/usr/lib/python3.9/site-packages/libqtile/layout/base.py", line 249, in current_client
    self._current_idx = self.clients.index(client)
ValueError: Window(name='d@arch-ideapad:~', wid=23068675) is not in list
2021-09-20 11:51:59,639 ERROR libqtile core.py:_xpoll():L329 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 297, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1677, in handle_PropertyNotify
    self.update_hints()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 639, in update_hints
    if self.group.floating_layout.match(self):
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in match
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in <genexpr>
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1526, in match
    return match.compare(self)
AttributeError: 'dict' object has no attribute 'compare'
2021-09-20 11:51:59,642 ERROR libqtile core.py:_xpoll():L329 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 297, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1677, in handle_PropertyNotify
    self.update_hints()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 639, in update_hints
    if self.group.floating_layout.match(self):
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in match
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in <genexpr>
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1526, in match
    return match.compare(self)
AttributeError: 'dict' object has no attribute 'compare'
2021-09-20 11:52:19,659 ERROR libqtile core.py:_xpoll():L329 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 297, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1675, in handle_PropertyNotify
    self.update_hints()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 639, in update_hints
    if self.group.floating_layout.match(self):
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in match
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in <genexpr>
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1526, in match
    return match.compare(self)
AttributeError: 'dict' object has no attribute 'compare'

# Configuration

[config.txt](https://github.com/qtile/qtile/files/7194619/config.txt)

**Comment by m-col** [comment]
Looks like this is the same issue as https://github.com/qtile/qtile/issues/2804. See there for a solution.

**Comment by leybodv** [comment]
@m-col Thanks! It is indeed a duplicate issue.
