### ISSUE TITLE
Qtile stopped opening windows after upgrade (0.18.0-2 -> 0.18.1-2)

### ISSUE THREAD

**Issue by yungParrot** [qtile/qtile#2827]
# Issue description

I have upgraded my system with `sudo pacman -Syu` and Qtile stopped working correctly after a reboot.

Opening *any* window wasn't working. Pressing `mod + enter` for launching a terminal window did nothing and restarting Qtile caused it to break.

I looked at the `qtile.log` file and found Python errors so I tried with another (3.9.6 instead of 3.9.7) Python version (because the Python version was also updated through the full system upgrade) but the error was still there. I then downgraded qtile through `sudo pacman -U /var/cache/pacman/pkg/qtile-0.18.0-2-x86_64.pkg.tar.zs` and now qtile works correctly.

# Qtile version

`0.18.1-2` installed from the AUR (`pacman -S qtile`).

# Stack traces

`~/.local/share/qtile/qtile.log`
```
2021-09-27 08:57:48,196 ERROR libqtile base.py:_wrapper():L307 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 231, in async_loop
    self._configure()
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 184, in _configure
    self.core.scan()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 253, in scan
    win = window.Window(item, self.qtile)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1244, in __init__
    group.add(self)
  File "/usr/lib/python3.9/site-packages/libqtile/group.py", line 243, in add
    elif self.floating_layout.match(win):
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in match
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in <genexpr>
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1526, in match
    return match.compare(self)
AttributeError: 'dict' object has no attribute 'compare'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 305, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.9/site-packages/libqtile/widget/graph.py", line 200, in update
    self.update_graph()
  File "/usr/lib/python3.9/site-packages/libqtile/widget/graph.py", line 254, in update_graph
    self.push(push_value)
  File "/usr/lib/python3.9/site-packages/libqtile/widget/graph.py", line 192, in push
    self.draw()
  File "/usr/lib/python3.9/site-packages/libqtile/widget/graph.py", line 150, in draw
    self.drawer.clear(self.background or self.bar.background)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/drawer.py", line 182, in clear
    self._check_xcb()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/drawer.py", line 122, in _check_xcb
    self._pixmap = self._create_pixmap()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/drawer.py", line 104, in _create_pixmap
    pixmap = self.qtile.core.conn.conn.generate_id()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 556, in invalid
    raise XcffibException("Invalid connection.")
xcffib.XcffibException: Invalid connection.
```
# Configuration

[My Qtile config on GitLab](https://gitlab.com/yungParrot/dotfiles/-/tree/master/.config/qtile)

---

If you need anything else please let me know 🤠

**Comment by elParaguayo** [comment]
Please try searching for your error first.

Duplicate of #2799, #2804 and #2807.

**Comment by yungParrot** [comment]
@elParaguayo Ok I'll look at those issues and close this one, thanks 🤠
