### ISSUE TITLE
(Widget Name) is not a known member of module

### ISSUE THREAD

**Issue by copypasteonly** [qtile/qtile#2841]
# Issue description

# Qtile version

# Stack traces

# Configuration

**Comment by elParaguayo** [comment]
Can you post the actual log messages please.

**Comment by copypasteonly** [comment]
> Can you post the actual log messages please.

Hello, from what I've noticed the widgets still work correctly even though it says the error, so I guess nothing is wrong? The error only appears while editing in nvim. So maybe it's an nvim issue? Nevertheless the widgets work and there are no problems. Also is it normal for the terminal to launch after half a second? It's really noticeable and annoying me.

**Comment by m-col** [comment]
Please post the error messages from ~/.local/share/qtile/qtile.log, otherwise we are pretty much unable to help you.

> Also is it normal for the terminal to launch after half a second?

**Comment by m-col** [comment]
Please post the error messages from ~/.local/share/qtile/qtile.log, otherwise we are pretty much unable to help you.

> Also is it normal for the terminal to launch after half a second?

No, this is not normal.

For what it's worth, there are many errors with that config, specifically many things use camel case when they should not e.g. `qtile.CurrentWindow` should be `qtile.current_window`.

**Comment by copypasteonly** [comment]
> Please post the error messages from ~/.local/share/qtile/qtile.log, otherwise we are pretty much unable to help you.
> 
> > Also is it normal for the terminal to launch after half a second?
> 
> No, this is not normal.
> 
> For what it's worth, there are many errors with that config, specifically many things use camel case when they should not e.g. `qtile.CurrentWindow` should be `qtile.current_window`.

I see this are the errors that I am getting. 
```
2021-10-04 14:44:59,105 ERROR libqtile manager.py:process_button_motion():L725 Mouse command error set_position_floating: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/command/interface.py", line 313, in call
    return SUCCESS, cmd(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1789, in cmd_set_position_floating
    self.tweak_float(x=x, y=y)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1436, in tweak_float
    screen = self.qtile.find_closest_screen(
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 630, in find_closest_screen
    return self._find_closest_closest(x, y, x_match + y_match)
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 654, in _find_closest_closest
    closest_screen = candidate_screens[0]
IndexError: list index out of range

2021-10-04 16:07:05,903 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
2021-10-04 16:07:06,557 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
2021-10-04 16:36:08,406 ERROR libqtile manager.py:process_key_event():L361 KB command error section_up: No such command
2021-10-04 16:36:11,976 ERROR libqtile manager.py:process_key_event():L361 KB command error section_up: No such command
2021-10-04 17:54:20,157 ERROR libqtile manager.py:process_key_event():L361 KB command error section_down: No such command
2021-10-04 17:54:20,542 ERROR libqtile manager.py:process_key_event():L361 KB command error section_up: No such command
2021-10-04 18:47:22,371 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
2021-10-04 18:47:22,752 ERROR libqtile manager.py:process_key_event():L361 KB command error section_down: No such command
2021-10-04 18:47:23,287 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
2021-10-04 18:47:23,600 ERROR libqtile manager.py:process_key_event():L361 KB command error move_right: No such command
2021-10-04 18:47:24,451 ERROR libqtile manager.py:process_key_event():L361 KB command error section_down: No such command
2021-10-04 18:47:24,717 ERROR libqtile manager.py:process_key_event():L361 KB command error move_right: No such command
2021-10-04 18:47:26,450 ERROR libqtile manager.py:process_key_event():L361 KB command error section_up: No such command
2021-10-04 18:47:27,518 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
2021-10-04 18:47:27,726 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
2021-10-04 18:47:27,909 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
2021-10-04 18:47:29,200 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
2021-10-04 18:47:29,659 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
2021-10-04 18:47:30,295 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
2021-10-04 18:47:30,754 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
2021-10-04 18:47:31,036 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
2021-10-04 18:47:31,243 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
2021-10-04 18:47:31,548 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
2021-10-04 18:47:31,759 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
2021-10-04 18:47:32,019 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
2021-10-04 18:47:32,646 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
2021-10-04 18:47:35,094 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
2021-10-04 18:47:35,557 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
2021-10-04 18:47:35,738 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
2021-10-04 18:47:35,925 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
2021-10-04 18:47:36,301 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
2021-10-04 18:47:36,484 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
2021-10-04 18:47:36,797 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
2021-10-04 18:47:36,979 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
2021-10-04 18:47:38,519 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
2021-10-04 18:47:38,927 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
```
I don't really see any errors when using qtile though so idk.

**Comment by jwijenbergh** [comment]
> > Please post the error messages from ~/.local/share/qtile/qtile.log, otherwise we are pretty much unable to help you.
> > > Also is it normal for the terminal to launch after half a second?
> > 
> > 
> > No, this is not normal.
> > For what it's worth, there are many errors with that config, specifically many things use camel case when they should not e.g. `qtile.CurrentWindow` should be `qtile.current_window`.
> 
> I see, these are the errors that I am getting.
> 
> ```
> 2021-10-04 14:44:59,105 ERROR libqtile manager.py:process_button_motion():L725 Mouse command error set_position_floating: Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/libqtile/command/interface.py", line 313, in call
>     return SUCCESS, cmd(*args, **kwargs)
>   File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1789, in cmd_set_position_floating
>     self.tweak_float(x=x, y=y)
>   File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1436, in tweak_float
>     screen = self.qtile.find_closest_screen(
>   File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 630, in find_closest_screen
>     return self._find_closest_closest(x, y, x_match + y_match)
>   File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 654, in _find_closest_closest
>     closest_screen = candidate_screens[0]
> IndexError: list index out of range
> 
> 2021-10-04 16:07:05,903 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> 2021-10-04 16:07:06,557 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> 2021-10-04 16:36:08,406 ERROR libqtile manager.py:process_key_event():L361 KB command error section_up: No such command
> 2021-10-04 16:36:11,976 ERROR libqtile manager.py:process_key_event():L361 KB command error section_up: No such command
> 2021-10-04 17:54:20,157 ERROR libqtile manager.py:process_key_event():L361 KB command error section_down: No such command
> 2021-10-04 17:54:20,542 ERROR libqtile manager.py:process_key_event():L361 KB command error section_up: No such command
> 2021-10-04 18:47:22,371 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
> 2021-10-04 18:47:22,752 ERROR libqtile manager.py:process_key_event():L361 KB command error section_down: No such command
> 2021-10-04 18:47:23,287 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
> 2021-10-04 18:47:23,600 ERROR libqtile manager.py:process_key_event():L361 KB command error move_right: No such command
> 2021-10-04 18:47:24,451 ERROR libqtile manager.py:process_key_event():L361 KB command error section_down: No such command
> 2021-10-04 18:47:24,717 ERROR libqtile manager.py:process_key_event():L361 KB command error move_right: No such command
> 2021-10-04 18:47:26,450 ERROR libqtile manager.py:process_key_event():L361 KB command error section_up: No such command
> 2021-10-04 18:47:27,518 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
> 2021-10-04 18:47:27,726 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
> 2021-10-04 18:47:27,909 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
> 2021-10-04 18:47:29,200 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> 2021-10-04 18:47:29,659 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> 2021-10-04 18:47:30,295 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> 2021-10-04 18:47:30,754 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> 2021-10-04 18:47:31,036 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> 2021-10-04 18:47:31,243 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> 2021-10-04 18:47:31,548 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> 2021-10-04 18:47:31,759 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> 2021-10-04 18:47:32,019 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> 2021-10-04 18:47:32,646 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
> 2021-10-04 18:47:35,094 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> 2021-10-04 18:47:35,557 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> 2021-10-04 18:47:35,738 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> 2021-10-04 18:47:35,925 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> 2021-10-04 18:47:36,301 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> 2021-10-04 18:47:36,484 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> 2021-10-04 18:47:36,797 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> 2021-10-04 18:47:36,979 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> 2021-10-04 18:47:38,519 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> 2021-10-04 18:47:38,927 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> ```
> 
> I don't really see any errors when using qtile though so idk. The only thing that's bothering me really is the slow opening of my terminal (Kitty) maybe it's a terminal issue?

The terminal thing doesn't have to be a qtile issue. Can you try a different terminal such as st and see if that is faster. On my machine the startup of st is much faster. It's a way more minimal terminal though. You could also try alacritty for a nice middle ground. If you want to stick with kitty you can also try kitty --single-instance to have a speed up when a kitty terminal is already opened.

Not a perfect way to test but this gives you a rough idea of the startup time:

![image](https://user-images.githubusercontent.com/46386452/135878317-9a71e1b6-954c-40a4-b6b2-2a71210bd888.png)
![image](https://user-images.githubusercontent.com/46386452/135878412-08287098-b5fd-4f87-b4f0-427ade9a97f2.png)
![image](https://user-images.githubusercontent.com/46386452/135878488-edd98299-c6d1-4792-8641-fb772a443928.png)

**Comment by copypasteonly** [comment]
> > > Please post the error messages from ~/.local/share/qtile/qtile.log, otherwise we are pretty much unable to help you.
> > > > Also is it normal for the terminal to launch after half a second?
> > > 
> > > 
> > > No, this is not normal.
> > > For what it's worth, there are many errors with that config, specifically many things use camel case when they should not e.g. `qtile.CurrentWindow` should be `qtile.current_window`.
> > 
> > 
> > I see, these are the errors that I am getting.
> > ```
> > 2021-10-04 14:44:59,105 ERROR libqtile manager.py:process_button_motion():L725 Mouse command error set_position_floating: Traceback (most recent call last):
> >   File "/usr/lib/python3.9/site-packages/libqtile/command/interface.py", line 313, in call
> >     return SUCCESS, cmd(*args, **kwargs)
> >   File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1789, in cmd_set_position_floating
> >     self.tweak_float(x=x, y=y)
> >   File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1436, in tweak_float
> >     screen = self.qtile.find_closest_screen(
> >   File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 630, in find_closest_screen
> >     return self._find_closest_closest(x, y, x_match + y_match)
> >   File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 654, in _find_closest_closest
> >     closest_screen = candidate_screens[0]
> > IndexError: list index out of range
> > 
> > 2021-10-04 16:07:05,903 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> > 2021-10-04 16:07:06,557 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> > 2021-10-04 16:36:08,406 ERROR libqtile manager.py:process_key_event():L361 KB command error section_up: No such command
> > 2021-10-04 16:36:11,976 ERROR libqtile manager.py:process_key_event():L361 KB command error section_up: No such command
> > 2021-10-04 17:54:20,157 ERROR libqtile manager.py:process_key_event():L361 KB command error section_down: No such command
> > 2021-10-04 17:54:20,542 ERROR libqtile manager.py:process_key_event():L361 KB command error section_up: No such command
> > 2021-10-04 18:47:22,371 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
> > 2021-10-04 18:47:22,752 ERROR libqtile manager.py:process_key_event():L361 KB command error section_down: No such command
> > 2021-10-04 18:47:23,287 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
> > 2021-10-04 18:47:23,600 ERROR libqtile manager.py:process_key_event():L361 KB command error move_right: No such command
> > 2021-10-04 18:47:24,451 ERROR libqtile manager.py:process_key_event():L361 KB command error section_down: No such command
> > 2021-10-04 18:47:24,717 ERROR libqtile manager.py:process_key_event():L361 KB command error move_right: No such command
> > 2021-10-04 18:47:26,450 ERROR libqtile manager.py:process_key_event():L361 KB command error section_up: No such command
> > 2021-10-04 18:47:27,518 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
> > 2021-10-04 18:47:27,726 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
> > 2021-10-04 18:47:27,909 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
> > 2021-10-04 18:47:29,200 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> > 2021-10-04 18:47:29,659 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> > 2021-10-04 18:47:30,295 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> > 2021-10-04 18:47:30,754 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> > 2021-10-04 18:47:31,036 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> > 2021-10-04 18:47:31,243 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> > 2021-10-04 18:47:31,548 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> > 2021-10-04 18:47:31,759 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> > 2021-10-04 18:47:32,019 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> > 2021-10-04 18:47:32,646 ERROR libqtile manager.py:process_key_event():L361 KB command error move_left: No such command
> > 2021-10-04 18:47:35,094 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> > 2021-10-04 18:47:35,557 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> > 2021-10-04 18:47:35,738 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> > 2021-10-04 18:47:35,925 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> > 2021-10-04 18:47:36,301 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> > 2021-10-04 18:47:36,484 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> > 2021-10-04 18:47:36,797 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> > 2021-10-04 18:47:36,979 ERROR libqtile manager.py:process_key_event():L361 KB command error increase_nmaster: No such command
> > 2021-10-04 18:47:38,519 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> > 2021-10-04 18:47:38,927 ERROR libqtile manager.py:process_key_event():L361 KB command error decrease_nmaster: No such command
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't really see any errors when using qtile though so idk. The only thing that's bothering me really is the slow opening of my terminal (Kitty) maybe it's a terminal issue?
> 
> The terminal thing doesn't have to be a qtile issue. Can you try a different terminal such as st and see if that is faster. On my machine the startup of st is much faster. It's a way more minimal terminal though. You could also try alacritty for a nice middle ground. If you want to stick with kitty you can also try `kitty --single-instance` to have a speed up when a kitty terminal is already opened.
> 
> Not a perfect way to test but this gives you a rough idea of the startup time:
> 
> ![image](https://user-images.githubusercontent.com/46386452/135878317-9a71e1b6-954c-40a4-b6b2-2a71210bd888.png) ![image](https://user-images.githubusercontent.com/46386452/135878412-08287098-b5fd-4f87-b4f0-427ade9a97f2.png) ![image](https://user-images.githubusercontent.com/46386452/135878488-edd98299-c6d1-4792-8641-fb772a443928.png)

Yep, just tried and st and it is a terminal issue. Might try to find other alternatives, thanks!
