### ISSUE TITLE
libqtile hook.py:fire():L391 Error in hook client_new: TypeError: 'in <string>' requires string as left operand, not list

### ISSUE THREAD

**Issue by aliceinwire** [qtile/qtile#2994]
### The bug:

2021-11-08 23:18:09,755 ERROR libqtile hook.py:fire():L391 Error in hook client_new
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/hook.py", line 389, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/libqtile/dgroups.py", line 169, in _add
    if rule.matches(client):
  File "/usr/lib/python3.9/site-packages/libqtile/config.py", line 683, in matches
    return any(w.match(m) for m in self.matchlist)
  File "/usr/lib/python3.9/site-packages/libqtile/config.py", line 683, in <genexpr>
    return any(w.match(m) for m in self.matchlist)
  File "/usr/lib/python3.9/site-packages/libqtile/window.py", line 1056, in match
    return match.compare(self)
  File "/usr/lib/python3.9/site-packages/libqtile/config.py", line 639, in compare
    if not match(rule_value):
  File "/usr/lib/python3.9/site-packages/libqtile/config.py", line 615, in predicate
    return match(value)
  File "/usr/lib/python3.9/site-packages/libqtile/config.py", line 614, in <lambda>
    match = getattr(other, 'match', lambda v: other in v)
TypeError: 'in <string>' requires string as left operand, not list

### 

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks for submitting the bug report.

Can you let us know what you were doing to trigger this bug so we can try to recreate it.
