### ISSUE TITLE
`xcffib.XcffibException: Invalid connection.` and `AttributeError: 'Screen' object has no attribute 'group'`

### ISSUE THREAD

**Issue by kovasap** [qtile/qtile#3038]
I was debugging some hard-to-reproduce qtile crashes and found these two exceptions repeated over and over in the qtile log:

```
2021-11-11 09:59:58,550 ERROR libqtile hook.py:fire():L395 Error in hook screen_change
Traceback (most recent call last):
  File "/home/kovas/qtile/libqtile/hook.py", line 393, in fire
    i(*args, **kwargs)
  File "/home/kovas/qtile/libqtile/core/manager.py", line 356, in cmd_reconfigure_screens
    self._process_screens()
  File "/home/kovas/qtile/libqtile/core/manager.py", line 337, in _process_screens
    scr._configure(self, i, x, y, w, h, grp)
  File "/home/kovas/qtile/libqtile/config.py", line 289, in _configure
    self.set_group(group)
  File "/home/kovas/qtile/libqtile/config.py", line 348, in set_group
    g1 = self.group
AttributeError: 'Screen' object has no attribute 'group'
2021-11-11 09:59:58,795 ERROR libqtile base.py:_wrapper():L310 got exception from widget timer
Traceback (most recent call last):
  File "/home/kovas/qtile/libqtile/widget/base.py", line 308, in _wrapper
    method(*method_args)
  File "/home/kovas/qtile/libqtile/widget/graph.py", line 200, in update
    self.update_graph()
  File "/home/kovas/qtile/libqtile/widget/graph.py", line 254, in update_graph
    self.push(push_value)
  File "/home/kovas/qtile/libqtile/widget/graph.py", line 192, in push
    self.draw()
  File "/home/kovas/qtile/libqtile/widget/graph.py", line 179, in draw
    self.drawer.draw(offsetx=self.offset, width=self.width)
  File "/home/kovas/qtile/libqtile/backend/base.py", line 708, in draw
    self._draw(offsetx, offsety, width, height)
  File "/home/kovas/qtile/libqtile/backend/x11/drawer.py", line 157, in _draw
    self.qtile.core.conn.conn.core.CopyArea(  # type: ignore
  File "/home/kovas/.virtualenvs/qtile/lib/python3.9/site-packages/xcffib/xproto.py", line 3035, in CopyArea
    return self.send_request(62, buf, is_checked=is_checked)
  File "/home/kovas/.virtualenvs/qtile/lib/python3.9/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/home/kovas/.virtualenvs/qtile/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/home/kovas/.virtualenvs/qtile/lib/python3.9/site-packages/xcffib/__init__.py", line 556, in invalid
    raise XcffibException("Invalid connection.")
xcffib.XcffibException: Invalid connection.
```

Any ideas what might be causing them?

My qtile version is:
```
bin/qtile --version
0.17.1.dev166+g684522d0
```

**Comment by m-col** [comment]
Not sure, but I suggest updating Qtile - it looks like you're a couple releases behind.

**Comment by kovasap** [comment]
After update I don't get the `'Screen' object has no attribute 'group'` error, but i still get the `Invalid connection.` error.

**Comment by elParaguayo** [comment]
Interesting. We're also seeing that screen error in #3039 but on a much more up to date install.
