### ISSUE TITLE
mouse_callbacks throws exception upon usage

### ISSUE THREAD

**Issue by TKaemp** [qtile/qtile#3054]
I tried applying `mouse_callbacks` to one of my widgets, however clicking on it throws an exception. Running 0.18.1.

The following snippet

```py
widget.TextBox(
    text="click me",
    mouse_callbacks={
        "Button1": lazy.spawn("playerctl play-pause"),
    },
),
```

returns the following in the logs

```py
2021-11-26 14:31:31,975 ERROR libqtile core.py:_xpoll():L329 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 297, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1108, in handle_ButtonPress
    self.process_button_click(e.event_x, e.event_y, e.detail)
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 378, in process_button_click
    widget.button_press(
  File "/usr/lib/python3.9/site-packages/libqtile/widget/base.py", line 237, in button_press
    self.mouse_callbacks[name]()
TypeError: 'LazyCall' object is not callable
```

**Comment by elParaguayo** [comment]
The ability for widgets to take `lazy` objects is not part of 0.18.1.

You'll need to run the latest git version or wait for us to push the next release (which should be soon) and then for that to be packaged by your distro.

**Comment by TKaemp** [comment]
Thank you for the fast response. Since I am using Arch, I simply replaced it with the git version. It is working perfectly fine now.
