### ISSUE TITLE
Can't use key combinations such as `Ctrl+Alt+F2` to switch to a different virtual console

### ISSUE THREAD

**Issue by mhwombat** [qtile/qtile#3055]
On other wayland compositors (e.g. river, sway) and X11 window managers, I can use key combinations such as `Ctrl+Alt+F2` to switch to a different virtual console. In Qtile, this key combination has no effect. I have verified that the problem occurs with the **default configuration**. Perhaps Qtile is somehow "grabbing" certain keys.

```
$ qtile -v
0.18.1
```

To investigate this issue, I launched `wev` from within *Sway* and pressed `Ctrl+Alt+F2`. Note that `wev` only reports the `Ctrl` and `Alt` press and release (at which point I was switched to virtual console 2).

```
[14:     wl_keyboard] key: serial: 602; time: 93610128; key: 37; state: 1 (pressed)
                      sym: Control_L    (65507), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000004: Control
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 604; time: 93610376; key: 64; state: 1 (pressed)
                      sym: Alt_L        (65513), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 0000000C: Control Mod1
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 606; time: 93610740; key: 37; state: 0 (released)
                      sym: Control_L    (65507), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000008: Mod1
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 608; time: 93610740; key: 64; state: 0 (released)
                      sym: Alt_L        (65513), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
```

Now compare this with what happens when I launched `wev` from within *Qtile* and pressed `Ctrl+Alt+F2`. Note that all three key press and release events are reported.

```
14:     wl_keyboard] key: serial: 144; time: 93748304; key: 37; state: 1 (pressed)
                      sym: Control_L    (65507), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000004: Control
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 146; time: 93748695; key: 64; state: 1 (pressed)
                      sym: Alt_L        (65513), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 0000000C: Control Mod1
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 148; time: 93749077; key: 68; state: 1 (pressed)
                      sym: XF86Switch_VT_2 (269024770), utf8: ''
[14:     wl_keyboard] key: serial: 149; time: 93749184; key: 68; state: 0 (released)
                      sym: XF86Switch_VT_2 (269024770), utf8: ''
[14:     wl_keyboard] key: serial: 150; time: 93749504; key: 64; state: 0 (released)
                      sym: Alt_L        (65513), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000004: Control
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 152; time: 93749552; key: 37; state: 0 (released)
                      sym: Control_L    (65507), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
```

**Comment by elParaguayo** [comment]
You need to bind keys to `lazy.cora.change_vt(x)` where `x` is the number of the vt to switch to.

**Comment by mhwombat** [comment]
Ah, thank you for that! So, I've added the following in my config:

```
    Key(["control", "mod1"], "XF86Switch_VT_1", lazy.core.change_vt(1), desc="Go to virtual console 1"),
    Key(["control", "mod1"], "XF86Switch_VT_2", lazy.core.change_vt(2), desc="Go to virtual console 2"),
    Key(["control", "mod1"], "XF86Switch_VT_3", lazy.core.change_vt(3), desc="Go to virtual console 3"),
    Key(["control", "mod1"], "XF86Switch_VT_4", lazy.core.change_vt(4), desc="Go to virtual console 4"),
    Key(["control", "mod1"], "XF86Switch_VT_5", lazy.core.change_vt(5), desc="Go to virtual console 5"),
    Key(["control", "mod1"], "XF86Switch_VT_6", lazy.core.change_vt(6), desc="Go to virtual console 6"),
    Key(["control", "mod1"], "XF86Switch_VT_7", lazy.core.change_vt(7), desc="Go to virtual console 7"),
    Key(["control", "mod1"], "XF86Switch_VT_8", lazy.core.change_vt(8), desc="Go to virtual console 8"),
    Key(["control", "mod1"], "XF86Switch_VT_9", lazy.core.change_vt(9), desc="Go to virtual console 9"),
```

When I press Ctrl+Alt+F2, etc., nothing happens but I do get lots of these messages sent to `stderr`:

```
00:00:12.642 [ERROR] [backend/drm/drm.c:1594] drmHandleEvent failed
00:00:12.642 [ERROR] [backend/drm/drm.c:1594] drmHandleEvent failed
00:00:12.642 [ERROR] [backend/drm/drm.c:1594] drmHandleEvent failed
00:00:12.642 [ERROR] [backend/drm/drm.c:1594] drmHandleEvent failed
00:00:12.642 [ERROR] [backend/drm/drm.c:1594] drmHandleEvent failed
00:00:12.642 [ERROR] [backend/drm/drm.c:1594] drmHandleEvent failed
00:00:12.642 [ERROR] [backend/drm/drm.c:1594] drmHandleEvent failed
00:00:12.642 [ERROR] [backend/drm/drm.c:1594] drmHandleEvent failed
00:00:12.642 [ERROR] [backend/drm/drm.c:1594] drmHandleEvent failed
```

Any thoughts?

**Comment by mhwombat** [comment]
I also added this to my config, but no joy.

```
    Key(["control", "mod1"], "F1", lazy.core.change_vt(1), desc="Go to virtual console 1"),
    Key(["control", "mod1"], "F2", lazy.core.change_vt(2), desc="Go to virtual console 2"),
    Key(["control", "mod1"], "F3", lazy.core.change_vt(3), desc="Go to virtual console 3"),
    Key(["control", "mod1"], "F4", lazy.core.change_vt(4), desc="Go to virtual console 4"),
    Key(["control", "mod1"], "F5", lazy.core.change_vt(5), desc="Go to virtual console 5"),
    Key(["control", "mod1"], "F6", lazy.core.change_vt(6), desc="Go to virtual console 6"),
    Key(["control", "mod1"], "F7", lazy.core.change_vt(7), desc="Go to virtual console 7"),
    Key(["control", "mod1"], "F8", lazy.core.change_vt(8), desc="Go to virtual console 8"),
    Key(["control", "mod1"], "F9", lazy.core.change_vt(9), desc="Go to virtual console 9"),
```

**Comment by m-col** [comment]
Those last ones should work. I think in some circumstances key combinations are implicitly modified e.g. I think Ctrl+alt+F1 is converted to XF86Switch_VT_1 in X. Maybe the ctrl-mod1-F1 is also being changed to something too. Could you try with "mod4" and "F1" only? These are working for me. Failing that - could you post your whole config?

**Comment by mhwombat** [comment]
That didn't work either, unfortunately. I also tried swapping the order `Key(["control", "mod1"],` to `Key(["mod1", "control"],` just in case that made a difference. It didn't.

Here's my config file:

```
from typing import List  # noqa: F401

from libqtile import bar, layout, widget
from libqtile.config import Click, Drag, Group, Key, Match, Screen
from libqtile.lazy import lazy
from libqtile.utils import guess_terminal

mod = "mod4"
terminal = guess_terminal()
menu = "bemenu-run"

keys = [
    # A list of available commands that can be bound to keys can be found
    # at https://docs.qtile.org/en/latest/manual/config/lazy.html

    # Switch between windows
    Key([mod], "Left", lazy.layout.left(), desc="Move focus to left"),
    Key([mod], "Right", lazy.layout.right(), desc="Move focus to right"),
    Key([mod], "Down", lazy.layout.down(), desc="Move focus down"),
    Key([mod], "Up", lazy.layout.up(), desc="Move focus up"),
    Key([mod], "space", lazy.layout.next(),
        desc="Move window focus to other window"),

    # Move windows between left/right columns or move up/down in current stack.
    # Moving out of range in Columns layout will create new column.
    Key([mod, "shift"], "Left", lazy.layout.shuffle_left(),
        desc="Move window to the left"),
    Key([mod, "shift"], "Right", lazy.layout.shuffle_right(),
        desc="Move window to the right"),
    Key([mod, "shift"], "Down", lazy.layout.shuffle_down(),
        desc="Move window down"),
    Key([mod, "shift"], "Up", lazy.layout.shuffle_up(), desc="Move window up"),

    # Grow windows. If current window is on the edge of screen and direction
    # will be to screen edge - window would shrink.
    Key([mod, "control"], "Left", lazy.layout.grow_left(),
        desc="Grow window to the left"),
    Key([mod, "control"], "Right", lazy.layout.grow_right(),
        desc="Grow window to the right"),
    Key([mod, "control"], "Down", lazy.layout.grow_down(),
        desc="Grow window down"),
    Key([mod, "control"], "Up", lazy.layout.grow_up(), desc="Grow window up"),
    Key([mod], "n", lazy.layout.normalize(), desc="Reset all window sizes"),

    # Toggle between split and unsplit sides of stack.
    # Split = all windows displayed
    # Unsplit = 1 window displayed, like Max layout, but still with
    # multiple stack panes
    # Key([mod, "shift"], "Return", lazy.layout.toggle_split(),
    #     desc="Toggle between split and unsplit sides of stack"),
    Key([mod], "Return", lazy.spawn(menu), desc="Show launch menu"),
    Key([mod, "shift"], "Return", lazy.spawn(terminal), desc="Launch terminal"),

    # Toggle between different layouts as defined below
    Key([mod], "Tab", lazy.next_layout(), desc="Toggle between layouts"),
    Key([mod], "Delete", lazy.window.kill(), desc="Kill focused window"),

    Key([mod, "control"], "r", lazy.reload_config(), desc="Reload the config"),
    Key([mod, "control"], "q", lazy.shutdown(), desc="Shutdown Qtile"),
    Key([mod], "r", lazy.spawncmd(),
        desc="Spawn a command using a prompt widget"),

    Key(["mod1", "control"], "XF86Switch_VT_1", lazy.core.change_vt(1), desc="Go to virtual console 1"),
    Key(["mod1", "control"], "XF86Switch_VT_2", lazy.core.change_vt(2), desc="Go to virtual console 2"),
    Key(["mod1", "control"], "XF86Switch_VT_3", lazy.core.change_vt(3), desc="Go to virtual console 3"),
    Key(["mod1", "control"], "XF86Switch_VT_4", lazy.core.change_vt(4), desc="Go to virtual console 4"),
    Key(["mod1", "control"], "XF86Switch_VT_5", lazy.core.change_vt(5), desc="Go to virtual console 5"),
    Key(["mod1", "control"], "XF86Switch_VT_6", lazy.core.change_vt(6), desc="Go to virtual console 6"),
    Key(["mod1", "control"], "XF86Switch_VT_7", lazy.core.change_vt(7), desc="Go to virtual console 7"),
    Key(["mod1", "control"], "XF86Switch_VT_8", lazy.core.change_vt(8), desc="Go to virtual console 8"),
    Key(["mod1", "control"], "XF86Switch_VT_9", lazy.core.change_vt(9), desc="Go to virtual console 9"),

    Key(["mod1", "control"], "F1", lazy.core.change_vt(1), desc="Go to virtual console 1"),
    Key(["mod1", "control"], "F2", lazy.core.change_vt(2), desc="Go to virtual console 2"),
    Key(["mod1", "control"], "F3", lazy.core.change_vt(3), desc="Go to virtual console 3"),
    Key(["mod1", "control"], "F4", lazy.core.change_vt(4), desc="Go to virtual console 4"),
    Key(["mod1", "control"], "F5", lazy.core.change_vt(5), desc="Go to virtual console 5"),
    Key(["mod1", "control"], "F6", lazy.core.change_vt(6), desc="Go to virtual console 6"),
    Key(["mod1", "control"], "F7", lazy.core.change_vt(7), desc="Go to virtual console 7"),
    Key(["mod1", "control"], "F8", lazy.core.change_vt(8), desc="Go to virtual console 8"),
    Key(["mod1", "control"], "F9", lazy.core.change_vt(9), desc="Go to virtual console 9"),

    Key([mod], "F1", lazy.core.change_vt(1), desc="Go to virtual console 1"),
    Key([mod], "F2", lazy.core.change_vt(2), desc="Go to virtual console 2"),
    Key([mod], "F3", lazy.core.change_vt(3), desc="Go to virtual console 3"),
    Key([mod], "F4", lazy.core.change_vt(4), desc="Go to virtual console 4"),
    Key([mod], "F5", lazy.core.change_vt(5), desc="Go to virtual console 5"),
    Key([mod], "F6", lazy.core.change_vt(6), desc="Go to virtual console 6"),
    Key([mod], "F7", lazy.core.change_vt(7), desc="Go to virtual console 7"),
    Key([mod], "F8", lazy.core.change_vt(8), desc="Go to virtual console 8"),
    Key([mod], "F9", lazy.core.change_vt(9), desc="Go to virtual console 9"),
]

groups = [Group(i) for i in "123456789nvmq"]

for i in groups:
    keys.extend([
        # mod1 + letter of group = switch to group
        Key([mod], i.name, lazy.group[i.name].toscreen(),
            desc="Switch to group {}".format(i.name)),

        # # mod1 + shift + letter of group = switch to & move focused window to group
        # Key([mod, "shift"], i.name, lazy.window.togroup(i.name, switch_group=True),
        #     desc="Switch to & move focused window to group {}".format(i.name)),
        # Or, use below if you prefer not to switch to that group.
        # mod1 + shift + letter of group = move focused window to group
        Key([mod, "shift"], i.name, lazy.window.togroup(i.name),
            desc="move focused window to group {}".format(i.name)),
    ])

layouts = [
    layout.Columns(border_focus_stack=['#d75f5f', '#8f3d3d'], border_width=4),
    layout.Max(),
    # Try more layouts by unleashing below layouts.
    # layout.Stack(num_stacks=2),
    # layout.Bsp(),
    # layout.Matrix(),
    # layout.MonadTall(),
    # layout.MonadWide(),
    # layout.RatioTile(),
    # layout.Tile(),
    # layout.TreeTab(),
    # layout.VerticalTile(),
    # layout.Zoomy(),
]

widget_defaults = dict(
    font='sans',
    fontsize=12,
    padding=3,
)
extension_defaults = widget_defaults.copy()

screens = [
    Screen(
        bottom=bar.Bar(
            [
                widget.CurrentLayout(),
                widget.GroupBox(),
                widget.Prompt(),
                widget.WindowName(),
                widget.Chord(
                    chords_colors={
                        'launch': ("#ff0000", "#ffffff"),
                    },
                    name_transform=lambda name: name.upper(),
                ),
                widget.TextBox("default config", name="default"),
                widget.TextBox("Press &lt;M-r&gt; to spawn", foreground="#d75f5f"),
                # widget.Systray(),
                widget.Clock(format='%A, %d %B %Y %H:%M'),
                widget.QuickExit(),
            ],
            24,
            # border_width=[2, 0, 2, 0],  # Draw top and bottom borders
            # border_color=["ff00ff", "000000", "ff00ff", "000000"]  # Borders are magenta
        ),
    ),
]

# Drag floating layouts.
mouse = [
    Drag([mod], "Button1", lazy.window.set_position_floating(),
         start=lazy.window.get_position()),
    Drag([mod], "Button3", lazy.window.set_size_floating(),
         start=lazy.window.get_size()),
    Click([mod], "Button2", lazy.window.bring_to_front())
]

dgroups_key_binder = None
dgroups_app_rules = []  # type: List
follow_mouse_focus = False
bring_front_click = False
cursor_warp = False
floating_layout = layout.Floating(float_rules=[
    # Run the utility of `xprop` to see the wm class and name of an X client.
    *layout.Floating.default_float_rules,
    Match(wm_class='confirmreset'),  # gitk
    Match(wm_class='makebranch'),  # gitk
    Match(wm_class='maketag'),  # gitk
    Match(wm_class='ssh-askpass'),  # ssh-askpass
    Match(title='branchdialog'),  # gitk
    Match(title='pinentry'),  # GPG key password entry
])
auto_fullscreen = True
focus_on_window_activation = "smart"
reconfigure_screens = True

# If things like steam games want to auto-minimize themselves when losing
# focus, should we respect this or not?
auto_minimize = True

# XXX: Gasp! We're lying here. In fact, nobody really uses or cares about this
# string besides java UI toolkits; you can see several discussions on the
# mailing lists, GitHub issues, and other WM documentation that suggest setting
# this string if your java app doesn't work correctly. We may as well just lie
# and say that we're a working one by default.
#
# We choose LG3D to maximize irony: it is a 3D non-reparenting WM written in
# java that happens to be on java's whitelist.
wmname = "LG3D"
```

**Comment by m-col** [comment]
Do you see any output in the log when you try to key combo?

**Comment by mhwombat** [comment]
Here's the log output. The `KB command error change_vt: No such command` looks suspicious!

```
2021-11-26 23:05:49,061 WARNING libqtile prompt.py:_configure():L434 Prompt widget only supports audible bell under X11
2021-11-26 23:06:01,798 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
2021-11-26 23:15:21,123 WARNING libqtile prompt.py:_configure():L434 Prompt widget only supports audible bell under X11
2021-11-26 23:15:33,294 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
2021-11-26 23:16:58,478 WARNING libqtile prompt.py:_configure():L434 Prompt widget only supports audible bell under X11
2021-11-26 23:17:01,107 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-26 23:17:02,579 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-26 23:17:11,966 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
2021-11-26 23:40:49,681 WARNING libqtile prompt.py:_configure():L434 Prompt widget only supports audible bell under X11
2021-11-26 23:40:54,211 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-26 23:40:57,842 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-26 23:40:59,698 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-26 23:41:00,130 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-26 23:41:00,514 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-26 23:41:00,938 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-26 23:41:23,034 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-26 23:41:31,418 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-26 23:43:36,402 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-26 23:43:37,898 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-26 23:43:42,306 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-26 23:43:44,954 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-26 23:43:47,178 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-26 23:44:06,354 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
2021-11-27 17:02:23,100 WARNING libqtile prompt.py:_configure():L434 Prompt widget only supports audible bell under X11
2021-11-27 17:02:26,435 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-27 17:02:32,179 ERROR libqtile manager.py:process_key_event():L361 KB command error togroup: No object window in path 'window'
2021-11-27 17:02:35,221 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
```

And here's what's sent to stdout and stderr:

```
2021-11-27 17:02:23,100 WARNING libqtile prompt.py:_configure():L434 Prompt widget only supports audible bell under X11
00:00:03.192 [ERROR] [libinput] event11 -   wired keyboard: client bug: event processing lagging behind by 27ms, your system is too slow

2021-11-27 17:02:26,435 ERROR libqtile manager.py:process_key_event():L361 KB command error change_vt: No such command
2021-11-27 17:02:32,179 ERROR libqtile manager.py:process_key_event():L361 KB command error togroup: No object window in path 'window'
Exception ignored from cffi callback <function notify_func at 0x7f3d6d2a1f70>:
Traceback (most recent call last):
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/pywayland/server/listener.py", line 33, in notify_func
    callback(listener, data)
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/libqtile/backend/wayland/keyboard.py", line 90, in _on_destroy
    self.finalize()
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/libqtile/backend/wayland/keyboard.py", line 68, in finalize
    if self.core.keyboards and self.core.seat.keyboard.destroyed:
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/wlroots/wlr_types/seat.py", line 119, in keyboard
    keyboard_ptr = lib.wlr_seat_get_keyboard(self._ptr)
TypeError: initializer for ctype 'struct wlr_seat *' must be a cdata pointer, not NoneType
Exception ignored from cffi callback <function notify_func at 0x7f3d6d2a1f70>:
Traceback (most recent call last):
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/pywayland/server/listener.py", line 33, in notify_func
    callback(listener, data)
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/libqtile/backend/wayland/keyboard.py", line 90, in _on_destroy
    self.finalize()
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/libqtile/backend/wayland/keyboard.py", line 68, in finalize
    if self.core.keyboards and self.core.seat.keyboard.destroyed:
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/wlroots/wlr_types/seat.py", line 119, in keyboard
    keyboard_ptr = lib.wlr_seat_get_keyboard(self._ptr)
TypeError: initializer for ctype 'struct wlr_seat *' must be a cdata pointer, not NoneType
Exception ignored from cffi callback <function notify_func at 0x7f3d6d2a1f70>:
Traceback (most recent call last):
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/pywayland/server/listener.py", line 33, in notify_func
    callback(listener, data)
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/libqtile/backend/wayland/keyboard.py", line 90, in _on_destroy
    self.finalize()
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/libqtile/backend/wayland/keyboard.py", line 68, in finalize
    if self.core.keyboards and self.core.seat.keyboard.destroyed:
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/wlroots/wlr_types/seat.py", line 119, in keyboard
    keyboard_ptr = lib.wlr_seat_get_keyboard(self._ptr)
TypeError: initializer for ctype 'struct wlr_seat *' must be a cdata pointer, not NoneType
Exception ignored from cffi callback <function notify_func at 0x7f3d6d2a1f70>:
Traceback (most recent call last):
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/pywayland/server/listener.py", line 33, in notify_func
    callback(listener, data)
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/libqtile/backend/wayland/keyboard.py", line 90, in _on_destroy
    self.finalize()
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/libqtile/backend/wayland/keyboard.py", line 68, in finalize
    if self.core.keyboards and self.core.seat.keyboard.destroyed:
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/wlroots/wlr_types/seat.py", line 119, in keyboard
    keyboard_ptr = lib.wlr_seat_get_keyboard(self._ptr)
TypeError: initializer for ctype 'struct wlr_seat *' must be a cdata pointer, not NoneType
Exception ignored from cffi callback <function notify_func at 0x7f3d6d2a1f70>:
Traceback (most recent call last):
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/pywayland/server/listener.py", line 33, in notify_func
    callback(listener, data)
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/libqtile/backend/wayland/keyboard.py", line 90, in _on_destroy
    self.finalize()
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/libqtile/backend/wayland/keyboard.py", line 68, in finalize
    if self.core.keyboards and self.core.seat.keyboard.destroyed:
  File "/nix/store/mpmk0s8pyy1m3py26d7djabnv6dhhyp7-qtile-0.18.1/lib/python3.9/site-packages/wlroots/wlr_types/seat.py", line 119, in keyboard
    keyboard_ptr = lib.wlr_seat_get_keyboard(self._ptr)
TypeError: initializer for ctype 'struct wlr_seat *' must be a cdata pointer, not NoneType
2021-11-27 17:02:35,221 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
```

Just to confirm the version:

```
$ qtile --version
0.18.1
```

**Comment by m-col** [comment]
OK looks like we were mistaken. `lazy.core.change_vt` is how you would access it from git or the next release. On 0.18.1 and before there is no `lazy.core`, and you can access it instead at `lazy.change_vt`. And the log output is showing that the keybinding is in fact working, so changing the lazy path should be enough!

**Comment by mhwombat** [comment]
It works! Thank you so much for the assistance. For the record, here's the relevant snippet from the working configuration:

```
    Key(["mod1", "control"], "F1", lazy.change_vt(1), desc="Go to virtual console 1"),
    Key(["mod1", "control"], "F2", lazy.change_vt(2), desc="Go to virtual console 2"),
    Key(["mod1", "control"], "F3", lazy.change_vt(3), desc="Go to virtual console 3"),
    Key(["mod1", "control"], "F4", lazy.change_vt(4), desc="Go to virtual console 4"),
    Key(["mod1", "control"], "F5", lazy.change_vt(5), desc="Go to virtual console 5"),
    Key(["mod1", "control"], "F6", lazy.change_vt(6), desc="Go to virtual console 6"),
    Key(["mod1", "control"], "F7", lazy.change_vt(7), desc="Go to virtual console 7"),
    Key(["mod1", "control"], "F8", lazy.change_vt(8), desc="Go to virtual console 8"),
    Key(["mod1", "control"], "F9", lazy.change_vt(9), desc="Go to virtual console 9"),

```

**Comment by mhwombat** [comment]
I'll add something about this to the wiki.
