### ISSUE TITLE
Tasklist widget

### ISSUE THREAD

**Issue by krive001** [qtile/qtile#3066]
log
```
2021-12-01 14:05:42,449 ERROR libqtile loop.py:_handle_exception():L64 cairo returned CAIRO_STATUS_INVALID_MATRIX: b'invalid matrix (not invertible)'
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 833, in f
    def cmd_info(self) -> None:
  File "/usr/lib/python3.9/site-packages/libqtile/bar.py", line 549, in _actual_draw
  File "/usr/lib/python3.9/site-packages/libqtile/widget/tasklist.py", line 489, in draw
    self.drawbox(
  File "/usr/lib/python3.9/site-packages/libqtile/widget/tasklist.py", line 384, in drawbox
    framed.draw_fill(offset, self.margin_y, rounded)
  File "/usr/lib/python3.9/site-packages/libqtile/drawer.py", line 192, in draw_fill
    self.draw(x, y, rounded=rounded, fill=True)
  File "/usr/lib/python3.9/site-packages/libqtile/drawer.py", line 157, in draw
    self.drawer.set_source_rgb(self.border_color)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/drawer.py", line 191, in set_source_rgb
  File "/usr/lib/python3.9/site-packages/libqtile/backend/base.py", line 757, in set_source_rgb
  File "/usr/lib/python3.9/site-packages/cairocffi/context.py", line 393, in set_source
    self._check_status()
  File "/usr/lib/python3.9/site-packages/cairocffi/context.py", line 107, in _check_status
    _check_status(cairo.cairo_status(self._pointer))
  File "/usr/lib/python3.9/site-packages/cairocffi/__init__.py", line 88, in _check_status
    raise exception(message, status)
cairocffi.CairoError: cairo returned CAIRO_STATUS_INVALID_MATRIX: b'invalid matrix (not invertible)'

```
config
```
tasks = widget.TaskList(
    highlight_method="block",
    border="#000000",
    margin=0,
    fontsize=0
)
```
```
qtile --version
0.18.2.dev105+gda93518b
```

**Comment by elParaguayo** [comment]
Thanks.

What window were you trying to open when this happened?

**Comment by krive001** [comment]
Brave

**Comment by elParaguayo** [comment]
I actually get a different error:
`SystemError: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)`
Do you have something similar?

This is because Arch recently updated `libffi`. I'm looking at the best way to deal with this as it's causing some issues elsewhere.

**Comment by elParaguayo** [comment]
Fixing the `libffi` issue on my machine makes the widget work correctly. The brave icon displays correctly too for me.

**Comment by krive001** [comment]
Yes. Same. Update, and no problem. Thanks.

**Comment by elParaguayo** [comment]
Great!
