### ISSUE TITLE
Qtile strated crashing too often

### ISSUE THREAD

**Issue by bssplatforms** [qtile/qtile#3107]
I've started to get crashes too. Tried qtile-git and qtile (Arch) packages, on both versions I get random crashes.
On qtile-git crashes were a bit too often. I've created this issue when I've got crash on stable version

[farid@unknown ~]$ qtile -v
0.18.1
[farid@unknown ~]$

2021-12-17 15:26:20,407 ERROR libqtile core.py:get_interesting_pid():L799 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 610, in poll_for_event
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 283, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 797, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-12-17 15:26:20,428 ERROR libqtile core.py:get_interesting_pid():L799 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 610, in poll_for_event
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 283, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 797, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-12-17 15:26:20,449 ERROR libqtile core.py:get_interesting_pid():L799 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 610, in poll_for_event
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 283, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 797, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-12-17 15:26:20,470 ERROR libqtile manager.py:finalize():L269 exception during finalize
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 260, in finalize
    widget.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 213, in finalize
    self.drawer.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 36, in finalize
    self._free_pixmap()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 116, in _free_pixmap
    self.qtile.core.conn.conn.core.FreePixmap(self._pixmap)
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2863, in FreePixmap
    return self.send_request(54, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-12-17 15:26:20,501 ERROR libqtile core.py:get_interesting_pid():L799 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 797, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-12-17 15:26:20,510 ERROR libqtile core.py:get_interesting_pid():L799 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 797, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-12-17 15:26:20,520 ERROR libqtile core.py:get_interesting_pid():L799 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 797, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-12-17 15:26:20,530 ERROR libqtile core.py:get_interesting_pid():L799 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 797, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-12-17 15:26:20,539 ERROR libqtile core.py:get_interesting_pid():L799 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 797, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-12-17 15:26:20,549 ERROR libqtile core.py:get_interesting_pid():L799 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 797, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-12-17 15:26:20,586 ERROR libqtile start.py:start():L91 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 89, in start
    q.loop()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 210, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 234, in async_loop
    self.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 272, in finalize
    self.core.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 172, in finalize
    self.conn.conn.core.DeletePropertyChecked(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2021-12-17 15:26:20,599 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate

**Comment by elParaguayo** [comment]
Thanks for reporting this.

Does the same thing happen if you run the default config?

**Comment by bssplatforms** [comment]
I'm running the same config starting from version when you've moved completely to python3 from python2. Never had issues so far. Besides, my config is almost close to the default one (there is no drastic changes). If it's required, I can post it here

**Comment by elParaguayo** [comment]
I'd like to see it if possible. I don't get regular crashes at all so I'd like to test your config to make sure it's not that.

**Comment by elParaguayo** [comment]
Also, can you describe what happens when you experience a crash i.e. can you trigger it reliably?

**Comment by bssplatforms** [comment]
Attached config. I cannot trigger the crash, it happens randomly and throws me to tty with an error. Mostly I've noticed to have when I do CPU/RAM heavy tasks like playing games (lutris), watching videos (youtube, twitch via chrome). And sometimes I can feel that during a typing even in a terminal/browser there are some input lag occur. It's really hard to explain or trigger so I'm helpless in that unfortunately.

[qtile_config.zip](https://github.com/qtile/qtile/files/7735160/qtile_config.zip)

**Comment by elParaguayo** [comment]
What happens if you disable your autostart script? If that works, try re-enabling lines one by one so we can see which one qtile doesn't like!

**Comment by bssplatforms** [comment]
Ok, I could find one case where I can get 100% guaranteed crash of Qtile. When I launch PortProton (application like Lutris) it crashes. 
Video: https://www.youtube.com/watch?v=Z_M13mautXQ

**Comment by elParaguayo** [comment]
Interesting. I wonder if it's the same issue as here: https://github.com/qtile/qtile/discussions/3074 (although that doesn't cause qtile to crash completely).

**Comment by bssplatforms** [comment]
Not the same issues in my opinion. In my case, Qtile completely crashes to tty. Strange that the same *.exe does work with Lutris but it crashes with PortProton. Uploading debug log during the crash

[qtile.log](https://github.com/qtile/qtile/files/7736237/qtile.log)
.

**Comment by elParaguayo** [comment]
Do you have any other window manager/desktop environment installed? If so, can you see if proton works with that exe file?

**Comment by bssplatforms** [comment]
Closing this issue. Turns out, this is application (PortProton) related problem. I've tried the same thing with BSPWM and it crashed it too. Sorry for inconvenience. My bad, had to test all cases before posting an issue. Closing this one. @elParaguayo  thanks a lot for your support :)

**Comment by elParaguayo** [comment]
No problem.
