### ISSUE TITLE
Qtile crash on Python update (3.10) [Arch Linux]

### ISSUE THREAD

**Issue by imaphatduc** [qtile/qtile#3108]
I met this problem when I updated the whole system (Arch Linux) this morning. After restarting the computer, qtile just crashed. Here is the error message.
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/main.py", line 9, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 559, in _build_master
    ws = cls()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 552, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 608, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2063, in find_on_path
    for dist in factory(fullpath):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2128, in distributions_from_metadata
    yield Distribution.from_location(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2591, in from_location
    )._reload_version()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2989, in _reload_version
    md_version = self._get_version()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2770, in _get_version
    version = _version_from_file(lines)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2554, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2765, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1417, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1407, in get_metadata
    value = self._get(path)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1611, in _get
    with open(path, 'rb') as stream:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.10/site-packages/google_api_core-2.3.2-py3.10.egg-info/PKG-INFO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/qtile", line 33, in <module>
    sys.exit(load_entry_point('qtile==0.18.1', 'console_scripts', 'qtile')())
  File "/usr/bin/qtile", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/main.py", line 11, in <module>
    except (pkg_resources.DistributionNotFound, ImportError):
NameError: name 'pkg_resources' is not defined
```
It seems like the Python update causes this, or I've missed something. Thanks in advance.

**Comment by elParaguayo** [comment]
I'm a bit suspicious of the `PermissionError` but I think the `pkg_resources` error come from an issue with your installation of `python-setuptools`.

What happens if you do `pacman -Qi python-setuptools`?

**Comment by m-col** [comment]
Or a bad installation of google_api_core - was that installed with pacman or with pip, or some other way?

**Comment by imaphatduc** [comment]
@elParaguayo It showed this in the terminal
```
Name            : python-setuptools
Version         : 1:57.4.0-6
Description     : Easily download, build, install, upgrade, and uninstall Python packages
Architecture    : any
URL             : https://pypi.org/project/setuptools/
Licenses        : PSF
Groups          : None
Provides        : python-distribute
Depends On      : python-appdirs  python-more-itertools  python-ordered-set  python-packaging  python-pyparsing
Optional Deps   : None
Required By     : manim  meson  python-distro  python-google-api-core  python-google-auth  python-mako  python-pandas  python-pip  python-pygments  qtile  s-tui
Optional For    : python  python-future
Conflicts With  : None
Replaces        : python-distribute
Installed Size  : 2.96 MiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Sat 11 Dec 2021 07:06:51 AM +07
Install Date    : Sat 18 Dec 2021 01:11:54 PM +07
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by imaphatduc** [comment]
@m-col I think google_api_core was installed as a dependency of another package. Does that mean I have to remove the package?

**Comment by elParaguayo** [comment]
What does `pacman -Qi python-google-api-core` give you?

**Comment by imaphatduc** [comment]
It showed these lines
```
Name            : python-google-api-core
Version         : 2.3.2-1
Description     : Google API client core library
Architecture    : any
URL             : https://github.com/googleapis/googleapis
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : python-setuptools  python-pytz  python-requests  python-googleapis-common-protos  python-google-auth
Optional Deps   : python-grpcio: for grpc support
Required By     : manim
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 885.29 KiB
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : Sat 18 Dec 2021 02:13:58 AM +07
Install Date    : Sat 18 Dec 2021 12:07:15 PM +07
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by m-col** [comment]
Does `/usr/lib/python3.10/site-packages/google_api_core-2.3.2-py3.10.egg-info/PKG-INFO` exist?

**Comment by m-col** [comment]
If you open a python repl and do `import pkg_resources` do you get the same error messages? I just installed python-google-api-core and `import pkg_resources` worked fine.

**Comment by imaphatduc** [comment]
@m-col `/usr/lib/python3.10/site-packages/google_api_core-2.3.2-py3.10.egg-info/PKG-INFO` does exist but have nothing in it. Also, when I run `import pkg_resources`, I get the exact same error.

**Comment by elParaguayo** [comment]
What are the permissions on that file?

**Comment by imaphatduc** [comment]
Fixed! I chown[ed] the necessary files and qtile can start now. Thanks for the support @m-col and @elParaguayo

**Comment by elParaguayo** [comment]
That doesn't really explain _why_ the permissions were wrong in the first place but I don't think we can answer that here as it's not related to Qtile.

**Comment by erlonbie** [comment]
> Fixed! I chown[ed] the necessary files and qtile can start now. Thanks for the support @m-col and @elParaguayo

Hi, I'm having the exact same issue, and I'm new to qtile (newbie). What do you mean with "I chown[ed] the necessary files"? I assume you changed some permissions. Could you tell me which files you chowned?

**Comment by imaphatduc** [comment]
@elParaguayo Yes, I agree with you. I don't clearly understand why the permissions changed after updating the system. 
@erlonbie You can do that by running chown commands like so: `sudo chown [your-target-username] /path/to/the/files/that/threw/you/permission/error/messages`. In my case, I ran these commands: `sudo chown username /usr/lib/python3.10/site-packages/google_api_core-2.3.2-py3.10.egg-info/namespace_packages.txt` and `sudo chown username /usr/lib/python3.10/site-packages/google_api_core-2.3.2-py3.10.egg-info/PKG-INFO`.

**Comment by erlonbie** [comment]
It worked! Thank you!
