### ISSUE TITLE
Qtile crashes after launching with lightdm

### ISSUE THREAD

**Issue by qmack2** [qtile/qtile#3191]
As stated in the title, when I try to start Qtile via login with lightdm, I see a black screen and then I'm immediately sent back to the lightdm login screen. Here is the output in the log file for Qtile:
```
2022-01-13 18:46:29,735 ERROR libqtile start.py:start():L94 Qtile crashed
Traceback (most recent call last):
  File "~/.local/lib/python3.8/site-packages/libqtile/scripts/start.py", line 92, in start
    q.loop()
  File "~/.local/lib/python3.8/site-packages/libqtile/core/manager.py", line 190, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "~/.local/lib/python3.8/site-packages/libqtile/core/manager.py", line 215, in async_loop
    self.load_config(initial=True)
  File "~/.local/lib/python3.8/site-packages/libqtile/core/manager.py", line 132, in load_config
    self._process_screens(reloading=not initial)
  File "~/.local/lib/python3.8/site-packages/libqtile/core/manager.py", line 340, in _process_screens
    scr._configure(self, i, x, y, w, h, grp)
  File "~/.local/lib/python3.8/site-packages/libqtile/config.py", line 304, in _configure
    i._configure(qtile, self)
  File "~/.local/lib/python3.8/site-packages/libqtile/bar.py", line 277, in _configure
    self.drawer.clear(self.background)
  File "~/.local/lib/python3.8/site-packages/libqtile/backend/x11/drawer.py", line 179, in clear
    self._check_xcb()
  File "~/.local/lib/python3.8/site-packages/libqtile/backend/x11/drawer.py", line 124, in _check_xcb
    self._xcb_surface = self._create_xcb_surface()
  File "~/.local/lib/python3.8/site-packages/libqtile/backend/x11/drawer.py", line 90, in _create_xcb_surface
    surface = cairocffi.XCBSurface(
  File "~/.local/lib/python3.8/site-packages/cairocffi/xcb.py", line 37, in __init__
    p = cairo.cairo_xcb_surface_create(
AttributeError: cffi library 'libcairo.so.2' has no function, constant or global variable named 'cairo_xcb_surface_create'
```
(note: I've replaced the home directory with the alias '~' where applicable)

I'm pretty sure everything is configured correctly (including my config file). When I run `pip3 check qtile` in a terminal, it says 'no broken requirements found'

When I run `qtile check` in a terminal, I get the output:
```
checking qtile config file ~/.config/qtile/config.py
stubtest not found, can't type check config file
install it and try again
Success: no issues found in 1 source file
config file type checking succeeded
config file can be loaded by qtile
```

What is going wrong then?

**Comment by jx11r** [comment]
Try install the package python-setuptools, sometimes LightDM gives problems.

**Comment by qmack2** [comment]
I got it up and running, thanks for your help everyone. Here are the commands I used:

```
sudo apt install python-setuptools
sudo pip uninstall cairocffi
sudo pip uninstall xcffib
sudo apt purge python3-cairocffi
sudo apt purge python3-xcffib
sudo apt autoremove
sudo apt autoclean
pip install 'xcffib >= 0.10.1' && pip install --no-cache-dir 'cairocffi >= 0.9.0'
```
