### ISSUE TITLE
Qtile does not start - login loop

### ISSUE THREAD

**Issue by vicrdguez** [qtile/qtile#3217]
Hi!

I've updated my system, after that I can't login into qtile, I enter the password in sddm and I get back to login after a short black screen. I've noticed as well that qtile got updated, I don't remember my former version but I think it was a v0.18 one.

Looking at the logs appears to return a chain of exception that I'm not able to understand.

Other WMs work fine, tested with bspwm and Openbox

### My system
- Arch linux (5.16.1-arch1-1)
- Qtile 0.19.0
- SDDM login

### Qtile logs

```
2022-01-18 21:40:29,857 WARNING libqtile theme.py:load():L10 THEME PATH: /home/vrodriguez/.config/qtile/colors.json
2022-01-18 21:40:32,674 ERROR libqtile manager.py:_finalize_configurables():L294 exception during finalize
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 658, in wait_for_reply
    self._process_error(error_p[0])
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 645, in _process_error
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 218, in async_loop
    self.load_config(initial=True)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 167, in load_config
    self.core.distribute_windows(initial)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 237, in distribute_windows
    _, _, children = self._root.query_tree()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 422, in query_tree
    q = self.conn.conn.core.QueryTree(self.wid).reply()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 332, in reply
    data = self.conn.wait_for_reply(self.sequence)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 284, in _finalize_configurables
    widget.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/systray.py", line 260, in finalize
    self.conn.conn.core.SetSelectionOwner(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2728, in SetSelectionOwner
    return self.send_request(22, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-18 21:40:32,731 ERROR libqtile core.py:_xpoll():L328 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 290, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-18 21:40:32,731 ERROR libqtile base.py:on_done():L632 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 658, in wait_for_reply
    self._process_error(error_p[0])
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 645, in _process_error
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 218, in async_loop
    self.load_config(initial=True)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 167, in load_config
    self.core.distribute_windows(initial)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 237, in distribute_windows
    _, _, children = self._root.query_tree()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 422, in query_tree
    q = self.conn.conn.core.QueryTree(self.wid).reply()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 332, in reply
    data = self.conn.wait_for_reply(self.sequence)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 221, in async_loop
    self.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 299, in finalize
    self.core.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 171, in finalize
    self.conn.conn.core.DeletePropertyChecked(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 624, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 535, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 80, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 135, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2022-01-18 21:40:32,734 ERROR libqtile start.py:start():L91 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 658, in wait_for_reply
    self._process_error(error_p[0])
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 645, in _process_error
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 218, in async_loop
    self.load_config(initial=True)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 167, in load_config
    self.core.distribute_windows(initial)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 237, in distribute_windows
    _, _, children = self._root.query_tree()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 422, in query_tree
    q = self.conn.conn.core.QueryTree(self.wid).reply()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 332, in reply
    data = self.conn.wait_for_reply(self.sequence)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 89, in start
    q.loop()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 195, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 221, in async_loop
    self.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 299, in finalize
    self.core.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 171, in finalize
    self.conn.conn.core.DeletePropertyChecked(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-18 21:40:32,734 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
```

**Comment by m-col** [comment]
Hello. That looks pretty nasty indeed. The `_finalize_configurables` on the second line of the logs happens when Qtile is shutting down or when the config is being reloaded. Was there any interesting log output even further up?

**Comment by vicrdguez** [comment]
Absolutely nasty! That's the entire log I can get from qtile logs sadly.
Executing `journalctl -b -p err` I can see how qtile fails somehow but I have not much more

```
ene 18 21:40:32 vic-ac systemd-coredump[6849]: [🡕] Process 6702 (qtile) of user 1000 dumped core.

                                               Module linux-vdso.so.1 with build-id f4c0c67a495415ccf56ef21d6eaadfebc34186ec
                                               Module libgpg-error.so.0 with build-id 3801187d42c4955bd93c605451430cdf1b164e63
                                               Module libgcc_s.so.1 with build-id 7f8508bb914546ada778809b64b99d234337d835
                                               Module libgcrypt.so.20 with build-id db45f5d5e0f7af1e77324fea1885f974619ad268
                                               Module libcap.so.2 with build-id f56c6cd6ad4d35053340d7ff2f8f954498796739
                                               Module liblz4.so.1 with build-id e63600ab23b2f6997f42fac2fa56e1f02ce159a1
                                               Module libogg.so.0 with build-id ca0cae30a809f10db1f16e54a23b4e5ff7b2c54c
                                               Module libvorbis.so.0 with build-id ad0a6c1af8f219b4e314090b6e8847223d424cbe
                                               Module libopus.so.0 with build-id 649d3ddab8764d7caf73648004a35cb13e23a5e1
                                               Module libFLAC.so.8 with build-id e568dc3d434723c72d6d302eb0b2559f27e91faa
                                               Module libvorbisenc.so.2 with build-id 28ed815b8b1d322e6bf2bfdce4b0af2789b74335
                                               Module libasyncns.so.0 with build-id 6acff139d56b5139ce5eb50a66c62b215e1d332d
                                               Module libsystemd.so.0 with build-id 69dfd360ef432adc8911dd446411765f1922fb48
                                               Module libsndfile.so.1 with build-id 72d5531e74ed3e9afe49e95e449c40cb8984a258
                                               Module libdbus-1.so.3 with build-id 74f2ab9c60512f3a93c932c3f627564d42e0b11e
                                               Module libpulsecommon-15.0.so with build-id a2e110b7a0b3bb46e42515afd55a61d78185835b
                                               Module libpulse.so.0 with build-id 10bd0ce0cfbb9405cee189faa1830cf34cab61a8
                                               Module _pulse_audio.abi3.so with build-id 115c9df0fe363ce2af905387c9184c7efc99ae8d
                                               Module resource.cpython-310-x86_64-linux-gnu.so with build-id 75aba5c2ad3cc4718f21161b1e714a2339f2ed6a
                                               Module _psutil_posix.cpython-310-x86_64-linux-gnu.so with build-id 4e1c636903162a9f46f021a46b61267a9cb41425
                                               Module _psutil_linux.cpython-310-x86_64-linux-gnu.so with build-id 93c2a13df2b23d1a036ed3a8f51bc957ea669c8a
                                               Module libxcb-util.so.1 with build-id 4188ebc629b472b560849c5792a69c1803c3d1a4
                                               Module libxcb-image.so.0 with build-id ee7f8577926fe7c1d6972036c2f8e6f727e43b1b
                                               Module libxcb-render-util.so.0 with build-id c64fb28ea20a320a9754273d9ea3af85f6f74b17
                                               Module libxcb-cursor.so.0 with build-id 69d87b342ff51e520334e5fda3dd33bcf09c1483
                                               Module libncursesw.so.6 with build-id 859adb8b03a5655151b4da104bc4b326a0d4bc8c
                                               Module _curses.cpython-310-x86_64-linux-gnu.so with build-id a8465b756e74c44b9222110796933a08b4dfc28a
                                               Module termios.cpython-310-x86_64-linux-gnu.so with build-id d0820c42a77103df9f22ae93b4c895dcec020a7c
                                               Module libzstd.so.1 with build-id 6214183688018e3fba6d66db10c2c8d0b45e0578
                                               Module _json.cpython-310-x86_64-linux-gnu.so with build-id fd30aaa80643f61a77fc8cf3e2198a0d8c33332f
                                               Module librt.so.1 with build-id 75484da2d6f1515189eefa076e0a40328834cd16
                                               Module libblkid.so.1 with build-id 057b6bc8eebd42d1f5cafe4f4ac72646aae1f2c5
                                               Module libresolv.so.2 with build-id c915c72668282861a813f7ea3c0780f37b681dc0
                                               Module libmount.so.1 with build-id 39e178b712b6635a8681182f7a9fbb64e6074aee
                                               Module libgmodule-2.0.so.0 with build-id 5da4523e8d6b5c244a0193e27093d1e61f6ac9e4
                                               Module libgio-2.0.so.0 with build-id bce5a3881708e1e885fa1c9c32e2769a6447c411
                                               Module libgobject-2.0.so.0 with build-id e67b3a29cecdd98c3d8bd6eb7524a812331b20a2
                                               Module libpcre.so.1 with build-id 845483dd0acba86de9f0313102bebbaf3ce52767
                                               Module libbrotlicommon.so.1 with build-id a4ba3f4b4571c8272343b621da812a6e24a202a7
                                               Module libglib-2.0.so.0 with build-id 220436a4e27f39372710df014d2517c0387eefa4
                                               Module libgraphite2.so.3 with build-id 47761dc11e553f519cde97ed9ee985be12ccdae2
                                               Module libbrotlidec.so.1 with build-id 45defc036e918e0140a72f1fbce6e7692d38241d
                                               Module libharfbuzz.so.0 with build-id 1d9dee49dd99162c3f83eb3259c3c88c6b4cd7fe
                                               Module libexpat.so.1 with build-id 64e977cfebfe7539f428dec3b388f5d0498b3108
                                               Module libpixman-1.so.0 with build-id 341f793dcada3a48a306a793d265a517e3f2e7d6
                                               Module libxcb-shm.so.0 with build-id fb797f299a446f559a95afcc168227482cc800d1
                                               Module libxcb-render.so.0 with build-id a37bdb37744b508be9dd29fd9ccb9bb0170d43e5
                                               Module libXrender.so.1 with build-id 97e0b9ab6ba96ebc86527cc2b3c3078aad8616b3
                                               Module libXext.so.6 with build-id d70f24beb4fad748d6becffdcc13e51be0a2ebfa
                                               Module libX11.so.6 with build-id 5ba5798d193c0065014b8c6252a0678671c8d478
                                               Module libfreetype.so.6 with build-id 26c5f833068ff72660d1975cbc2074c3eb47fad8
                                               Module libfontconfig.so.1 with build-id 1103a641395c7d3b42e49b793d3a9ea927c77bf6
                                               Module libpng16.so.16 with build-id 2dc0bce07f199bf983c07a05fb95a6f4af83a9b3
                                               Module libcairo.so.2 with build-id 06820af9cf79c2deb207d9533a61caf04e67a8ad
                                               Module libXdmcp.so.6 with build-id 8ca0792d23c8b8b4c0864297512349292bea5955
                                               Module libXau.so.6 with build-id 1c67764663e07bec24d8951e5fd93f4d165979ff
                                               Module libxcb.so.1 with build-id 0d1ef11740a5daad2ee331e812a51aa6574af222
                                               Module _cffi_backend.cpython-310-x86_64-linux-gnu.so with build-id 14f947568859abe55c43794fb77b35e65f5d57f2
                                               Module libffi.so.8 with build-id f90d8b734f6de9b25faedb8cbfab7054dafc0a42
                                               Module _ctypes.cpython-310-x86_64-linux-gnu.so with build-id b9dd3414243c0051a1a37f1ce2716e1337ca638b
                                               Module _asyncio.cpython-310-x86_64-linux-gnu.so with build-id e475282197da2cea6f678a62a0f43c8e6e55a7cd
                                               Module _contextvars.cpython-310-x86_64-linux-gnu.so with build-id d02cbc4cf1ddfe441286a643f5c3c12cfb0f5a62
                                               Module _opcode.cpython-310-x86_64-linux-gnu.so with build-id 8060800fd6b98bdb7290e3e37ac40a77d4094290
                                               Module libcrypto.so.1.1 with build-id 4c926b672d97886b123e03a008387aecf0786de4
                                               Module libssl.so.1.1 with build-id 1024424ab33a3767da03f4fdb1fc1b02479f160f
                                               Module _ssl.cpython-310-x86_64-linux-gnu.so with build-id a2200ec2b1bae144168663990a7926d54e93f125
                                               Module _posixsubprocess.cpython-310-x86_64-linux-gnu.so with build-id b7f95287990119b300ebc142785ed84111421ce5
                                               Module fcntl.cpython-310-x86_64-linux-gnu.so with build-id f441ff1a71c63f12a5bd16b25efe14f5cac5ff8a
                                               Module _queue.cpython-310-x86_64-linux-gnu.so with build-id cb6622d4d989700f67dfadd3495ddb3b7bead085
                                               Module _heapq.cpython-310-x86_64-linux-gnu.so with build-id 0839af7db1f7d81c6f0f916c78215fdfc217d76b
                                               Module _pickle.cpython-310-x86_64-linux-gnu.so with build-id b4cf941b6521d406db2dab620cf24c78e4cb6d6d
                                               Module _datetime.cpython-310-x86_64-linux-gnu.so with build-id 200d5e82b9ad9daa88459dce14fa1bdd8c4780cc
                                               Module array.cpython-310-x86_64-linux-gnu.so with build-id 78a2c826a7854d4d45450af0d5588558b0ab1528
                                               Module select.cpython-310-x86_64-linux-gnu.so with build-id 28ee4682af4e7f3f12a5fcf2a53a434ac1c1ec5a
                                               Module _socket.cpython-310-x86_64-linux-gnu.so with build-id 01cb2b77484be793e5227e7320763ffdfbb3c720
                                               Module _sha512.cpython-310-x86_64-linux-gnu.so with build-id 009c6df1f3007e64daca05eb4dbd80c1ac2eb283
                                               Module _random.cpython-310-x86_64-linux-gnu.so with build-id dfaafefe4258b660906e4e65050e8ed5c2994e98
                                               Module _bisect.cpython-310-x86_64-linux-gnu.so with build-id da73094c835a1b29c3b2ba9ec8383fb5baf433ae
                                               Module math.cpython-310-x86_64-linux-gnu.so with build-id 4ec6812a7d388c6ce2ec0792b84719d8c74be257
                                               Module _struct.cpython-310-x86_64-linux-gnu.so with build-id da786c07067aecb63374411c00ad51a40d63a2c5
                                               Module liblzma.so.5 with build-id 8b615460aa230708c5183f16bede67aa0437d95e
                                               Module _lzma.cpython-310-x86_64-linux-gnu.so with build-id 95e187a714088aec9dc45f19bcb24cd640c63ec9
                                               Module libbz2.so.1.0 with build-id 919597c477c9b2cb9cdbb7745ed6494ac0e6da60
                                               Module _bz2.cpython-310-x86_64-linux-gnu.so with build-id 2db8fac78e082ddd710716ce8c64fa9e10bcd7d8
                                               Module zlib.cpython-310-x86_64-linux-gnu.so with build-id c57a4ab44931603f94e3b27b6691f3f83abc940e
                                               Module libz.so.1 with build-id 0c1459c56513efd5d53eb3868290e9afee6a6a26
                                               Module binascii.cpython-310-x86_64-linux-gnu.so with build-id b1b12052d3ffd9cd731c95228822e344d7a90c4b
                                               Module _csv.cpython-310-x86_64-linux-gnu.so with build-id 777aa9e61a8520bdaed9c78cfabce88911c5ea80
                                               Module ld-linux-x86-64.so.2 with build-id 040cc3dd10461562f177df39e3be2f3704258c3c
                                               Module libm.so.6 with build-id 2b8fd1f869ecab4e0b55e92f2f151897f6818acf
                                               Module libutil.so.1 with build-id af6d8200064ee6e6a01252884d166b44f0a6121b
                                               Module libdl.so.2 with build-id 5abc547e7b0949f89f3c0e21ab0c8331a7440a8a
                                               Module libpthread.so.0 with build-id 07c8f95b4f3251d08550217ad8a1f31066229996
                                               Module libc.so.6 with build-id 4b406737057708c0e4c642345a703c47a61c73dc
                                               Module libpython3.10.so.1.0 with build-id 7e95a25426f0a060157776206e516d838f1bfc25
                                               Module python3.10 with build-id 0326c5cf3b41c4230b3944b7d4a33c590eea62f3
                                               Stack trace of thread 6702:
                                               #0  0x00007efcb2e66930 n/a (n/a + 0x0)
                                               #1  0x00007efcb409bed8 n/a (n/a + 0x0)
                                               ELF object binary architecture: AMD x86-64
```

**Comment by m-col** [comment]
Please could you post your config / a link to it?

**Comment by vicrdguez** [comment]
Sure, I've uploaded my config here: https://github.com/vicrdguez/qtile_conf
It was working perfectly until now, looks like I can't find the main reason why now it doesn't

**Comment by vicrdguez** [comment]
Tried different things, now the error is different when starting, but the screen gets stucked into SDDM and gets blocked (you can't do anything), so no longer a login loop, but still bad haha

```
2022-01-26 11:56:18,344 ERROR libqtile start.py:start():L94 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 92, in start
    q.loop()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 190, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 215, in async_loop
    self.load_config(initial=True)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 132, in load_config
    self._process_screens(reloading=not initial)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 340, in _process_screens
    scr._configure(self, i, x, y, w, h, grp, reconfigure_gaps=reconfigure_gaps)
  File "/usr/lib/python3.10/site-packages/libqtile/config.py", line 307, in _configure
    i._configure(qtile, self)
  File "/usr/lib/python3.10/site-packages/libqtile/bar.py", line 288, in _configure
    self.drawer.clear(self.background)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 179, in clear
    self._check_xcb()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 124, in _check_xcb
    self._xcb_surface = self._create_xcb_surface()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 90, in _create_xcb_surface
    surface = cairocffi.XCBSurface(
  File "/home/vrodriguez/.local/lib/python3.10/site-packages/cairocffi/xcb.py", line 37, in __init__
    p = cairo.cairo_xcb_surface_create(
AttributeError: cffi library 'libcairo.so.2' has no function, constant or global variable named 'cairo_xcb_surface_create'
```

**Comment by elParaguayo** [comment]
That looks like cairocffi was installed without xcffib support.
Have a look at: http://docs.qtile.org/en/stable/manual/hacking.html?highlight=xcffib#cairo-errors

**Comment by vicrdguez** [comment]
@elParaguayo thanks for the help! that solved that current issue. However I'm back to the original issue again, with a login loop:
`xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.`

**Comment by elParaguayo** [comment]
Does the same thing happen if you use the default config?

**Comment by vicrdguez** [comment]
No, I've tested with the default config and qtile starts. However I can't find what was different between before the update and now. Maybe a lib, or a command is not existing anymore? 

which surprises me is that qtile is not falling back to default config if there is an error. I remember it did

**Comment by elParaguayo** [comment]
OK - that's interesting. Qtile will only fallback to the default config if there's an error in your config file (i.e. it's an invalid python file). However, I suspect your config is valid but there's some combination of objects in it which is causing the connection to break.
