### ISSUE TITLE
Doesn't respond to keymaps for a minute after waking from sleep

### ISSUE THREAD

**Issue by AmitGolden** [qtile/qtile#3233]
Qtile doesn't respond to keymaps for around a minute after waking from sleep.
Tried downgrading, doesn't seem to work.[
[My config](https://github.com/AmitGolden/dotfiles/blob/main/.config/qtile/config.py)

**Comment by elParaguayo** [comment]
Very odd. I don't see this behaviour at all. 

What version are you running? Is there anything in your logs?

**Comment by AmitGolden** [comment]
Also, the bar seems to freeze and not update while qtile isn't responding.

Logs around the time my PC got into sleep:
```
2022-01-22 14:56:53,021 ERROR libqtile loop.py:_handle_exception():L64 xcb connection errors because of socket, pipe and other stream errors.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 681, in request_check
    self._process_error(err)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 645, in _process_error
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 833, in f
    func(*args)
  File "/usr/lib/python3.10/site-packages/libqtile/bar.py", line 573, in _actual_draw
    i.draw()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/systray.py", line 230, in draw
    icon.place(
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 896, in place
    self.paint_borders(bordercolor, borderwidth)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 905, in paint_borders
    self.window.paint_borders(self.depth, color, width, self.width, self.height)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 435, in paint_borders
    self.set_property('_NET_FRAME_EXTENTS', [borderwidth] * 4)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 356, in set_property
    ).check()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 339, in check
    self.conn.request_check(self.sequence)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-22 14:56:53,028 ERROR libqtile core.py:_xpoll():L328 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 290, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-22 14:56:53,029 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 290, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-22 14:56:53,032 ERROR libqtile manager.py:_finalize_configurables():L294 exception during finalize
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 284, in _finalize_configurables
    widget.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 232, in finalize
    self.drawer.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 36, in finalize
    self._free_pixmap()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 116, in _free_pixmap
    self.qtile.core.conn.conn.core.FreePixmap(self._pixmap)
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2863, in FreePixmap
    return self.send_request(54, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-22 14:56:53,034 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-22 14:56:53,034 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-22 14:56:53,038 ERROR libqtile start.py:start():L91 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 89, in start
    q.loop()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 195, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 221, in async_loop
    self.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 299, in finalize
    self.core.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 171, in finalize
    self.conn.conn.core.DeletePropertyChecked(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-22 14:56:53,040 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
2022-01-22 14:58:35,962 ERROR libqtile manager.py:_finalize_configurables():L294 exception during finalize
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 284, in _finalize_configurables
    for sx, sy, sw, sh in self.core.get_screen_info():
  File "/usr/lib/python3.10/site-packages/libqtile/widget/systray.py", line 270, in finalize
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-22 14:58:35,964 ERROR libqtile core.py:_xpoll():L328 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 290, in _xpoll
    event_type = event.__class__.__name__
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-22 14:58:35,965 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 290, in _xpoll
    event_type = event.__class__.__name__
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    except OSError:
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-22 14:58:35,994 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    except OSError:
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-22 14:58:35,995 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    except OSError:
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 284, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 377, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-22 14:58:36,033 ERROR libqtile base.py:on_done():L620 poll() raised exceptions, not rescheduling
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 221, in async_loop
    self.core.setup_listener(self)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 299, in finalize
    self.current_screen = scr
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 171, in finalize
    def finalize(self) -> None:
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 617, in on_done
    instance, on bars across multiple screens.
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/generic_poll_text.py", line 34, in poll
    return "You need a poll function"
  File "/home/amitgold/.config/qtile/config.py", line 467, in get_keyboard_layout
    subprocess.check_output(["xkblayout-state", "print", '"%s"'])
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['xkblayout-state', 'print', '"%s"']' died with <Signals.SIGABRT: 6>.
2022-01-22 14:58:36,036 WARNING libqtile base.py:on_done():L634 poll() returned None, not rescheduling
2022-01-22 14:58:36,037 ERROR libqtile start.py:start():L91 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 89, in start
    q.loop()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 195, in loop
    hook.fire("startup_complete")
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 221, in async_loop
    self.core.setup_listener(self)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 299, in finalize
    self.current_screen = scr
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 171, in finalize
    def finalize(self) -> None:
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-01-22 14:58:36,038 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
```

**Comment by elParaguayo** [comment]
Those errors are coming before qtile stops (and are typically harmless because qtile is exiting) ​but qtile shouldn't be exiting when your laptop sleeps.

Are you using some sort of login manager? Can you tell us a bit about your setup?

**Comment by AmitGolden** [comment]
Yes,
I'm using lightdm.
Also, I have some scripts running in the background, one manage new screen connections, one to manage backlight dimming on inactivity, and one Wich is a custom caffeine script.
Some are running inside an infinite loop and checking for their status.

Furthermore, just to make sure things are clear, other applications behave as always when Qtile freezes. I can use my mouse and interact with them.
Just everything that has to do with Qtile freezes

**Comment by elParaguayo** [comment]
Thanks.

Can you try disabling the scripts and see if this still happens.

If it carries on, try using the default config next.

**Comment by AmitGolden** [comment]
I tried disabling the scripts, but it continued to happen.
I'll try next using the default config.

**Comment by AmitGolden** [comment]
Ok, using the default config it works

**Comment by AmitGolden** [comment]
Tried disabling things, and found out my Volume widget is causing this behaviour:
```python
widget.Volume(
    foreground=colors["green"],
    mouse_callbacks={"Button1": lambda: qtile.cmd_spawn("pavucontrol")},
),
```

What can I do to fix it?

**Comment by m-col** [comment]
If you disable just one of those two arguments does it fix it?

**Comment by elParaguayo** [comment]
I wonder if it's getting stuck checking the volume level when it wakes up.

**Comment by m-col** [comment]
Perhaps this would fix it by running it async?:
```py
    mouse_callbacks={"Button1": lazy.spawn("pavucontrol")},
```

**Comment by m-col** [comment]
Is that even supported?

**Comment by elParaguayo** [comment]
I don't think it's anything to do with the callback. I think it's the background polling of volume levels.

**Comment by m-col** [comment]
Ah I see. @AmitGolden could you try the `PulseVolume` widget instead? Pipewire supports using pulseaudio clients, so maybe that'll work fine.

**Comment by AmitGolden** [comment]
Using PulseVolume fixes this.
The problem is that it takes a few seconds to update, and it always displays 1% lower than the actual volume, so it works worse than the regular Volume widget.

**Comment by m-col** [comment]
The 1% offset error should be fixed on master (by https://github.com/qtile/qtile/pull/3208), so that'll be fixed in the next release.

**Comment by elParaguayo** [comment]
I think someone posted on Reddit about that different volume level. It's not a Qtile bug.

**Comment by AmitGolden** [comment]
And what can I do about the slow update time?

**Comment by m-col** [comment]
> Using PulseVolume fixes this.

Sorry, think I misunderstood - does using PulseVolme fix the slow update time or something else?

I suspect the slow update time with `Volume`/amixer is because of its interaction with pipewire. If you change the volume manually on the command line using amixer, does it work right away?

**Comment by AmitGolden** [comment]
Using PulseVolume fixes the freezing problem.
However, anytime I change the volume, it takes a few seconds to update the percentage on the bar UI, but no freeze is caused

**Comment by m-col** [comment]
If you watch pavucontrol or some other program that displays the current volume, then increase and decrease the volume using the widget, does the volume in that program update right away, or only when the bar updates? This will tell us whether the slowness is coming from using the interface used by the widget, or just in the widget updating its contents.

**Comment by AmitGolden** [comment]
In pavucontrol it updates immediately

**Comment by m-col** [comment]
Interesting, thanks. Will do some testing

**Comment by m-col** [comment]
That delay is pretty bad. I can't seem to reduce it by adding `self.update` at the end of the increase/decrease commands. Not really sure how to approach improving that...

**Comment by elParaguayo** [comment]
Is the delay caused by the widget or the command that's being run?

**Comment by m-col** [comment]
It's not a command per se, as it's all within a cffi interface for that 
widget, so it will be some part of the widget... possibly within the C 
code. I assume it uses a standard interface though, if all it is doing 
is requesting volume changes, so I'm not sure if there will be any way 
to speed it up. Unless maybe we make that request, then make another to 
fetch the volume, if for some reason the initial request that wants to 
change settings takes longer to return than one that simply gets data.
