### ISSUE TITLE
Cannot login to qtile from Gnome

### ISSUE THREAD

**Issue by PyB1l** [qtile/qtile#3257]
I followed the instructions for  [gnome](http://docs.qtile.org/en/stable/manual/config/gnome.html), I see the option Qtile session in login screen but when I login I am redirected to login again,

`~/.local/share/qtile/qtile.log` complains for existing window manager GNOME Shell

**Comment by PyB1l** [comment]
I have successfully build qtile from source, I have copied the default `config.py` to `~/.config/qtile/config.py` and I have added the following snippet to the very beginning of my config:
```
import subprocess
import os
from libqtile import hook

@hook.subscribe.startup
def dbus_register():
    id = os.environ.get('DESKTOP_AUTOSTART_ID')
    if not id:
        return
    subprocess.Popen(['dbus-send',
                      '--session',
                      '--print-reply',
                      '--dest=org.gnome.SessionManager',
                      '/org/gnome/SessionManager',
                      'org.gnome.SessionManager.RegisterClient',
                      'string:qtile',
                      'string:' + id])
```
and lastly  I have created the required entries `usr/share/xsessions/qtile_gnome.desktop`, `/usr/share/gnome-session/sessions/qtile.session`, ` /usr/share/applications/qtile.desktop` 

On reboot when I login I get - almost -  immediately ( I can see the desktop for a moment) redirected to login again.
If i login to gnome or i3 to inspect the  `qtile.log` I see error for existing window manager GNOME Shell.

My laptop runs Ubuntu 20.04

**Comment by nazar-pc** [comment]
What does your `/usr/share/gnome-session/sessions/qtile.session` look like? Does it have `gnome-shell` in required components by any chance?

**Comment by ilyachch** [comment]
same for me

```
~ ➜  cat /usr/share/xsessions/qtile_gnome.desktop
[Desktop Entry]
Name=Qtile GNOME
Comment=Tiling window manager
#TryExec=/usr/bin/gnome-session
Exec=gnome-session --session=qtile
Type=XSession
```
```
~ ➜  cat /usr/share/gnome-session/sessions/qtile.session
[GNOME Session]
Name=Qtile session
RequiredComponents=qtile;org.gnome.SettingsDaemon.A11ySettings;org.gnome.SettingsDaemon.Color;org.gnome.SettingsDaemon.Datetime;org.gnome.SettingsDaemon.Housekeeping;org.gnome.SettingsDaemon.Keyboard;org.gnome.SettingsDaemon.MediaKeys;org.gnome.SettingsDaemon.Power;org.gnome.SettingsDaemon.PrintNotifications;org.gnome.SettingsDaemon.Rfkill;org.gnome.SettingsDaemon.ScreensaverProxy;org.gnome.SettingsDaemon.Sharing;org.gnome.SettingsDaemon.Smartcard;org.gnome.SettingsDaemon.Sound;org.gnome.SettingsDaemon.Wacom;org.gnome.SettingsDaemon.XSettings;
```

```
~ ➜  cat /usr/share/applications/qtile.desktop
[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=Qtile
Exec=qtile start
NoDisplay=true
X-GNOME-WMName=Qtile
X-GNOME-Autostart-Phase=WindowManager
X-GNOME-Provides=windowmanager
X-GNOME-Autostart-Notify=false
```

```
~ ➜  tail -n 2 .local/share/qtile/qtile.log
2022-03-09 00:30:10,136 ERROR libqtile core.py:__init__():L99 not starting; existing window manager GNOME Shell
2022-03-09 00:30:10,482 ERROR libqtile core.py:__init__():L99 not starting; existing window manager GNOME Shell

```

**Comment by ilyachch** [comment]
also, I've added logging to snippet from manual:
```
logger.info("Config loaded")

@hook.subscribe.startup
def dbus_register():
    logger.info("Registering dbus")
    id = os.environ.get('DESKTOP_AUTOSTART_ID')
    logger.debug("DBUS_DESKTOP_AUTOSTART_ID: %s", id)
```

But none of this messages appeared in logs. So, I hope there should be a way to call drun register command earlier

**Comment by elParaguayo** [comment]
The default warning level is `warning` so `info` messages wouldn't appear.

**Comment by ilyachch** [comment]
replaced with warning
```
logger.warning("Config loaded")


@hook.subscribe.startup
def dbus_register():
    logger.warning("Registering dbus")
    id = os.environ.get('DESKTOP_AUTOSTART_ID')
    logger.warning("DBUS_DESKTOP_AUTOSTART_ID: %s", id)
 
```
No messages in logs

**Comment by elParaguayo** [comment]
How are you importing logger?

It should be `from libqtile.log_utils import logger`. 

Can you also run `qtile cmd-obj -o cmd -f loglevelname`.

**Comment by ilyachch** [comment]
I've imported it exactly this way. This remark about logging is not a problem by itself. But it can point, that config may not be read on startup.

I've checked syslog:
```
Mar  9 10:26:54 ThinkPad systemd[1701]: Reached target Tasks to be run before GNOME Session starts.
Mar  9 10:26:54 ThinkPad systemd[1701]: Starting GNOME Session Manager (session: qtile)...
Mar  9 10:26:54 ThinkPad gnome-session[37577]: gnome-session-binary[37577]: WARNING: Could not parse desktop file gsettings-data-convert.desktop or it references a not found TryExec binary
Mar  9 10:26:54 ThinkPad gnome-session-binary[37577]: WARNING: Could not parse desktop file gsettings-data-convert.desktop or it references a not found TryExec binary
Mar  9 10:26:55 ThinkPad gnome-keyring-ssh.desktop[37587]: SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
Mar  9 10:26:55 ThinkPad gnome-keyring-pkcs11.desktop[37588]: SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
Mar  9 10:26:55 ThinkPad gnome-keyring-secrets.desktop[37589]: SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
Mar  9 10:26:55 ThinkPad systemd[1701]: Started GNOME Session Manager (session: qtile).
Mar  9 10:26:55 ThinkPad systemd[1701]: Reached target GNOME Session Manager is ready.
Mar  9 10:26:55 ThinkPad systemd[1701]: Starting GNOME Shell on X11...
...
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME Shell on X11.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Shell on X11.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Session is initialized.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME session X11 services.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME X11 Session.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Session (session: qtile).
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting Signal initialization done to GNOME Session Manager...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME Accessibility settings...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME Color management...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME Date & Time handling...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME Maintenance of expirable data...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME Keyboard handling...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME Media keys handling...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME Power management handling...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME Printer notifications...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME RFKill handling...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME Freedesktop screensaver handling...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME Sharing handling...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME Smartcard handling...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME Sound sample caching handling...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME USB protection handling...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME Wacom handling...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME WWan management...
Mar  9 10:26:56 ThinkPad systemd[1701]: Starting GNOME XSettings...
Mar  9 10:26:56 ThinkPad systemd[1701]: gnome-session-signal-init.service: Succeeded.
Mar  9 10:26:56 ThinkPad systemd[1701]: Finished Signal initialization done to GNOME Session Manager.
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME Accessibility settings.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Accessibility settings.
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME Maintenance of expirable data.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Maintenance of expirable data.
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME Freedesktop screensaver handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Freedesktop screensaver handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME Sharing handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Sharing handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME Smartcard handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Smartcard handling.
Mar  9 10:26:56 ThinkPad kernel: [ 5187.043856] rfkill: input handler disabled
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME RFKill handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME RFKill handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME USB protection handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME USB protection handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME Date & Time handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Date & Time handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME Keyboard handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Keyboard handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME Sound sample caching handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Sound sample caching handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME WWan management.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME WWan management.
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME Power management handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Power management handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME Color management.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Color management.
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME Media keys handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Media keys handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME Wacom handling.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Wacom handling.
Mar  9 10:26:56 ThinkPad NetworkManager[776]: <info>  [1646814416.4984] agent-manager: agent[61de4dba1727499a,:1.466/org.gnome.Shell.NetworkAgent/1000]: agent registered
Mar  9 10:26:56 ThinkPad gnome-shell[37591]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Mar  9 10:26:56 ThinkPad gnome-shell[37013]: Failed to set CRTC gamma: drmModeCrtcSetGamma on CRTC 67 failed: Permission denied
Mar  9 10:26:56 ThinkPad systemd[36941]: tracker-extract.service: Succeeded.
Mar  9 10:26:56 ThinkPad gsd-media-keys[37882]: Failed to grab accelerator for keybinding settings:playback-random
Mar  9 10:26:56 ThinkPad gsd-media-keys[37882]: Failed to grab accelerator for keybinding settings:playback-repeat
Mar  9 10:26:56 ThinkPad gsd-media-keys[37882]: Failed to grab accelerator for keybinding settings:hibernate
Mar  9 10:26:56 ThinkPad gsd-media-keys[37882]: Failed to grab accelerator for keybinding settings:rfkill
Mar  9 10:26:56 ThinkPad colord[863]: failed to get session [pid 37874]: No data available
Mar  9 10:26:56 ThinkPad gnome-shell[37013]: Failed to set CRTC gamma: drmModeCrtcSetGamma on CRTC 67 failed: Permission denied
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME XSettings.
Mar  9 10:26:56 ThinkPad systemd[1701]: Started GNOME Printer notifications.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Printer notifications.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME XSettings.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME Session.
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target GNOME X11 Session (session: qtile).
Mar  9 10:26:56 ThinkPad systemd[1701]: Reached target Current graphical user session.
Mar  9 10:26:56 ThinkPad systemd[1701]: Condition check resulted in GNOME Initial Setup being skipped.
Mar  9 10:26:56 ThinkPad systemd[1701]: Condition check resulted in GNOME Welcome Tour being skipped.
Mar  9 10:26:56 ThinkPad qtile.desktop[37883]: 2022-03-09 10:26:56,794 ERROR libqtile core.py:__init__():L99 not starting; existing window manager GNOME Shell
Mar  9 10:26:56 ThinkPad qtile.desktop[37883]: Traceback (most recent call last):
Mar  9 10:26:56 ThinkPad qtile.desktop[37883]:   File "/usr/local/bin/qtile", line 8, in <module>
Mar  9 10:26:56 ThinkPad qtile.desktop[37883]:     sys.exit(main())
Mar  9 10:26:56 ThinkPad qtile.desktop[37883]:   File "/home/ilyachch/.opt/qtile/lib/python3.8/site-packages/libqtile/scripts/main.py", line 66, in main
Mar  9 10:26:56 ThinkPad qtile.desktop[37883]:     options.func(options)
Mar  9 10:26:56 ThinkPad qtile.desktop[37883]:   File "/home/ilyachch/.opt/qtile/lib/python3.8/site-packages/libqtile/scripts/start.py", line 90, in start
Mar  9 10:26:56 ThinkPad qtile.desktop[37883]:     q = make_qtile(options)
Mar  9 10:26:56 ThinkPad qtile.desktop[37883]:   File "/home/ilyachch/.opt/qtile/lib/python3.8/site-packages/libqtile/scripts/start.py", line 51, in make_qtile
Mar  9 10:26:56 ThinkPad qtile.desktop[37883]:     kore = libqtile.backend.get_core(options.backend)
Mar  9 10:26:56 ThinkPad qtile.desktop[37883]:   File "/home/ilyachch/.opt/qtile/lib/python3.8/site-packages/libqtile/backend/__init__.py", line 15, in get_core
Mar  9 10:26:56 ThinkPad qtile.desktop[37883]:     return importlib.import_module(f"libqtile.backend.{backend}.core").Core(*args)
Mar  9 10:26:56 ThinkPad qtile.desktop[37883]:   File "/home/ilyachch/.opt/qtile/lib/python3.8/site-packages/libqtile/backend/x11/core.py", line 100, in __init__
Mar  9 10:26:56 ThinkPad qtile.desktop[37883]:     raise ExistingWMException(existing_wmname)
Mar  9 10:26:56 ThinkPad qtile.desktop[37883]: libqtile.backend.x11.core.ExistingWMException: GNOME Shell
```

So, gnome-shell starts before qtile and qtile fails with `ExistingWMException`

**Comment by elParaguayo** [comment]
Sorry I should have read the whole thread again. Hardly surprising that you weren't getting any log messages based on this.

Unfortunately I don't use gnome so am unlikely to be able to do much here.

**Comment by ilyachch** [comment]
@nazar-pc can you take a look, please?

**Comment by nazar-pc** [comment]
I suspect `DesktopNames` is what you might be lacking, gnome-shell shouldn't be starting. Also make sure you run X11 session, not Wayland.

Here is my setup:
```
nazar-pc@nazar-pc:~> cat /usr/share/xsessions/custom.desktop
[Desktop Entry]
Name=Custom session
Comment=Custom session
#Exec=/usr/lib/gnome-session/run-systemd-session custom-session.target
TryExec=/usr/bin/gnome-session
Exec=gnome-session --session=custom
Type=Application
DesktopNames=Custom
nazar-pc@nazar-pc:~> cat /usr/share/gnome-session/sessions/custom.session 
[GNOME Session]
Name=Custom
RequiredComponents=qtile
DesktopName=Custom
nazar-pc@nazar-pc:~> cat ~/.local/share/applications/qtile.desktop 
[Desktop Entry]
Name=Qtile
Type=Application
Exec=qtile start
Icon=qtile
NoDisplay=true
OnlyShowIn=Custom
X-GNOME-WMName=qtile
X-GNOME-Autostart-Phase=WindowManager
X-GNOME-Autostart-Notify=false
X-GNOME-Provides=windowmanager
```

I can then use `OnlyShowIn=Custom` in autostart desktop items to control what I want to start in my custom session.

In case it matters, I use LightDM instead of GDM. I vaguely remember I had some issues with GDM several years ago, LightDM worked great for me since with GTK greeter.

**Comment by ilyachch** [comment]
so, finally, I solved the problem. I've used this https://github.com/i3-gnome/i3-gnome project and made everything like there. Now it works with GDM and LightDM

**Comment by elParaguayo** [comment]
Great. Can you share what you've done so we can update the docs (or, ideally, could you make the changes yourself and submit a pull request)?

**Comment by ilyachch** [comment]
Sure

**Comment by severindellsperger** [comment]
@ilyachch Can you share your configuration here? 
I get it up and running but it's quite buggy. 
How about you?

**Comment by ilyachch** [comment]
@severindellsperger 
I've made an ansible role for installing qtile
[qtile.zip](https://github.com/qtile/qtile/files/9102512/qtile.zip)

It allowed me to launch it, but some things do not work, such as lock screen, notifications, keyboard layout changing, sound etc.

So, apply it on your own risk=)

**Comment by m-col** [comment]
Looks like you got this all sorted so I'll close this.
