### ISSUE TITLE
Qtile semi-crash disallowing you to click or use key bindings, vol.2

### ISSUE THREAD

**Issue by FrostyX** [qtile/qtile#3276]
In 2019 I reported #1445 and we considered it solved but it either continues to be broken or I have encountered a very similar issue. It behaves exactly like #1445, so I will copy-paste it here

Randomly, from time to time (~ once a week), it happens to me, that Qtile halfway crashes and

- I still see the desktop, it doesn't disappear or fail or restart, anything
- I can move the mouse, but I cannot click on anything
- I can't use my key bindings (I can use ctrl+alft+f2 to switch to TTY though)
- I can type to the focused window

This time, in `~/.local/share/qtile/qtile.log` appears:

```
2022-01-30 06:55:25,157 ERROR libqtile manager.py:process_key_event():L389 KB command error spawn: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/command/interface.py", line 316, in call
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 1101, in cmd_spawn
    """Run cmd, in a shell or not (default).
IndexError: list index out of range

2022-01-30 06:55:25,390 ERROR libqtile manager.py:process_key_event():L389 KB command error spawn: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/command/interface.py", line 316, in call
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 1101, in cmd_spawn
    """Run cmd, in a shell or not (default).
IndexError: list index out of range

2022-01-30 06:55:26,291 ERROR libqtile manager.py:process_key_event():L389 KB command error spawn: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/command/interface.py", line 316, in call
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 1101, in cmd_spawn
    """Run cmd, in a shell or not (default).
IndexError: list index out of range

2022-01-30 06:55:26,568 ERROR libqtile manager.py:process_key_event():L389 KB command error spawn: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/command/interface.py", line 316, in call
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 1101, in cmd_spawn
    """Run cmd, in a shell or not (default).
IndexError: list index out of range
```

When I try to run `qtile-cmd -o cmd -f restart` or another Qtile command, I get:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.10/asyncio/streams.py", line 662, in read
    block = await self.read(self._limit)
  File "/usr/lib64/python3.10/asyncio/streams.py", line 669, in read
    await self._wait_for_data('read')
  File "/usr/lib64/python3.10/asyncio/streams.py", line 502, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/ipc.py", line 181, in async_send
    read_data = await asyncio.wait_for(reader.read(), timeout=10)
  File "/usr/lib64/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/qtile", line 33, in <module>
    sys.exit(load_entry_point('qtile==0.20.0', 'console_scripts', 'qtile')())
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/main.py", line 66, in main
    options.func(options)
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/cmd_obj.py", line 165, in cmd_obj
    obj = get_object(cmd_client, args.obj_spec)
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/cmd_obj.py", line 109, in get_object
    client = client.navigate(arg0, arg1)
  File "/usr/lib/python3.10/site-packages/libqtile/command/client.py", line 94, in navigate
    if not self._command.has_item(self._current_node, name, normalized_selector):
  File "/usr/lib/python3.10/site-packages/libqtile/command/interface.py", line 276, in has_item
    _, items = self.execute(items_call, (object_type,), {})
  File "/usr/lib/python3.10/site-packages/libqtile/command/interface.py", line 225, in execute
    status, result = self._client.send((call.parent.selectors, call.name, args, kwargs))
  File "/usr/lib/python3.10/site-packages/libqtile/ipc.py", line 161, in send
    return asyncio.run(self.async_send(msg))
  File "/usr/lib64/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/ipc.py", line 183, in async_send
    raise IPCError("Server not responding")
libqtile.ipc.IPCError: Server not responding
```

Any help is appreciated, at the moment I am forced to deal with this by `killall -9 qtile` and it really hurts.

**Comment by philiparvidsson** [comment]
This has just now started happening to me after a recent update.

The interesting thing is that I can get mouse clicks to work again, usually by focusing a different window (by using keyboard shortcuts) or showing/hiding the scratchpad a few times.

I'm unsure as to the steps in this workaround, but by shifting focus a few times and showing/hiding scratchpad, I can pretty much always get mouse clicks to work again.

**Comment by m-col** [comment]
That first error `IndexError: list index out of range` seems to be caused by using `lazy.spawn` with an empty string, or another string that is not being correctly split to create the command as a list. This seems to be bound to a key in your config. What is the config for that `Key`?

**Comment by philiparvidsson** [comment]
I actually found a way to reproduce the workaround:

Activate a scratchpad window, then hide it. Then use alt-tab (I have custom alt-tab functionality) back to it. This, itself, triggers a bug: The displayed group is set to the scratchpad group. Then switch back. Then the bug you are describing is reset.

**Comment by m-col** [comment]
What do you have bound to alt-tab?

**Comment by philiparvidsson** [comment]
For completeness, alt-tab code:

```python
# List of windows that we've focused recently, in the order they were focused.
window_list = []

@hook.subscribe.client_focus
def on_client_focus(window):
    # Remove the window we're about to focus from the list if it's already in
    # it.
    for w in window_list:
        if w.wid == window.wid:
            window_list.remove(w)
            break

    window_list.append(window)
    if len(window_list) > 3:
        window_list.pop(0)


def switch_to_previous_window(qtile, *args, go_back=False):
    if len(window_list) < 2:
        return

    cur_wnd = window_list[-1]
    prev_wnd = window_list[0] if go_back else window_list[-2]

    cur_grp = cur_wnd.group
    prev_grp = prev_wnd.group

    prev_wnd.group.focus(prev_wnd)

    if prev_wnd.group != cur_wnd.group:
        # The previous window is in another group (thus another screen).
        cur_scrn = cur_grp.screen
        prev_scrn = prev_grp.screen

        if prev_scrn:
            # If the previous group has a screen, it means we're on a
            # multi-monitor setup. That, in turn, means that we dont need to
            # switch groups on this screen. Instead, we can just change the
            # focused screen to the other monitor.
            qtile.focus_screen(prev_scrn.index)
        else:
            # The previous group doesn't have a screen, so we have to switch
            # this screen to show a different group.
            cur_scrn.group = prev_grp
            cur_grp.set_screen(None)
            prev_grp.set_screen(cur_scrn)
```

**Comment by philiparvidsson** [comment]
> What do you have bound to alt-tab?

See above post. It is bound like this:

```python
    "M-<Tab>"   : lazy.function(switch_to_previous_window),
    "M-S-<Tab>" : lazy.function(switch_to_previous_window, go_back=True),
```

**Comment by philiparvidsson** [comment]
By the way, @FrostyX. Are you running picom or some other composition manager? I have only encountered the bug when running picom. On the other hand, I usually have it running (merely for the dim functionality).

**Comment by philiparvidsson** [comment]
> What do you have bound to alt-tab?

Steps for reproducing workaround:

1. Wait for bug to occur
2. Press hotkey to show scratchpad window
3. Press hotkey again to hide the scratchpad window
4. Press S-<Tab> to trigger `switch_to_previous_window`
5. Notice how Qtile switches to scratchpad group (this, in itself is a bug)
6. Press S-<Tab> again to switch back.
7. Workaround activated - you can now click with mouse again.

**Comment by m-col** [comment]
Your function above doesn't account for windows that are killed and no longer valid. What happens if you try to go back to a window that is no longer alive?

**Comment by philiparvidsson** [comment]
> Your function above doesn't account for windows that are killed and no longer valid. What happens if you try to go back to a window that is no longer alive?

That's a bug - I'm not done with the function yet. Nothing happens so it's not really a problem. It probably triggers some exception but it's not breaking anything. Either way, that's not relevant for the issue in this thread. But you're absolutely right.

**Comment by philiparvidsson** [comment]
Actually, what might be solving it is the group switching. @FrostyX if you switch to another group and then back (if you can), is the problem solved?

**Comment by FrostyX** [comment]
> The interesting thing is that I can get mouse clicks to work again, usually by focusing a different window (by using keyboard shortcuts) or showing/hiding the scratchpad a few times.

I can't do that, none of my keyboard shortcuts work at that point

> That first error IndexError: list index out of range seems to be caused by using lazy.spawn with an empty string, or another string that is not being correctly split to create the command as a list. This seems to be bound to a key in your config. What is the config for that Key?

@m-col How do I find out what `L389 KB` key binding is, please?

> Are you running picom or some other composition manager?

Thank you for the hint. I am not running any composition manager though

> Actually, what might be solving it is the group switching. @FrostyX if you switch to another group and then back (if you can), is the problem solved?

I can't switch groups at that point. Or at least I haven't figured out how. Clicking on the panel doesn't work (I think, I will try next time to be sure) and key bindings doesn't work either.

**Comment by philiparvidsson** [comment]
> I can't switch groups at that point. Or at least I haven't figured out how. Clicking on the panel doesn't work (I think, I will try next time to be sure) and key bindings doesn't work either.

I'm wondering if we're encountering the same bug. This bug is new to me - it just started happening after a recent update.

Are you entirely sure NO shortcuts are working? Would you be able to reproduce it and then try to apply my "alt-tab workaround"?

**Comment by m-col** [comment]
Sorry, missed this.

> @m-col How do I find out what L389 KB key binding is, please?

The L389 is the line number within the file where the log message was made, so unfortunately doesn't indicate what the key was. If you enable debug logging you should get much more information about the key that was pressed.

**Comment by FrostyX** [comment]
@m-col, I added the following line into my `config.py`:

```
logger.setLevel(logging.DEBUG)
```

This is the end of my `qtile.log` - [qtile-bug.log](https://github.com/qtile/qtile/files/8846094/qtile-bug.log)
Do you see anything helpful there?

**Comment by jwijenbergh** [comment]
Just chiming in, did you try with the default config? Also does this still happen on e.g. master? Thanks

**Comment by jwijenbergh** [comment]
Thanks, so can this stay closed @FrostyX

**Comment by jwijenbergh** [comment]
> This issue is stale because it has been open 90 days with no activity. Remove the `status: stale` label or comment, or this will be closed in 30 days.

I will be the one to close this
