### ISSUE TITLE
Qtile freeze ı don't know why

### ISSUE THREAD

**Issue by ArchKubi** [qtile/qtile#3296]
2022-02-03 16:59:35,756 ERROR libqtile core.py:_xpoll():L331 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 285, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 612, in poll_for_event
    return self.hoist_event(e)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 686, in hoist_event
    return self._process_error(ffi.cast("xcb_generic_error_t *", e))
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 649, in _process_error
    raise error(buf)                                                                                               
xcffib.xproto.MatchError

**Comment by elParaguayo** [comment]
Sorry to hear that.

Unfortunately, a `MatchError` wouldn't typically cause a freeze and there's nothing in that message that can help debug your issue.

We're going to need much more info to try and help. Which version are your running, what's your config, what were you doing when qtile froze?

**Comment by ArchKubi** [comment]
0.20.0 version
[config.txt](https://github.com/qtile/qtile/files/8000418/config.txt)
ı just use vscode practice and listen video 
but ı hear video qtile freeze ı dont know why

**Comment by ArchKubi** [comment]
2022-02-05 12:07:35,292 ERROR libqtile start.py:start():L94 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 92, in start
    q.loop()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 190, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 218, in async_loop
    self.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 298, in finalize
    self.core.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 161, in finalize
    self.conn.conn.core.DeletePropertyChecked(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-02-05 12:07:35,305 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate

**Comment by elParaguayo** [comment]
@ArchKubi are you still getting this issue or can we close this?

**Comment by ArchKubi** [comment]
ı use i3 now but one day test this again
