### ISSUE TITLE
Qtile loses connection with X when shutting down

### ISSUE THREAD

**Issue by zakissimo** [qtile/qtile#3351]
Nothing concerning here, but it seems like Qtile is not shutting down fast enough whenever I "shutdown now" and throws errors right before computer shut down. Is there a way to make qtile end before X ?

Again, nothing concerning, but it's a bit messy. (Maybe my system is too slow ?)

```
2022-02-17 21:13:16,855 ERROR libqtile core.py:_xpoll():L323 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 610, in poll_for_event
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 285, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-02-17 21:13:16,856 ERROR libqtile manager.py:_finalize_configurables():L293 exception during finalize
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 281, in _finalize_configurables
    widget.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 232, in finalize
    self.drawer.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 37, in finalize
    self._free_pixmap()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 117, in _free_pixmap
    self.qtile.core.conn.conn.core.FreePixmap(self._pixmap)
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2863, in FreePixmap
    return self.send_request(54, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
```

**Comment by jwijenbergh** [comment]
I have taken a look at this and I couldn't find a way to close qtile before x closes, is that even possible? Looking at other wms, if I look at it correctly, they don't handle this

**Comment by elParaguayo** [comment]
I wonder, if we know we're exiting then can't we just swallow the ConnectionExceptions?

i.e. in this section:
https://github.com/qtile/qtile/blob/4c98020e14be7b022a305854a18b7a2df4cdb2eb/libqtile/backend/x11/core.py#L323-L334

We could look at the lifecycle state (or some other variable) and, if we're shutting down anyway, ignore these errors.

**Comment by jwijenbergh** [comment]
> I wonder, if we know we're exiting then can't we just swallow the ConnectionExceptions?
> 
> i.e. in this section:
> 
> https://github.com/qtile/qtile/blob/4c98020e14be7b022a305854a18b7a2df4cdb2eb/libqtile/backend/x11/core.py#L323-L334
> 
> We could look at the lifecycle state (or some other variable) and, if we're shutting down anyway, ignore these errors.

Yeah I also think that this is the best way we can improve this. It's annoying that these rather normal exit conditions get logged as users often think that is a bug within qtile

**Comment by deivi98** [comment]
Same issue here. I have `lazy.spawn("shutdown now")` in my config to shutdown my computer with a shortcut. It has always worked, when recently suddenly stopped working. When using the shortcut, qtile shuts down but I am back to login and the computer does not shutdown.

At first I though it could be something related to another package/app, but when shutting down terminal it works just fine. Then I checked and I have the same error logs as well. Was this caused by a recent version?

**Comment by deivi98** [comment]
Issue magically disappeared recently, still don't know the reason but I'm happy.

**Comment by m-col** [comment]
> Issue magically disappeared recently, still don't know the reason but I'm happy.

Classic. https://github.com/qtile/qtile/pull/4073/ is set to auto-merge and should fix this for good.
