### ISSUE TITLE
[Wayland] Qtile crashes after exiting program that played fullscreen video

### ISSUE THREAD

**Issue by arjan-s** [qtile/qtile#3361]
When using for instance Firefox or mpv to play a fullscreen video, Qtile (current git master) crashes when exiting the program. So in the case of mpv Qtile crashes immediately after the video, but in the case of Firefox I can play multiple Youtube videos and it will only crash after exiting Firefox. In both programs I can also toggle endlessly between fullscreen and windowed (tiled) without problems.

I've reproduced this problem after checking out a fresh copy of the git repo by using the `wephyr` script in the repo after setting up a development environment with `dev.sh` from the repo.

This is the traceback causing the crash after exiting Firefox:
```
Exception ignored from cffi callback <function notify_func at 0x7fdde8862b00>:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 32, in notify_func
    data = listener._signal._data_wrapper(data)
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/surface.py", line 26, in __init__
    self.commit_event = Signal(ptr=ffi.addressof(self._ptr.events.commit))
AttributeError: cdata 'void *' has no attribute 'events'
Exception ignored from cffi callback <function notify_func at 0x7fdde8862b00>:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 32, in notify_func
    data = listener._signal._data_wrapper(data)
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/surface.py", line 26, in __init__
    self.commit_event = Signal(ptr=ffi.addressof(self._ptr.events.commit))
AttributeError: cdata 'void *' has no attribute 'events'
Exception ignored from cffi callback <function notify_func at 0x7fdde8862b00>:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 32, in notify_func
    data = listener._signal._data_wrapper(data)
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/surface.py", line 26, in __init__
    self.commit_event = Signal(ptr=ffi.addressof(self._ptr.events.commit))
AttributeError: cdata 'void *' has no attribute 'events'
Exception ignored from cffi callback <function notify_func at 0x7fdde8862b00>:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 32, in notify_func
    data = listener._signal._data_wrapper(data)
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/surface.py", line 26, in __init__
    self.commit_event = Signal(ptr=ffi.addressof(self._ptr.events.commit))
AttributeError: cdata 'void *' has no attribute 'events'
free(): invalid next size (fast)
```
And this is the traceback after exiting mpv:
```
Exception ignored from cffi callback <function notify_func at 0x7f09e513eb00>:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 32, in notify_func
    data = listener._signal._data_wrapper(data)
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/surface.py", line 26, in __init__
    self.commit_event = Signal(ptr=ffi.addressof(self._ptr.events.commit))
AttributeError: cdata 'void *' has no attribute 'events'
Exception ignored from cffi callback <function notify_func at 0x7f09e513eb00>:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 32, in notify_func
    data = listener._signal._data_wrapper(data)
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/surface.py", line 26, in __init__
    self.commit_event = Signal(ptr=ffi.addressof(self._ptr.events.commit))
AttributeError: cdata 'void *' has no attribute 'events'
Exception ignored from cffi callback <function notify_func at 0x7f09e513eb00>:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 32, in notify_func
    data = listener._signal._data_wrapper(data)
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/surface.py", line 26, in __init__
    self.commit_event = Signal(ptr=ffi.addressof(self._ptr.events.commit))
AttributeError: cdata 'void *' has no attribute 'events'
Exception ignored from cffi callback <function notify_func at 0x7f09e513eb00>:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 32, in notify_func
    data = listener._signal._data_wrapper(data)
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/surface.py", line 26, in __init__
    self.commit_event = Signal(ptr=ffi.addressof(self._ptr.events.commit))
AttributeError: cdata 'void *' has no attribute 'events'
Exception ignored from cffi callback <function notify_func at 0x7f09e513eb00>:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 32, in notify_func
    data = listener._signal._data_wrapper(data)
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/surface.py", line 26, in __init__
    self.commit_event = Signal(ptr=ffi.addressof(self._ptr.events.commit))
AttributeError: cdata 'void *' has no attribute 'events'
Exception ignored from cffi callback <function notify_func at 0x7f09e513eb00>:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 32, in notify_func
    data = listener._signal._data_wrapper(data)
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/surface.py", line 26, in __init__
    self.commit_event = Signal(ptr=ffi.addressof(self._ptr.events.commit))
AttributeError: cdata 'void *' has no attribute 'events'
free(): invalid size
```

**Comment by m-col** [comment]
Nice pattern detecting1 I've had this a few times but could never figure out a reliable way to reproduce it.

Thanks, this helps a lot!

**Comment by m-col** [comment]
I think it's something to do with idle inhibitors.

**Comment by m-col** [comment]
This should be fixed now with v0.4.11 of pywayland. Please re-open if you update to pywayland and find that it is not fixed.

**Comment by arjan-s** [comment]
@m-col I don't see an option to reopen this issue, but I'm afraid it's not fixed. I'm now running the current git master with pywayland 0.4.11 and pywlroots 0.15.9.

**Comment by m-col** [comment]
Do you get the error with mpv, and if so, does it need to be fullscreen?

**Comment by arjan-s** [comment]
Yes with mpv, and no it doesn't have to be full screen. But I found it happens more if I skip forward/backward a few times in a video.

**Comment by m-col** [comment]
Interestng, thanks. And you're 100% sure Qtile is running using pywayland 0.4.11?

**Comment by arjan-s** [comment]
Yes, and I even checked that your fix is in the code that's running, to make sure it isn't a mistake by the packager.

**Comment by cr1ogen** [comment]
I think It is the same as #3259, which was also closed but it was not fixed

**Comment by m-col** [comment]
Do you still see the tracebacks pasted in the top comment?

**Comment by arjan-s** [comment]
Yes, the tracebacks are still the same

**Comment by m-col** [comment]
OK, I was being stupid, I had an extra commit to pywlroots in use that I totally forgot about! I've submitted it there and seems to fix this: https://github.com/flacjacket/pywlroots/pull/79

**Comment by arjan-s** [comment]
No problem! Glad you found it!
I'll test it again when a new pywlroots release is out.

**Comment by arjan-s** [comment]
Yes! With pywlroots 0.15.10 this issue is solved for me as well.

**Comment by m-col** [comment]
Great to hear. Should I close this then?

**Comment by arjan-s** [comment]
Oh, I forgot I opened it :)
I'll close it now.
