### ISSUE TITLE
Emacs won't float

### ISSUE THREAD

**Issue by mhwombat** [qtile/qtile#3398]
### The issue:

In Qtile, emacs always starts as a floating window for some reason. Worse, I can't toggle it to non-floating.

- Other apps launch in tiled windows as desired.
- Toggling other windows between floating and non-floating works fine.
- I'm using Wayland.
- The problem doesn't occur in sway.
- Possibly related to #3273?

```
$ qtile --version
0.20.0
```

Here's my config:
```
from typing import List  # noqa: F401

from libqtile import bar, layout, widget, extension
from libqtile.config import Click, Drag, Group, Key, Match, Screen
from libqtile.lazy import lazy
from libqtile.utils import guess_terminal
import sys
import os

config_dir = os.path.dirname(__file__)
print("The config dir is : " + config_dir)
from colour import Colour

logo = "mod4"
alt="mod1"

terminal = guess_terminal()
launcher = "amys-launcher"

keys = [
    # A list of available commands that can be bound to keys can be found
    # at https://docs.qtile.org/en/latest/manual/config/lazy.html

    # Switch between windows
    Key([logo], "Left", lazy.layout.left(), desc="Move focus to left"),
    Key([logo], "Right", lazy.layout.right(), desc="Move focus to right"),
    Key([logo], "Down", lazy.layout.down(), desc="Move focus down"),
    Key([logo], "Up", lazy.layout.up(), desc="Move focus up"),
    Key([logo], "space", lazy.layout.next(),
        desc="Move window focus to other window"),

    # Move windows between left/right columns or move up/down in current stack.
    # Moving out of range in Columns layout will create new column.
    Key([logo, "shift"], "Left", lazy.layout.shuffle_left(),
        desc="Move window to the left"),
    Key([logo, "shift"], "Right", lazy.layout.shuffle_right(),
        desc="Move window to the right"),
    Key([logo, "shift"], "Down", lazy.layout.shuffle_down(),
        desc="Move window down"),
    Key([logo, "shift"], "Up", lazy.layout.shuffle_up(), desc="Move window up"),

    # Grow windows. If current window is on the edge of screen and direction
    # will be to screen edge - window would shrink.
    Key([logo, "control"], "Left", lazy.layout.grow_left(),
        desc="Grow window to the left"),
    Key([logo, "control"], "Right", lazy.layout.grow_right(),
        desc="Grow window to the right"),
    Key([logo, "control"], "Down", lazy.layout.grow_down(),
        desc="Grow window down"),
    Key([logo, "control"], "Up", lazy.layout.grow_up(), desc="Grow window up"),
    Key([logo], "n", lazy.layout.normalize(), desc="Reset all window sizes"),

    # Swap??? windows between left/right columns or up/down in current stack.
    Key([logo, alt], "Left", lazy.layout.flip_left(),
        desc="Move window to the left"),
    Key([logo, alt], "Right", lazy.layout.flip_right(),
        desc="Move window to the right"),
    Key([logo, alt], "Down", lazy.layout.flip_down(),
        desc="Move window down"),
    Key([logo, alt], "Up", lazy.layout.flip_up(), desc="Move window up"),

    # Key([logo, "control"], 'Return', lazy.run_extension(extension.WindowList(
    #     dmenu_prompt=">"
    # ))),

    # Toggle between split and unsplit sides of stack.
    # Split = all windows displayed
    # Unsplit = 1 window displayed, like Max layout, but still with
    # multiple stack panes
    # Key([logo, "shift"], "Return", lazy.layout.toggle_split(),
    #     desc="Toggle between split and unsplit sides of stack"),
    Key([logo], "Return", lazy.spawn(launcher), desc="Show launch menu"),
    Key([logo, "shift"], "Return", lazy.spawn(terminal), desc="Launch terminal"),

    # Toggle between different layouts as defined below
    Key([logo], "Tab", lazy.next_layout(), desc="Toggle between layouts"),
    Key([logo], "Delete", lazy.window.kill(), desc="Kill focused window"),

    Key([logo, "control"], "r", lazy.reload_config(), desc="Reload the config"),
    Key([logo, "control"], "q", lazy.shutdown(), desc="Shutdown Qtile"),
    # Key([logo], "r", lazy.spawncmd(),
    #     desc="Spawn a command using a prompt widget"),

    Key([logo, "control"], "f", lazy.window.toggle_floating()),
    Key([logo, "control", "shift"], "f", lazy.window.toggle_fullscreen()),

    Key([alt, "control"], "F1", lazy.core.change_vt(1), desc="Go to virtual console 1"),
    Key([alt, "control"], "F2", lazy.core.change_vt(2), desc="Go to virtual console 2"),
    Key([alt, "control"], "F3", lazy.core.change_vt(3), desc="Go to virtual console 3"),
    Key([alt, "control"], "F4", lazy.core.change_vt(4), desc="Go to virtual console 4"),
    Key([alt, "control"], "F5", lazy.core.change_vt(5), desc="Go to virtual console 5"),
    Key([alt, "control"], "F6", lazy.core.change_vt(6), desc="Go to virtual console 6"),
    Key([alt, "control"], "F7", lazy.core.change_vt(7), desc="Go to virtual console 7"),
    Key([alt, "control"], "F8", lazy.core.change_vt(8), desc="Go to virtual console 8"),
    Key([alt, "control"], "F9", lazy.core.change_vt(9), desc="Go to virtual console 9"),
]

# What other window managers often call "workspaces".
groups = [Group(i) for i in ["1", "2", "3", "4", "5", "6", "7", "8", "9",
                             "nixos", "vmware", "maths", "haskell", "qtile"]]

for g in groups:
    shortcut_key=g.name[0];
    # print(f"DEBUG g={g}, shortcut_key={shortcut_key}")
    keys.extend([
        # mod1 + letter of group = switch to group
        Key([logo], shortcut_key, lazy.group[g.name].toscreen(),
            desc="Switch to group {}".format(g.name)),

        # mod1 + shift + letter of group = move focused window to group
        Key([logo, "shift"], shortcut_key, lazy.window.togroup(g.name),
            desc="move focused window to group {}".format(g.name)),
    ])

layouts = [
#    layout.Columns(border_focus_stack=['#d75f5f', '#8f3d3d'], border_width=4),
    layout.Bsp(
        # Border colour(s) for the focused window.
        border_focus=Colour.base0D,
        # Border colour(s) for un-focused windows.
        border_normal=Colour.base04,
	# Border width.
        border_width=6,
        # New clients are inserted in the shortest branch.
	#fair=True,
        # Amount by which to grow a window/column.
	#grow_amount=10,
        # New client occupies lower or right subspace.
	#lower_right=True,
	# Margin of the layout (int or list of ints [N E S W]).
        #margin=0,
        # Width/height ratio that defines the partition direction.
        #ratio=1.6
    ),
    layout.Tile(
        # Border colour(s) for the focused window.
        border_focus=Colour.base0D,
        # Border colour(s) for un-focused windows.
        border_normal=Colour.base04,
    )
]

widget_defaults = dict(
    font='sans',
    fontsize=12,
    padding=3,
)
extension_defaults = widget_defaults.copy()

status_bar_widgets = [
    widget.CurrentLayout(),
    widget.CurrentLayoutIcon(),
    widget.CurrentScreen(active_color=Colour.base0A, inactive_colour=Colour.base0D),
    widget.GroupBox(),
    widget.Prompt(),
    # widget.Wlan(
    #         format='{essid} {quality}/70',
    #         update_interval=5
    #     ),
    widget.WindowName(),
    widget.Spacer(length=10),
    widget.Net(
        format='  {interface}: {down} ↓↑ {up}',
        update_interval=10
    ),
    widget.Spacer(length=10),
    widget.Chord(
        chords_colors={
            'launch': ("#ff0000", "#ffffff"),
        },
        name_transform=lambda name: name.upper(),
    ),
    widget.Spacer(length=10),
    widget.ThermalSensor(),
    widget.Spacer(length=10),
    widget.Memory(
        format=' {MemUsed: .0f}{mm}/{MemTotal: .0f}{mm}',
        update_interval=10
    ),
    widget.Spacer(length=10),
    widget.CPU(
        format=' {freq_current}GHz {load_percent}%',
        update_interval=10
    ),
    widget.Spacer(length=10),
    widget.Clock(
        foreground=Colour.base00,
        background=Colour.base0D,
        format='%A, %d %B %Y %H:%M'
    ),
]

screens = [
    Screen(
        bottom=bar.Bar([
            widget.CurrentLayout(),
            widget.CurrentLayoutIcon(),
            widget.CurrentScreen(active_color=Colour.base0A, inactive_colour=Colour.base0D),
            widget.GroupBox(),
            widget.Prompt(),
            # widget.Wlan(
            #         format='{essid} {quality}/70',
            #         update_interval=5
            #     ),
            widget.WindowName(),
            widget.Spacer(length=10),
            widget.Net(
                format='  {interface}: {down} ↓↑ {up}',
                update_interval=10
            ),
            widget.Spacer(length=10),
            widget.Chord(
                chords_colors={
                    'launch': ("#ff0000", "#ffffff"),
                },
                name_transform=lambda name: name.upper(),
            ),
            widget.Spacer(length=10),
            widget.ThermalSensor(),
            widget.Spacer(length=10),
            widget.Memory(
                format=' {MemUsed: .0f}{mm}/{MemTotal: .0f}{mm}',
                update_interval=10
            ),
            widget.Spacer(length=10),
            widget.CPU(
                format=' {freq_current}GHz {load_percent}%',
                update_interval=10
            ),
            widget.Spacer(length=10),
            widget.Clock(
                foreground=Colour.base00,
                background=Colour.base0D,
                format='%A, %d %B %Y %H:%M'
            ),
        ],
        24)),
    Screen(
        bottom=bar.Bar([
            widget.CurrentLayout(),
            widget.CurrentLayoutIcon(),
            widget.CurrentScreen(active_color=Colour.base0A, inactive_colour=Colour.base0D),
            widget.GroupBox(),
            widget.Prompt(),
            # widget.Wlan(
            #         format='{essid} {quality}/70',
            #         update_interval=5
            #     ),
            widget.WindowName(),
            widget.Spacer(length=10),
            widget.Net(
                format='  {interface}: {down} ↓↑ {up}',
                update_interval=10
            ),
            widget.Spacer(length=10),
            widget.Chord(
                chords_colors={
                    'launch': ("#ff0000", "#ffffff"),
                },
                name_transform=lambda name: name.upper(),
            ),
            widget.Spacer(length=10),
            widget.ThermalSensor(),
            widget.Spacer(length=10),
            widget.Memory(
                format=' {MemUsed: .0f}{mm}/{MemTotal: .0f}{mm}',
                update_interval=10
            ),
            widget.Spacer(length=10),
            widget.CPU(
                format=' {freq_current}GHz {load_percent}%',
                update_interval=10
            ),
            widget.Spacer(length=10),
            widget.Clock(
                foreground=Colour.base00,
                background=Colour.base0D,
                format='%A, %d %B %Y %H:%M'
            ),
        ],
        24))
]

# Drag floating layouts.
mouse = [
    Drag([logo], "Button1", lazy.window.set_position_floating(),
         start=lazy.window.get_position()),
    Drag([logo], "Button3", lazy.window.set_size_floating(),
         start=lazy.window.get_size()),
    Click([logo], "Button2", lazy.window.bring_to_front())
]

dgroups_key_binder = None
dgroups_app_rules = []  # type: List
follow_mouse_focus = False
bring_front_click = False
cursor_warp = False
# floating_layout = layout.Floating(float_rules=[
#     # Run the utility of `xprop` to see the wm class and name of an X client.
#     *layout.Floating.default_float_rules,
#     Match(wm_class='confirmreset'),  # gitk
#     Match(wm_class='makebranch'),  # gitk
#     Match(wm_class='maketag'),  # gitk
#     Match(wm_class='ssh-askpass'),  # ssh-askpass
#     Match(title='branchdialog'),  # gitk
#     Match(title='pinentry'),  # GPG key password entry
# ])
auto_fullscreen = True
focus_on_window_activation = "smart"
reconfigure_screens = True

# If things like steam games want to auto-minimize themselves when losing
# focus, should we respect this or not?
auto_minimize = True

# XXX: Gasp! We're lying here. In fact, nobody really uses or cares about this
# string besides java UI toolkits; you can see several discussions on the
# mailing lists, GitHub issues, and other WM documentation that suggest setting
# this string if your java app doesn't work correctly. We may as well just lie
# and say that we're a working one by default.
#
# We choose LG3D to maximize irony: it is a 3D non-reparenting WM written in
# java that happens to be on java's whitelist.
wmname = "LG3D"
```

Nothing interesting in the log:
```
2022-03-02 14:39:55,741 WARNING libqtile prompt.py:_configure():L428 Prompt widget only supports audible bell under X11
2022-03-02 14:39:55,745 WARNING libqtile prompt.py:_configure():L428 Prompt widget only supports audible bell under X11
2022-03-02 14:40:30,725 WARNING libqtile window.py:_on_destroy():L229 Window destroyed before unmap event.
2022-03-02 14:41:41,439 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
2022-03-02 14:47:17,631 WARNING libqtile prompt.py:_configure():L428 Prompt widget only supports audible bell under X11
2022-03-02 14:47:17,636 WARNING libqtile prompt.py:_configure():L428 Prompt widget only supports audible bell under X11
2022-03-02 14:47:21,761 WARNING libqtile window.py:_on_destroy():L229 Window destroyed before unmap event.
2022-03-02 14:52:14,350 WARNING libqtile prompt.py:_configure():L428 Prompt widget only supports audible bell under X11
2022-03-02 14:52:14,353 WARNING libqtile prompt.py:_configure():L428 Prompt widget only supports audible bell under X11
2022-03-02 14:53:01,643 WARNING libqtile prompt.py:_configure():L428 Prompt widget only supports audible bell under X11
2022-03-02 14:53:01,646 WARNING libqtile prompt.py:_configure():L428 Prompt widget only supports audible bell under X11
2022-03-02 14:59:02,528 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
2022-03-02 14:59:18,218 WARNING libqtile prompt.py:_configure():L428 Prompt widget only supports audible bell under X11
2022-03-02 14:59:18,223 WARNING libqtile prompt.py:_configure():L428 Prompt widget only supports audible bell under X11
2022-03-02 15:00:11,445 WARNING libqtile lifecycle.py:_atexit():L38 Qtile will now terminate
2022-03-02 15:03:30,844 WARNING libqtile prompt.py:_configure():L428 Prompt widget only supports audible bell under X11
2022-03-02 15:03:30,849 WARNING libqtile prompt.py:_configure():L428 Prompt widget only supports audible bell under X11
2022-03-02 15:07:51,384 WARNING libqtile window.py:_on_destroy():L229 Window destroyed before unmap event.
2022-03-02 15:08:31,209 WARNING libqtile window.py:_on_destroy():L229 Window destroyed before unmap event.
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by cr1ogen** [comment]
The problem is fixed en dev version, i'm in qtile 0.20.1.dev73+g84328b65
What I don't know is if the solution is uploaded to the stable version or if we have to wait for a new version of Qtile

**Comment by elParaguayo** [comment]
@mhwombat can you confirm this is fixed in current dev version?

**Comment by mhwombat** [comment]
Unfortunately, I can't tell you one way or the other. I'm having trouble building the dev version, getting your build system and NixOS to play nicely together.

**Comment by mhwombat** [comment]
The issue I'm having is that `./scripts/ffibuild` is trying to write to a directory that it shouldn't write to.

```
$ ./scripts/ffibuild
building pango
building xcursors
building pulseaudio volume control
building Wayland libinput interface
Traceback (most recent call last):
  File "/home/amy/qtile/./libqtile/backend/wayland/libinput_ffi_build.py", line 1, in <module>
    import wlroots.ffi_build as wlr
  File "/nix/store/8swq5q8zg4syyzimf86z1vrfckn5id0y-python3.9-pywlroots-0.15.10/lib/python3.9/site-packages/wlroots/ffi_build.py", line 2426, in <module>
    check_version()
  File "/nix/store/8swq5q8zg4syyzimf86z1vrfckn5id0y-python3.9-pywlroots-0.15.10/lib/python3.9/site-packages/wlroots/ffi_build.py", line 51, in check_version
    wlroots_version = load_wlroots_version()
  File "/nix/store/8swq5q8zg4syyzimf86z1vrfckn5id0y-python3.9-pywlroots-0.15.10/lib/python3.9/site-packages/wlroots/ffi_build.py", line 38, in load_wlroots_version
    lib = ffi.verify("#include <wlr/version.h>")
  File "/nix/store/kn83mgxdlbv56rk4whv8ns7w7b2h5mw8-python3.9-cffi-1.15.0/lib/python3.9/site-packages/cffi/api.py", line 468, in verify
    lib = self.verifier.load_library()
  File "/nix/store/kn83mgxdlbv56rk4whv8ns7w7b2h5mw8-python3.9-cffi-1.15.0/lib/python3.9/site-packages/cffi/verifier.py", line 104, in load_library
    self._write_source()
  File "/nix/store/kn83mgxdlbv56rk4whv8ns7w7b2h5mw8-python3.9-cffi-1.15.0/lib/python3.9/site-packages/cffi/verifier.py", line 193, in _write_source
    with open(self.sourcefilename, "w") as fp:
OSError: [Errno 30] Read-only file system: '/nix/store/8swq5q8zg4syyzimf86z1vrfckn5id0y-python3.9-pywlroots-0.15.10/lib/python3.9/site-packages/wlroots/__pycache__/_cffi__xa540dd32xe9d2d037.c'
```

To narrow the problem down, I added a trace to `./libqtile/backend/wayland/libinput_ffi_build.py` and got this:

```
 --- modulename: genericpath, funcname: isdir
genericpath.py(41):     try:
genericpath.py(42):         st = os.stat(s)
genericpath.py(45):     return stat.S_ISDIR(st.st_mode)
verifier.py(193):                 with open(self.sourcefilename, "w") as fp:
verifier.py(106):             return self._load_library()
ffi_build.py(39):     except PermissionError:
<frozen importlib._bootstrap>(681): <frozen importlib._bootstrap>(682): <frozen importlib._bootstrap>(683): <frozen importlib._bootstrap>(686): <frozen importlib._bootstrap>(1007):  --- modulename: _bootstrap, funcname: __exit__
<frozen importlib._bootstrap>(161):  --- modulename: _bootstrap, funcname: release
<frozen importlib._bootstrap>(113): <frozen importlib._bootstrap>(114): <frozen importlib._bootstrap>(115): <frozen importlib._bootstrap>(117): <frozen importlib._bootstrap>(118): <frozen importlib._bootstrap>(119): <frozen importlib._bootstrap>(120): <frozen importlib._bootstrap>(121):  --- modulename: _bootstrap, funcname: cb
Cannot run file './libqtile/backend/wayland/libinput_ffi_build.py' because: [Errno 30] Read-only file system: '/nix/store/8swq5q8zg4syyzimf86z1vrfckn5id0y-python3.9-pywlroots-0.15.10/lib/python3.9/site-packages/wlroots/__pycache__/_cffi__xa540dd32xe9d2d037.c'
<frozen importlib._bootstrap>(186): <frozen importlib._bootstrap>(187): <frozen importlib._bootstrap>(191): <frozen importlib._bootstrap>(192): <frozen importlib._bootstrap>(194):
```

**Comment by elParaguayo** [comment]
I've no idea how Nix does things but this might be something for @m-col as he added that additional building step.

Not sure why that one's problematic when the others are ok.

**Comment by mhwombat** [comment]
Just checked, and I can run that script in the 0.20.0 release without problems.

**Comment by elParaguayo** [comment]
Great. So we can close this?

**Comment by m-col** [comment]
I think this is a pywlroots issue: https://github.com/flacjacket/pywlroots/pull/81 I'm not 100% certain that PR will fix it, but it might do.

**Comment by mhwombat** [comment]
Fixed now.
