### ISSUE TITLE
Setting "alt" as a modifier crashes Qtile

### ISSUE THREAD

**Issue by zakissimo** [qtile/qtile#3417]
```
qtile --version
0.20.0
```
### The issue:
For the following binds, I tried replacing "mod2" by alt or  "mod1" or even "Alt_L". Every time, after a refresh, Qtile crashes.
```
mod = "mod4"
mod1 = "alt"
mod2 = "control"

keys = [
    Key([mod2], "j", increase_gaps(), desc=""),
    Key([mod2], "k", decrease_gaps(), desc=""),
```
Here's what my log reports:
```
2022-03-10 22:28:45,514 WARNING libqtile lifecycle.py:_atexit():L34 Restarting Qtile with os.execv(...)
2022-03-10 22:28:45,914 ERROR libqtile base.py:on_done():L627 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 619, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 522, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 81, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 138, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2022-03-10 22:28:45,914 ERROR libqtile base.py:on_done():L627 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 619, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 522, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 81, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 138, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2022-03-10 22:28:46,051 ERROR libqtile start.py:start():L94 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/xcbq.py", line 810, in translate_masks
    masks.append(ModMasks[i])
KeyError: 'alt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 441, in lookup_key
    modmask = xcbq.translate_masks(key.modifiers)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/xcbq.py", line 812, in translate_masks
    raise XCBQError("Unknown modifier: %s" % i) from e
libqtile.backend.x11.xcbq.XCBQError: Unknown modifier: alt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 92, in start
    q.loop()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 190, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 215, in async_loop
    self.load_config(initial=True)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 136, in load_config
    self.grab_key(key)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 406, in grab_key
    keysym, mask_key = self.core.grab_key(key)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 449, in grab_key
    keysym, modmask = self.lookup_key(key)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 443, in lookup_key
    raise utils.QtileError(err)
libqtile.utils.QtileError: Unknown modifier: alt
2022-03-10 22:31:17,415 WARNING libqtile core.py:grab_key():L454 Can't grab <Key (['mod4'], egrave)> (unknown keysym: 0xe8)
2022-03-10 22:31:17,416 WARNING libqtile core.py:grab_key():L454 Can't grab <Key (['mod4', 'shift'], egrave)> (unknown keysym: 0xe8)
2022-03-10 22:31:17,416 WARNING libqtile core.py:grab_key():L454 Can't grab <Key (['mod4'], ccedilla)> (unknown keysym: 0xe7)
2022-03-10 22:31:17,416 WARNING libqtile core.py:grab_key():L454 Can't grab <Key (['mod4', 'shift'], ccedilla)> (unknown keysym: 0xe7)
2022-03-10 22:31:17,416 WARNING libqtile core.py:grab_key():L454 Can't grab <Key (['mod4'], agrave)> (unknown keysym: 0xe0)
2022-03-10 22:31:17,416 WARNING libqtile core.py:grab_key():L454 Can't grab <Key (['mod4', 'shift'], agrave)> (unknown keysym: 0xe0)
2022-03-10 22:32:50,626 WARNING libqtile lifecycle.py:_atexit():L34 Restarting Qtile with os.execv(...)
2022-03-10 22:32:51,018 ERROR libqtile base.py:on_done():L627 Failed to reschedule.
```

Same thing for "Alt_L":
```
libqtile.backend.x11.xcbq.XCBQError: Unknown modifier: Alt_L
...
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I suspect those keys are actually mapped to modkeys. Try running `xmodmap -pm` to show which keys are mapped to which modifiers and then use that mod name in your config.

I suspect Alt is `mod1`.

**Comment by zakissimo** [comment]
You legend !

```
$ xmodmap -pm

xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x31)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3      
mod4        Super_L (0x42),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

Mapping mod1 to "mod1" did the trick. Thanks! <3
