### ISSUE TITLE
Can't add custom icons on a widget

### ISSUE THREAD

**Issue by PolSust** [qtile/qtile#3458]
#### Trying to add custom icons on my BatteryIcon widget like so:
```python
  widget.BatteryIcon(
                    theme_path="/home/{user}/.config/qtile/icons/battery"
                ),
```
 #### But the widget crashes and I get this error:
```python
2022-03-29 16:34:33,672 WARNING libqtile lifecycle.py:_atexit():L34 Restarting Qtile with os.execv(...)
2022-03-29 16:34:33,934 ERROR libqtile bar.py:_configure_widget():L324 BatteryIcon widget crashed during _configure with error: SystemError("ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)")
2022-03-29 16:34:34,190 ERROR libqtile loop.py:_handle_exception():L61 'battery-full-charged'
Traceback (most recent call last):
  File "/usr/lib64/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/{user}/.local/lib/python3.10/site-packages/libqtile/core/manager.py", line 825, in f
    func(*args)
  File "/home/{user}/.local/lib/python3.10/site-packages/libqtile/widget/battery.py", line 488, in timer_setup
    self.update()
  File "/home/{user}/.local/lib/python3.10/site-packages/libqtile/widget/battery.py", line 511, in update
    self.draw()
  File "/home/{user}/.local/lib/python3.10/site-packages/libqtile/widget/battery.py", line 515, in draw
    self.drawer.ctx.set_source(self.surfaces[self.current_icon])
KeyError: 'battery-full-charged'
```

Looks like there's a version mismatch with **libffi** should I try to update or downgrade my version?

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I'm not an expert on this but I've seen the issue come up before (e.g. https://github.com/qtile/qtile/issues/1332#issuecomment-897443575 and following comments).

If `libffi` has recently been upgraded, you may need to rebuild your qtile installation (including the `cairocffi` and `xcffib` packages)
