### ISSUE TITLE
Qtile crashing and after TypeError in pangocffi.py

### ISSUE THREAD

**Issue by JoaoDDuarte** [qtile/qtile#3483]
### The issue:

I am running Qtile 0.21.0 and seemingly at random, my qtile crashed at 18:59 and I am not sure which error caused it (I am assuming the pangocffi.py one):

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 303, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1151, in handle_KeyPress
    self.process_key_press(keysym)
  File "/usr/lib/python3.10/site-packages/libqtile/bar.py", line 524, in process_key_press
    if self.has_keyboard:
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: Bar has no attribute: has_keyboard
2022-04-07 18:59:35,817 ERROR libqtile hook.py:fire():L391 Error in hook screen_change
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 389, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 361, in cmd_reconfigure_screens
    self._process_screens()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 342, in _process_screens
    scr._configure(self, i, x, y, w, h, grp, reconfigure_gaps=reconfigure_gaps)
  File "/usr/lib/python3.10/site-packages/libqtile/config.py", line 308, in _configure
    self.paint(self.wallpaper, self.wallpaper_mode)
  File "/usr/lib/python3.10/site-packages/libqtile/config.py", line 311, in paint
    self.qtile.paint_screen(self, path, mode)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 373, in paint_screen
    self.core.painter.paint(screen, image_path, mode)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/xcbq.py", line 762, in paint
    self.conn.core.ChangeProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2712, in ChangeProperty
    return self.send_request(18, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-04-07 18:59:37,650 ERROR libqtile base.py:on_done():L635 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 627, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 530, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 81, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 138, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2022-04-07 18:59:39,415 ERROR libqtile base.py:on_done():L635 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 627, in on_done
    self.update(result)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 530, in update
    old_width = self.layout.width
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 81, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 138, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2022-04-07 18:59:39,416 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
```
It's a bit strange as I was running the VSCode Python debugger for an unrelated project when this happened. 

If you guys think that my config is relevant, please do tell me which part as it's a bit long and chopped up into multiple files. 

I am not quite sure what else to say as I do not see any obvious cause. If it happens again, I will update this bug report.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Hi, thanks for the report. I think this is fixed on master: https://github.com/qtile/qtile/commit/1ee37fda3ca77ee6142a1afe5377d2e108ed1526

To avoid the problem, you could run qtile from master. I expect you aren't getting it regularly or predictably?

**Comment by JoaoDDuarte** [comment]
Ah ok, I'll pull from master and I believe I'm using pypi for managing qtile - I'll switch to getting qtile from source :)
