### ISSUE TITLE
Can not run qtile in debian 11 from any Desktop Managers

### ISSUE THREAD

**Issue by prateekamana** [qtile/qtile#3494]
### The issue:

Can not run qtile from any desktop manager
**Version** : 0.21.0
**Logs** : 
```
2022-04-10 18:35:10,759 ERROR libqtile start.py:start():L94 Qtile crashed
Traceback (most recent call last):
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/scripts/start.py", line 92, in start
    q.loop()
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/core/manager.py", line 192, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/core/manager.py", line 217, in async_loop
    self.load_config(initial=True)
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/core/manager.py", line 134, in load_config
    self._process_screens(reloading=not initial)
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/core/manager.py", line 342, in _process_screens
    scr._configure(self, i, x, y, w, h, grp, reconfigure_gaps=reconfigure_gaps)
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/config.py", line 305, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/bar.py", line 294, in _configure
    self.drawer.clear(self.background)
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/backend/x11/drawer.py", line 177, in clear
    self._check_xcb()
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/backend/x11/drawer.py", line 122, in _check_xcb
    self._xcb_surface = self._create_xcb_surface()
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/backend/x11/drawer.py", line 88, in _create_xcb_surface
    surface = cairocffi.XCBSurface(
  File "/home/amana/.local/lib/python3.9/site-packages/cairocffi/xcb.py", line 37, in __init__
    p = cairo.cairo_xcb_surface_create(
AttributeError: cffi library 'libcairo.so.2' has no function, constant or global variable named 'cairo_xcb_surface_create'
2022-04-10 18:42:58,115 ERROR libqtile start.py:start():L94 Qtile crashed
Traceback (most recent call last):
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/scripts/start.py", line 92, in start
    q.loop()
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/core/manager.py", line 192, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/core/manager.py", line 217, in async_loop
    self.load_config(initial=True)
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/core/manager.py", line 134, in load_config
    self._process_screens(reloading=not initial)
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/core/manager.py", line 342, in _process_screens
    scr._configure(self, i, x, y, w, h, grp, reconfigure_gaps=reconfigure_gaps)
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/config.py", line 305, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/bar.py", line 294, in _configure
    self.drawer.clear(self.background)
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/backend/x11/drawer.py", line 177, in clear
    self._check_xcb()
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/backend/x11/drawer.py", line 122, in _check_xcb
    self._xcb_surface = self._create_xcb_surface()
  File "/home/amana/.local/lib/python3.9/site-packages/libqtile/backend/x11/drawer.py", line 88, in _create_xcb_surface
    surface = cairocffi.XCBSurface(
  File "/home/amana/.local/lib/python3.9/site-packages/cairocffi/xcb.py", line 37, in __init__
    p = cairo.cairo_xcb_surface_create(
AttributeError: cffi library 'libcairo.so.2' has no function, constant or global variable named 'cairo_xcb_surface_create'
```
**qtile.desktop** :
```
[Desktop Entry]
Name=Qtile
Comment=Qtile Session
Exec=qtile start
Type=Application
Keywords=wm;tiling
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by prateekamana** [comment]
When I try to log in with qtile, it throws me back to the login screen.

**Comment by m-col** [comment]
It looks like your cairocffi was not built with xcffib support.  To fix this:

  - Ensure a recent xcffib is installed (pip install 'xcffib>=0.5.0')
  - The pip cache is cleared (remove ~/.cache/pip, if it exists)
  - Reinstall cairocffi, either:

      pip install --no-deps --ignore-installed cairocffi

    or

      pip uninstall cairocffi && pip install cairocffi

**Comment by prateekamana** [comment]
That fixed it, you're a legend m-col, thanks a lot for such swift responses.

**Comment by m-col** [comment]
You're very welcome.
