### ISSUE TITLE
Qtile freezes since last system update.

### ISSUE THREAD

**Issue by mcizek-2** [qtile/qtile#3499]
### The issue:

My qtile version is 0.20.0.
In case it is relevant my OS is Gentoo.

Since yesterday my Qtile started freezing. Last thing I remember doing was updating some packages and fonts.

The log only displays this message on a loop 

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/keen/.local/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 328, in _xpoll
    self.remove_listener()
  File "/home/keen/.local/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 212, in remove_listener
    loop = asyncio.get_running_loop()
RuntimeError: no running event loop
2022-04-11 11:46:13,966 ERROR libqtile core.py:_xpoll():L323 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/home/keen/.local/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 285, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-04-11 11:46:13,966 ERROR libqtile loop.py:_handle_exception():L61 no running event loop
Traceback (most recent call last):
  File "/home/keen/.local/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 285, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/keen/.local/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 328, in _xpoll
    self.remove_listener()
  File "/home/keen/.local/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 212, in remove_listener
    loop = asyncio.get_running_loop()
RuntimeError: no running event loop
2022-04-11 11:46:13,966 ERROR libqtile core.py:_xpoll():L323 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/home/keen/.local/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 285, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-04-11 11:46:13,966 ERROR libqtile loop.py:_handle_exception():L61 no running event loop
Traceback (most recent call last):
  File "/home/keen/.local/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 285, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/keen/.local/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 328, in _xpoll
    self.remove_listener()
  File "/home/keen/.local/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 212, in remove_listener
    loop = asyncio.get_running_loop()
RuntimeError: no running event loop
2022-04-11 11:56:07,690 ERROR libqtile core.py:_xpoll():L323 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/home/keen/.local/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 285, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.9/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

```

When I start qtile with the default config, it doesn't seem to freeze but I still do get these errors on a loop. If you think it could be relevant please let me know if I should post here my config as well.

### Required:

- [ ] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Thanks for the report. Unfortunately there's nothing in that log extract that points to the root cause.

Have you tried v0.21? Might be worth seeing if the issue is still present there.

**Comment by elParaguayo** [comment]
Maybe that hook is getting fired too early.

Try checking if `w is None` and, if so, just exit your function.

**Comment by mcizek-2** [comment]
I found it.
When I fooled around with my fonts yesterday, I changed the locale of my system and that ended up messing up the script I used.

Since it had nothing to do with Qtile, so I'm closing this now.

And thanks for the help @elParaguayo .
