### ISSUE TITLE
Python module "collections.Iterable" is deprecated

### ISSUE THREAD

**Issue by mike-pisman** [qtile/qtile#3570]
### The issue:

Not exactly a Qtile issue, so I'm sorry for off-topic, though I decided to post in case someone will need help in the future. 
So I have updated to Ubuntu 22, and Python 3.10 finally. In Python 3.10  `collections.Iterable` have been moved to `collections.abc.Iterable`, which causes an error when trying to iterate over the bar's widget list.
```ERROR libqtile loop.py:_handle_exception():L63 module 'collections' has no attribute 'Iterable'
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/<username>/.local/lib/python3.10/site-packages/libqtile/core/manager.py", line 798, in f
    func(*args)
  File "/home/<username>/.local/lib/python3.10/site-packages/libqtile/bar.py", line 456, in _actual_draw
    i.draw()
  File "/home/<username>/.local/lib/python3.10/site-packages/libqtile/widget/groupbox.py", line 391, in draw
    self.drawbox(
  File "/home/<username>/.local/lib/python3.10/site-packages/libqtile/widget/groupbox.py", line 115, in drawbox
    framed = self.layout.framed(
  File "/home/<username>/.local/lib/python3.10/site-packages/libqtile/drawer.py", line 133, in framed
    return TextFrame(self, border_width, border_color, pad_x, pad_y, highlight_color=highlight_color)
  File "/home/<username>/.local/lib/python3.10/site-packages/libqtile/drawer.py", line 144, in __init__
    if isinstance(pad_x, collections.Iterable):
```

The solution that worked for me:
```
find /home/<username>/.local/lib/python3.10 -type f | xargs sed -i 's/collections.Iterable/collections.abc.Iterable/g'
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
What version of qtile are you running? 

Looking at the code for v0.21, I see this:
https://github.com/qtile/qtile/blob/b4577ac757fed2f6cd545133930254f40fdf3f79/libqtile/drawer.py#L147

**Comment by mike-pisman** [comment]
> What version of qtile are you running?
> Looking at the code for v0.21, I see this:

I had to reinstall qtile after upgrading the system and though that would get me the latest version, but it installed 0.18 for some reason, probably the version I had before. Updated to 0.21, everything seems to work. Sorry for that, will double check next time.
