### ISSUE TITLE
BatteryIcon can't load theme

### ISSUE THREAD

**Issue by AmbivalentDig** [qtile/qtile#3593]
### The issue:

Added theme_path to BatteryIcon and now an error pops up.
[qtile.log](https://github.com/qtile/qtile/files/8791281/qtile.log)

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Please could you post your config for `BatteryIcon`?

Log snippet for ref:
```
2022-05-28 17:20:41,408 WARNING libqtile lifecycle.py:_atexit():L33 Restarting Qtile with os.execv(...)
2022-05-28 17:20:41,616 ERROR libqtile bar.py:_configure_widget():L340 BatteryIcon widget crashed during _configure with error: LoadingError("Wasn't able to find images corresponding to the names: {'battery-full-charging.*', 'battery-low.*', 'battery-good.*', 'battery-caution.*', 'battery-missing.*', 'battery-full-charged.*', 'battery-full.*', 'battery-good-charging.*', 'battery-caution-charging.*', 'battery-low-charging.*'}")
2022-05-28 17:20:41,772 ERROR libqtile loop.py:_handle_exception():L63 'battery-good-charging'
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 845, in f
    func(*args)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/battery.py", line 504, in timer_setup
    self.update()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/battery.py", line 528, in update
    self.draw()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/battery.py", line 532, in draw
    self.drawer.ctx.set_source(self.surfaces[self.current_icon])
KeyError: 'battery-good-charging'
```

> now an error pops up

please could you describe what error happens? Is it just the widget that crashes, or does all of qtile error?

**Comment by elParaguayo** [comment]
Looks like the theme doesn't have the icons. 

Should just be a widget crash rather than full qtile crash.

**Comment by AmbivalentDig** [comment]
Only BatteryIcon falls. Everything else works as it should. There are no more errors and this is the entire log file.
Specified the full path to the topic. Did not work out. Then I looked at the sources and decided that the file extensions were not needed, but this is also not for long. After that I got the file extensions back. And nothing has changed.
config for BatteryIcon
`
widget.BatteryIcon(
                       background = colors[0],
                       theme_path = '/home/ambi/.config/qtile/battery/q/.'
                  ),
`
This is what the error looks like
![image](https://user-images.githubusercontent.com/105814790/170829812-d580d472-5557-4f18-9e50-fdb880cc8200.png)
Theme folder:
![image](https://user-images.githubusercontent.com/105814790/170829831-8f90bf46-1560-4d9b-839d-924a48422667.png)

**Comment by m-col** [comment]
Nice theme! Looks very clean.

What file types are those images?

**Comment by AmbivalentDig** [comment]
Thanks for the kind word.

Files in svg format. I tried to convert to png format, but this is also not long.

**Comment by m-col** [comment]
If you remove the `theme_path` argument, does it work fine with qtile's default battery icons?

**Comment by AmbivalentDig** [comment]
Yes
![image](https://user-images.githubusercontent.com/105814790/170830332-de0ff2e8-8481-4a3a-97a0-12ec191e7eb9.png)

**Comment by m-col** [comment]
Can you try with: `/ambi/.config/qtile/battery/q`

**Comment by m-col** [comment]
Sorry I made a typo - i mean `/home/ambi/.config/qtile/battery/q`.

I tested something similar locally and your original format should work too, so I dont think this test will make any difference.

I'm not sure why it isn't working!

**Comment by AmbivalentDig** [comment]
Only the name of the icon on which everything breaks has changed

`2022-05-28 17:48:02,378 ERROR libqtile bar.py:_configure_widget():L340 BatteryIcon widget crashed during _configure with error: LoadingError("Wasn't able to find images corresponding to the names: {'battery-good.*', 'battery-missing.*', 'battery-full-charged.*', 'battery-full-charging.*', 'battery-low.*', 'battery-caution.*', 'battery-low-charging.*', 'battery-good-charging.*', 'battery-full.*', 'battery-caution-charging.*'}")
2022-05-28 17:48:02,528 ERROR libqtile loop.py:_handle_exception():L63 'battery-full-charging'
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 845, in f
    func(*args)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/battery.py", line 504, in timer_setup
    self.update()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/battery.py", line 528, in update
    self.draw()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/battery.py", line 532, in draw
    self.drawer.ctx.set_source(self.surfaces[self.current_icon])
KeyError: 'battery-full-charging'`

**Comment by m-col** [comment]
Do your images have extensions in the file names at all? I see in your screenshot it looks like they don't, and the file searching is added a period character e.g. `'battery-full.*'`, so maybe that's why it isn't matching.

**Comment by AmbivalentDig** [comment]
File extensions available

![image](https://user-images.githubusercontent.com/105814790/170830766-9e97b502-e65a-4900-a7c5-564ff5459ffc.png)

**Comment by m-col** [comment]
Hmm, I am stumped. Would you be happy to debug on your system? The relevant code is here: https://github.com/qtile/qtile/blob/master/libqtile/images.py#L321-L343

This function is being used here: https://github.com/qtile/qtile/blob/master/libqtile/widget/battery.py#L514

**Comment by StarTroop** [comment]
I have the exact same issue, but the same function works properly in the Volume widget. I'm not sure how to go about changing the scripts to troubleshoot, but just by eyeing the two widgets' scripts I can see some differences, though I don't know which ones are relevant. I noticed that the Volume widget imports 'images' from 'libqtile', but the BatteryIcon widget does not.

**Comment by elParaguayo** [comment]
@AmbivalentDig - can you share the icon theme for this so I can try to recreate using your icons?
