### ISSUE TITLE
Can't login to the qtile wayland session

### ISSUE THREAD

**Issue by deepanshu188** [qtile/qtile#3601]
### The issue:

Qtile x11 is working fine but wayland session does not open.

I have tried **qtile start -b wayland** command on terminal but it is throwing following errors

```
Traceback (most recent call last):
  File "/sbin/qtile", line 33, in <module>
    sys.exit(load_entry_point('qtile==0.21.0', 'console_scripts', 'qtile')())
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/main.py", line 66, in main
    options.func(options)
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 90, in start
    q = make_qtile(options)
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 51, in make_qtile
    kore = libqtile.backend.get_core(options.backend)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/__init__.py", line 15, in get_core
    return importlib.import_module(f"libqtile.backend.{backend}.core").Core(*args)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/__init__.py", line 2, in <module>
    from libqtile.backend.wayland.inputs import InputConfig  # noqa: F401
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/inputs.py", line 26, in <module>
    from wlroots import ffi, lib
ModuleNotFoundError: No module named 'wlroots'

```

I don't know why it is saying no module named 'wlroots' cause i have wlroots installed.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Do you have `pywlroots` installed? https://github.com/flacjacket/pywlroots. This is the python bindings to the wlroots library.

**Comment by elParaguayo** [comment]
@m-col should/can we add a test in the `main.py` script (or somewhere else) that checks for the `pywlroots` package and gives a graceful error message when it's not available and the user wants to run the wayland backend?

**Comment by m-col** [comment]
Yep good idea: https://github.com/qtile/qtile/pull/3602

I'll add one for xcffib too, but trying that now I see `libqtile.backend.x11.core` is imported (and therefore `libqtile/backend/x11/__init__.py` is loaded) by `confreader` and so the approach in that PR would raise an error even when using wayland exclusively. May need to move that confreader check into the backend. xcffib shouldn't be required, and I'm hoping that it isn't!
