### ISSUE TITLE
[wayland] Window is hidden in some layouts.

### ISSUE THREAD

**Issue by Sydiepus** [qtile/qtile#3611]
### The issue:

I have a problem with ONLYOFFICE desktop editors where when i open it it's hidden until i switch to floating layout.
I use columns as default.
If i switch back to columns the window disappear.
To make it use the columns : 
- Switch to full screen.
- Switch to columns layout.
- Switch to normal... (unfullscreen).
- Now it's working fine with columns layout and doesn't disappear.

It's working fine in sway and Qtile on X11 backend.

Layouts in which the window is not hidden : 
- floating.
- bsp.
- matrix (the window disappear after i switch groups).

Qtile version : 0.21.1.dev61+g2ed6be19

What's inside the logs : 
- Switch group launch ONLYOFFICE desktop editors.
- Switch between columns and floating layout multiple times.
- Close the window. 

logs with DEBUG flag : 
```
2022-06-05 11:44:19,875 DEBUG libqtile interface.py:call():L310 Command: toscreen((), {'toggle': True})
2022-06-05 11:44:19,876 DEBUG libqtile window.py:_on_unmap():L702 Signal: xdgwindow unmap
2022-06-05 11:44:19,877 DEBUG libqtile hook.py:fire():L396 Internal event: setgroup((), {})
2022-06-05 11:44:19,880 DEBUG libqtile hook.py:fire():L396 Internal event: focus_change((), {})
2022-06-05 11:44:19,881 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825930>, <group.Group ('二')>), {})
2022-06-05 11:44:20,307 DEBUG libqtile interface.py:call():L310 Command: spawn(('rofi -show drun',), {})
2022-06-05 11:44:20,353 DEBUG libqtile core.py:_on_new_layer_surface():L499 Signal: layer_shell new_surface_event
2022-06-05 11:44:20,354 DEBUG libqtile output.py:organise_layers():L250 Output: organising layers
2022-06-05 11:44:20,354 INFO libqtile core.py:_on_new_layer_surface():L504 Managing new layer_shell window with window ID: 3
2022-06-05 11:44:20,354 DEBUG libqtile hook.py:fire():L396 Internal event: client_new((Static(name='<no name>', wid=3),), {})
2022-06-05 11:44:20,354 DEBUG libqtile hook.py:fire():L396 Internal event: client_managed((Static(name='<no name>', wid=3),), {})
2022-06-05 11:44:20,417 DEBUG libqtile window.py:_on_map():L1481 Signal: layerstatic map
2022-06-05 11:44:20,417 DEBUG libqtile output.py:organise_layers():L250 Output: organising layers
2022-06-05 11:44:20,418 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:44:20,418 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Static(name='<no name>', wid=3),), {})
2022-06-05 11:44:20,484 DEBUG libqtile output.py:organise_layers():L250 Output: organising layers
2022-06-05 11:44:23,728 DEBUG libqtile window.py:_on_unmap():L1487 Signal: layerstatic unmap
2022-06-05 11:44:23,729 DEBUG libqtile output.py:organise_layers():L250 Output: organising layers
2022-06-05 11:44:23,729 DEBUG libqtile output.py:organise_layers():L250 Output: organising layers
2022-06-05 11:44:23,730 DEBUG libqtile window.py:_on_destroy():L1221 Signal: static destroy
2022-06-05 11:44:23,731 DEBUG libqtile hook.py:fire():L396 Internal event: client_killed((Static(name='<no name>', wid=3),), {})
2022-06-05 11:44:23,801 DEBUG libqtile core.py:_on_xwayland_new_surface():L534 Signal: xwayland new_surface
2022-06-05 11:44:23,899 DEBUG libqtile core.py:_on_xwayland_new_surface():L534 Signal: xwayland new_surface
2022-06-05 11:44:23,968 DEBUG libqtile core.py:_on_xwayland_new_surface():L534 Signal: xwayland new_surface
2022-06-05 11:44:24,037 DEBUG libqtile core.py:_on_xwayland_new_surface():L534 Signal: xwayland new_surface
2022-06-05 11:44:24,043 DEBUG libqtile window.py:_on_destroy():L171 Signal: window destroy
2022-06-05 11:44:24,095 DEBUG libqtile core.py:_on_xwayland_new_surface():L534 Signal: xwayland new_surface
2022-06-05 11:44:24,095 DEBUG libqtile core.py:_on_xwayland_new_surface():L534 Signal: xwayland new_surface
2022-06-05 11:44:24,114 DEBUG libqtile core.py:_on_xwayland_new_surface():L534 Signal: xwayland new_surface
2022-06-05 11:44:24,121 DEBUG libqtile core.py:_on_xwayland_new_surface():L534 Signal: xwayland new_surface
2022-06-05 11:44:24,126 DEBUG libqtile core.py:_on_xwayland_new_surface():L534 Signal: xwayland new_surface
2022-06-05 11:44:24,182 DEBUG libqtile window.py:_on_map():L892 Signal: xwindow map
2022-06-05 11:44:24,182 DEBUG libqtile window.py:_on_map():L897 Managing new XWayland window with window ID: 3
2022-06-05 11:44:24,183 DEBUG libqtile hook.py:fire():L396 Internal event: client_new((Window(name='DesktopEditors', wid=3),), {})
2022-06-05 11:44:24,183 DEBUG libqtile hook.py:fire():L396 Internal event: group_window_add((<group.Group ('二')>, Window(name='DesktopEditors', wid=3)), {})
2022-06-05 11:44:24,183 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/home/noen/.local/lib/python3.10/site-packages/libqtile/backend/wayland/window.py", line 943, in _on_map
    self.qtile.manage(self)
  File "/home/noen/.local/lib/python3.10/site-packages/libqtile/core/manager.py", line 624, in manage
    self.current_screen.group.add(win, focus=win.can_steal_focus)
  File "/home/noen/.local/lib/python3.10/site-packages/libqtile/group.py", line 255, in add
    elif self.floating_layout.match(win) and not win.fullscreen:
  File "/home/noen/.local/lib/python3.10/site-packages/libqtile/layout/floating.py", line 114, in match
    return any(win.match(rule) for rule in self.float_rules)
  File "/home/noen/.local/lib/python3.10/site-packages/libqtile/layout/floating.py", line 114, in <genexpr>
    return any(win.match(rule) for rule in self.float_rules)
  File "/home/noen/.local/lib/python3.10/site-packages/libqtile/backend/wayland/window.py", line 459, in match
    return match.compare(self)
  File "/home/noen/.local/lib/python3.10/site-packages/libqtile/config.py", line 849, in compare
    value = client.get_wm_type()
  File "/home/noen/.local/lib/python3.10/site-packages/libqtile/backend/wayland/window.py", line 1019, in get_wm_type
    return self.core.xwayland_atoms[wm_type[0]]
KeyError: 344
2022-06-05 11:44:32,244 DEBUG libqtile interface.py:call():L310 Command: toscreen((), {'toggle': True})
2022-06-05 11:44:32,244 DEBUG libqtile window.py:_on_map():L652 Signal: xdgwindow map
2022-06-05 11:44:32,244 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:44:32,244 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='noen@none: tail -n 90 -f .local/share/qtile/qtile.log', wid=2),), {})
2022-06-05 11:44:32,244 DEBUG libqtile hook.py:fire():L396 Internal event: setgroup((), {})
2022-06-05 11:44:32,246 DEBUG libqtile hook.py:fire():L396 Internal event: focus_change((), {})
2022-06-05 11:44:32,246 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825810>, <group.Group ('一')>), {})
2022-06-05 11:44:42,260 DEBUG libqtile interface.py:call():L310 Command: toscreen((), {'toggle': True})
2022-06-05 11:44:42,261 DEBUG libqtile window.py:_on_unmap():L702 Signal: xdgwindow unmap
2022-06-05 11:44:42,262 DEBUG libqtile hook.py:fire():L396 Internal event: setgroup((), {})
2022-06-05 11:44:42,263 DEBUG libqtile hook.py:fire():L396 Internal event: focus_change((), {})
2022-06-05 11:44:42,264 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825930>, <group.Group ('二')>), {})
2022-06-05 11:44:42,772 DEBUG libqtile interface.py:call():L310 Command: next_layout((), {})
2022-06-05 11:44:42,773 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.floating.Floating object at 0x7f59cf825990>, <group.Group ('二')>), {})
2022-06-05 11:44:42,775 DEBUG libqtile window.py:_on_map():L892 Signal: xwindow map
2022-06-05 11:44:42,775 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:44:43,700 DEBUG libqtile interface.py:call():L310 Command: next_layout((), {})
2022-06-05 11:44:43,701 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825930>, <group.Group ('二')>), {})
2022-06-05 11:44:43,702 DEBUG libqtile window.py:_on_unmap():L950 Signal: xwindow unmap
2022-06-05 11:44:44,228 DEBUG libqtile interface.py:call():L310 Command: next_layout((), {})
2022-06-05 11:44:44,229 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.floating.Floating object at 0x7f59cf825990>, <group.Group ('二')>), {})
2022-06-05 11:44:44,230 DEBUG libqtile window.py:_on_map():L892 Signal: xwindow map
2022-06-05 11:44:44,231 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:44:44,660 DEBUG libqtile interface.py:call():L310 Command: next_layout((), {})
2022-06-05 11:44:44,661 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825930>, <group.Group ('二')>), {})
2022-06-05 11:44:44,662 DEBUG libqtile window.py:_on_unmap():L950 Signal: xwindow unmap
2022-06-05 11:44:45,012 DEBUG libqtile interface.py:call():L310 Command: toscreen((), {'toggle': True})
2022-06-05 11:44:45,013 DEBUG libqtile window.py:_on_map():L652 Signal: xdgwindow map
2022-06-05 11:44:45,014 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:44:45,015 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='noen@none: tail -n 90 -f .local/share/qtile/qtile.log', wid=2),), {})
2022-06-05 11:44:45,015 DEBUG libqtile hook.py:fire():L396 Internal event: setgroup((), {})
2022-06-05 11:44:45,016 DEBUG libqtile hook.py:fire():L396 Internal event: focus_change((), {})
2022-06-05 11:44:45,017 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825810>, <group.Group ('一')>), {})
2022-06-05 11:44:59,909 DEBUG libqtile interface.py:call():L310 Command: toscreen((), {'toggle': True})
2022-06-05 11:44:59,910 DEBUG libqtile window.py:_on_unmap():L702 Signal: xdgwindow unmap
2022-06-05 11:44:59,911 DEBUG libqtile hook.py:fire():L396 Internal event: setgroup((), {})
2022-06-05 11:44:59,911 DEBUG libqtile hook.py:fire():L396 Internal event: focus_change((), {})
2022-06-05 11:44:59,912 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825930>, <group.Group ('二')>), {})
2022-06-05 11:45:00,757 DEBUG libqtile interface.py:call():L310 Command: next_layout((), {})
2022-06-05 11:45:00,758 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.floating.Floating object at 0x7f59cf825990>, <group.Group ('二')>), {})
2022-06-05 11:45:00,759 DEBUG libqtile window.py:_on_map():L892 Signal: xwindow map
2022-06-05 11:45:00,760 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:45:02,005 DEBUG libqtile interface.py:call():L310 Command: next((), {})
2022-06-05 11:45:02,325 DEBUG libqtile interface.py:call():L310 Command: next((), {})
2022-06-05 11:45:02,453 DEBUG libqtile interface.py:call():L310 Command: next((), {})
2022-06-05 11:45:03,085 DEBUG libqtile hook.py:fire():L396 Internal event: client_mouse_enter((Window(name='DesktopEditors', wid=3),), {})
2022-06-05 11:45:03,086 DEBUG libqtile hook.py:fire():L396 Internal event: focus_change((), {})
2022-06-05 11:45:03,088 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='DesktopEditors', wid=3),), {})
2022-06-05 11:45:03,098 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:03,109 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:03,158 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:03,174 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:03,184 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:03,312 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:03,316 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:03,338 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:03,384 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:03,398 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:03,476 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:03,892 DEBUG libqtile interface.py:call():L310 Command: next_layout((), {})
2022-06-05 11:45:03,893 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825930>, <group.Group ('二')>), {})
2022-06-05 11:45:03,893 DEBUG libqtile window.py:_on_unmap():L950 Signal: xwindow unmap
2022-06-05 11:45:03,893 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:45:03,894 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='DesktopEditors', wid=3),), {})
2022-06-05 11:45:03,965 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:04,197 DEBUG libqtile interface.py:call():L310 Command: next_layout((), {})
2022-06-05 11:45:04,198 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.floating.Floating object at 0x7f59cf825990>, <group.Group ('二')>), {})
2022-06-05 11:45:04,199 DEBUG libqtile window.py:_on_map():L892 Signal: xwindow map
2022-06-05 11:45:04,200 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='DesktopEditors', wid=3),), {})
2022-06-05 11:45:04,390 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:04,393 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:04,526 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:04,542 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:04,576 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:04,608 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:05,140 DEBUG libqtile interface.py:call():L310 Command: next_layout((), {})
2022-06-05 11:45:05,141 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825930>, <group.Group ('二')>), {})
2022-06-05 11:45:05,142 DEBUG libqtile window.py:_on_unmap():L950 Signal: xwindow unmap
2022-06-05 11:45:05,143 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:45:05,144 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='DesktopEditors', wid=3),), {})
2022-06-05 11:45:05,209 DEBUG libqtile core.py:_on_request_cursor():L351 Signal: seat request_set_cursor_event
2022-06-05 11:45:05,396 DEBUG libqtile interface.py:call():L310 Command: next_layout((), {})
2022-06-05 11:45:05,397 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.floating.Floating object at 0x7f59cf825990>, <group.Group ('二')>), {})
2022-06-05 11:45:05,398 DEBUG libqtile window.py:_on_map():L892 Signal: xwindow map
2022-06-05 11:45:05,399 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='DesktopEditors', wid=3),), {})
2022-06-05 11:45:05,877 DEBUG libqtile interface.py:call():L310 Command: next_layout((), {})
2022-06-05 11:45:05,878 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825930>, <group.Group ('二')>), {})
2022-06-05 11:45:05,879 DEBUG libqtile window.py:_on_unmap():L950 Signal: xwindow unmap
2022-06-05 11:45:05,880 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:45:05,881 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='DesktopEditors', wid=3),), {})
2022-06-05 11:45:06,245 DEBUG libqtile interface.py:call():L310 Command: toscreen((), {'toggle': True})
2022-06-05 11:45:06,246 DEBUG libqtile window.py:_on_map():L652 Signal: xdgwindow map
2022-06-05 11:45:06,247 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:45:06,248 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='noen@none: tail -n 90 -f .local/share/qtile/qtile.log', wid=2),), {})
2022-06-05 11:45:06,249 DEBUG libqtile hook.py:fire():L396 Internal event: setgroup((), {})
2022-06-05 11:45:06,249 DEBUG libqtile hook.py:fire():L396 Internal event: focus_change((), {})
2022-06-05 11:45:06,250 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825810>, <group.Group ('一')>), {})
2022-06-05 11:45:09,781 DEBUG libqtile interface.py:call():L310 Command: toscreen((), {'toggle': True})
2022-06-05 11:45:09,782 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:45:09,783 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='DesktopEditors', wid=3),), {})
2022-06-05 11:45:09,784 DEBUG libqtile window.py:_on_unmap():L702 Signal: xdgwindow unmap
2022-06-05 11:45:09,785 DEBUG libqtile hook.py:fire():L396 Internal event: setgroup((), {})
2022-06-05 11:45:09,785 DEBUG libqtile hook.py:fire():L396 Internal event: focus_change((), {})
2022-06-05 11:45:09,786 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825930>, <group.Group ('二')>), {})
2022-06-05 11:45:10,421 DEBUG libqtile interface.py:call():L310 Command: toscreen((), {'toggle': True})
2022-06-05 11:45:10,422 DEBUG libqtile window.py:_on_map():L652 Signal: xdgwindow map
2022-06-05 11:45:10,423 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:45:10,424 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='noen@none: tail -n 90 -f .local/share/qtile/qtile.log', wid=2),), {})
2022-06-05 11:45:10,425 DEBUG libqtile hook.py:fire():L396 Internal event: setgroup((), {})
2022-06-05 11:45:10,425 DEBUG libqtile hook.py:fire():L396 Internal event: focus_change((), {})
2022-06-05 11:45:10,425 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825810>, <group.Group ('一')>), {})
2022-06-05 11:45:10,885 DEBUG libqtile interface.py:call():L310 Command: toscreen((), {'toggle': True})
2022-06-05 11:45:10,886 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:45:10,887 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='DesktopEditors', wid=3),), {})
2022-06-05 11:45:10,888 DEBUG libqtile window.py:_on_unmap():L702 Signal: xdgwindow unmap
2022-06-05 11:45:10,889 DEBUG libqtile hook.py:fire():L396 Internal event: setgroup((), {})
2022-06-05 11:45:10,890 DEBUG libqtile hook.py:fire():L396 Internal event: focus_change((), {})
2022-06-05 11:45:10,891 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825930>, <group.Group ('二')>), {})
2022-06-05 11:45:11,285 DEBUG libqtile interface.py:call():L310 Command: toscreen((), {'toggle': True})
2022-06-05 11:45:11,286 DEBUG libqtile window.py:_on_map():L652 Signal: xdgwindow map
2022-06-05 11:45:11,288 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:45:11,289 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='noen@none: tail -n 90 -f .local/share/qtile/qtile.log', wid=2),), {})
2022-06-05 11:45:11,289 DEBUG libqtile hook.py:fire():L396 Internal event: setgroup((), {})
2022-06-05 11:45:11,290 DEBUG libqtile hook.py:fire():L396 Internal event: focus_change((), {})
2022-06-05 11:45:11,291 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825810>, <group.Group ('一')>), {})
2022-06-05 11:45:11,877 DEBUG libqtile interface.py:call():L310 Command: next_layout((), {})
2022-06-05 11:45:11,878 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.floating.Floating object at 0x7f59cf825870>, <group.Group ('一')>), {})
2022-06-05 11:45:11,880 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='noen@none: tail -n 90 -f .local/share/qtile/qtile.log', wid=2),), {})
2022-06-05 11:45:12,885 DEBUG libqtile interface.py:call():L310 Command: next_layout((), {})
2022-06-05 11:45:12,886 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825810>, <group.Group ('一')>), {})
2022-06-05 11:45:12,887 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='noen@none: tail -n 90 -f .local/share/qtile/qtile.log', wid=2),), {})
2022-06-05 11:45:13,525 DEBUG libqtile interface.py:call():L310 Command: toscreen((), {'toggle': True})
2022-06-05 11:45:13,526 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:45:13,528 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='DesktopEditors', wid=3),), {})
2022-06-05 11:45:13,528 DEBUG libqtile window.py:_on_unmap():L702 Signal: xdgwindow unmap
2022-06-05 11:45:13,529 DEBUG libqtile hook.py:fire():L396 Internal event: setgroup((), {})
2022-06-05 11:45:13,530 DEBUG libqtile hook.py:fire():L396 Internal event: focus_change((), {})
2022-06-05 11:45:13,530 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825930>, <group.Group ('二')>), {})
2022-06-05 11:45:13,925 DEBUG libqtile interface.py:call():L310 Command: next_layout((), {})
2022-06-05 11:45:13,926 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.floating.Floating object at 0x7f59cf825990>, <group.Group ('二')>), {})
2022-06-05 11:45:13,927 DEBUG libqtile window.py:_on_map():L892 Signal: xwindow map
2022-06-05 11:45:13,928 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='DesktopEditors', wid=3),), {})
2022-06-05 11:45:14,726 DEBUG libqtile interface.py:call():L310 Command: kill((), {})
2022-06-05 11:45:14,832 DEBUG libqtile window.py:_on_destroy():L171 Signal: window destroy
2022-06-05 11:45:14,835 DEBUG libqtile window.py:_on_unmap():L950 Signal: xwindow unmap
2022-06-05 11:45:14,835 DEBUG libqtile hook.py:fire():L396 Internal event: client_killed((Window(name='DesktopEditors', wid=3),), {})
2022-06-05 11:45:14,835 DEBUG libqtile dgroups.py:_del():L251 Deleting <group.Group ('二')> in 1s
2022-06-05 11:45:14,837 DEBUG libqtile core.py:_on_xwayland_new_surface():L534 Signal: xwayland new_surface
2022-06-05 11:45:14,837 DEBUG libqtile window.py:_on_destroy():L171 Signal: window destroy
2022-06-05 11:45:14,837 DEBUG libqtile window.py:_on_destroy():L171 Signal: window destroy
2022-06-05 11:45:14,837 DEBUG libqtile window.py:_on_destroy():L171 Signal: window destroy
2022-06-05 11:45:14,861 DEBUG libqtile window.py:_on_destroy():L171 Signal: window destroy
2022-06-05 11:45:14,862 DEBUG libqtile window.py:_on_destroy():L171 Signal: window destroy
2022-06-05 11:45:15,173 DEBUG libqtile interface.py:call():L310 Command: toscreen((), {'toggle': True})
2022-06-05 11:45:15,174 DEBUG libqtile window.py:_on_map():L652 Signal: xdgwindow map
2022-06-05 11:45:15,175 DEBUG libqtile core.py:focus_window():L813 Focussing new window
2022-06-05 11:45:15,176 DEBUG libqtile hook.py:fire():L396 Internal event: client_focus((Window(name='noen@none: tail -n 90 -f .local/share/qtile/qtile.log', wid=2),), {})
2022-06-05 11:45:15,177 DEBUG libqtile hook.py:fire():L396 Internal event: setgroup((), {})
2022-06-05 11:45:15,179 DEBUG libqtile hook.py:fire():L396 Internal event: focus_change((), {})
2022-06-05 11:45:15,180 DEBUG libqtile hook.py:fire():L396 Internal event: layout_change((<libqtile.layout.columns.Columns object at 0x7f59cf825810>, <group.Group ('一')>), {})
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Please could you post an `xprop` of the window from X11?

**Comment by Sydiepus** [comment]
Sure.
 
```
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_MAXIMIZED_VERT
_NET_FRAME_EXTENTS(CARDINAL) = 3, 3, 3, 3
_NET_WM_DESKTOP(CARDINAL) = 0
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_ICON(CARDINAL) =
_NET_WM_ICON_NAME(UTF8_STRING) =
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) =
_NET_WM_NAME(UTF8_STRING) = "DesktopEditors"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x1000007
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
_NET_WM_PID(CARDINAL) = 15461
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 16777259
WM_CLASS(STRING) = "DesktopEditors", "DesktopEditors"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 0, 0
		user specified size: 1425 by 885
		program specified minimum size: 960 by 661
		window gravity: Static

```

**Comment by m-col** [comment]
Perfect, thanks!

**Comment by m-col** [comment]
I think I have a fix: https://github.com/qtile/qtile/pull/3612

Would you be able to test it out to confirm it fixes the issue?

**Comment by Sydiepus** [comment]
Yes, i will test it right away.

**Comment by Sydiepus** [comment]
Working!

tested all layouts working as expected.

**Comment by m-col** [comment]
Brilliant, thanks for confirming!
