### ISSUE TITLE
KeyboardLayout widget do not work with non EN layout

### ISSUE THREAD

**Issue by kafkaGen** [qtile/qtile#3640]
### The issue:

I configured KeyboardLayout widget with two languages EN and UA. It does not switch layout with **option** parameter. Also when I switch it manually no qtile shortcuts are working (unknown keysym in logs).  Later to switch layout I have configured /etc/X11/xorg.conf.d/10-keyboard.conf.

qtile version:
0.21.0

qtile config:
https://github.com/NemaOchka/instruct/blob/main/qtile/config.py

logs file:
```
2022-06-19 12:54:00,921 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 571, in wrapper
    return f(*args)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 658, in wait_for_reply
    self._process_error(error_p[0])
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 645, in _process_error
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 381, in get_property
    ).reply()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 332, in reply
    data = self.conn.wait_for_reply(self.sequence)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-06-19 12:54:00,924 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-06-19 12:54:00,925 ERROR libqtile core.py:_xpoll():L327 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 289, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-06-19 12:54:00,926 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 289, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-06-19 12:54:00,927 ERROR libqtile manager.py:_finalize_configurables():L295 exception during finalize
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 283, in _finalize_configurables
    widget.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 240, in finalize
    self.drawer.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 35, in finalize
    self._free_pixmap()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 115, in _free_pixmap
    self.qtile.core.conn.conn.core.FreePixmap(self._pixmap)
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2863, in FreePixmap
    return self.send_request(54, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-06-19 12:54:00,931 ERROR libqtile start.py:start():L94 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 92, in start
    q.loop()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 192, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 220, in async_loop
    self.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 300, in finalize
    self.core.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 165, in finalize
    self.conn.conn.core.DeletePropertyChecked(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-06-19 12:54:00,933 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-06-19 12:59:30,317 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], q)> (unknown keysym: 0x71)
2022-06-19 12:59:30,320 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], o)> (unknown keysym: 0x6f)
2022-06-19 12:59:30,320 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], o)> (unknown keysym: 0x6f)
2022-06-19 12:59:30,320 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], r)> (unknown keysym: 0x72)
2022-06-19 12:59:30,320 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], q)> (unknown keysym: 0x71)
2022-06-19 12:59:30,320 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], b)> (unknown keysym: 0x62)
2022-06-19 12:59:30,320 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], t)> (unknown keysym: 0x74)
2022-06-19 12:59:30,320 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], d)> (unknown keysym: 0x64)
2022-06-19 12:59:30,320 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], r)> (unknown keysym: 0x72)
2022-06-19 12:59:30,321 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], g)> (unknown keysym: 0x67)
2022-06-19 12:59:30,321 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod1', 'control'], r)> (unknown keysym: 0x72)
2022-06-19 12:59:30,321 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod1', 'control'], p)> (unknown keysym: 0x70)
2022-06-19 12:59:30,321 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod1', 'control'], s)> (unknown keysym: 0x73)
2022-06-19 12:59:30,321 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], j)> (unknown keysym: 0x6a)
2022-06-19 12:59:30,321 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], k)> (unknown keysym: 0x6b)
2022-06-19 12:59:30,321 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], j)> (unknown keysym: 0x6a)
2022-06-19 12:59:30,322 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], k)> (unknown keysym: 0x6b)
2022-06-19 12:59:30,322 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'control'], j)> (unknown keysym: 0x6a)
2022-06-19 12:59:30,322 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'control'], k)> (unknown keysym: 0x6b)
2022-06-19 12:59:30,322 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], h)> (unknown keysym: 0x68)
2022-06-19 12:59:30,322 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], l)> (unknown keysym: 0x6c)
2022-06-19 12:59:30,322 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], h)> (unknown keysym: 0x68)
2022-06-19 12:59:30,322 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], l)> (unknown keysym: 0x6c)
2022-06-19 12:59:30,322 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'control'], h)> (unknown keysym: 0x68)
2022-06-19 12:59:30,322 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'control'], l)> (unknown keysym: 0x6c)
2022-06-19 12:59:30,322 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], n)> (unknown keysym: 0x6e)
2022-06-19 12:59:30,323 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], m)> (unknown keysym: 0x6d)
2022-06-19 12:59:30,323 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], f)> (unknown keysym: 0x66)
2022-06-19 12:59:30,323 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], f)> (unknown keysym: 0x66)
2022-06-19 12:59:46,000 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], q)> (unknown keysym: 0x71)
2022-06-19 12:59:46,000 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], o)> (unknown keysym: 0x6f)
2022-06-19 12:59:46,000 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], o)> (unknown keysym: 0x6f)
2022-06-19 12:59:46,000 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], r)> (unknown keysym: 0x72)
2022-06-19 12:59:46,000 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], q)> (unknown keysym: 0x71)
2022-06-19 12:59:46,000 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], b)> (unknown keysym: 0x62)
2022-06-19 12:59:46,001 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], t)> (unknown keysym: 0x74)
2022-06-19 12:59:46,001 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], d)> (unknown keysym: 0x64)
2022-06-19 12:59:46,001 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], r)> (unknown keysym: 0x72)
2022-06-19 12:59:46,001 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], g)> (unknown keysym: 0x67)
2022-06-19 12:59:46,001 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod1', 'control'], r)> (unknown keysym: 0x72)
2022-06-19 12:59:46,002 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod1', 'control'], p)> (unknown keysym: 0x70)
2022-06-19 12:59:46,002 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod1', 'control'], s)> (unknown keysym: 0x73)
2022-06-19 12:59:46,002 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], j)> (unknown keysym: 0x6a)
2022-06-19 12:59:46,002 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], k)> (unknown keysym: 0x6b)
2022-06-19 12:59:46,002 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], j)> (unknown keysym: 0x6a)
2022-06-19 12:59:46,002 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], k)> (unknown keysym: 0x6b)
2022-06-19 12:59:46,002 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'control'], j)> (unknown keysym: 0x6a)
2022-06-19 12:59:46,002 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'control'], k)> (unknown keysym: 0x6b)
2022-06-19 12:59:46,002 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], h)> (unknown keysym: 0x68)
2022-06-19 12:59:46,002 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], l)> (unknown keysym: 0x6c)
2022-06-19 12:59:46,003 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], h)> (unknown keysym: 0x68)
2022-06-19 12:59:46,003 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], l)> (unknown keysym: 0x6c)
2022-06-19 12:59:46,003 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'control'], h)> (unknown keysym: 0x68)
2022-06-19 12:59:46,003 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'control'], l)> (unknown keysym: 0x6c)
2022-06-19 12:59:46,003 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], n)> (unknown keysym: 0x6e)
2022-06-19 12:59:46,003 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], m)> (unknown keysym: 0x6d)
2022-06-19 12:59:46,003 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], f)> (unknown keysym: 0x66)
2022-06-19 12:59:46,003 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], f)> (unknown keysym: 0x66)
2022-06-19 12:59:57,359 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], q)> (unknown keysym: 0x71)
2022-06-19 12:59:57,360 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], o)> (unknown keysym: 0x6f)
2022-06-19 12:59:57,360 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], o)> (unknown keysym: 0x6f)
2022-06-19 12:59:57,360 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], r)> (unknown keysym: 0x72)
2022-06-19 12:59:57,360 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], q)> (unknown keysym: 0x71)
2022-06-19 12:59:57,360 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], b)> (unknown keysym: 0x62)
2022-06-19 12:59:57,360 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], t)> (unknown keysym: 0x74)
2022-06-19 12:59:57,360 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], d)> (unknown keysym: 0x64)
2022-06-19 12:59:57,360 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], r)> (unknown keysym: 0x72)
2022-06-19 12:59:57,361 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], g)> (unknown keysym: 0x67)
2022-06-19 12:59:57,361 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod1', 'control'], r)> (unknown keysym: 0x72)
2022-06-19 12:59:57,361 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod1', 'control'], p)> (unknown keysym: 0x70)
2022-06-19 12:59:57,361 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod1', 'control'], s)> (unknown keysym: 0x73)
2022-06-19 12:59:57,361 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], j)> (unknown keysym: 0x6a)
2022-06-19 12:59:57,362 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], k)> (unknown keysym: 0x6b)
2022-06-19 12:59:57,362 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], j)> (unknown keysym: 0x6a)
2022-06-19 12:59:57,362 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], k)> (unknown keysym: 0x6b)
2022-06-19 12:59:57,362 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'control'], j)> (unknown keysym: 0x6a)
2022-06-19 12:59:57,362 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'control'], k)> (unknown keysym: 0x6b)
2022-06-19 12:59:57,362 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], h)> (unknown keysym: 0x68)
2022-06-19 12:59:57,362 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], l)> (unknown keysym: 0x6c)
2022-06-19 12:59:57,362 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], h)> (unknown keysym: 0x68)
2022-06-19 12:59:57,362 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], l)> (unknown keysym: 0x6c)
2022-06-19 12:59:57,362 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'control'], h)> (unknown keysym: 0x68)
2022-06-19 12:59:57,363 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'control'], l)> (unknown keysym: 0x6c)
2022-06-19 12:59:57,363 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], n)> (unknown keysym: 0x6e)
2022-06-19 12:59:57,363 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], m)> (unknown keysym: 0x6d)
2022-06-19 12:59:57,363 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4', 'shift'], f)> (unknown keysym: 0x66)
2022-06-19 12:59:57,363 WARNING libqtile core.py:grab_key():L458 Can't grab <Key (['mod4'], f)> (unknown keysym: 0x66)
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by refaelsh** [comment]
+1

**Comment by elParaguayo** [comment]
I wouldn't mind @m-col weighing in here as I'm not an expert when it comes to the lower level keybinding. However, my understanding is that we need to be able to bind keycodes as keysyms change depending on the layout.

**Comment by elParaguayo** [comment]
Don't think this is resolved. Would still be good to get @m-col's opinion.
