### ISSUE TITLE
start slows down

### ISSUE THREAD

**Issue by navik61** [qtile/qtile#3673]
### The issue:

qtile ver. 0.21.0
log
2022-07-03 23:06:23,215 ERROR libqtile core.py:_xpoll():L335 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 303, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 701, in handle_DestroyNotify
    if self.qtile.current_window is None:
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 569, in current_window
    return self.current_screen.group.current_window
AttributeError: 'Qtile' object has no attribute 'current_screen'022-07-03 23:06:23,215 ERROR libqtile core.py:_xpoll():L335 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 303, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 701, in handle_DestroyNotify
    if self.qtile.current_window is None:
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 569, in current_window
    return self.current_screen.group.current_window
AttributeError: 'Qtile' object has no attribute 'current_screen'

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
@navik61 to add to m-col's comment: your log extract doesn't really tell us much. It would be good to know:
- When does this issue arise? You mention "start" but can you be clearer?
- What are the symptoms? "slow down" doesn't tell us much.
- Does this happen every time?
- What does your config look like?
- Does the issue arise with the default config?

**Comment by navik61** [comment]
PS: it is the same with the default configuration
