### ISSUE TITLE
[Wayland] Qtile wayland not launch

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#3683]
### The issue:

qtile -v
0.21.1.dev75+g6620786f

When I want to start qtile with the command start -b wayland it gives me the following error
````MESA-LOADER: failed to open radeonsi: /usr/lib64/dri/radeonsi_dri.so: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: radeonsi
MESA-LOADER: failed to open kms_swrast: /usr/lib64/dri/kms_swrast_dri.so: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio (search paths /usr/lib64/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio (search paths /usr/lib64/dri, suffix _dri)
failed to load swrast driver
00:00:00.019 [render/allocator/gbm.c:198] gbm_create_device failed
00:00:00.019 [render/allocator/allocator.c:134] Failed to create allocator
Traceback (most recent call last):
  File "/usr/local/bin/qtile", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/libqtile/scripts/main.py", line 66, in main
    options.func(options)
  File "/usr/local/lib/python3.10/dist-packages/libqtile/scripts/start.py", line 88, in start
    q = make_qtile(options)
  File "/usr/local/lib/python3.10/dist-packages/libqtile/scripts/start.py", line 51, in make_qtile
    kore = libqtile.backend.get_core(options.backend)
  File "/usr/local/lib/python3.10/dist-packages/libqtile/backend/__init__.py", line 15, in get_core
    return importlib.import_module(f"libqtile.backend.{backend}.core").Core(*args)
  File "/usr/local/lib/python3.10/dist-packages/libqtile/backend/wayland/core.py", line 119, in __init__
    ) = wlroots_helper.build_compositor(self.display)
  File "/usr/local/lib/python3.10/dist-packages/wlroots/helper.py", line 30, in build_compositor
    allocator = Allocator.autocreate(backend, renderer)
  File "/usr/local/lib/python3.10/dist-packages/wlroots/allocator.py", line 25, in autocreate
    raise RuntimeError("Unable to create an allocator.")
RuntimeError: Unable to create an allocator.
````

Looking for bugs in this comment https://github.com/qtile/qtile/issues/3654#issuecomment-1173020406 told me to try this command

`pipx inject --pip-args "--no-binary :all: --no-cache-dir" qtile pywlroots
`

with which I was able to get qtile working on wayland, but pipx installs version 0.21.0 not the dev version.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by cr1ogen** [comment]
> This seems to be a dependency issue in Debian?
> 
> I assume at some point you ran `pipx install [...] qtile`? Looking in the pipx user manual, you can track the master version instead: `pipx install [...] git+https://github.com/qtile/qtile.git`

Maybe it's a dependency problem, as you say.  Right now I'm on the road, next weekend when I get back I'm going to try your Pipx advice.  Thank you very much

**Comment by cr1ogen** [comment]
I had to copy and paste the wlroots and pywlroots folder from the Qtile installation I made with pipx ```pipx inject --pip-args "--no-binary :all: --no-cache-dir" qtile pywlroots```  into the qtile-git installation folder using ```pip install .``` and so that no error and start qtile wayland

**Comment by cr1ogen** [comment]
I opened the issue again in case someone knows why it can happen.  Thank you

**Comment by cr1ogen** [comment]
It seems to be a problem with wlroots, because on a fresh install I just replaced the wlroots folder from the pipx install and it worked.

**Comment by 3nprob** [comment]
What is your problem now, exactly?

**Comment by cr1ogen** [comment]
> What is your problem now, exactly?

The problem was with the first comment. Actually the problem still exists if I install qtile from the repository with pip. If I do the steps I did in the fourth comment, I don't have the error

**Comment by 3nprob** [comment]
So how did try my advice to `pipx install` from master instead? You shouldn't need to d oeither the inject or the copy, really.

**Comment by m-col** [comment]
Is this the same issue as described here?: https://github.com/qtile/qtile/issues/3756#issuecomment-1250114832

**Comment by jwijenbergh** [comment]
Closing due to inactivity and the fact that this doesn't seem like a qtile issue
