### ISSUE TITLE
Unable to switch workspaces after using KeyChord

### ISSUE THREAD

**Issue by kelvinvj111** [qtile/qtile#3734]
# The issue:
After using a KeyChord, I am unable to switch workspaces (modkey + 1...9) unless I click on them on the bar or restart qtile. 

- Qtile version: 0.21.0
- Distro: EndeavourOS
- Link to config: https://github.com/kelvinvj111/qtile-config/blob/main/config.py
### Logs: 
```
2022-08-01 00:09:52,477 ERROR libqtile hook.py:fire():L391 Error in hook setgroup
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 389, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 138, in <lambda>
    libqtile.hook.subscribe.setgroup(lambda: self.key_binder(self))
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 43, in func
    dgroup.qtile.ungrab_key(key)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 414, in ungrab_key
    self.keys_map.pop((keysym, mask_key))
KeyError: (49, 64)
2022-08-01 00:09:59,001 ERROR libqtile hook.py:fire():L391 Error in hook setgroup
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 389, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 138, in <lambda>
    libqtile.hook.subscribe.setgroup(lambda: self.key_binder(self))
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 43, in func
    dgroup.qtile.ungrab_key(key)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 414, in ungrab_key
    self.keys_map.pop((keysym, mask_key))
KeyError: (49, 64)
2022-08-01 00:09:59,481 ERROR libqtile hook.py:fire():L391 Error in hook setgroup
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 389, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 138, in <lambda>
    libqtile.hook.subscribe.setgroup(lambda: self.key_binder(self))
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 43, in func
    dgroup.qtile.ungrab_key(key)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 414, in ungrab_key
    self.keys_map.pop((keysym, mask_key))
KeyError: (49, 64)
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I can't recreate this. If I execute a `KeyChord` I can switch groups afterwards.

One question: what do you mean by `after using a KeyChord`? As per your config, `mod+p` starts the KeyChord. If you try to switch groups at that point, it won't work. You'll need to press `escape` to exit the KeyChord. However, if you press `i`, your networkmanager_dmenu script should run, at which point switching groups should work.

**Comment by kelvinvj111** [comment]
By `after using a KeyChord`, I mean pressing `mod+p` and then press `i` to run networkmanager_dmenu, which works (i.e. the networkmanager_dmenu script does run). In my case however, switching groups does not work after running the networkmanager_dmenu script. 

I found a thread on the qtile subreddit that described the same issue I was having. According to the poster, the issue seems to be with `dgroups` and posted a solution that worked. 

I removed two lines: 
```
from libqtile.dgroups import simple_key_binder
dgroups_key_binder = simple_key_binder(mod)
```

and added this instead (tiny change for ScratchPad):
```
for i in groups[:-1]:
    keys.extend([
        Key([mod], i.name,
            lazy.group[i.name].toscreen(),
            desc="Switch to group {}".format(i.name)),
        Key([mod], "Right",
            lazy.screen.next_group(),
            desc="Switch to next group"),
        Key([mod], "Left",
            lazy.screen.prev_group(),
            desc="Switch to previous group"),
        Key([mod, "shift"], i.name,
            lazy.window.togroup(i.name, switch_group=True),
            desc="Switch to & move focused window to group {}".format(i.name)),
    ])
```
This works for me and the behavior is as you described.

Reddit thread referenced: https://www.reddit.com/r/qtile/comments/r2nwmg/keychord_binding/
