### ISSUE TITLE
WL: Mouse capture not released

### ISSUE THREAD

**Issue by 3nprob** [qtile/qtile#3776]
### The issue:

When running a graphical VM trough qemu with [spicy](https://www.spice-space.org/), the mouse is captured inside the VM viewer and can not be moved outside the bounds of its window. This part works as expected in qtile.

Pressing a key combination (in my case Ctrl+Alt+G) inside the WM is supposed to release the cursor. This does not work. Even after the VM has been gracefully terminated and all related processes are confirmed dead, the cursor is stuck inside the region that was previously occupied by the window.

`reload_config()` in qtile shell or sending `USR1` to the qtile process has no effect.

Qtile version  `c8d3aad10ecdc9ce3837011f8efdb38787604695` on Linux (Wayland)

Errors seen in logs:

```
2022-08-20 09:32:51,512 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/window.py", line 947, in _on_destroy
    self.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/window.py", line 937, in finalize
    self.disable()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/window.py", line 974, in disable
    if self.wlr_constraint.current.committed & PointerConstraintV1StateField.CURSOR_HINT:
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/pointer_constraints_v1.py", line 95, in committed
    return PointerConstraintV1StateField(self._ptr.committed)
  File "/usr/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 3 is not a valid PointerConstraintV1StateField
2022-08-20 09:32:51,690 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/core.py", line 467, in _on_new_pointer_constraint
    self.active_pointer_constraint.disable()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/window.py", line 974, in disable
    if self.wlr_constraint.current.committed & PointerConstraintV1StateField.CURSOR_HINT:
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/pointer_constraints_v1.py", line 95, in committed
    return PointerConstraintV1StateField(self._ptr.committed)
  File "/usr/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 3 is not a valid PointerConstraintV1StateField
2022-08-20 09:32:51,760 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/core.py", line 467, in _on_new_pointer_constraint
    self.active_pointer_constraint.disable()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/window.py", line 974, in disable
    if self.wlr_constraint.current.committed & PointerConstraintV1StateField.CURSOR_HINT:
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/pointer_constraints_v1.py", line 95, in committed
    return PointerConstraintV1StateField(self._ptr.committed)
  File "/usr/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 0 is not a valid PointerConstraintV1StateField
[...]
# REPEATS
[...]
2022-08-20 09:32:52,165 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/core.py", line 467, in _on_new_pointer_constraint
    self.active_pointer_constraint.disable()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/window.py", line 974, in disable
    if self.wlr_constraint.current.committed & PointerConstraintV1StateField.CURSOR_HINT:
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/pointer_constraints_v1.py", line 95, in committed
    return PointerConstraintV1StateField(self._ptr.committed)
  File "/usr/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 0 is not a valid PointerConstraintV1StateField
2022-08-20 09:34:11,736 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/xwindow.py", line 136, in _on_unmap
    self.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/window.py", line 130, in finalize
    self.core.remove_pointer_constraints(self)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/core.py", line 1072, in remove_pointer_constraints
    pc.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/window.py", line 937, in finalize
    self.disable()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/window.py", line 974, in disable
    if self.wlr_constraint.current.committed & PointerConstraintV1StateField.CURSOR_HINT:
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/pointer_constraints_v1.py", line 95, in committed
    return PointerConstraintV1StateField(self._ptr.committed)
  File "/usr/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 0 is not a valid PointerConstraintV1StateField
```

Similar errors appeared in #3575

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by 3nprob** [comment]
Funny fact: I can move the confined are to other parts of the viewport by moving around the screen position in `wldisplays` :upside_down_face:

**Comment by m-col** [comment]
Please could you test https://github.com/flacjacket/pywlroots/pull/99 and see if that fixes it?

**Comment by 3nprob** [comment]
> Please could you test [flacjacket/pywlroots#99](https://github.com/flacjacket/pywlroots/pull/99) and see if that fixes it?

Thanks a bunch! Will have to wait a bit for that but will do and report back there

**Comment by m-col** [comment]
I'm confident that the linked pywlroots PR fixed this, and indeed the `disable` function inside your pasted log output won't raise an error, e.g.:
```py
>>> from wlroots.wlr_types.pointer_constraints_v1 import PointerConstraintV1StateField
>>> 0 & PointerConstraintV1StateField.CURSOR_HINT
<PointerConstraintV1StateField.0: 0>
```
so I'm going to close this. Please feel free to re-open if I'm mistaken :)
