### ISSUE TITLE
window.group is NoneType

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#3786]
### The issue:

```console
$ qtile -v
0.21.1.dev91+g5e54027e
```

> hook
```py
@hook.subscribe.client_new
def _resize_and_move(client):
    try:
        wm_class = client.window.get_wm_class()[0]
    except Exception:
        wm_class = None
    if wm_class == "gsimplecal":
        client.cmd_enable_floating()
        client.cmd_set_position_floating(x=2395, y=7)
    if wm_class == "qtilekeys":
        client.cmd_enable_fullscreen()
```

> qtile.log
```py
2022-08-22 02:18:06,144 ERROR libqtile hook.py:fire():L406 Error in hook client_new
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 404, in fire
    i(*args, **kwargs)
  File "/home/ervin/.config/qtile-x11/modules/hooks.py", line 56, in _resize_and_move
    client.cmd_enable_fullscreen()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1844, in cmd_enable_fullscreen
    self.fullscreen = True
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1367, in fullscreen
    screen = self.group.screen or self.qtile.find_closest_screen(self.x, self.y)
AttributeError: 'NoneType' object has no attribute 'screen'
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I suspect the problem here is that, as you're using the `client_new` hook, the window hasn't been allocated to a group yet.

So, you can either use the `client_managed` hook (but this will tile the window first, I think) or you can set the window's group in your hook before calling `client.cmd_enable_fullscreen()` e.g.
``` python
    if wm_class == "qtilekeys":
        client.group = qtile.current_group
        client.cmd_enable_fullscreen()
```

Untested, but it might work!
