### ISSUE TITLE
Starting Pycharm (SNAP)

### ISSUE THREAD

**Issue by sehHeiden** [qtile/qtile#3797]
### The issue:

I want to start pycharm-community on qtile. It opens. I see the starting window. Than a grey window opens. This probably the main window and that its. In the bar I can see the description of the name of the window opened. But I can not see anything in the window nor do anything in it.
PCharm works in normal in KDE Plasma on the same machine.

Qtile Version in use: 0.21.1.dev87+g2ecbb5fd
Pycharm seams to be installed by snap.
Python version: 3.8.12

The last error messages and warnings (some are to other issues) are:

```
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-08-27 11:23:11,382 ERROR libqtile core.py:get_interesting_pid():L815 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/libqtile/backend/x11/core.py", line 813, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-08-27 11:23:11,384 ERROR libqtile start.py:start():L92 Qtile crashed
Traceback (most recent call last):
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/libqtile/scripts/start.py", line 90, in start
    q.loop()
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/libqtile/core/manager.py", line 197, in loop
    asyncio.run(self.async_loop())
  File "/home/sebastian/anaconda3/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/sebastian/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/libqtile/core/manager.py", line 225, in async_loop
    self.finalize()
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/libqtile/core/manager.py", line 305, in finalize
    self.core.finalize()
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/libqtile/backend/x11/core.py", line 170, in finalize
    self.conn.conn.core.DeletePropertyChecked(
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/home/sebastian/anaconda3/lib/python3.8/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-08-27 11:23:11,388 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-08-27 11:23:44,547 WARNING libqtile mpris2widget.py:__init__():L112 The use of 'stop_pause_text' is deprecated. Please use 'paused_text' and 'stopped_text' instead.
2022-08-27 11:23:44,369 WARNING libqtile base.py:_configure():L504 mpris2: You must specify a width when enabling scrolling.
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by m-col** [comment]
Yeah we've had similar problems with jetbrains: https://github.com/qtile/qtile/issues/3657, https://github.com/qtile/qtile/issues/2172, https://github.com/qtile/qtile/issues/1641, https://github.com/qtile/qtile/issues/1548

A couple of potential fixes from those are:
- setting `wmname = "LG3D"` in your config
- setting `_JAVA_AWT_WM_NONREPARENTING=1` in the environment (see https://github.com/qtile/qtile/issues/1641#issuecomment-616100733)

**Comment by Meresmata** [comment]
I uninstalled my snap version and installed flatpak... which fixed it for me.
