### ISSUE TITLE
Error on latest git version

### ISSUE THREAD

**Issue by mrchainman** [qtile/qtile#3832]
### The issue:

If i try to start qtile i get the following:
``` 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qtile-0.21.1.dev106+g5161618c.d20220914-py3.10-linux-x86_64.egg/libqtile/confreader.py", line 97, in update
    value = settings[key]
KeyError: 'mouse'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/qtile", line 33, in <module>
    sys.exit(load_entry_point('qtile==0.21.1.dev106+g5161618c.d20220914', 'console_scripts', 'qtile')())
  File "/usr/lib/python3.10/site-packages/qtile-0.21.1.dev106+g5161618c.d20220914-py3.10-linux-x86_64.egg/libqtile/scripts/main.py", line 66, in main
    options.func(options)
  File "/usr/lib/python3.10/site-packages/qtile-0.21.1.dev106+g5161618c.d20220914-py3.10-linux-x86_64.egg/libqtile/scripts/start.py", line 86, in start
    q = make_qtile(options)
  File "/usr/lib/python3.10/site-packages/qtile-0.21.1.dev106+g5161618c.d20220914-py3.10-linux-x86_64.egg/libqtile/scripts/start.py", line 64, in make_qtile
    config = confreader.Config(options.configfile)
  File "/usr/lib/python3.10/site-packages/qtile-0.21.1.dev106+g5161618c.d20220914-py3.10-linux-x86_64.egg/libqtile/confreader.py", line 86, in __init__
    self.update(**settings)
  File "/usr/lib/python3.10/site-packages/qtile-0.21.1.dev106+g5161618c.d20220914-py3.10-linux-x86_64.egg/libqtile/confreader.py", line 99, in update
    value = getattr(self, key, default[key])
KeyError: 'mouse'
```

It doesn't say where exactly it gets 'mouse' from, the only occurence I find is in my config file for mouse configuration:
``` python
# Drag floating layouts.
mouse = [
    Drag(
        [mod],
        "Button1",
        lazy.window.set_position_floating(),
        start=lazy.window.get_position(),
    ),
    Drag(
        [mod], "Button3", lazy.window.set_size_floating(), start=lazy.window.get_size()
    ),
    Click([mod], "Button2", lazy.window.bring_to_front()),
]
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Do you get the same error with the default config? If not, can you share your full config?

**Comment by mrchainman** [comment]
It works with the default config...
That's a little tricky haha.
Basically what i wanna do is package my own version of qtile with my config set as default, so what I did was clone the repo, got to libqtile/resources and put in my configs (you can find them here https://github.com/mrchainman/chainos-qtile-config/tree/integrated)
Maybe I messed something up in the process?

**Comment by mrchainman** [comment]
BTW, if I run my config (without the libqtile.resources) imports by leaving the config under /etc and using qtile start -c it works...

**Comment by elParaguayo** [comment]
If you just put `mouse = []` in your default_config.py file, does the issue go away?

**Comment by mrchainman** [comment]
Than it complaints about the Key error extension_defaults, could it be that my custom imports collide with some qtile internal ones?

**Comment by elParaguayo** [comment]
Are you overriding the actual default_config?

**Comment by mrchainman** [comment]
Awesome got it working.
So 2 things where missing:
I needed to explicitly import the above in the default_config.py and (I am dumb xD) I was missing wl_input_rules

Thanks for the help :D
Maybe the list you posted should be added to the FAQ?

**Comment by elParaguayo** [comment]
Glad it's working.

What happens is that, when a config file is loaded, any missing variables are filled with the values from the default config. If you don't touch that file, you should be ok.

I don't think we expected anyone to override the default_config file!

**Comment by mrchainman** [comment]
Alright got it, yeah it seams to be a real edge case, but good to know! Thanks
