### ISSUE TITLE
Screen seems to be drawn behind background while using 2 monitors 0.21.0

### ISSUE THREAD

**Issue by DevArctic** [qtile/qtile#3840]
### The issue:

I switched my username and home directory today and everything mostly went OK, but qtile seems to have broken with my two monitors. Before the migration I had everything working exactly how I wanted and now qtile seems to draw the bar and all the windows behind the background of the laptop screen. The external monitor works as expected. 

I start qtile with SDDM and when I start without the external monitor connected, the laptop screen works fine, the bar shows up and everything. When I start with the two connected, the background shows on the laptop screen but the bar doesn't. But I can still click the groups in the lower left hand corner like normal, I just can't see anything. Windows don't show up either. Only the mouse cursor. If I drag a window from the top, where my external monitor is located, they go down but don't appear on the laptop screen.

I know it must have something to do with the username change but I can't for the life of me figure it out. 

Here's my config.py, which is valid, for the two screens.

```
`screens = [
    Screen(
        bottom=bar.Bar(
            [
        #highlight_method='line',highlight_color=["#011704,#185722"]
                widget.CurrentLayoutIcon(scale=0.5),
                widget.GroupBox(font='Font Awesome 6 Free',highlight_method='line',this_current_screen_border='#1c7678',this_screen_border='#0c3536',disable_drag='True'),
                widget.Prompt(),
                widget.WindowName(),
                widget.WidgetBox(
                    text_closed="",
                    text_open=" ",
                    widgets=[
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn('firefox')}
                                    ),
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn('gedit')}
                                    ),
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn('thunar')}
                                    ),
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn('transmission-gtk')}
                                    ),
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn('gthumb')}
                                    ),
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn('keepassxc')}
                                    ),
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn(['sh','-c','steam'])}
                                    ),
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn(['multimc'])}
                                    ),
                    	widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn('sudo iwgtk')}
                                    )                                        

                ]),    
                widget.TextBox(text='  |  '),
                widget.Battery(unknown_char="",charge_char="",discharge_char="",empty_char='',full_char='',format='{percent:2.0%}'),                     
                widget.TextBox(text='  |  '),
                widget.Clock(format='%B %d, %Y %I:%M %p'),
                widget.TextBox(text='  |  '),
                widget.QuickExit(default_text='[  ]', countdown_format='[ {} ]'),
                widget.TextBox(text='   '),
            ],
            32,
            background="#00000000",
            # border_width=[2, 0, 2, 0],  # Draw top and bottom borders
            # border_color=["ff00ff", "000000", "ff00ff", "000000"]  # Borders are magenta
        ),

    ),
    Screen(
        bottom=bar.Bar(
            [
        #highlight_method='line',highlight_color=["#011704,#185722"]
                widget.CurrentLayoutIcon(scale=0.5),
                widget.GroupBox(font='Font Awesome 6 Free',highlight_method='line',this_current_screen_border='#1c7678',this_screen_border='#0c3536',disable_drag='True'),
                widget.Prompt(),
                widget.WindowName(),
                widget.WidgetBox(
                    text_closed="",
                    text_open=" ",
                    widgets=[
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn('firefox')}
                                    ),
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn('gedit')}
                                    ),
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn('thunar')}
                                    ),
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn('transmission-gtk')}
                                    ),
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn('gthumb')}
                                    ),
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn('keepassxc')}
                                    ),
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn(['sh','-c','steam'])}
                                    ),
                        widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn(['multimc'])}
                                    ),
                    	widget.TextBox(text='',
                                mouse_callbacks={
                                    'Button1': lazy.spawn('sudo iwgtk')}
                                    )                                        

                ]),    
                widget.TextBox(text='  |  '),
                widget.Battery(unknown_char="",charge_char="",discharge_char="",empty_char='',full_char='',format='{percent:2.0%}'),                     
                widget.TextBox(text='  |  '),
                widget.Clock(format='%B %d, %Y %I:%M %p'),
                widget.TextBox(text='  |  '),
                widget.QuickExit(default_text='[  ]', countdown_format='[ {} ]'),
                widget.TextBox(text='   '),
            ],
            32,
            background="#00000000",
            # border_width=[2, 0, 2, 0],  # Draw top and bottom borders
            # border_color=["ff00ff", "000000", "ff00ff", "000000"]  # Borders are magenta
        ),

    )
]`

```
Here's the logs from the past hour or two:
```

`pipe and other stream errors.
2022-09-17 02:47:10,416 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-09-17 02:50:21,515 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-09-17 02:52:21,258 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-09-17 03:01:37,760 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-09-17 03:11:03,794 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-09-17 03:14:35,754 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-09-17 03:21:46,448 ERROR libqtile core.py:_xpoll():L335 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 303, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1151, in handle_KeyPress
    self.process_key_press(keysym)
  File "/usr/lib/python3.10/site-packages/libqtile/bar.py", line 524, in process_key_press
    if self.has_keyboard:
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: Bar has no attribute: has_keyboard
2022-09-17 03:21:55,842 ERROR libqtile core.py:_xpoll():L335 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 303, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1151, in handle_KeyPress
    self.process_key_press(keysym)
  File "/usr/lib/python3.10/site-packages/libqtile/bar.py", line 524, in process_key_press
    if self.has_keyboard:
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: Bar has no attribute: has_keyboard
2022-09-17 03:22:02,775 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-09-17 03:27:13,714 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-09-17 03:31:21,008 ERROR libqtile loop.py:_handle_exception():L63 xcb connection errors because of socket, pipe and other stream errors.
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 846, in f
    self.core.flush()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 797, in flush
    self.conn.flush()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/xcbq.py", line 645, in flush
    return self.conn.flush()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 573, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-09-17 03:31:21,011 ERROR libqtile core.py:_xpoll():L327 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 289, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-09-17 03:31:21,011 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 289, in _xpoll
    event = self.conn.conn.poll_for_event()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-09-17 03:31:21,013 ERROR libqtile loop.py:_handle_exception():L63 xcb connection errors because of socket, pipe and other stream errors.
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 864, in f
    self.core.flush()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 797, in flush
    self.conn.flush()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/xcbq.py", line 645, in flush
    return self.conn.flush()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-09-17 03:31:21,013 ERROR libqtile loop.py:_handle_exception():L63 xcb connection errors because of socket, pipe and other stream errors.
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 864, in f
    self.core.flush()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 797, in flush
    self.conn.flush()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/xcbq.py", line 645, in flush
    return self.conn.flush()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-09-17 03:31:21,014 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-09-17 03:31:21,014 ERROR libqtile core.py:get_interesting_pid():L810 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 808, in get_interesting_pid
    return win.window.get_net_wm_pid()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2720, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-09-17 03:31:21,015 ERROR libqtile manager.py:_finalize_configurables():L295 exception during finalize
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 283, in _finalize_configurables
    widget.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 240, in finalize
    self.drawer.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 35, in finalize
    self._free_pixmap()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/drawer.py", line 115, in _free_pixmap
    self.qtile.core.conn.conn.core.FreePixmap(self._pixmap)
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2863, in FreePixmap
    return self.send_request(54, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-09-17 03:31:21,017 ERROR libqtile start.py:start():L94 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 92, in start
    q.loop()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 192, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 220, in async_loop
    self.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 300, in finalize
    self.core.finalize()
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 165, in finalize
    self.conn.conn.core.DeletePropertyChecked(
  File "/usr/lib/python3.10/site-packages/xcffib/xproto.py", line 2716, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 391, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.10/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2022-09-17 03:31:21,019 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-09-17 03:36:17,202 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-09-17 03:48:06,519 ERROR libqtile core.py:__init__():L103 not starting; existing window manager LG3D
2022-09-17 03:48:08,074 ERROR libqtile core.py:__init__():L103 not starting; existing window manager LG3D
2022-09-17 03:48:57,605 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-09-17 04:07:05,265 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate`
```

I tried reinstalling with sudo pacman -S qtile but no luck.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by DevArctic** [comment]
I just tried using the default config, and disabled feh, and the laptop screen just shows up black. The top screen shows up grey. I don't see anything, but I can log out by clicking the lower right of the laptop screen. I can open terminals up on the grey external monitor. So it seems qtile is running just fine, it's just not rendering correctly. 

I also have KDE Plasma installed, and that runs without a hitch between the two screens. Granted, I haven't configured it at all. I'd really like to get back to using qtile though. I really like it.

**Comment by m-col** [comment]
Would you be able to test with git version? One of earliest logged errors `AttributeError: Bar has no attribute: has_keyboard` looks like it shouldn't happen in the git version, so if all the other errors snowballed from that one then it might be fixed.

**Comment by DevArctic** [comment]
I replaced qtile with qtile-git but it's still the same. Grey on external monitor, black on laptop. But functional.

**Comment by DevArctic** [comment]
I created a new user, started qtile, and it works. I ported my config over to the new profile, it works. I changed the old users name to 'broken' and ported the name 'arctic' over to the new user. It works. So....... 

I must have done something wrong creating that particular user. I've got it saved as broken, so if you want me to fuck around with it just to see what's wrong with it, I'm willing to do that, but it's essentially fixed.

**Comment by elParaguayo** [comment]
I'm inclined to close this as it doesn't really sound like a qtile issue.

**Comment by DevArctic** [comment]
It's some kind of confusion between sddm, X11 and qtile. When I put the xrandr command in xsession to set up two screens, it results in the behavior. If I comment it out and run, the two monitors render correctly as one screen. Then I manually put in xrandr, and it updates fine. There must be something that needs to be set up and it's running xrandr too early.
