### ISSUE TITLE
AttributeError: 'str' object has no attribute 'check'

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#3871]
### The issue:

```console
$ qtile -v
0.22.2.dev5+g419e3418
```
Why is the version 0.22.2.blabla tho? :) Shouldn't it be 0.22.1.dev5+g419e3418?

```
2022-10-02 12:37:58,092 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 616, in handle_KeyPress
    self.qtile.process_key_event(keysym, event.state & self._valid_mask)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 402, in process_key_event
    if cmd.check(self):
AttributeError: 'str' object has no attribute 'check'
```
This happens with every keybinding as far as I can tell.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Can you paste your config? My guess is that you've got a keybinding where you've added a description but didn't make this a keyword argument with `desc=`.

**Comment by ervinpopescu** [comment]
Ah, you're right. I've deleted the `desc=`, having not known this is needed.
