### ISSUE TITLE
layout.Tile border_focus gives NameError if modified

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile#394]
When setting `layout.Tile` with `border_focus` argument, i.e. with:
```python
layout.Tile(ratio=0.5, border_focus="ffffff") 
```
Qtile crashes and says:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/libqtile/manager.py", line 585, in _xpoll
    r = h(e)
  File "/usr/lib/python2.7/dist-packages/libqtile/manager.py", line 892, in handle_UnmapNotify
    self.unmanage(e.window)
  File "/usr/lib/python2.7/dist-packages/libqtile/manager.py", line 406, in unmanage
    c.group.remove(c)
  File "/usr/lib/python2.7/dist-packages/libqtile/group.py", line 215, in remove
    self.focus(nextfocus, True)
  File "/usr/lib/python2.7/dist-packages/libqtile/group.py", line 156, in focus
    l.focus(win)
  File "/usr/lib/python2.7/dist-packages/libqtile/layout/max.py", line 46, in focus
    self.group.layoutAll()
  File "/usr/lib/python2.7/dist-packages/libqtile/group.py", line 92, in layoutAll
    self.layout.layout(normal, screen)
  File "/usr/lib/python2.7/dist-packages/libqtile/layout/base.py", line 54, in layout
    self.configure(i, screen)
  File "/usr/lib/python2.7/dist-packages/libqtile/layout/tile.py", line 189, in configure
    bc = self.group.qtile.colorPixel(self.border_focus)
  File "/usr/lib/python2.7/dist-packages/libqtile/utils.py", line 99, in wrap
    ret = f(self, *args)
  File "/usr/lib/python2.7/dist-packages/libqtile/manager.py", line 364, in colorPixel
    return self.conn.screens[0].default_colormap.alloc_color(name).pixel
  File "/usr/lib/python2.7/dist-packages/libqtile/xcbq.py", line 288, in alloc_color
    self.cid, len(color), color
BadName: <xcb.xproto.NameError object at 0x319c908>
```

**Comment by aniruddhkanojia** [comment]
The [documentation](http://docs.qtile.org/en/latest/manual/ref/layouts.html#libqtile.layout.tile.Tile) shows that a '#' character should prefix the hex code.If the string does not start with '#'  it considers it as a named color like 'blue' or 'black'.
Hence this exception.

We could modify [this] (https://github.com/qtile/qtile/blob/develop/libqtile/xcbq.py#L310) to accomodate for hex codes without '#'.

**Comment by kynikos** [comment]
Wouldn't it be cleaner to follow Python's EAFP philosophy and `try` `AllocNamedColor` first, and in case `BadName` is raised do the `AllocColor` block, also using negative indices to extract the `color` bits so you don't have to worry about the initial `#`?

**Comment by aniruddhkanojia** [comment]
I guess you are right.
Will get on that asap.
