### ISSUE TITLE
PulseVolume widget raised KeyError when specifying theme_path

### ISSUE THREAD

**Issue by johann2357** [qtile/qtile#4039]
### The issue:

I wanted to do use `PulseVolume` widget specifying the `theme_path`, but a `KeyError` exception happened, and I expected that the icons were displayed correctly. I think this is a bug.

- `qtile --version` -> `0.22.1`
- Relevant logs:
```
2022-12-06 02:43:41,917 ERROR libqtile loop.py:_handle_exception():L63 'audio-volume-muted'
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 862, in f
    func(*args)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/pulse_volume.py", line 245, in timer_setup
    self.poll()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/pulse_volume.py", line 218, in poll
    self.update()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/pulse_volume.py", line 230, in update
    self._update_drawer()
  File "/usr/lib/python3.10/site-packages/libqtile/widget/volume.py", line 147, in _update_drawer
    self.drawer.ctx.set_source(self.surfaces[img_name])
KeyError: 'audio-volume-muted'
```
- Part of config:
```python
                widget.PulseVolume(
                    get_volume_command="pamixer --get-volume-human",
                    volume_app="pamixer",
                    theme_path="/usr/share/icons/Papirus/24x24/panel/",
                ),
```

- Possible problem:
    - Looks like widget tried to draw the icons before loading them.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by johann2357** [comment]
PR with the fix was merged :smiley:
