### ISSUE TITLE
Battery plugin error on Freebsd

### ISSUE THREAD

**Issue by kobzarchekg** [qtile/qtile#4087]
### The issue:

When i try to use Battery widget on Freebsd 13.1 ive got the error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/libqtile/core/manager.py", line 113, in load_config
    self.config.load()
  File "/usr/local/lib/python3.9/site-packages/libqtile/confreader.py", line 110, in load
    config = importlib.import_module(name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/kobzar/.config/qtile/config.py", line 282, in <module>
    widget.Battery(
  File "/usr/local/lib/python3.9/site-packages/libqtile/widget/battery.py", line 335, in __init__
    self._battery = self._load_battery(**config)
  File "/usr/local/lib/python3.9/site-packages/libqtile/widget/battery.py", line 345, in _load_battery
    return load_battery(**config)
  File "/usr/local/lib/python3.9/site-packages/libqtile/widget/battery.py", line 99, in load_battery
    return _FreeBSDBattery(str(config["battery"]))
KeyError: 'battery'
```

So, i just change this value in battery.py widget
```
#return _FreeBSDBattery(str(config["battery"]))
return _FreeBSDBattery("0")
```
And now all look fine

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment]
You can fix this for now by setting battery to 0 (integer) in your widget config. But this is indeed a bug
