### ISSUE TITLE
Ampersand in window name return an error

### ISSUE THREAD

**Issue by Jareng** [qtile/qtile#4107]
## Qtile version
0.22.1

## Issue
Ampersands in window name return an error with the WindowTabs widget
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 404, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/windowtabs.py", line 82, in update
    self.text = self.separator.join(names)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 483, in text
    self.layout.text = self.formatted_text
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 72, in text
    attrlist, value, accel_char = pangocffi.parse_markup(value)
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 186, in parse_markup
    raise Exception("parse_markup() failed for %s" % value)
Exception: parse_markup() failed for b'<b>Search \xc2\xb7 & \xe2\x80\x94 Mozilla Firefox</b>'
```

The same goes for the Mpris2 widget
```
2023-01-07 17:07:22,656 ERROR libqtile loop.py:_handle_exception():L63 parse_markup() failed for b'Fireman & Dancer - Royal Republic'
NoneType: None
2023-01-07 17:07:22,656 ERROR libqtile loop.py:_handle_exception():L63 parse_markup() failed for b'Fireman & Dancer - Royal Republic'
NoneType: None
````

Found a similar issue [#1685](https://github.com/qtile/qtile/issues/1685) but for the WindowName widget

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
It's an issue in any text based widget. The fact that it's a different widget doesn't change anything.

We need to fix this.
