### ISSUE TITLE
KeyChords break dgroups_key_binder = simple_key_binder("mod4") workspaces keybindings

### ISSUE THREAD

**Issue by Sniki** [qtile/qtile#4198]
### The issue:

Qtile version 0.22.1

Workspaces keybindings (mod+123456789) of dgroups_key_binder = simple_key_binder("mod4") break when you use a KeyChord, a config reload/restart fixes the issue until next KeyChord is used. clicking on a workspace with mouse does switch the workspace but not with keybinding, so it's only a problem with the keybinding.

The workspaces setup from default qtile config is not affected.

So as far as i tried to narrow the issue, i came to conclusion that it is somewhere in dgroups_key_binder = simple_key_binder("mod4").

Here is the qtile log:
`
2023-03-16 19:13:29,911 ERROR libqtile hook.py:fire():L406 Error in hook setgroup
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 404, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 138, in <lambda>
    libqtile.hook.subscribe.setgroup(lambda: self.key_binder(self))
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 43, in func
    dgroup.qtile.ungrab_key(key)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 429, in ungrab_key
    self.keys_map.pop((keysym, mask_key))
KeyError: (49, 64)
2023-03-16 19:13:30,274 ERROR libqtile hook.py:fire():L406 Error in hook setgroup
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 404, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 138, in <lambda>
    libqtile.hook.subscribe.setgroup(lambda: self.key_binder(self))
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 43, in func
    dgroup.qtile.ungrab_key(key)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 429, in ungrab_key
    self.keys_map.pop((keysym, mask_key))
KeyError: (49, 64)
`

Also as a file: 
[qtile.log](https://github.com/qtile/qtile/files/10995620/qtile.log)

This is an issue that exists over a year (on prior qtile versions as well) but i had no time to investigate on why it's happening, is it on my side(config) or is it a qtile bug and now i can confirm it's a bug on qtile.
Had to force myself to use workspaces setup from default config (no glyphs, no wm_class matches) so i can have KeyChords.

Thanks in advance !

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
I think this may be fixed in latest git version. Are you able to test?

**Comment by Sniki** [comment]
> I think this may be fixed in latest git version. Are you able to test?

Yes, thanks for pointing this out, i noticed that there is qtile-git from AUR and after installing the issue is resolved, thanks a lot.

Off topic: when should we expect next release ?

**Comment by elParaguayo** [comment]
There are a couple of relatively large updates (X11 layering and Wayland/wlroots 0.16) that we're looking to get finished. Once those are working, we'll push the next release. It's just taking us a bit of time.
