### ISSUE TITLE
Wayland - refresh rate / resolution

### ISSUE THREAD

**Issue by meffwo** [qtile/qtile#4199]
### The issue:

When I try to change display refresh rate by wlr-randr or kanshi terminal hangs / sometimes even Qtile just shuts down itself.
I expected Qtile to just change display refresh rate but its still locked on 60.

Qtile version - 0.22.1

```
2023-03-17 17:25:59,084 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/core.py", line 359, in _on_output_manager_apply
    self._output_manager_reconfigure(config, True)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/core.py", line 634, in _output_manager_reconfigure
    head.state.output.commit()
  File "/usr/lib/python3.10/site-packages/wlroots/wlr_types/output.py", line 197, in commit
    raise RuntimeError("Rendering on output failed")
RuntimeError: Rendering on output failed
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment]
Can you try #3985?

**Comment by ervinpopescu** [comment]
@elParaguayo @tych0 @jwijenbergh this can be closed as well, `wlr-randr` works perfectly fine now.
