### ISSUE TITLE
Getting error while trying to start qtile's wayland session.

### ISSUE THREAD

**Issue by apoorv569** [qtile/qtile#4223]
### The issue:

Qtile version: 0.22.1

Output of `~/.local/share/qtile/qtile.log`
```
  cat .local/share/qtile/qtile.log
2023-04-03 04:03:39,951 ERROR libqtile core.py:__init__():L103 not starting; existing window manager LG3D
2023-04-03 04:03:46,508 ERROR libqtile core.py:__init__():L103 not starting; existing window manager LG3D
2023-04-03 04:31:32,309 ERROR libqtile net.py:poll():L167 Net widget errored while polling:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/net.py", line 140, in poll
    down = new_stats[intf]["down"] - self.stats[intf]["down"]
KeyError: 'wlp13s0'
2023-04-03 04:31:32,383 WARNING libqtile base.py:on_done():L804 poll() returned None, not rescheduling
2023-04-03 04:32:47,082 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
```

The X11 session works fine. I start my X session from `lightdm`. But when I try to start the wayland session from `TTY` by running `qtile start -b wayland` I get error,
```
 qtile start -b wayland
Traceback (most recent call last):
  File "/usr/bin/qtile", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/main.py", line 66, in main
    options.func(options)
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 88, in start
    q = make_qtile(options)
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 51, in make_qtile
    kore = libqtile.backend.get_core(options.backend)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/__init__.py", line 15, in get_core
    return importlib.import_module(f"libqtile.backend.{backend}.core").Core(*args)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/core.py", line 79, in <module>
    from libqtile.backend.wayland import inputs, layer, window, wlrq, xdgwindow, xwindow
  File "/usr/lib/python3.10/site-packages/libqtile/backend/wayland/xdgwindow.py", line 31, in <module>
    from wlroots.wlr_types.xdg_shell import XdgPopup, XdgSurface, XdgTopLevelSetFullscreenEvent
ImportError: cannot import name 'XdgTopLevelSetFullscreenEvent' from 'wlroots.wlr_types.xdg_shell' (/home/apoorv/.local/lib/python3.10/site-packages/wlroots/wlr_types/xdg_shell.py)
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by Malex** [comment]
Error message is the same as https://github.com/qtile/qtile/issues/4190, probably duplicated

**Comment by apoorv569** [comment]
> Error message is the same as #4190, probably duplicated

I think I might have solved this issue. I had `pywlroots` and `wlroots` version `0.16.` installed and `qtile` needs `0.15`. Downgrading to `0.15` solved the issue.
