### ISSUE TITLE
Qtile not starting after massive package upgrade on Arch

### ISSUE THREAD

**Issue by Crystal4276** [qtile/qtile#4251]
### The issue:

Qtile is not starting after massive package upgrade on Arch

Aur package reinstalled:
 4 aur/qtile-extras-git r142.e522e59-1 [+2 ~0.28] [Installed: r260.da6ce83-1]
    Unofficial mods for qtile that are unlikely to be maintained in the main repo.
 3 aur/qtile-git 0.20.0.r33.gc1f50739-3 [+70 ~0.00] [Installed: 0.22.1.r185.g4ecf1bde-1]
    A full-featured, pure-Python tiling window manager - X11. (git version)

```python
❯ qtile
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/qtile", line 33, in <module>
    sys.exit(load_entry_point('qtile==0.22.2.dev185+g4ecf1bde', 'console_scripts', 'qtile')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/sbin/qtile", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for qtile
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
Can you run the following, please:
```
pacman -Ql qtile-git
pacman -Ql qtile-extras-git
```

**Comment by ample-samples** [comment]
The package can be rebuilt using:
`yay -S qtile-git --answerclean All`
