### ISSUE TITLE
Annoying error in the logs

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#4269]
### The issue:

0.22.2.dev185+g4ecf1bde

```
2023-05-20 18:35:53,867 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/githubnotifications.py", line 147, in _read_data
    self.draw()
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/githubnotifications.py", line 156, in draw
    self.drawer.clear(self.background or self.bar.background)
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/decorations.py", line 822, in new_clear
    decoration.draw()
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/decorations.py", line 418, in draw
    self.drawer.ctx.reset_clip()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'reset_clip'
```

If it's already on the list, feel free to close this.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
This is a qtile-extras bug, not qtile. Can you post it on the qtile-extras issues page instead please.

**Comment by ervinpopescu** [comment]
> This is a qtile-extras bug, not qtile. Can you post it on the qtile-extras issues page instead please.

Oops. 👍🏻
