### ISSUE TITLE
Yet another libcairo.so.2 issue

### ISSUE THREAD

**Issue by otval229** [qtile/qtile#4284]
### The issue:

I can't start qtile

Last error log:

---
```
2023-05-31 18:15:06,780 ERROR libqtile start.py:start():L92 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/scripts/start.py", line 90, in start
    q.loop()
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 198, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 223, in async_loop
    self.load_config(initial=True)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 136, in load_config
    self._process_screens(reloading=not initial)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 359, in _process_screens
    scr._configure(self, i, x, y, w, h, grp, reconfigure_gaps=reconfigure_gaps)
  File "/usr/lib/python3.11/site-packages/libqtile/config.py", line 412, in _configure
    i._configure(qtile, self, reconfigure=reconfigure_gaps)
  File "/usr/lib/python3.11/site-packages/libqtile/bar.py", line 277, in _configure
    self.drawer.clear(self.background)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 177, in clear
    self._check_xcb()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 122, in _check_xcb
    self._xcb_surface = self._create_xcb_surface()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 88, in _create_xcb_surface
    surface = cairocffi.XCBSurface(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/artix/.local/lib/python3.11/site-packages/cairocffi/xcb.py", line 37, in __init__
    p = cairo.cairo_xcb_surface_create(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: cffi library 'libcairo.so.2' has no function, constant or global variable named 'cairo_xcb_surface_create'
```
---

Tried to fix the error following this guide http://docs.qtile.org/en/stable/manual/troubleshooting.html#cairo-errors and this guide https://github.com/qtile/qtile/issues/3494 but of course neither 1nd nor 2nd guide didn't work for me 

P.S I've installed qtile with pacman package manager and tried to start with SDDM

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by ramnes** [comment]
Desinstall these packages and reinstall them, in that order: python-xcffib python-cairocffi qtile
 
 Make sure that nothing is left behind after you desinstalled / before reinstalling (e.g. with mlocate).

**Comment by elParaguayo** [comment]
There's a more recent issue with cairocffi where, because pip is building packages in an isolated environment, it doesn't see the xcffib installation. You may therefore need to run `pip install --no-cache --upgrade --no-build-isolation cairocffi`.

**Comment by elParaguayo** [comment]
However, if you're on Arch, the packaged version of `cairocffi` (`python-cairocffi`) should be built with xcb support.

**Comment by ramnes** [comment]
uh I wasn't aware of that build isolation thing, let's update the docs then: #4285

**Comment by otval229** [comment]
The methods suggested above did not help. However, for the sake of interest, I decided to try installing qtile using pip, but qtile could not be installed, the following error took off:
---
```
It looks like your cairocffi was not built with xcffib support. To fix this:
      
        - Ensure a recent xcffib is installed (pip install 'xcffib>=0.5.0')
        - The pip cache is cleared (remove ~/.cache/pip, if it exists)
        - Reinstall cairocffi, either:
      
            pip install --no-deps --ignore-installed cairocffi
      
          or
      
            pip uninstall cairocffi && pip install cairocffi
```
---
I tried to solve the problem, focusing on the methods suggested in the error, but it did not help and the problem did not disappear, although I did everything right

**Comment by ramnes** [comment]
When installing with pip, did you use `--no-build-isolation` when installing cairocffi and qtile, as mentioned by @elParaguayo ?

**Comment by elParaguayo** [comment]
Ugh. We really need to get this fixed in cairocffi...

I am slightly surprised this is needed here as they seem to be using an Arch based distro and, from my personal experience, the currently packaged version of `python-cairocffi` has been built with xcffib support.

Regardless, if using `pip` to install qtile then, yes, add the `--no-build-isolation` option there too.

**Comment by elParaguayo** [comment]
@otval229 see https://github.com/qtile/qtile/issues/4265#issuecomment-1562633050

**Comment by ramnes** [comment]
@elParaguayo yes, I opened the discussion on cairocffi there: https://github.com/Kozea/cairocffi/issues/214

**Comment by otval229** [comment]
``` pip install --no-cache --upgrade --no-build-isolation cairocffi ```
^ The command returns that the requirement is already satisfied and nothing more. Idk how pip really works but looks like that command does nothing 
Same output after ```python -m pip install --no-cache --upgrade --no-build-isolation "cairocffi[xcb]"``` from #4625
I think the issue is in my linux distro (Artix) because when I tried to install qtile on Debian VM with pip, I had no errors

**Comment by otval229** [comment]
> I think the issue is in my linux distro (Artix) because when I tried to install qtile on Debian VM with pip, I had no errors
Or I just broke my system because I'm a retard

**Comment by ramnes** [comment]
Do you get an error when running `python -c "from cairocffi import cairo; cairo.cairo_xcb_surface_create"`?

If not, try installing Qtile with `pip install --no-cache -I --no-build-isolation qtile`

**Comment by otval229** [comment]
```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: cffi library 'libcairo.so.2' has no function, constant or global variable named 'cairo_xcb_surface_create'. Did you mean: 'cairo_pdf_surface_create'?

```

**Comment by elParaguayo** [comment]
Agree with ramnes. Check the `cairocffi` installation first. If you get an error there, you can add `--force-reinstall` to those options.

**Comment by otval229** [comment]
Omg looks like --force-reinstall helped
```
python -c "from cairocffi import cairo; cairo.cairo_xcb_surface_create"``` runs without errors

**Comment by elParaguayo** [comment]
Re: "command not found". I suspect that's because pip installed qtile locally and so the executable file would not have been in your path.

Be careful as you've not got 2 versions of qtile installed: one systemwide (via `pacman`) and one locally (via `pip`).

**Comment by filipiz** [comment]
I'm also on arch.
`--force-reinstall` also worked for me.
Thanks
