### ISSUE TITLE
Error compiling Qtile

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#4298]
### The issue:

Looking for the solution to the problem #4290  I followed the steps of a user for whom the installation through a virtual environment worked. 
``` The following steps were used on Ubuntu 23.04:

Required packages: python3-virtualenv python3-pip

mkdir ~/qtile python3 -m virtualenv ~/qtile source ~/qtile/bin/activate

pip install xcffib==1.3.0 pip install --no-cache-dir cairocffi pip install --no-use-pep517 --no-build-isolation qtile

OPTIONAL: pip install dbus-next

#Leaving the virtualenv deactivate

When installing qtile by pip, it does not create the xsessions entry and also does not create the /usr/share/doc/qtile/default_config.py file

Alternative default config file: https://github.com/qtile/qtile/blob/master/libqtile/resources/default_config.py

OPTIONAL: install package: python3-virtualenv-clone

#move virtualenv folder 'qtile' for /opt/qtile sudo virtualenv-clone ~/qtile /opt/qtile

#replace user sudo chown -R user:user /opt/qtile

#set qtile for enviroment mkdir ~/.local/share/bin ln -s /opt/qtile/bin/qtile ~/.local/share/bin/qtile

#add PATH ~/.local/share/bin on .bashrc or .zshrc export PATH="$HOME/.local/share/bin:$PATH"

#creating an entry in xsessions | /usr/share/xsessions/qtile.desktop [Desktop Entry] Name=Qtile Comment=Qtile Session Exec=/opt/qtile/bin/qtile start Type=Application X-GDM-SessionRegisters=true Keywords=wm;tiling
```
But when you get to the part of installing Qtile using `pip install --no-use-pep517 --no-build-isolation qtile`

I get the following error

```Collecting qtile
  Using cached qtile-0.22.1.tar.gz (488 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      /home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/config/setupcfg.py:515: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      /home/cr1ogen/qtile/lib/python3.11/site-packages/wlroots/__pycache__/_cffi__x58fcf130x56f3363a.c:265:10: fatal error: wlr/version.h: No existe el fichero o el directorio
        265 | #include <wlr/version.h>
            |          ^~~~~~~~~~~~~~~
      compilation terminated.
      Traceback (most recent call last):
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 186, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1007, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/cffi/ffiplatform.py", line 51, in _build
          dist.run_command('build_ext')
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
          self._build_extensions_serial()
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 549, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 599, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-uchgdyok/qtile_22a8f79921d74f9b82ccf0c39e8f522a/setup.py", line 105, in <module>
          cffi_modules=get_cffi_modules(),
                       ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-uchgdyok/qtile_22a8f79921d74f9b82ccf0c39e8f522a/setup.py", line 89, in get_cffi_modules
          import wlroots.ffi_build
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/wlroots/ffi_build.py", line 2930, in <module>
          check_version()
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/wlroots/ffi_build.py", line 52, in check_version
          wlroots_version = load_wlroots_version()
                            ^^^^^^^^^^^^^^^^^^^^^^
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/wlroots/ffi_build.py", line 39, in load_wlroots_version
          lib = ffi.verify("#include <wlr/version.h>")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/cffi/api.py", line 468, in verify
          lib = self.verifier.load_library()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/cffi/verifier.py", line 105, in load_library
          self._compile_module()
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/cffi/verifier.py", line 202, in _compile_module
          outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/cffi/ffiplatform.py", line 22, in compile
          outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/cr1ogen/qtile/lib/python3.11/site-packages/cffi/ffiplatform.py", line 58, in _build
          raise VerificationError('%s: %s' % (e.__class__.__name__, e))
      cffi.VerificationError: CompileError: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details. 
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by johnazule** [comment]
What version of pywlroots do you have installed? I had the same issue until I downgraded to pywlroots 0.15.24 using ``pip install "pywlroots<0.16"`` (Quotes are needed to prevent the shell trying to pipe the ``<``) or ``pip install pywlroots==0.15.24``. If you are using a virtualenv I had the most luck using ``python -m pip`` instead of ``pip``

**Comment by cr1ogen** [comment]
> What version of pywlroots do you have installed? I had the same issue until I downgraded to pywlroots 0.15.24 using `pip install "pywlroots<0.16"` (Quotes are needed to prevent the shell trying to pipe the `<`) or `pip install pywlroots==0.15.24`. If you are using a virtualenv I had the most luck using `python -m pip` instead of `pip`

Hello. I just tried downloading the version of pywlroots that you recommended and tried with `python -m pip` and it keeps giving me an error. Thanks for the tips anyway

**Comment by johnazule** [comment]
Do you have wlroots 0.15.24 installed aswell?

**Comment by clotodex** [comment]
Make sure like @johnazule said that you have the right wlroots version (.16 is not supported yet).
Then because of issues like this I build a script to reproducibly build qtile (and qtile-extras), doing all the quirks which were discussed in other issues. https://github.com/clotodex/qtile-install-script check it out if it still does not work for you.

**Comment by cr1ogen** [comment]
I was able to install Qtile with the latest recently updated dev version qtile-0.22.2.dev202+g0dc89418 with `pip install .`  You can close the issue if you want.
