### ISSUE TITLE
After a Python Upgrade, Qtile eventually dies

### ISSUE THREAD

**Issue by mikeBoterf** [qtile/qtile#4315]
### The issue:

Whenever Python is upgraded (current version is now 3.11.3) the system after about 1-2 mins will eventually die. I can't seem to recover from this state unless I reboot the machine. Once restarted, I'm back to normal. Not sure what's the root cause, this is what I've found in journalctl and coredump

```sh
Jun 21 10:22:44 my-nuc systemd-coredump[3956527]: [🡕] Process 3514 (python) of user 1000 dumped core.

                                                   Stack trace of thread 3514:
                                                   #0  0x00007f4da7806950 n/a (n/a + 0x0)
                                                   #1  0x00007f4da8a81318 n/a (n/a + 0x0)
                                                   ELF object binary architecture: AMD x86-64
```

```sh
sudo coredumpctl info 3514
           PID: 3514 (python)
           UID: 1000 (mboterf)
           GID: 1000 (local_users)
        Signal: 11 (SEGV)
     Timestamp: Wed 2023-06-21 10:22:44 CDT (17min ago)
  Command Line: /usr/bin/python /usr/bin/qtile start --no-spawn --with-state=/tmp/qtile-state
    Executable: /usr/bin/python3.11
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (mboterf)
       Boot ID: removed
    Machine ID: removed
      Hostname: my-nuc
       Storage: /var/lib/systemd/coredump/core.python.1000.3c632110fbde424da964f112ce6827b1.3514.1687360964000000.zst (present)
  Size on Disk: 7.2M
       Message: Process 3514 (python) of user 1000 dumped core.

                Stack trace of thread 3514:
                #0  0x00007f4da7806950 n/a (n/a + 0x0)
                #1  0x00007f4da8a81318 n/a (n/a + 0x0)
                ELF object binary architecture: AMD x86-64
```

qtile --version
0.22.1

logs:
[qtile-crash-log.log](https://github.com/qtile/qtile/files/11820167/qtile-crash-log.log)

relevant log messages: I probably missed the important ones, please check file:

```sh
2023-06-21 10:22:25,368 ERROR libqtile group.py:layout():L128 No such layout: floating
2023-06-21 10:22:25,947 ERROR libqtile net.py:poll():L167 Net widget errored while polling:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/net.py", line 140, in poll
    down = new_stats[intf]["down"] - self.stats[intf]["down"]
           ~~~~~~~~~^^^^^^
KeyError: 'eth0'
2023-06-21 10:22:25,966 WARNING libqtile base.py:on_done():L804 poll() returned None, not rescheduling
2023-06-21 10:22:44,404 ERROR libqtile loop.py:_handle_exception():L63 xcb connection errors because of socket, pipe and other stream errors.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 579, in wrapper
    return f(*args)
           ^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 689, in request_check
    self._process_error(err)
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 653, in _process_error
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 862, in f
    func(*args)
  File "/usr/lib/python3.11/site-packages/libqtile/bar.py", line 616, in _actual_draw
    i.draw()
  File "/usr/lib/python3.11/site-packages/libqtile/widget/systray.py", line 258, in draw
    icon.place(xoffset, yoffset, icon.width, self.icon_size, 0, None)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/window.py", line 906, in place
    self.paint_borders(bordercolor, borderwidth)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/window.py", line 915, in paint_borders
    self.window.paint_borders(self.depth, color, width, self.width, self.height)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/window.py", line 428, in paint_borders
    self.set_property("_NET_FRAME_EXTENTS", [borderwidth] * 4)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/window.py", line 357, in set_property
    ).check()
      ^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 340, in check
    self.conn.request_check(self.sequence)
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 581, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-06-21 10:22:44,406 ERROR libqtile core.py:_xpoll():L332 Shutting down due to X connection error XCB_CONN_ERROR (1)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 294, in _xpoll
    event = self.conn.conn.poll_for_event()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

2023-06-21 10:22:44,436 ERROR libqtile core.py:get_interesting_pid():L815 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 813, in get_interesting_pid
    return win.window.get_net_wm_pid()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/xproto.py", line 2832, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 392, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-06-21 10:22:44,450 ERROR libqtile start.py:start():L92 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/scripts/start.py", line 90, in start
    q.loop()
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 198, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 226, in async_loop
    self.finalize()
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 306, in finalize
    self.core.finalize()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 170, in finalize
    self.conn.conn.core.DeletePropertyChecked(
  File "/usr/lib/python3.11/site-packages/xcffib/xproto.py", line 2828, in DeleteProperty
    return self.send_request(19, buf, is_checked=is_checked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 392, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-06-21 10:22:44,451 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
```

Sorry for the long log. That's everything around the time of the crash

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by ramnes** [comment]
Is the log file you shared complete or do you have other logs above?

**Comment by mtwb47** [comment]
The same issue, only mine will not even start up after logging in from the display manager. Same errors in qtile.log

**Comment by mikeBoterf** [comment]
> Is the log file you shared complete or do you have other logs above?

What is attached is complete. Posted is abbreviated.

**Comment by DeeeeLAN** [comment]
My X11 is crashing after a while, repeatedly. I will log in and use the system for maybe an hour or two, then Qtile and X will crash and I will end up back at my terminal session. Here is a section of my qtile log that output at the time of the crash:

<details>
<summary>qtile.log</summary>

```shell
2023-08-07 23:48:17,902 ERROR libqtile base.py:_wrapper():L384 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 382, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 201, in update
    self.update_graph()
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 371, in update_graph
    self.push(change)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 193, in push
    self.draw()
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 180, in draw
    self.drawer.draw(offsetx=self.offset, offsety=self.offsety, width=self.width)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base/drawer.py", line 210, in draw
    self._draw(offsetx, offsety, width, height)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 191, in _draw
    self.qtile.core.conn.conn.core.CopyArea(
  File "/usr/lib/python3.11/site-packages/xcffib/xproto.py", line 3152, in CopyArea
    return self.send_request(62, buf, is_checked=is_checked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 389, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-08-07 23:48:17,914 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 937, in f
    self.core.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 894, in flush
    self.conn.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/xcbq.py", line 613, in flush
    return self.conn.flush()
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-08-07 23:48:17,917 WARNING libqtile core.py:_xpoll():L366 Shutting down due to disconnection from X server
2023-08-07 23:48:17,917 WARNING libqtile core.py:graceful_shutdown():L906 Server disconnected, couldn\'t close windows gracefully.
2023-08-07 23:48:17,929 ERROR libqtile base.py:_wrapper():L384 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 382, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 201, in update
    self.update_graph()
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 255, in update_graph
    self.push(push_value)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 193, in push
    self.draw()
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 180, in draw
    self.drawer.draw(offsetx=self.offset, offsety=self.offsety, width=self.width)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base/drawer.py", line 210, in draw
    self._draw(offsetx, offsety, width, height)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 185, in _draw
    self._check_xcb()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 158, in _check_xcb
    self._pixmap = self._create_pixmap()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 139, in _create_pixmap
    pixmap = self.qtile.core.conn.conn.generate_id()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-08-07 23:48:17,930 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 937, in f
    self.core.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 894, in flush
    self.conn.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/xcbq.py", line 613, in flush
    return self.conn.flush()
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-08-07 23:48:17,931 ERROR libqtile base.py:_wrapper():L384 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 382, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 201, in update
    self.update_graph()
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 446, in update_graph
    self.push(val)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 193, in push
    self.draw()
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 180, in draw
    self.drawer.draw(offsetx=self.offset, offsety=self.offsety, width=self.width)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base/drawer.py", line 210, in draw
    self._draw(offsetx, offsety, width, height)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 185, in _draw
    self._check_xcb()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 158, in _check_xcb
    self._pixmap = self._create_pixmap()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 139, in _create_pixmap
    pixmap = self.qtile.core.conn.conn.generate_id()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-08-07 23:48:17,931 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 937, in f
    self.core.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 894, in flush
    self.conn.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/xcbq.py", line 613, in flush
    return self.conn.flush()
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-08-07 23:48:17,933 ERROR libqtile base.py:_wrapper():L384 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 382, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 201, in update
    self.update_graph()
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 413, in update_graph
    self.push(val)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 193, in push
    self.draw()
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 180, in draw
    self.drawer.draw(offsetx=self.offset, offsety=self.offsety, width=self.width)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base/drawer.py", line 210, in draw
    self._draw(offsetx, offsety, width, height)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 185, in _draw
    self._check_xcb()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 158, in _check_xcb
    self._pixmap = self._create_pixmap()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 139, in _create_pixmap
    pixmap = self.qtile.core.conn.conn.generate_id()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-08-07 23:48:17,933 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 937, in f
    self.core.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 894, in flush
    self.conn.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/xcbq.py", line 613, in flush
    return self.conn.flush()
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-08-07 23:48:17,934 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 937, in f
    self.core.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 894, in flush
    self.conn.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/xcbq.py", line 613, in flush
    return self.conn.flush()
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-08-07 23:48:17,935 ERROR libqtile base.py:_wrapper():L384 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 382, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 201, in update
    self.update_graph()
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 291, in update_graph
    self.push(val["MemTotal"] - val["MemFree"] - val["Buffers"] - val["Cached"])
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 193, in push
    self.draw()
  File "/usr/lib/python3.11/site-packages/libqtile/widget/graph.py", line 180, in draw
    self.drawer.draw(offsetx=self.offset, offsety=self.offsety, width=self.width)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base/drawer.py", line 210, in draw
    self._draw(offsetx, offsety, width, height)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 185, in _draw
    self._check_xcb()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 158, in _check_xcb
    self._pixmap = self._create_pixmap()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/drawer.py", line 139, in _create_pixmap
    pixmap = self.qtile.core.conn.conn.generate_id()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-08-07 23:48:17,936 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 937, in f
    self.core.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 894, in flush
    self.conn.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/xcbq.py", line 613, in flush
    return self.conn.flush()
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-08-07 23:48:17,937 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 937, in f
    self.core.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 894, in flush
    self.conn.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/xcbq.py", line 613, in flush
    return self.conn.flush()
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-08-07 23:48:17,941 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 937, in f
    self.core.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 894, in flush
    self.conn.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/xcbq.py", line 613, in flush
    return self.conn.flush()
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-08-07 23:48:17,968 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 937, in f
    self.core.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 894, in flush
    self.conn.flush()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/xcbq.py", line 613, in flush
    return self.conn.flush()
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-08-07 23:48:18,056 ERROR libqtile base.py:on_done():L837 Failed to reschedule.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 831, in on_done
    self.update(result)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 735, in update
    old_width = self.layout.width
                ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base/drawer.py", line 379, in width
    return self.layout.get_pixel_size()[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/pangocffi.py", line 137, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2023-08-07 23:48:18,057 INFO libqtile start.py:start():L94 Exiting...
2023-08-07 23:48:18,058 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
```

</details>

**Comment by DeeeeLAN** [comment]
I have not been having the crashing issue recently. Currently on 0.23.1.dev67+gd3d80d0b

**Comment by ramnes** [comment]
Great, I'll go ahead and close then, feel free to comment and I'll reopen if needed.
