### ISSUE TITLE
Error starting qtile wayland

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#4382]
### The issue:

Qtile version 0.22.2.dev326+g6357381a

I can't start wayland, give me this error in console

``` 
❯ qtile start -b wayland
Traceback (most recent call last):
  File "/usr/lib/python3.11/dist-packages/wlroots/wlr_types/__init__.py", line 51, in __getattr__
    return globals()[name]
           ~~~~~~~~~^^^^^^
KeyError: 'Buffer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/qtile", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/libqtile/scripts/main.py", line 76, in main
    func(options)
  File "/usr/local/lib/python3.11/dist-packages/libqtile/scripts/start.py", line 88, in start
    q = make_qtile(options)
        ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/libqtile/scripts/start.py", line 51, in make_qtile
    kore = libqtile.backend.get_core(options.backend)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/libqtile/backend/__init__.py", line 15, in get_core
    return importlib.import_module(f"libqtile.backend.{backend}.core").Core(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/dist-packages/libqtile/backend/wayland/__init__.py", line 23, in <module>
    from libqtile.backend.wayland.inputs import InputConfig  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/libqtile/backend/wayland/inputs.py", line 30, in <module>
    from libqtile.backend.wayland.wlrq import HasListeners, buttons
  File "/usr/local/lib/python3.11/dist-packages/libqtile/backend/wayland/wlrq.py", line 30, in <module>
    from wlroots.wlr_types import Buffer, SceneBuffer, SceneTree, data_device_manager
  File "/usr/lib/python3.11/dist-packages/wlroots/wlr_types/__init__.py", line 53, in __getattr__
    raise ImportError(f"cannot import name '{name}' from wlroots.wlr_types")
ImportError: cannot import name 'Buffer' from wlroots.wlr_types
```

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by jwijenbergh** [comment]
What is your pywlroots version?

**Comment by cr1ogen** [comment]
> What is your pywlroots version?

pywlroots 0.16.4

**Comment by drishal** [comment]
I am also having the same issue while trying to install qtile
