### ISSUE TITLE
qtile crashes on reload if Group name is unicode string

### ISSUE THREAD

**Issue by eigengrau** [qtile/qtile#440]
I tried providing a unicode literal to the Group class. Initially, this seemed to work nicely and the string rendered properly on the bar. However, I noticed that once I try reloading qtile while such a group is active, the session will crash.

Below is a traceback from my logs.
```
2014-06-04 18:19:53,261 ERROR fire:219 Error in hook client_new
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/libqtile/hook.py", line 217, in fire
    i(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/libqtile/dgroups.py", line 142, in _add
    group_added = self.qtile.addGroup(rule.group, layout, layouts)
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 328, in addGroup
    self.update_net_desktops()
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 314, in update_net_desktops
    "_NET_DESKTOP_NAMES", "\0".join([i.name for i in self.groups])
  File "/usr/lib/python2.7/site-packages/libqtile/xcbq.py", line 595, in set_property
    buf
  File "/usr/lib/python2.7/site-packages/xcb/xproto.py", line 1612, in ChangeProperty
    buf.write(str(buffer(array('B', data))))
TypeError: an integer is required
2014-06-04 18:19:55,005 ERROR fire:219 Error in hook setgroup
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/libqtile/hook.py", line 217, in fire
    i(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 314, in update_net_desktops
    "_NET_DESKTOP_NAMES", "\0".join([i.name for i in self.groups])
  File "/usr/lib/python2.7/site-packages/libqtile/xcbq.py", line 595, in set_property
    buf
  File "/usr/lib/python2.7/site-packages/xcb/xproto.py", line 1612, in ChangeProperty
    buf.write(str(buffer(array('B', data))))
TypeError: an integer is required
```

**Comment by flacjacket** [comment]
Is this still a problem with the current git? @tych0 This looks like a utf-8 bug we should squash before 0.9.1

**Comment by eigengrau** [comment]
Hi! I retried, and I’m not seeing a crash anymore if I specify the group name as a regular Python 2 string (i. e., raw bytes in UTF-8). So this seems mostly resolved.

qtile still crashes when the group name is given as a unicode literal. This seems to be because somewhere, the unicode string is being decoded from ASCII.

```
2015-01-29 11:20:10,479 ERROR fire:243 Error in hook client_new
Traceback (most recent call last):
  File "/home/seb/Dev/spielwiese/qtile/libqtile/hook.py", line 241, in fire
    i(*args, **kwargs)
  File "/home/seb/Dev/spielwiese/qtile/libqtile/dgroups.py", line 152, in _add
    group_added = self.qtile.addGroup(rule.group, layout, layouts)
  File "/home/seb/Dev/spielwiese/qtile/libqtile/manager.py", line 399, in addGroup
    self.update_net_desktops()
  File "/home/seb/Dev/spielwiese/qtile/libqtile/manager.py", line 385, in update_net_desktops
    "_NET_DESKTOP_NAMES", "\0".join([i.name for i in self.groups])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 0: ordinal not in range(128)
```

**Comment by flacjacket** [comment]
This also seems to crash in Python 3

```
2015-01-29 12:05:31,334 qtile make_qtile:123  Qtile crashed during startup
Traceback (most recent call last):
  File "./bin/qtile", line 120, in make_qtile
    state=options.state,
  File "/home/sean/qtile/qtile/bin/libqtile/manager.py", line 144, in __init__
    self.dgroups = DGroups(self, self.config.groups, key_binder)
  File "/home/sean/qtile/qtile/bin/libqtile/dgroups.py", line 67, in __init__
    self._setup_groups()
  File "/home/sean/qtile/qtile/bin/libqtile/dgroups.py", line 100, in _setup_groups
    self.add_dgroup(group, group.init)
  File "/home/sean/qtile/qtile/bin/libqtile/dgroups.py", line 96, in add_dgroup
    self.qtile.addGroup(group.name, group.layout, group.layouts)
  File "/home/sean/qtile/qtile/bin/libqtile/manager.py", line 399, in addGroup
    self.update_net_desktops()
  File "/home/sean/qtile/qtile/bin/libqtile/manager.py", line 385, in update_net_desktops
    "_NET_DESKTOP_NAMES", u"\0".join(i.name for i in self.groups)
  File "/home/sean/qtile/qtile/bin/libqtile/xcbq.py", line 612, in set_property
    ).check()
  File "/usr/lib64/python3.4/site-packages/xcffib/xproto.py", line 1870, in ChangeProperty
    buf.write(xcffib.pack_list(data, "c"))
  File "/usr/lib64/python3.4/site-packages/xcffib/__init__.py", line 688, in pack_list
    from_ = [b.encode('latin-1') for b in from_]
  File "/usr/lib64/python3.4/site-packages/xcffib/__init__.py", line 688, in <listcomp>
    from_ = [b.encode('latin-1') for b in from_]
UnicodeEncodeError: 'latin-1' codec can't encode character '\u03a8' in position 0: ordinal not in range(256)
```

**Comment by flacjacket** [comment]
@eigengrau I was able to get unicode group names working by fixing xcffib, can you try installing the xcffib from tych0/xcffib#33 ?

**Comment by eigengrau** [comment]
@flacjacket I built your fix_py2_unicode_pack branch. I tried setting a group name to `u"🎩"`, and this yields:

```
2015-01-30 14:54:01,917 qtile make_qtile:123  Qtile crashed during startup
Traceback (most recent call last):
  File "/usr/bin/qtile", line 120, in make_qtile
    state=options.state,
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 144, in __init__
    self.dgroups = DGroups(self, self.config.groups, key_binder)
  File "/usr/lib/python2.7/site-packages/libqtile/dgroups.py", line 67, in __init__
    self._setup_groups()
  File "/usr/lib/python2.7/site-packages/libqtile/dgroups.py", line 100, in _setup_groups
    self.add_dgroup(group, group.init)
  File "/usr/lib/python2.7/site-packages/libqtile/dgroups.py", line 96, in add_dgroup
    self.qtile.addGroup(group.name, group.layout, group.layouts)
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 399, in addGroup
    self.update_net_desktops()
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 385, in update_net_desktops
    "_NET_DESKTOP_NAMES", "\0".join([i.name for i in self.groups])
  File "/usr/lib/python2.7/site-packages/libqtile/xcbq.py", line 611, in set_property
    value
  File "/tmp/xcffib/lib/python2.7/site-packages/xcffib-0.1.10-py2.7-linux-x86_64.egg/xcffib/__init__.py", line 305, in check
    self.conn.request_check(self.sequence)
  File "/tmp/xcffib/lib/python2.7/site-packages/xcffib-0.1.10-py2.7-linux-x86_64.egg/xcffib/__init__.py", line 517, in wrapper
    return f(*args)
  File "/tmp/xcffib/lib/python2.7/site-packages/xcffib-0.1.10-py2.7-linux-x86_64.egg/xcffib/__init__.py", line 610, in request_check
    self._process_error(err)
  File "/tmp/xcffib/lib/python2.7/site-packages/xcffib-0.1.10-py2.7-linux-x86_64.egg/xcffib/__init__.py", line 581, in _process_error
    raise error(buf)
LengthError
Traceback (most recent call last):
  File "/usr/bin/qtile", line 129, in <module>
    q = make_qtile()
  File "/usr/bin/qtile", line 120, in make_qtile
    state=options.state,
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 144, in __init__
    self.dgroups = DGroups(self, self.config.groups, key_binder)
  File "/usr/lib/python2.7/site-packages/libqtile/dgroups.py", line 67, in __init__
    self._setup_groups()
  File "/usr/lib/python2.7/site-packages/libqtile/dgroups.py", line 100, in _setup_groups
    self.add_dgroup(group, group.init)
  File "/usr/lib/python2.7/site-packages/libqtile/dgroups.py", line 96, in add_dgroup
    self.qtile.addGroup(group.name, group.layout, group.layouts)
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 399, in addGroup
    self.update_net_desktops()
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 385, in update_net_desktops
    "_NET_DESKTOP_NAMES", "\0".join([i.name for i in self.groups])
  File "/usr/lib/python2.7/site-packages/libqtile/xcbq.py", line 611, in set_property
    value
  File "/tmp/xcffib/lib/python2.7/site-packages/xcffib-0.1.10-py2.7-linux-x86_64.egg/xcffib/__init__.py", line 305, in check
    self.conn.request_check(self.sequence)
  File "/tmp/xcffib/lib/python2.7/site-packages/xcffib-0.1.10-py2.7-linux-x86_64.egg/xcffib/__init__.py", line 517, in wrapper
    return f(*args)
  File "/tmp/xcffib/lib/python2.7/site-packages/xcffib-0.1.10-py2.7-linux-x86_64.egg/xcffib/__init__.py", line 610, in request_check
    self._process_error(err)
  File "/tmp/xcffib/lib/python2.7/site-packages/xcffib-0.1.10-py2.7-linux-x86_64.egg/xcffib/__init__.py", line 581, in _process_error
    raise error(buf)
xcffib.xproto.LengthError
```

Setting the name to `"🎩"` (no Unicode literal) still works.

**Comment by flacjacket** [comment]
Hmm, that's very odd. Both unicode escape characters and direct unicode characters _should_ work, @eigengrau can you post your config somewhere so I can try it?

**Comment by eigengrau** [comment]
@flacjacket This is the minimal config for which I can reproduce the LengthError.

```
# coding: utf-8
from libqtile.config import Group
groups = [
    Group(
        "1",
        position=1,
    ),
    Group(
        u"🎩",
        position=2,
    )
]
```

Oddly, when I only have the one ``u"🎩"`` group, no error is thrown.

**Comment by tych0** [comment]
On Fri, Jan 30, 2015 at 08:37:24AM -0800, eigengrau wrote:
> @flacjacket This is the minimal config for which I can reproduce the LengthError.
> 
> ```
> # coding: utf-8
> from libqtile.config import Group
> groups = [
>     Group(
>         "1",
>         position=1,
>     ),
>     Group(
>         u"🎩",
>         position=2,
>     )
> ]
> ```
> 
> Oddly, when I only have the one ``u"🎩"`` group, no error is thrown.

Can you post an xtrace with the qtile log when you get the error?

**Comment by flacjacket** [comment]
I see, I had picked too simple a unicode character when I was testing it such that it still packed into the same number of bytes. Try with that same xcffib branch and with #591

**Comment by eigengrau** [comment]
xtrace here. https://www.sendspace.com/file/1eiigj

**Comment by eigengrau** [comment]
I ran qtile 48cda8d in combination with xcffib 4e90708 and it seems to work 👍

**Comment by flacjacket** [comment]
@tycho, I think this can be closed with the current changes to master.

**Comment by tycho** [comment]
You mean @tych0. :)

**Comment by flacjacket** [comment]
Ah, yeah, right :)

**Comment by eigengrau** [comment]
Thanks for looking into this!
