### ISSUE TITLE
[Wayland] Screen order reversed using git master

### ISSUE THREAD

**Issue by justinesmithies** [qtile/qtile#4407]
### The issue:

I'm running on Void Linux and have both `wlroots0.16` and `wlroots0.16-devel` installed along with all the required deps installed using pip.

Qtile version: ```0.22.2.dev335+gbd507e89```

I've been running Qtile stable for a while on my dual screen setup and I obviously use kanshi too. I have it setup to make my external monitor HDMI screen 0 on the left and the laptop e-DP screen 1 on the right. Also this means Qtile draws my primary bar on screen 0 my external HDMI screen and the secondary bar on my laptop screen which is to the right of the main. This all works perfectly so I was suprised to find when I unistalled Qtile stable and installed the latest Qtile from the Git repo that the screen orders are reversed even when using exactly the same configs for both Qtile and kanshi.
The latest version makes my external HDMI screen 1 and the laptop e-DP screen 0.
IF I switch back to stable everything is all ok and when I reinstall the latest git version the screens are reversed.

My kanshi config is here:

```
profile Laptop {
	output eDP-1 position 0,0 mode 1920x1080
	#exec sh -c "$HOME/.config/yambar/scripts/yambar-start.sh"
}

profile Dock {
	output HDMI-A-1 position 0,0 mode 1920x1080
	output eDP-1 position 1920,0 mode 1920x1080
	#exec sh -c "$HOME/.config/yambar/scripts/yambar-start.sh"
}
```
My dotfiles are here but they are a little outdated due to changes but I have already rectified the changes according to the changelog locally. I've just not pushed my updated configs yet until I'm 100% happy.

 https://codeberg.org/JustineSmithies/qtile-wayland-dotfiles/src/branch/master/.config/qtile

The only errors I see in my logs are here:

```
2023-08-19 08:40:28,737 WARNING libqtile screens.py:<module>():L20 Found 2 monitor(s)
2023-08-19 08:40:29,369 WARNING libqtile hooks.py:outputs_changed():L28 Screens reconfigured
2023-08-19 08:40:29,369 WARNING libqtile hooks.py:outputs_changed():L28 Screens reconfigured
2023-08-19 08:40:30,371 WARNING libqtile hooks.py:outputs_changed():L30 Reloading config...
2023-08-19 08:40:30,388 WARNING libqtile screens.py:<module>():L20 Found 2 monitor(s)
2023-08-19 08:40:30,406 WARNING libqtile screens.py:<module>():L20 Found 2 monitor(s)
2023-08-19 08:40:30,554 WARNING libqtile hooks.py:outputs_changed():L30 Reloading config...
2023-08-19 08:40:30,569 WARNING libqtile screens.py:<module>():L20 Found 2 monitor(s)
2023-08-19 08:40:30,599 WARNING libqtile screens.py:<module>():L20 Found 2 monitor(s)
2023-08-19 08:40:30,772 ERROR libqtile base.py:on_done():L837 Failed to reschedule.
Traceback (most recent call last):
  File "/home/justine/.local/lib/python3.11/site-packages/libqtile/widget/base.py", line 831, in on_done
    self.update(result)
  File "/home/justine/.local/lib/python3.11/site-packages/libqtile/widget/base.py", line 735, in update
    old_width = self.layout.width
                ^^^^^^^^^^^^^^^^^
  File "/home/justine/.local/lib/python3.11/site-packages/libqtile/backend/base/drawer.py", line 402, in width
    return self.layout.get_pixel_size()[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justine/.local/lib/python3.11/site-packages/libqtile/pangocffi.py", line 137, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
```
I do not get the error lines if I just use one screen.

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by justinesmithies** [comment]
That fixes the issue partly as the bars are now on the correct screens now but when qtile starts focus is still on the laptop screen eDP-1 which is screen index 1 when focus should start on screen index 0 which is my main HDMI-A-1 external screen.

**Comment by jwijenbergh** [comment]
2 bugs left https://github.com/qtile/qtile/pull/4408#issuecomment-1685026164

> Initial focus is not always on screen 0, on stable release wayland it was
Windows swap monitors when screen indexes are changed (e.g. swapping monitor positions with wdispays also swaps the windows which should not happen)

Come on github!

**Comment by jwijenbergh** [comment]
Confirmed fully fixed now. 

> Windows swap monitors when screen indexes are changed (e.g. swapping monitor positions with wdispays also swaps the windows which should not happen)

This might still be a problem though but this was not the original issue
