### ISSUE TITLE
widget.GenPollCommand output Attribute Error

### ISSUE THREAD

**Issue by kalkulusrampage** [qtile/qtile#4430]
### The issue:

qtile version: 0.22.1

I did it with widget.GenPollText, now I am trying to replicate with GenPollCommand but I can't try with the widget because always give an error:

I tried with both the one commented and one empty and one with less args all give me attribute rror.
```python
#widget.CurrentLayout(),
 15                 widget.GenPollText(
 14                         update_interval=0.02,
 13  func=lambda: subprocess.check_output("/home/josemaria/getvolumen.sh").decode("utf-8").strip(),
 12                         shell=True),
 11                 #widget.GenPollCommand(
 10                 #       update_interval=1,
  9                 #       cmd="echo $(wpctl get-volume @DEFAULT_AUDIO_SINK@ | cut -d. -f2)%",
  8                 #       shell=True),
  7                 widget.DF(visible_on_warn=False,partition="/home"),
  6                 widget.GroupBox(),
  5                 widget.NvidiaSensors(),
  4                 widget.WindowName(padding=15,background=luna_colors[3],foreground=luna_colors[0]),
  3                 #widget.TextBox("A sword behind every blade of grass", foreground="#d75f5f"),
  2                 #NB Systray is incompatible with Wayland, consider using StatusNotifier instead
  1                 widget.Systray(background=luna_colors[3],padding=15),
163                 widget.GenPollCommand(shell=True),
``` 

Here the log output:
<details><summary>Details</summary>
<p>

2023-08-30 22:05:49,550 ERROR libqtile manager.py:cmd_reload_config():L266 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 264, in cmd_reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 125, in load
    self._reload_config_submodules(path)
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 114, in _reload_config_submodules
    importlib.reload(module)
  File "/usr/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/josemaria/.config/qtile/config.py", line 163, in <module>
    widget.GenPollCommand(shell=True),
    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/utils.py", line 213, in __getattr__
    raise AttributeError
AttributeError
2023-08-30 22:05:49,551 WARNING libqtile utils.py:send_notification():L236 dbus-next is not installed. Unable to send notifications.

</p>
</details> 

### Required:

- [X] I have searched past issues to see if this bug has already been reported.

**Comment by elParaguayo** [comment]
`GenPollCommand` is not available in 0.22.1. It was added after that release.

**Comment by ramnes** [comment]
Going ahead and closing then! Feel free to comment and I'll be happy to reopen if needed.

**Comment by kalkulusrampage** [comment]
thanks for quick response
