### ISSUE TITLE
Qtile not starting after upgrading python-xcffib

### ISSUE THREAD

**Issue by arthchan** [qtile/qtile#4492]
### Issue description

Recently, I updated python-xcffib from from version 1.3.0-1 to 1.4.0-1. After a system (X11 on Arch) reboot, Qtile was unable to start, and I was redirected to the login page (lightdm) again. I was stuck in the login loop no matter how many times I logged in. After reading the log, I decided to downgrade python-xcffib back to 1.3.0-1 and finally Qtile started normally.

As python-xcffib is a dependency for Qtile, perhaps you should downgrade the package if encountering the same problem with me, or even not to upgrade the package in question at the first place.

I will try to further look into the details and see if I can find the actual problem and fix it.

### Version

0.22.1

### Backend

X11 (default)

### Logs

```text
[Date & Time] ERROR libqtile start.py:start():L92 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 582, in wrapper
    return wrapper
                   
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 692, in request_check
    """ Hoist an xcb_generic_event_t to the right xcffib structure. """
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 656, in _process_error
    buf = CffiUnpacker(c_error)
    ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 570, in invalid
    """
        
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/scripts/start.py", line 90, in start
    q.loop()
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 198, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 226, in async_loop
    self.finalize()
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 306, in finalize
    self.core.finalize()
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 173, in finalize
    ).check()
      ^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 340, in check
    return self.conn.discard_reply(self.sequence)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 584, in wrapper
    @ensure_connected
                ^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 570, in invalid
    """
        
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ramnes** [comment]
Upgrade Qtile to 0.23

**Comment by arthchan** [comment]
@ramnes Thanks a lot!!! Actually there is a post #4491 that has raised this problem. It's my fault for overlooking it. Pacman only has qtile 0.22.1 as the latest version so I think I will upgrade them in one go as you suggested.
