### ISSUE TITLE
PulseVolume Import Error after update

### ISSUE THREAD

**Issue by Abhishek-Raj-Poudel** [qtile/qtile#4497]
### Issue description

After updating my system I got a Import Error:PulseVolume in my widget bar, I checked the qtile logs and found out that I didn't have **pulsectl_asyncio** package which I installed with aur(this could be the problem cause It was a outdated version but Aur only had that version so i installed it) and some more error started appearing . Please help cause I haven't used python that much and didn't understand the error as well. Thankyou

### Version

0.23.0

### Backend

X11 (default)

### Config

```python
from libqtile import bar, layout, widget
from libqtile.config import Click, Drag, Group, Key, Match, Screen
from libqtile.lazy import lazy
from libqtile.utils import guess_terminal

from themes import Dracula, Midnight, Monokai, Tomorrow, One_dark, Nordic, Catppuccin, Custom

from keyBinding import bindings, mod

from qtile_extras.widget import WiFiIcon
from widgets.battery_text import BatteryText


import os
from datetime import datetime

# theme to choose
# theme = Custom
theme =Custom

# Keybindings
keys = bindings


groups = [Group(i) for i in "1234567"]

for i in groups:
    keys.extend(
        [
            Key(
                [mod],
                i.name,
                lazy.group[i.name].toscreen(),
                desc="Switch to group {}".format(i.name),
            ),
            Key([mod, "shift"], i.name, lazy.window.togroup(i.name),
                desc="move focused window to group {}".format(i.name)),
        ]
    )



layouts = [
    layout.MonadTall(
        #border_focus=theme["BG1"],
        border_focus="00000033",
        border_width=0,
        margin=6,
        ),

    layout.Max(),
]



widget_defaults = dict(
    font="JetBrains Mono Nerd",
    fontsize=14,
    padding=4,
    border_color= theme["blue"],
)
extension_defaults = widget_defaults.copy()

screens = [
    Screen(
        bottom=bar.Bar(
            [
                widget.TextBox("•", foreground=theme["BG1"]),
                widget.TextBox("",foreground=theme["magenta"],padding=7),
                widget.Clock(format="%Y-%m-%d %a"),
                widget.TextBox("|", foreground=theme["BG1"]),

                # Time
                widget.TextBox("",foreground=theme["magenta"],padding=7),
                widget.Clock(format="%I:%M %p"),

                widget.Spacer(),

                widget.GroupBox(
                    highlight_method='text',
                    foreground=theme["foreground"],
                    active = theme["white"],
                    inactive = theme["BG6"],
                    this_current_screen_border= theme["yellow"],
                    urgent_border = theme["red"],
                    urgent_text = theme["red"],
                    padding_x = 14
                    
                    ),

                widget.Spacer(),
               # widget.Memory(),
                 #: Wifi
                WiFiIcon(interface='wlp4s0',padding_x=8,padding_y=8,
                active_colour=theme["magenta"],inactive_colour=theme['BG1']),
                widget.TextBox("|", foreground=theme["BG1"]),

#: for audio
                widget.TextBox("",foreground=theme["magenta"],padding=7),
                # widget.PulseVolume(foreground=theme["magenta"]),
                widget.Volume(channel='IEC958'),
                widget.TextBox("|", foreground=theme["BG1"]),

#: for brightness
                widget.TextBox("󰃝", foreground=theme["magenta"],padding=7),
                widget.Backlight(
                    brightness_file="/sys/class/backlight/amdgpu_bl1/brightness",
                    max_brightness_file="/sys/class/backlight/amdgpu_bl1/max_brightness",
                    ),
                widget.TextBox("|", foreground=theme["BG1"]),
# cpu 
                widget.TextBox("",padding=7 ),
                widget.CPU(format='{load_percent}%'),
                widget.TextBox("•", foreground=theme["BG1"]),

# cpu temp
                widget.ThermalSensor(),
                widget.TextBox("|", foreground=theme["BG1"]),

BatteryText(
                    10,
                    foreground=theme["foreground"],
                    fontsize=14,
                ),
#: Check Updates
                # widget.TextBox("",foreground=theme["blue"],padding=7),
                widget.CheckUpdates(display_format='  {updates}',distro='Arch_yay',foreground=theme["yellow"]),
                widget.TextBox("•", foreground=theme["BG1"]),
            ],
            30,
            background="1f1d2ecc",
        ),
    ),
]

# Drag floating layouts.
mouse = [
    Drag([mod], "Button1", lazy.window.set_position_floating(), start=lazy.window.get_position()),
    Drag([mod], "Button3", lazy.window.set_size_floating(), start=lazy.window.get_size()),
    Click([mod], "Button2", lazy.window.bring_to_front()),
]

dgroups_key_binder = None
dgroups_app_rules = []  # type: list
follow_mouse_focus = True
bring_front_click = False
cursor_warp = False
floating_layout = layout.Floating(
    float_rules=[
        # Run the utility of `xprop` to see the wm class and name of an X client.
        *layout.Floating.default_float_rules,
        Match(wm_class="confirmreset"),  # gitk
        Match(wm_class="makebranch"),  # gitk
        Match(wm_class="maketag"),  # gitk
        Match(wm_class="ssh-askpass"),  # ssh-askpass
        Match(title="branchdialog"),  # gitk
        Match(title="pinentry"),  # GPG key password entry
    ]
)
auto_fullscreen = True
focus_on_window_activation = "smart"
reconfigure_screens = True

# If things like steam games want to auto-minimize themselves when losing
# focus, should we respect this or not?
auto_minimize = True

# When using the Wayland backend, this can be used to configure input devices.
wl_input_rules = None

# XXX: Gasp! We're lying here. In fact, nobody really uses or cares about this
# string besides java UI toolkits; you can see several discussions on the
# mailing lists, GitHub issues, and other WM documentation that suggest setting
# this string if your java app doesn't work correctly. We may as well just lie
# and say that we're a working one by default.
#
# We choose LG3D to maximize irony: it is a 3D non-reparenting WM written in
# java that happens to be on java's whitelist.
wmname = "LG3D"
```

### Logs

```text
2023-10-07 19:22:28,476 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 132, in load
    config = importlib.reload(sys.modules[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/abhi/.config/qtile/config.py", line 100, in <module>
    widget.PulseVolume(foreground=theme["magenta"]),
    ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/utils.py", line 259, in __getattr__
    return import_class(module_path, name, fallback=fallback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/utils.py", line 230, in import_class
    module = importlib.import_module(module_path, __package__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/libqtile/widget/pulse_volume.py", line 21, in <module>
    import pulsectl_asyncio
  File "/usr/lib/python3.11/site-packages/pulsectl_asyncio/__init__.py", line 1, in <module>
    from .pulsectl_async import PulseAsync
  File "/usr/lib/python3.11/site-packages/pulsectl_asyncio/pulsectl_async.py", line 66, in <module>
    class PulseAsync(object):
  File "/usr/lib/python3.11/site-packages/pulsectl_asyncio/pulsectl_async.py", line 311, in PulseAsync
    card_profile_set_by_index = _pulse_method_call(
                                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pulsectl_asyncio/pulsectl_async.py", line 303, in _pulse_method_call
    func_args = list(inspect.getargspec(func or (lambda: None)))
                     ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
The AUR package is out of date. The Arch packagers will hopefully update and put in the main repo soon.

You need pulsectl_asyncio >= 1.0.0.

**Comment by elParaguayo** [comment]
This `PKGBUILD` file should work for now
```
pkgname=python-pulsectl-asyncio-git
_gitname=pulsectl-asyncio
pkgver=20230601
pkgrel=1
pkgdesc="Asyncio frontend for pulsectl, a Python bindings library for PulseAudio (libpulse) -- git version"
arch=('x86_64')
url="https://github.com/mhthies/pulsectl-asyncio"
license=('MIT')
depends=('python>=3.6' 'python-pulsectl>=1:21.5.18')
makedepends=('git' 'python-setuptools' 'python-build' 'python-installer')
provides=('python-pulsectl-asyncio')
conflicts=('python-pulsectl-asyncio')
source=('git+https://github.com/mhthies/pulsectl-asyncio.git')
md5sums=('SKIP')

pkgver() {
  cd "${srcdir}/${_gitname}"
  git log -1 --format="%cd" --date=short | sed 's|-||g'
}

build() {
  cd "$_gitname"
  python -m build --wheel
}

package()
{
  cd "$_gitname"
  python -m installer --destdir="$pkgdir" dist/*.whl
}
```

**Comment by Abhishek-Raj-Poudel** [comment]
It Works now . Thankyou so much

**Comment by bodograumann** [comment]
The aur package fails to install with yay for me with
> python: can't open file '/home/bodo/.cache/yay/python-pulsectl-asyncio-git/src/pulsectl-asyncio/setup.py': [Errno 2] No such file or directory

**Comment by elParaguayo** [comment]
The AUR package doesn't work but you can use the modified PKGBUILD file above.
