### ISSUE TITLE
StatusNotifier couldn't be load in wayland

### ISSUE THREAD

**Issue by superiums** [qtile/qtile#4503]
### Issue description

StatusNotifier couldn't be load in wayland

### Version

0.23.0

### Backend

Wayland (experimental)

### Config

```python
widget.StatusNotifier(),
```

### Logs

```text
2023-10-08 13:07:35,608 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/statusnotifier.py", line 666, in _config_async
    await host.start(on_item_added=draw, on_item_removed=draw, on_icon_changed=draw)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/statusnotifier.py", line 548, in start
    self.bus = await MessageBus().connect()
                     ^^^^^^^^^^^^
  File "/home/shvo/.local/lib/python3.11/site-packages/dbus_next/aio/message_bus.py", line 122, in __init__
    super().__init__(bus_address, bus_type, ProxyObject)
  File "/home/shvo/.local/lib/python3.11/site-packages/dbus_next/message_bus.py", line 85, in __init__
    self._setup_socket()
  File "/home/shvo/.local/lib/python3.11/site-packages/dbus_next/message_bus.py", line 575, in _setup_socket
    raise err
  File "/home/shvo/.local/lib/python3.11/site-packages/dbus_next/message_bus.py", line 548, in _setup_socket
    self._sock.connect(filename)
FileNotFoundError: [Errno 2] 没有那个文件或目录
2023-10-08 13:08:09,359 ERROR wlroots log.py:log_func_callback():L15 [libseat] [libseat/backend/logind.c:199] Could not close device: 连接被对方重设
2023-10-08 13:08:09,360 ERROR wlroots log.py:log_func_callback():L15 [backend/session/session.c:356] Failed to close device 44: 成功
2023-10-08 13:08:09,360 ERROR wlroots log.py:log_func_callback():L15 [libseat] [libseat/backend/logind.c:199] Could not close device: 传输端点尚未连接
2023-10-08 13:08:09,360 ERROR wlroots log.py:log_func_callback():L15 [backend/session/session.c:356] Failed to close device 41: 成功
2023-10-08 13:08:09,360 ERROR wlroots log.py:log_func_callback():L15 [libseat] [libseat/backend/logind.c:199] Could not close device: 传输端点尚未连接
2023-10-08 13:08:09,360 ERROR wlroots log.py:log_func_callback():L15 [backend/session/session.c:356] Failed to close device 45: 成功
2023-10-08 13:08:09,360 ERROR wlroots log.py:log_func_callback():L15 [libseat] [libseat/backend/logind.c:199] Could not close device: 传输端点尚未连接
2023-10-08 13:08:09,360 ERROR wlroots log.py:log_func_callback():L15 [backend/session/session.c:356] Failed to close device 36: 成功
2023-10-08 13:08:09,361 ERROR wlroots log.py:log_func_callback():L15 [libseat] [libseat/backend/logind.c:199] Could not close device: 传输端点尚未连接
2023-10-08 13:08:09,361 ERROR wlroots log.py:log_func_callback():L15 [backend/session/session.c:356] Failed to close device 37: 成功
2023-10-08 13:08:09,361 ERROR wlroots log.py:log_func_callback():L15 [libseat] [libseat/backend/logind.c:199] Could not close device: 传输端点尚未连接
2023-10-08 13:08:09,361 ERROR wlroots log.py:log_func_callback():L15 [backend/session/session.c:356] Failed to close device 40: 成功
2023-10-08 13:08:09,361 ERROR wlroots log.py:log_func_callback():L15 [libseat] [libseat/backend/logind.c:199] Could not close device: 传输端点尚未连接
2023-10-08 13:08:09,361 ERROR wlroots log.py:log_func_callback():L15 [backend/session/session.c:356] Failed to close device 42: 成功
2023-10-08 13:08:09,361 ERROR wlroots log.py:log_func_callback():L15 [libseat] [libseat/backend/logind.c:199] Could not close device: 传输端点尚未连接
2023-10-08 13:08:09,361 ERROR wlroots log.py:log_func_callback():L15 [backend/session/session.c:356] Failed to close device 43: 成功
2023-10-08 13:08:09,361 ERROR wlroots log.py:log_func_callback():L15 [libseat] [libseat/backend/logind.c:199] Could not close device: 传输端点尚未连接
2023-10-08 13:08:09,361 ERROR wlroots log.py:log_func_callback():L15 [backend/session/session.c:356] Failed to close device 39: 成功
2023-10-08 13:08:09,361 ERROR wlroots log.py:log_func_callback():L15 [libseat] [libseat/backend/logind.c:199] Could not close device: 传输端点尚未连接
2023-10-08 13:08:09,361 ERROR wlroots log.py:log_func_callback():L15 [backend/session/session.c:356] Failed to close device 38: 成功
2023-10-08 13:08:09,409 ERROR wlroots log.py:log_func_callback():L15 [backend/drm/atomic.c:72] connector eDP-1: Atomic commit failed: 权限不够
2023-10-08 13:08:09,410 ERROR wlroots log.py:log_func_callback():L15 [backend/drm/drm.c:991] connector eDP-1: Failed to disable CRTC 67
2023-10-08 13:08:09,411 ERROR wlroots log.py:log_func_callback():L15 [libseat] [libseat/backend/logind.c:199] Could not close device: 传输端点尚未连接
2023-10-08 13:08:09,411 ERROR wlroots log.py:log_func_callback():L15 [backend/session/session.c:356] Failed to close device 14: 成功
2023-10-08 13:08:09,412 ERROR wlroots log.py:log_func_callback():L15 [libseat] [libseat/backend/logind.c:365] Could not release control of session: 传输端点尚未连接
2023-10-08 13:08:09,412 ERROR libqtile base.py:on_done():L857 Failed to reschedule timer for net.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 851, in on_done
    self.update(result)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 755, in update
    old_width = self.layout.width
                ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base/drawer.py", line 421, in width
    return self.layout.get_pixel_size()[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/pangocffi.py", line 137, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2023-10-08 13:08:09,413 ERROR libqtile base.py:on_done():L857 Failed to reschedule timer for cpu.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 851, in on_done
    self.update(result)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 755, in update
    old_width = self.layout.width
                ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base/drawer.py", line 421, in width
    return self.layout.get_pixel_size()[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/pangocffi.py", line 137, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2023-10-08 13:08:09,414 ERROR libqtile base.py:on_done():L857 Failed to reschedule timer for memory.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 851, in on_done
    self.update(result)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 755, in update
    old_width = self.layout.width
                ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base/drawer.py", line 421, in width
    return self.layout.get_pixel_size()[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/pangocffi.py", line 137, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2023-10-08 13:08:09,414 ERROR libqtile base.py:on_done():L857 Failed to reschedule timer for cmus.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 851, in on_done
    self.update(result)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 755, in update
    old_width = self.layout.width
                ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base/drawer.py", line 421, in width
    return self.layout.get_pixel_size()[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/pangocffi.py", line 137, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
2023-10-08 13:08:09,417 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2023-10-08 13:08:09,464 ERROR wlroots log.py:log_func_callback():L15 [backend/drm/atomic.c:72] connector eDP-1: Atomic commit failed: Permission denied
2023-10-08 13:08:09,464 ERROR wlroots log.py:log_func_callback():L15 [backend/drm/drm.c:991] connector eDP-1: Failed to disable CRTC 67
2023-10-08 13:08:09,464 ERROR wlroots log.py:log_func_callback():L15 [libseat] [libseat/backend/logind.c:199] Could not close device: Transport endpoint is not connected
2023-10-08 13:08:09,464 ERROR wlroots log.py:log_func_callback():L15 [backend/session/session.c:356] Failed to close device 14: Success
2023-10-08 13:08:09,464 ERROR wlroots log.py:log_func_callback():L15 [libseat] [libseat/backend/logind.c:365] Could not release control of session: Transport endpoint is not connected
2023-10-08 13:08:09,476 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2023-10-08 14:04:48,664 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/statusnotifier.py", line 666, in _config_async
    await host.start(on_item_added=draw, on_item_removed=draw, on_icon_changed=draw)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/statusnotifier.py", line 548, in start
    self.bus = await MessageBus().connect()
                     ^^^^^^^^^^^^
  File "/home/shvo/.local/lib/python3.11/site-packages/dbus_next/aio/message_bus.py", line 122, in __init__
    super().__init__(bus_address, bus_type, ProxyObject)
  File "/home/shvo/.local/lib/python3.11/site-packages/dbus_next/message_bus.py", line 85, in __init__
    self._setup_socket()
  File "/home/shvo/.local/lib/python3.11/site-packages/dbus_next/message_bus.py", line 575, in _setup_socket
    raise err
  File "/home/shvo/.local/lib/python3.11/site-packages/dbus_next/message_bus.py", line 548, in _setup_socket
    self._sock.connect(filename)
FileNotFoundError: [Errno 2] 没有那个文件或目录
2023-10-08 14:42:09,919 WARNING libqtile base.py:__getattr__():L271 Deprecation Warning: commands exposed via IPC no longer use the 'cmd_' prefix. Please replace 'cmd_spawn' with 'spawn' in your code.
2023-10-08 14:44:51,577 ERROR wlroots log.py:log_func_callback():L15 [libinput] event15 - MSFT0001:00 04F3:3138 Touchpad: client bug: event processing lagging behind by 66ms, your system is too slow

2023-10-08 14:46:50,736 ERROR wlroots log.py:log_func_callback():L15 [xwayland/xwm.c:1522] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 890, value 12583087
2023-10-08 14:46:50,737 ERROR wlroots log.py:log_func_callback():L15 [xwayland/xwm.c:1522] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 891, value 12583087
2023-10-08 14:48:37,962 ERROR wlroots log.py:log_func_callback():L15 [xwayland/xwm.c:1522] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 1031, value 12583088
2023-10-08 14:48:37,962 ERROR wlroots log.py:log_func_callback():L15 [xwayland/xwm.c:1522] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 1032, value 12583088
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Is dbus running?

**Comment by superiums** [comment]
i've tried to run qtile like this
```
dbus-launch qtile -b wayland
```
but found xwayland takes 100%cpu of 2 core.
so i just run it without dbus-launch. 

let me try export dbus address manually.

**Comment by elParaguayo** [comment]
OK. This isn't a qtile bug. If dbus isn't running, the widget can't work.

**Comment by superiums** [comment]
thanks.
after launch dbus, the error was gone.
but new err reported:
```
2023-10-08 15:26:13,812 WARNING libqtile statusnotifier.py:start():L172 Cannot find icon in current theme and no icon provided by StatusNotifierItem.
2023-10-08 15:26:13,984 WARNING libqtile statusnotifier.py:start():L172 Cannot find icon in current theme and no icon provided by StatusNotifierItem.
```

**Comment by elParaguayo** [comment]
This is the same issue as your TaskList issue. You don't seem to have any icons installed (or the widget can't find them). 

If you don't pass `theme_path`, (I think) the `pyxdg` library just looks in `/usr/share/icons/hicolor`.

**Comment by superiums** [comment]
after specify path:
```
                    theme_path = "Obsidian-Mint",
                    theme_mode = "preferred"
```

the nm-applet displayed in the tray.
but fcitx not.

**Comment by elParaguayo** [comment]
`theme_mode = "preferred"` is just for `TaskList` as icons are disabled by default. That option makes no sense for a tray widget.

Do you know if `fcitx` has an available icon?

I'm not convinced any of this is an issue with the widgets themselves.

**Comment by superiums** [comment]
i think the icon is there , because it works in waybar. xfce.
it's a keyboard icon.

**Comment by superiums** [comment]
now, also i agree it may be not an issue of qtile.

**Comment by elParaguayo** [comment]
OK - `fcitx` is looking for an icon called `input-keyboard`. Does this exist on your system (e.g. with `getIconPath`)?

**Comment by superiums** [comment]
```python
>>> from xdg.IconTheme import getIconPath
>>> getIconPath('input-keyboard')
'/usr/share/icons/hicolor/48x48/status/input-keyboard.png'
```
it is there.

```json
                widget.StatusNotifier(
                    # theme_path = "Obsidian-Mint",
                    # theme_path = "/usr/share/icons/hicolor",
                    # theme_mode = "preferred"
                    ),
```
comment the config or not, seems act the same.

**Comment by elParaguayo** [comment]
Ok. Let me investigate when I have some time.

**Comment by elParaguayo** [comment]
Use `icon_theme="Obsidian-Mint"` not `theme_path`.

**Comment by ramnes** [comment]
Original issue has been resolved.
