### ISSUE TITLE
Volume and Chord widget freez qtile on wayland

### ISSUE THREAD

**Issue by superiums** [qtile/qtile#4505]
### Issue description

i'm on wayland.

after tens of tries, i finally found:
my crash/freez of qtile , was caused by these widget:
- volume
- chord

i use wirepipe instead of pulseaudio, no matter it was started or not, it freez my desktop. all hot keys and mouse not response.

### Version

0.23.0

### Backend

Wayland (experimental)

### Config

```python
as it freezed the desktop, no keys or mouse response, i had to press power button.
so i commented it


                # widget.Chord(
                #     chords_colors={
                #         "launch": ("#ff0000", "#ffffff"),
                #     },
                #     name_transform=lambda name: name.upper(),
                # ),

                # widget.Volume(
                #          foreground = colors[7],
                #          fmt = '🕫  Vol: {}',
                #     ),
```

### Logs

```text
log for volume

2023-10-05 18:28:32,933 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2023-10-05 18:29:26,083 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/wayland/output.py", line 113, in _on_frame
    with self.wlr_output as wlr_output:
  File "/usr/lib/python3.11/site-packages/wlroots/wlr_types/output.py", line 162, in __exit__
    self.commit()
  File "/usr/lib/python3.11/site-packages/wlroots/wlr_types/output.py", line 197, in commit
    raise RuntimeError("Rendering on output failed")
RuntimeError: Rendering on output failed
2023-10-05 18:29:26,087 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/wayland/output.py", line 113, in _on_frame
    with self.wlr_output as wlr_output:
  File "/usr/lib/python3.11/site-packages/wlroots/wlr_types/output.py", line 162, in __exit__
    self.commit()
  File "/usr/lib/python3.11/site-packages/wlroots/wlr_types/output.py", line 197, in commit
    raise RuntimeError("Rendering on output failed")
RuntimeError: Rendering on output failed




log for chord
```bash
2023-10-05 21:00:56,994 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/wayland/window.py", line 176, in _on_destroy
    self.qtile.unmanage(self.wid)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 649, in unmanage
    c.group.remove(c)
  File "/usr/lib/python3.11/site-packages/libqtile/group.py", line 286, in remove
    i.remove(win)
  File "/usr/lib/python3.11/site-packages/libqtile/layout/tree.py", line 444, in remove
    self.draw_panel()
  File "/usr/lib/python3.11/site-packages/libqtile/layout/tree.py", line 460, in draw_panel
    self._tree.draw(self, 0)
  File "/usr/lib/python3.11/site-packages/libqtile/layout/tree.py", line 72, in draw
    top = i.draw(layout, top, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/layout/tree.py", line 225, in draw
    layout._drawer.draw_hbar(layout.section_fg, 0, layout.panel_width, top, linewidth=1)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base.py", line 897, in draw_hbar
    self.set_source_rgb(color)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base.py", line 839, in set_source_rgb
    ctx.set_source_rgba(*utils.rgb(colour))
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_source_rgba'
2023-10-05 21:00:56,996 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/wayland/output.py", line 113, in _on_frame
    with self.wlr_output as wlr_output:
  File "/usr/lib/python3.11/site-packages/wlroots/wlr_types/output.py", line 162, in __exit__
    self.commit()
  File "/usr/lib/python3.11/site-packages/wlroots/wlr_types/output.py", line 197, in commit
    raise RuntimeError("Rendering on output failed")
RuntimeError: Rendering on output failed
2023-10-05 21:00:57,008 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/wayland/output.py", line 113, in _on_frame
    with self.wlr_output as wlr_output:
  File "/usr/lib/python3.11/site-packages/wlroots/wlr_types/output.py", line 162, in __exit__
    self.commit()
  File "/usr/lib/python3.11/site-packages/wlroots/wlr_types/output.py", line 197, in commit
    raise RuntimeError("Rendering on output failed")
RuntimeError: Rendering on output failed
```
```


### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
It's weird as there's nothing specific to those widgets in the logs. In fact, the chord log shows the crash happened in the layout.

I'll need to defer these to @m-col and @jwijenbergh to see if they can recreate.
