### ISSUE TITLE
ModuleNotFoundError in Arch package

### ISSUE THREAD

**Issue by g-wizzy** [qtile/qtile#4512]
### Issue description

Hello,

I've been using qtile for a while now, and I love it. It suddenly stopped working today and I'm not quite sure how to go around and solve it.

I installed qtile on my Manjaro machine through pacman, and it is the 0.22.1-4 version. When starting my session today, I was booted back to the login screen. The qtile logs were empty. Launching `qtile start` from a console session gave me the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/pangocffi.py", line 51, in <module>
    from libqtile._ffi_pango import ffi
  File "/usr/lib/python3.11/site-packages/libqtile/_ffi_pango.py", line 3, in <module>
    from cairocffi._generated.ffi import ffi as _ffi0
ModuleNotFoundError: No module named 'cairocffi._generated'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/qtile", line 5, in <module>
    from libqtile.scripts.main import main
  File "/usr/lib/python3.11/site-packages/libqtile/scripts/main.py", line 6, in <module>
    from libqtile.scripts import check, cmd_obj, migrate, run_cmd, shell, start, top
  File "/usr/lib/python3.11/site-packages/libqtile/scripts/check.py", line 27, in <module>
    from libqtile import confreader
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 31, in <module>
    from libqtile.backend.x11 import core
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 37, in <module>
    from libqtile.backend import base
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base.py", line 11, in <module>
    from libqtile import drawer, pangocffi, utils
  File "/usr/lib/python3.11/site-packages/libqtile/drawer.py", line 35, in <module>
    from libqtile import pangocffi, utils
  File "/usr/lib/python3.11/site-packages/libqtile/pangocffi.py", line 53, in <module>
    raise ImportError("No module named libqtile._ffi_pango, be sure to run `./scripts/ffibuild`")
ImportError: No module named libqtile._ffi_pango, be sure to run `./scripts/ffibuild`
```

I tried reinstalling qtile as well as python-cairocffi, python-cffi and pango, without encountering any problem, but to no success.

Does anyone know where could the problem lie ?

### Version

0.22.1-4

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
You've upgraded cairocffi to 1.6.0 (and probably xcffib to 1.4.0) but qtile 0.22.1 doesn't support those versions. You need 0.23.0 which is in the Arch repos but maybe hasn't reached Manjaro's yet.

**Comment by dipeshkaphle** [comment]
Was able to solve this by downloading `downgrade`, then ran `downgrade qtile` and selected the most recent version(which i guess fetches from arch repositories)

**Comment by yobleck** [comment]
Fellow (annoyed) Manjaro user here can also confirm. This appears to be a classic case of Manjaro not updating Arch packages at the same rate. according to Manjaro's repos (https://packages.manjaro.org/?query=qtile) Qtile 0.23 is stuck in the testing branch >:(
