### ISSUE TITLE
Qtile 0.23 issues when closing window

### ISSUE THREAD

**Issue by dmolin** [qtile/qtile#4518]
### Issue description

Just upgraded to the latest version of Qtile (including the required dependencies).
Upon entering the X11 session, if I open two windows(app) and then close one, the remaining app is not resized to take all the space in the display (it essentially remains with a "hole" in the display where the app/window just closed was placed).
In the Qtile logs I can see this popping up at the same time as I close the application/window:

```
File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 804, in handle_UnmapNotify
    self.qtile.unmanage(event.window)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 712, in unmanage
    c.group.remove(c)
  File "/usr/lib/python3.11/site-packages/libqtile/group.py", line 291, in remove
    i.remove(win)
  File "/home/user/.config/qtile/tabbed.py", line 250, in remove
    self._tabs.pop(win)
KeyError: Window(name='~', wid=37748747)
2023-10-13 21:49:29,157 ERROR libqtile core.py:_xpoll():L370 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 345, in _xpoll
    self.handle_event(event)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 312, in handle_event
    ret = target(event)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 804, in handle_UnmapNotify
    self.qtile.unmanage(event.window)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 712, in unmanage
    c.group.remove(c)
  File "/usr/lib/python3.11/site-packages/libqtile/group.py", line 291, in remove
    i.remove(win)
  File "/home/user/.config/qtile/tabbed.py", line 250, in remove
    self._tabs.pop(win)
KeyError: Window(name='~', wid=37748747)
```

![image](https://github.com/qtile/qtile/assets/861513/33f667ca-0a36-4670-8b0d-b4ebf3390113)

The remaining window gets correctly resized only when I click on it with my mouse
 
This happens only on Qtile 0.23; As soon as I downgrade Qtile to 0.22 (along with its dependencies python-cairocffi and python-xcffib) then all works correctly as expected

### Version

0.23.0

### Backend

X11 (default)

### Logs

```text
File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 804, in handle_UnmapNotify
    self.qtile.unmanage(event.window)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 712, in unmanage
    c.group.remove(c)
  File "/usr/lib/python3.11/site-packages/libqtile/group.py", line 291, in remove
    i.remove(win)
  File "/home/user/.config/qtile/tabbed.py", line 250, in remove
    self._tabs.pop(win)
KeyError: Window(name='~', wid=37748747)
2023-10-13 21:49:29,157 ERROR libqtile core.py:_xpoll():L370 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 345, in _xpoll
    self.handle_event(event)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 312, in handle_event
    ret = target(event)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 804, in handle_UnmapNotify
    self.qtile.unmanage(event.window)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 712, in unmanage
    c.group.remove(c)
  File "/usr/lib/python3.11/site-packages/libqtile/group.py", line 291, in remove
    i.remove(win)
  File "/home/user/.config/qtile/tabbed.py", line 250, in remove
    self._tabs.pop(win)
KeyError: Window(name='~', wid=37748747)
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by dmolin** [comment]
Closing this issue. the error was caused by an external Qtile Layout
