### ISSUE TITLE
Qtile Fails to Load

### ISSUE THREAD

**Issue by mtwb47** [qtile/qtile#4543]
### Issue description

After running an update on openSUSE Tumbleweed and rebooting, qtile fails to load past a black screen.

Qtile installed from the openSUSE main repository, package version attached. I do not have the wayland version enabled, so I cannot test it there. 

### Version

0.22.1-4.2

### Backend

X11 (default)

### Config

```python
#pywal1 config
from typing import List  # noqa: F401
import os
import subprocess
from os import path

from libqtile import bar, layout, widget, hook, qtile
from libqtile.config import Click, Drag, Group, ScratchPad, DropDown, Key, Match, Screen
from libqtile.lazy import lazy
from settings.path import qtile_path
import colors

mod = "mod4"
terminal = "kitty"
clipmenu = "clipmenu"

keys = [
# Open terminal
    Key([mod], "Return", lazy.spawn(terminal)),
    Key([mod], "x", lazy.spawn(clipmenu)),
# Qtile System Actions
    Key([mod, "shift"], "r", lazy.restart()),
    Key([mod, "shift"], "x", lazy.shutdown()),
# Active Window Actions
    Key([mod], "f", lazy.window.toggle_fullscreen()),
    Key([mod], "q", lazy.window.kill()),
    Key([mod, "control"], "h",
        lazy.layout.grow_right(),
        lazy.layout.grow(),
        lazy.layout.increase_ratio(),
        lazy.layout.delete()
        ),
    Key([mod, "control"], "Right",
        lazy.layout.grow_right(),
        lazy.layout.grow(),
        lazy.layout.increase_ratio(),
        lazy.layout.delete()
        ),
    Key([mod, "control"], "l",
        lazy.layout.grow_left(),
        lazy.layout.shrink(),
        lazy.layout.decrease_ratio(),
        lazy.layout.add()
        ),
    Key([mod, "control"], "Left",
        lazy.layout.grow_left(),
        lazy.layout.shrink(),
        lazy.layout.decrease_ratio(),
        lazy.layout.add()
        ),
    Key([mod, "control"], "k",
        lazy.layout.grow_up(),
        lazy.layout.grow(),
        lazy.layout.decrease_nmaster()
        ),
    Key([mod, "control"], "Up",
        lazy.layout.grow_up(),
        lazy.layout.grow(),
        lazy.layout.decrease_nmaster()
        ),
    Key([mod, "control"], "j",
        lazy.layout.grow_down(),
        lazy.layout.shrink(),
        lazy.layout.increase_nmaster()
        ),
    Key([mod, "control"], "Down",
        lazy.layout.grow_down(),
        lazy.layout.shrink(),
        lazy.layout.increase_nmaster()
        ),

# Window Focus (Arrows and Vim keys)
    Key([mod], "Up", lazy.layout.up()),
    Key([mod], "Down", lazy.layout.down()),
    Key([mod], "Left", lazy.layout.left()),
    Key([mod], "Right", lazy.layout.right()),
    Key([mod], "k", lazy.layout.up()),
    Key([mod], "j", lazy.layout.down()),
    Key([mod], "h", lazy.layout.left()),
    Key([mod], "l", lazy.layout.right()),

# Qtile Layout Actions
    Key([mod], "r", lazy.layout.reset()),
    Key([mod], "Tab", lazy.next_layout()),
    Key([mod, "shift"], "f", lazy.layout.flip()),
    Key([mod, "shift"], "space", lazy.window.toggle_floating()),

# Move windows around MonadTall/MonadWide Layouts
    Key([mod, "shift"], "Up", lazy.layout.shuffle_up()),
    Key([mod, "shift"], "Down", lazy.layout.shuffle_down()),
    Key([mod, "shift"], "Left", lazy.layout.swap_left()),
    Key([mod, "shift"], "Right", lazy.layout.swap_right()),
    Key([mod, "shift"], "k", lazy.layout.shuffle_up()),
    Key([mod, "shift"], "j", lazy.layout.shuffle_down()),
    Key([mod, "shift"], "h", lazy.layout.swap_left()),
    Key([mod, "shift"], "l", lazy.layout.swap_right()),
    
# Switch focus to specific monitor (out of three)
    Key([mod], "i", lazy.to_screen(0)),
    Key([mod], "o", lazy.to_screen(1)),

# Switch focus of monitors
    Key([mod], "period", lazy.next_screen()),
    Key([mod], "comma", lazy.prev_screen()),
]

# Create labels for groups and assign them a default layout.
groups = []


group_names = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "minus", "equal", "F1", "F2", "F3", "F4", "F5"]

group_labels = ["󰖟", "", "", "", "", "", "", "", "ﭮ", "", "", "﨣", "F1", "F2", "F3", "F4", "F5"]
#group_labels = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]

group_layouts = ["monadtall", "monadtall", "monadtall", "monadtall", "monadtall", "monadtall", "monadtall", "monadtall", "monadtall", "monadtall", "monadtall", "monadtall", "monadtall", "monadtall", "monadtall", "monadtall", "monadtall"]

# Add group names, labels, and default layouts to the groups object.
for i in range(len(group_names)):
    groups.append(
        Group(
            name=group_names[i],
            layout=group_layouts[i].lower(),
            label=group_labels[i],
        ))

# Add group specific keybindings
for i in groups:
    keys.extend([
        Key([mod], i.name, lazy.group[i.name].toscreen(), desc="Mod + number to move to that group."),
        Key(["mod1"], "Tab", lazy.screen.next_group(), desc="Move to next group."),
        Key(["mod1", "shift"], "Tab", lazy.screen.prev_group(), desc="Move to previous group."),
        Key([mod, "shift"], i.name, lazy.window.togroup(i.name), desc="Move focused window to new group."),
    ])

# Define scratchpads
groups.append(ScratchPad("scratchpad", [
    DropDown("term", "kitty --class=scratch", width=0.8, height=0.8, x=0.1, y=0.1, opacity=1),
    DropDown("term2", "kitty --class=scratch", width=0.8, height=0.8, x=0.1, y=0.1, opacity=1),
    DropDown("ranger", "kitty --class=ranger -e ranger", width=0.8, height=0.8, x=0.1, y=0.1, opacity=0.9),
    DropDown("volume", "kitty --class=volume -e pulsemixer", width=0.8, height=0.8, x=0.1, y=0.1, opacity=0.9),
    DropDown("mus", "kitty --class=mus -e flatpak run io.github.hrkfdn.ncspot", width=0.8, height=0.8, x=0.1, y=0.1, opacity=0.9),
    DropDown("news", "kitty --class=news -e newsboat", width=0.8, height=0.8, x=0.1, y=0.1, opacity=0.9),

]))

# Scratchpad keybindings
keys.extend([
    Key([mod], "n", lazy.group['scratchpad'].dropdown_toggle('term')),
    Key([mod], "c", lazy.group['scratchpad'].dropdown_toggle('ranger')),
    Key([mod], "v", lazy.group['scratchpad'].dropdown_toggle('volume')),
    Key([mod], "m", lazy.group['scratchpad'].dropdown_toggle('mus')),
    Key([mod], "b", lazy.group['scratchpad'].dropdown_toggle('news')),
    Key([mod, "shift"], "n", lazy.group['scratchpad'].dropdown_toggle('term2')),
])

colors = []
cache='/home/matt/.cache/wal/colors'
def load_colors(cache):
    with open(cache, 'r') as file:
        for i in range(8):
            colors.append(file.readline().strip())
    colors.append('#ffffff')
    lazy.reload()
load_colors(cache)

# Define layouts and layout themes
layout_theme = {
        "margin":20,
        "border_width": 4,
        "border_focus": colors[3],
        "border_normal": colors[1]
    }

layouts = [
    layout.MonadTall(**layout_theme),
    layout.MonadWide(**layout_theme),
    layout.MonadThreeCol(**layout_theme),
    layout.MonadWide(**layout_theme),
    layout.Floating(**layout_theme),
    layout.Spiral(**layout_theme),
    layout.RatioTile(**layout_theme),
    layout.Max(**layout_theme)
]

# Mouse callback functions
def launch_menu():
    qtile.cmd_spawn("rofi -show drun -show-icons")

# Define Widgets
widget_defaults = dict(
    font="JetBrainsMono Nerd Font Mono",
    fontsize = 12,
    padding = 2,
    background=colors[0]
)

def init_widgets_list(monitor_num):
    widgets_list = [
        widget.GroupBox(
            font="JetBrainsMono Nerd Font Mono",
            fontsize = 20,
            margin_y = 4,
            margin_x = 4,
            padding_y = 6,
            padding_x = 6,
            borderwidth = 2,
            disable_drag = True,
            active = colors[1],
            inactive = colors[1],
            hide_unused = True,
            rounded = False,
            highlight_method = "line",
     	    block_highlight_text_color = colors[4],
            highlight_color = [colors[0], colors[0]],
            this_current_screen_border = colors[7],
            this_screen_border = colors[4],
            other_screen_border = colors[3],
            other_current_screen_border = colors[3],
            urgent_alert_method = "line",
            urgent_border = colors[6],
            urgent_text = colors[1],
            foreground = colors[8],
            background = colors[0],
            use_mouse_wheel = False
        ),
        widget.Sep(linewidth = 1, padding = 10, foreground = colors[0],background = colors[0]),
        widget.OpenWeather(
            app_key = "4cf3731a25d1d1f4e4a00207afd451a2",
            cityid = "4997193",
            format = '{icon} {main_temp}°',
            metric = False,
            font = "JetBrainsMono Nerd Font Mono",
            fontsize = 13,
            foreground = colors[8],
        ),
        widget.Sep(linewidth = 1, padding = 10, foreground = colors[0],background = colors[0]),
        widget.TaskList(
            icon_size = 13,
            font = "JetBrainsMono Nerd Font Mono",
            fontsize= 13,
            foreground = colors[8],
            background = colors[3],
            borderwidth = 0,
            border = colors[0],
            margin_y = -6,
            margin = 0,
            padding = 8,
            highlight_method = "block",
            title_width_method = "uniform",
            urgent_alert_method = "border",
            urgent_border = colors[0],
            rounded = False,
            txt_floating = "🗗 ",
            txt_maximized = "🗖 ",
            txt_minimized = "🗕 ",
        ),
        widget.TextBox(text = "󰕾", fontsize = 25, font = "JetBrainsMono Nerd Font Mono", foreground = colors[6]),
        widget.PulseVolume(
                    foreground=colors[8],
                    padding=10,
                ),
        widget.Sep(linewidth = 1, padding = 10, foreground = colors[0],background = colors[0]),
        widget.Sep(linewidth = 0, padding = 10),
        widget.TextBox(text = "", fontsize = 20, font = "JetBrainsMono Nerd Font Mono", foreground = colors[5]),
        widget.CPU(
            font = "JetBrainsMono Nerd Font Mono",
            update_interval = 1.0,
            format = '{load_percent}%',
            foreground = colors[8],
            padding = 5
        ),
        widget.Sep(linewidth = 0, padding = 10),
        widget.TextBox(text = "", fontsize = 20, font = "JetBrainsMono Nerd Font Mono", foreground = colors[7]),
        widget.Memory(
            font = "JetBrainsMono Nerd Font Mono",
            foreground = colors[8],
            format = '{MemUsed: .0f}{mm} /{MemTotal: .0f}{mm}',
            measure_mem='G',
            padding = 5,
        ),
        widget.Sep(linewidth = 0, padding = 10),
        widget.TextBox(text = "", fontsize = 20, font = "JetBrainsMono Nerd Font Mono", foreground = colors[6]),
        widget.Clock(format='%I:%M %p', font = "JetBrainsMono Nerd Font Mono", padding = 10, foreground = colors[8]),
       # widget.Systray(background = colors[0], icon_size = 20, padding = 4),
        widget.Sep(linewidth = 1, padding = 10, foreground = colors[0], background = colors[0]),
        widget.CurrentLayoutIcon(scale = 0.5, foreground = colors[0], background = colors[4], padding = 10,),
    ]

    return widgets_list

def init_secondary_widgets_list(monitor_num):
    secondary_widgets_list = init_widgets_list(monitor_num)
#    del secondary_widgets_list[20:21]
    return secondary_widgets_list

widgets_list = init_widgets_list("1")
secondary_widgets_list = init_secondary_widgets_list("2")

screens = [
    Screen(top=bar.Bar(widgets=widgets_list, size=25, background=colors[0], margin=0, opacity=0.8),),
    Screen(top=bar.Bar(widgets=secondary_widgets_list, size=25, background=colors[0], margin=0, opacity=0.8),),
    ]

# Drag floating layouts.
mouse = [
    Drag([mod], "Button1", lazy.window.set_position_floating(),
         start=lazy.window.get_position()),
    Drag([mod], "Button3", lazy.window.set_size_floating(),
         start=lazy.window.get_size()),
    Click([mod], "Button2", lazy.window.bring_to_front())
]

@hook.subscribe.startup_once
def autostart():
   home = os.path.expanduser('~/.config/qtile/scripts/autostart.sh')
   subprocess.run([home])

dgroups_key_binder = None
dgroups_app_rules = []  # type: List
follow_mouse_focus = True
bring_front_click = False
cursor_warp = False
floating_layout = layout.Floating(float_rules=[
    *layout.Floating.default_float_rules,
    Match(wm_class='confirmreset'),  # gitk
    Match(wm_class='makebranch'),  # gitk
    Match(wm_class='maketag'),  # gitk
    Match(wm_class='ssh-askpass'),  # ssh-askpass
    Match(title='branchdialog'),  # gitk
    Match(title='pinentry'),  # GPG key password entry
], fullscreen_border_width = 0, border_width = 0)
auto_fullscreen = True
focus_on_window_activation = "smart"
reconfigure_screens = True

auto_minimize = True
wmname = "Qtile 0.21.0"
```

### Logs

```text
2023-10-25 01:44:35,359 ERROR libqtile core.py:get_interesting_pid():L815 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/core.py", line 294, in _xpoll
    event = self.conn.conn.poll_for_event()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 580, in wrapper
    finally:
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 570, in invalid
    """
        
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/core.py", line 813, in get_interesting_pid
    return win.window.get_net_wm_pid()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/xproto.py", line 2836, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 392, in send_request
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 580, in wrapper
    finally:
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 570, in invalid
    """
        
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-10-25 01:44:35,360 ERROR libqtile core.py:get_interesting_pid():L815 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/core.py", line 294, in _xpoll
    event = self.conn.conn.poll_for_event()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 580, in wrapper
    finally:
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 570, in invalid
    """
        
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/core.py", line 813, in get_interesting_pid
    return win.window.get_net_wm_pid()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/xproto.py", line 2836, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 392, in send_request
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 580, in wrapper
    finally:
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 570, in invalid
    """
        
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-10-25 01:44:35,360 ERROR libqtile core.py:get_interesting_pid():L815 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/core.py", line 294, in _xpoll
    event = self.conn.conn.poll_for_event()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 580, in wrapper
    finally:
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 570, in invalid
    """
        
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/core.py", line 813, in get_interesting_pid
    return win.window.get_net_wm_pid()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/xproto.py", line 2836, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 392, in send_request
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 580, in wrapper
    finally:
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 570, in invalid
    """
        
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-10-25 01:44:35,361 ERROR libqtile core.py:get_interesting_pid():L815 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/core.py", line 813, in get_interesting_pid
    return win.window.get_net_wm_pid()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/xproto.py", line 2836, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 392, in send_request
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 580, in wrapper
    finally:
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 570, in invalid
    """
        
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-10-25 01:44:35,362 ERROR libqtile core.py:get_interesting_pid():L815 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/core.py", line 813, in get_interesting_pid
    return win.window.get_net_wm_pid()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/xproto.py", line 2836, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 392, in send_request
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 580, in wrapper
    finally:
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 570, in invalid
    """
        
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-10-25 01:44:35,362 ERROR libqtile core.py:get_interesting_pid():L815 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/core.py", line 813, in get_interesting_pid
    return win.window.get_net_wm_pid()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/xproto.py", line 2836, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 392, in send_request
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 580, in wrapper
    finally:
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 570, in invalid
    """
        
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-10-25 01:44:35,363 ERROR libqtile core.py:get_interesting_pid():L815 Got an exception in getting the window pid
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/core.py", line 813, in get_interesting_pid
    return win.window.get_net_wm_pid()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/window.py", line 293, in get_net_wm_pid
    r = self.get_property("_NET_WM_PID", unpack=int)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/window.py", line 374, in get_property
    r = self.conn.conn.core.GetProperty(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/xproto.py", line 2836, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 392, in send_request
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 580, in wrapper
    finally:
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 570, in invalid
    """
        
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-10-25 01:44:35,367 ERROR libqtile start.py:start():L92 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 582, in wrapper
    return wrapper
                   
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 692, in request_check
    """ Hoist an xcb_generic_event_t to the right xcffib structure. """
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 656, in _process_error
    buf = CffiUnpacker(c_error)
    ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 570, in invalid
    """
        
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/libqtile/scripts/start.py", line 90, in start
    q.loop()
  File "/usr/lib64/python3.11/site-packages/libqtile/core/manager.py", line 198, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libqtile/core/manager.py", line 226, in async_loop
    self.finalize()
  File "/usr/lib64/python3.11/site-packages/libqtile/core/manager.py", line 306, in finalize
    self.core.finalize()
  File "/usr/lib64/python3.11/site-packages/libqtile/backend/x11/core.py", line 173, in finalize
    ).check()
      ^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 340, in check
    return self.conn.discard_reply(self.sequence)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 584, in wrapper
    @ensure_connected
                ^^^^^^
  File "/usr/lib/python3.11/site-packages/xcffib/__init__.py", line 570, in invalid
    """
        
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2023-10-25 01:44:35,370 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ramnes** [comment]
Closing in favor of #4538. Qtile package seems broken on OpenSUSE, you probably want to raise the issue / contribute upstream. Or install Qtile from source. :)

**Comment by uncomfyhalomacro** [comment]
@mtwb47 grab a working qtile binary here https://github.com/qtile/qtile/issues/4538#issuecomment-1780254646
