### ISSUE TITLE
`qtile_info` root command raises IPCError on latest master

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#4563]
### Issue description

This happens when running `qtile cmd-obj -o cmd -f qtile_info` for example, but also any other way of calling it, eg. through `InteractiveCommandClient`.

Traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/ipc.py", line 121, in unpack
    assert len(data) >= HDRLEN
           ^^^^^^^^^^^^^^^^^^^
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/qtile", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/scripts/main.py", line 76, in main
    func(options)
  File "/usr/lib/python3.11/site-packages/libqtile/scripts/cmd_obj.py", line 182, in cmd_obj
    ret = run_function(obj, args.function, args.args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/scripts/cmd_obj.py", line 132, in run_function
    ret = client.call(funcname, *args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/command/client.py", line 131, in call
    return self._command.execute(call, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/command/interface.py", line 232, in execute
    status, result = self._client.send((call.parent.selectors, call.name, args, kwargs))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/ipc.py", line 171, in send
    return asyncio.run(self.async_send(msg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/ipc.py", line 199, in async_send
    data, _ = _IPC.unpack(read_data, is_json=self.is_json)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/ipc.py", line 126, in unpack
    raise IPCError("error reading reply! (probably the socket was disconnected)") from e
libqtile.ipc.IPCError: error reading reply! (probably the socket was disconnected)
```

Will try to debug this on the default config.

### Version

0.23.1.dev67+gd3d80d0b

### Backend

X11 (default)

### Logs

```text
2023-11-07 16:40:26,596 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/ipc.py", line 237, in _server_callback
    result = _IPC.pack(rep, is_json=is_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/ipc.py", line 135, in pack
    msg_bytes = marshal.dumps(msg)
                ^^^^^^^^^^^^^^^^^^
ValueError: unmarshallable object
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Thanks for the report. We'll take a look.

Out of curiosity, what do you use `qtile_info` for?

**Comment by ervinpopescu** [comment]
```console
$ grep qtile_info -rni --files-with-matches ~/bin | wc -l
4
```
:)

**Comment by elParaguayo** [comment]
I am very confused by this. I can confirm that I get the same error. However, if I load the same commit via a xephyr session or in another TTY, I don't get the error...

**Comment by ervinpopescu** [comment]
Yep, I tried the same in a different TTY with the default config and I mistakenly concluded that the issue is my config. Either way, it's the `unmarshallable object` we should be looking at. Is there a way to intercept the bytes that are being sent/received?

**Comment by ervinpopescu** [comment]
These are the messages packed by `_IPC.pack` in the Xephyr session:
```python
2023-11-09 12:16:21,319 libqtile ipc.py:pack():L136 (0, ['add_rule', 'addgroup', 'change_window_order', 'commands', 'critical', 'debug', 'delgroup', 'display_kb', 'doc', 'error', 'eval', 'findwindow', 'fire_user_hook', 'function', 'get_groups', 'get_screens', 'get_state', 'get_test_data', 'hide_show_bar', 'info', 'internal_windows', 'items', 'labelgroup', 'list_widgets', 'loglevel', 'loglevelname', 'next_layout', 'next_screen', 'next_urgent', 'pause', 'prev_layout', 'prev_screen', 'qtile_info', 'qtilecmd', 'reconfigure_screens', 'reload_config', 'remove_rule', 'restart', 'run_extension', 'shutdown', 'simulate_keypress', 'spawn', 'spawncmd', 'status', 'switch_groups', 'switch_window', 'switchgroup', 'sync', 'to_layout_index', 'to_screen', 'togroup', 'tracemalloc_dump', 'tracemalloc_toggle', 'ungrab_all_chords', 'ungrab_chord', 'validate_config', 'warning', 'windows'])
2023-11-09 12:16:21,326 libqtile ipc.py:pack():L136 (0, {'config_path': '/lib/python3.11/site-packages/libqtile/resources/default_config.py', 'version': '0.23.0b3.dev1+g9307373d', 'log_level': 'INFO'})
```
These are the messages in the main Qtile session:
```py
2023-11-09 12:47:20,860 ERROR libqtile ipc.py:pack():L136 ([], 'commands', (), {})
2023-11-09 12:47:20,862 ERROR libqtile ipc.py:pack():L136 (0, ['add_rule', 'addgroup', 'change_window_order', 'commands', 'critical', 'debug', 'delgroup', 'display_kb', 'doc', 'error', 'eval', 'findwindow', 'fire_user_hook', 'function', 'get_groups', 'get_screens', 'get_state', 'get_test_data', 'hide_show_bar', 'info', 'internal_windows', 'items', 'labelgroup', 'list_widgets', 'loglevel', 'loglevelname', 'next_layout', 'next_screen', 'next_urgent', 'pause', 'prev_layout', 'prev_screen', 'qtile_info', 'qtilecmd', 'reconfigure_screens', 'reload_config', 'remove_rule', 'restart', 'run_extension', 'shutdown', 'simulate_keypress', 'spawn', 'spawncmd', 'status', 'switch_groups', 'switch_window', 'switchgroup', 'sync', 'to_layout_index', 'to_screen', 'togroup', 'tracemalloc_dump', 'tracemalloc_toggle', 'ungrab_all_chords', 'ungrab_chord', 'validate_config', 'warning', 'windows'])
2023-11-09 12:47:20,869 ERROR libqtile ipc.py:pack():L136 Message ([], 'qtile_info', (), {})
2023-11-09 12:47:20,870 ERROR libqtile ipc.py:pack():L136 Message (0, {'config_path': PosixPath('/home/ervin/.config/qtile/config.py'), 'version': '0.22.2.dev484+g8b5ce13c', 'log_level': 'WARNING', 'log_path': '/home/ervin/.local/share/qtile/qtile.log'})
```
It's `str`ange to me that the `PosixPath` does not get `str`ingified. Either way, I tested it  and will open a PR.
