### ISSUE TITLE
[wayland] missing handle_activation_request() in SceneTree

### ISSUE THREAD

**Issue by pg83** [qtile/qtile#4565]
### Issue description

Sometimes have such errors in qtile.log, do not quite understand how to reproduce it, and when it happens:

```
2023-11-08 16:12:51,658 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/ix/store/UCa9W8mB9JMNDogm-lib-py-wayland-py/lib/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/ix/store/SL8asQZCgLklM1pM-lib-qtile-py/lib/libqtile/backend/wayland/core.py", line 853, in _on_xdg_activation_v1_request_activate
    win.handle_activation_request(focus_on_window_activation)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SceneTree' object has no attribute 'handle_activation_request'
2023-11-08 16:12:53,149 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
```

### Version

dev

### Backend

Wayland (experimental)

### Config

```python
https://github.com/pg83/bayanwm/blob/main/config.py
```

### Logs

```text
2023-11-08 16:12:51,658 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/ix/store/UCa9W8mB9JMNDogm-lib-py-wayland-py/lib/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/ix/store/SL8asQZCgLklM1pM-lib-qtile-py/lib/libqtile/backend/wayland/core.py", line 853, in _on_xdg_activation_v1_request_activate
    win.handle_activation_request(focus_on_window_activation)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SceneTree' object has no attribute 'handle_activation_request'
2023-11-08 16:12:53,149 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by pg83** [comment]
Managed to fix it in https://github.com/pg83/ix/blob/main/pkgs/bin/qtile/py/core.py#L852-L853, will send PR later

**Comment by pg83** [comment]
What I supposed to do, if maintainers dont bother to merge this PR?
