### ISSUE TITLE
`reconfigure_screens` config and functionality are buggy 

### ISSUE THREAD

**Issue by ervinpopescu** [qtile/qtile#4673]
### Issue description

After a change was done to the screens configuration (monitor added and `autorandr` run), the following was the state:

![screens_issue](https://github.com/qtile/qtile/assets/84532402/0e7094a9-25df-477a-9832-f70644734f64)

This is probably related to the `scale` applied to the external monitors, as my laptop is HiDPI and the monitors are not.

**After reloading the config, everything is configured correctly.**

`autorandr` profile: https://termbin.com/167h

~~The number of `No screen at target` errors is 3 times less the number of times the actual `screen_change` hook is fired by the way, since I could see the config reloading 12 times, hook which for some reason also triggers the `screens_reconfigured` hook just twice, since I can see only 2 notifications.~~

Scratch that, the behavior is random, except for the `No screen at target` errors which seem to be 4 all the time.

### Version

0.24.1.dev11+g00dcf122

### Backend

X11 (default)

### Config

```python
reconfigure_screens = True

@hook.subscribe.screen_change
def reload(event):
    qtile.reload_config()

@hook.subscribe.screens_reconfigured
def change_wallpaper():
    send_notification("qtile", "screen change detected.")
    with open(os.path.expanduser("~/.local/share/wallpaper/log")) as f:
        path = f.readlines()[0].split(" ")[-1]
    subprocess.call(f"run_wall.sh {path} all".split())
```

### Logs

```
2024-01-29 00:47:29,410 ERROR libqtile window.py:update_strut():L1637 No screen at target
2024-01-29 00:47:31,603 ERROR libqtile window.py:update_strut():L1637 No screen at target
2024-01-29 00:47:31,604 ERROR libqtile window.py:update_strut():L1637 No screen at target
2024-01-29 00:47:31,606 ERROR libqtile window.py:update_strut():L1637 No screen at target
2024-01-29 00:47:44,518 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 945, in f
    func(*args)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 627, in draw
    self.drawer.clear(self.background or self.bar.background)
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/decorations.py", line 832, in new_clear
    self._pre_clear(colour)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base/drawer.py", line 307, in clear
    self.ctx.save()
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'save'
x144
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
I agree it's buggy and will try to take a look.

I know there have been issues with autorandr before.

**Comment by ervinpopescu** [comment]
Thanks! Let me know if and how I can help.

**Comment by elParaguayo** [comment]
What's the actual issue shown in the screenshot? Is it the positioning of the screens?

I doubt the qtile-extras decoration issue is relevant here (I've seen it at other times too) but the lines above may be more interesting.

**Comment by ervinpopescu** [comment]
> What's the actual issue shown in the screenshot? Is it the positioning of the screens?

Yes, Qtile does not seem to understand the different scale and positions the screens as half of what they physically are. You can see the background behind which is correctly set using `nitrogen` in a custom script.

> I doubt the qtile-extras decoration issue is relevant here (I've seen it at other times too) but the lines above may be more interesting.

Indeed, I am going to turn debug logging on and test again, in hopes of some more useful logs.

**Comment by ervinpopescu** [comment]
I forgot about this issue, since I haven't used external screens in a while.

Enabled debug logs with:
```
$ echo > ~/.local/share/qtile/qtile.log; date; qtile cmd-obj -o cmd -f debug; date; xev -1 -event randr; date; qtile cmd-obj -o cmd -f warning
Wed Jun 26 11:37:39 AM EEST 2024
sleeping 5 seconds
```
[Output of xev](https://pastebin.com/PbrjrEiq)

Skimming through debug logs and ignoring `Window` events:

```bash
$ grep -vE 'bound method Window.handle_PropertyNotify of Window|bound method Static.handle_PropertyNotify of Static|bound method Internal.handle_Expose of Internal\(wid=|Expose \(targets: \[\]\)|bound method Static.handle_ConfigureRequest of Static|bound method Icon.handle_PropertyNotify of <libqtile.widget.systray.Icon|ConfigureNotify \(targets: \[\]\)|bound method Window.handle_ConfigureRequest of Window|window.py:handle_PropertyNotify' ~/.local/share/qtile/qtile.log
```
[Output](https://pastebin.com/JpNKZEXT)

[Full logs](https://pastebin.com/9yx02VXp)

I, for one don't see a lot here, if you guys would like to take a look, I would more than appreciate it.

For now, `reconfigure_screens = False` for me :)

**Comment by ervinpopescu** [comment]
For reference, this works, oddly enough:

```py
@hook.subscribe.screen_change
def screen_change(event):
    qtile.reconfigure_screens()
    qtile.reconfigure_screens()
```

**Comment by ervinpopescu** [comment]
Still probably an issue, but I've transitioned to Wayland since and I don't think I'll need X11 for anything, so I can't follow up on this one.

I still remember a couple of people on the internets talking about this, but I don't know where or when.

**Comment by ervinpopescu** [comment]
@github-actions i hate you with passion

**Comment by ervinpopescu** [comment]
@github-actions i hate you with 2x passion

**Comment by ervinpopescu** [comment]
If no one wants this open, I guess we can close? @elParaguayo @tych0

**Comment by elParaguayo** [comment]
Is it still an issue?

**Comment by ervinpopescu** [comment]
I'm using Wayland and don't want to/can't :( devote time to testing it again, but probably yes...

**Comment by Etn40ff** [comment]
I can confirm that something is still amiss: sometimes when I disconnect and reconnect an external monitor the screen gets messed up
