### ISSUE TITLE
Special characters cause MPRIS2 widget to crash

### ISSUE THREAD

**Issue by sephii** [qtile/qtile#4674]
### Issue description

When the song metadata contains special (non-utf8?) characters, the MPRIS2 widget crashes (see the logs).

I’m not sure how this should be fixed. One way could be to:

* Make [`pangocffi.parse_markup`](https://github.com/qtile/qtile/blob/0aca7be183be00134acb3221dd39cadf690b7b6c/libqtile/pangocffi.py#L185) raise a specific exception (instead of just `Exception`)
* Catch it in [`TextLayout.text`](https://github.com/qtile/qtile/blob/0aca7be183be00134acb3221dd39cadf690b7b6c/libqtile/backend/base/drawer.py#L412) and don’t set any attributes, just update the text

### Version

0.23.0

### Backend

X11 (default)

### Logs

```text
2024-01-30 08:59:43,582 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/nix/store/vvij2hfg27558x8afzzjvanxc13vh8h0-python3-3.11.6-env/lib/python3.11/site-packages/libqtile/widget/mpris2widget.py", line 262, in process_message
    self.parse_message(*message.body)
  File "/nix/store/vvij2hfg27558x8afzzjvanxc13vh8h0-python3-3.11.6-env/lib/python3.11/site-packages/libqtile/widget/mpris2widget.py", line 353, in parse_message
    self.update(self.displaytext)
  File "/nix/store/vvij2hfg27558x8afzzjvanxc13vh8h0-python3-3.11.6-env/lib/python3.11/site-packages/libqtile/widget/base.py", line 756, in update
    self.text = text
    ^^^^^^^^^
  File "/nix/store/vvij2hfg27558x8afzzjvanxc13vh8h0-python3-3.11.6-env/lib/python3.11/site-packages/libqtile/widget/base.py", line 527, in text
    self.layout.text = self.formatted_text
    ^^^^^^^^^^^^^^^^
  File "/nix/store/vvij2hfg27558x8afzzjvanxc13vh8h0-python3-3.11.6-env/lib/python3.11/site-packages/libqtile/backend/base/drawer.py", line 412, in text
    attrlist, value, accel_char = pangocffi.parse_markup(value)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vvij2hfg27558x8afzzjvanxc13vh8h0-python3-3.11.6-env/lib/python3.11/site-packages/libqtile/pangocffi.py", line 185, in parse_markup
    raise Exception("parse_markup() failed for %s" % value)
Exception: parse_markup() failed for b'Paused: Emil - Piano Collections Nier Gestalt & Replicant - \xe5\xb8\x86\xe8\xb6\xb3 \xe5\x9c\xad\xe5\x90\xbe(MONACA)'
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Yes. It's the `&` sign. This happens on multiple widgets. I need to put a proper fix in place for this.

**Comment by elParaguayo** [comment]
Can you see if #4680 fixes this for you.
