### ISSUE TITLE
Can't keybind groups to digits with azerty keyboards 

### ISSUE THREAD

**Issue by morgandavidson** [qtile/qtile#4708]
### Issue description

The two following keybindings: 

```
for i in groups:
    keys.extend([
  Key([mod],
      i.name,
      lazy.group[i.name].toscreen()),

  Key([mod, "shift"],
      i.name,
      lazy.window.togroup(i.name, switch_group=True))
    ])
```

Don't work with `groups = [Group(i) for i in "123456789"]`.

But they work with `groups = [Group(i) for i in "abcdefghi"]`.

Hence, I assume the issue comes from how Qtile handles Azerty (fr) layouts.

### Version

0.24.0

### Backend

X11 (default)

### Config

```python
# Imports
# :PROPERTIES:
# :CUSTOM_ID: h:7f34dd2c-848b-486c-a4b8-86d943d4faae
# :END:

from libqtile.config import Key, Group, Match
from libqtile.command import lazy
from .keys import keys, mod

# =groups= variable

groups = [
    Group("1"),
    Group("2", matches=[Match(wm_class=["emacs"])]),
    Group("3", matches=[Match(wm_class=["chromium"])]),
    Group("4", matches=[Match(wm_class=["keepassxc"])]),
    Group("5", matches=[Match(wm_class=["telegram-desktop"])]),
    Group("6"),
    Group("7"),
    Group("8"),
    Group("9"),
]

# Keybinding configuration

for i in groups:
  keys.extend([
    # mod1 + letter of group = switch to group
    Key([mod],
	i.name,
	lazy.group[i.name].toscreen(),
	desc="Switch to group {}".format(i.name)),

    # mod1 + shift + letter of group = switch to & move focused window to group
    Key([mod, "shift"],
	i.name,
	lazy.window.togroup(i.name, switch_group=True),
	desc="Switch to & move focused window to group {}".format(i.name)),

    Key([mod], "Right",
	lazy.screen.next_group(),
	desc="Switch to next group"),

    Key([mod], "Next",
	lazy.screen.next_group(),
	desc="Switch to next group"),

    Key([mod], "Tab",
	lazy.screen.next_group(),
	desc="Switch to next group"),

    Key([mod], "Left",
	lazy.screen.prev_group(),
	desc="Switch to previous group"),

    Key([mod], "Prior",
	lazy.screen.prev_group(),
	desc="Switch to previous group"),

    Key([mod, "shift" ], "Tab",
	lazy.screen.prev_group(),
	desc="Switch to previous group"),
  ])
```

### Logs

```text
2024-02-22 22:42:51,328 WARNING libqtile config.py:convert_deprecated_list():L824 Your Match with the wm_class property is using lists which are deprecated, replace Match(wm_class=['emacs']) with Match(wm_class=re.compile(r"^(emacs)$")) after importing the 're' module
2024-02-22 22:42:51,328 WARNING libqtile config.py:convert_deprecated_list():L824 Your Match with the wm_class property is using lists which are deprecated, replace Match(wm_class=['chromium']) with Match(wm_class=re.compile(r"^(chromium)$")) after importing the 're' module
2024-02-22 22:42:51,328 WARNING libqtile config.py:convert_deprecated_list():L824 Your Match with the wm_class property is using lists which are deprecated, replace Match(wm_class=['keepassxc']) with Match(wm_class=re.compile(r"^(keepassxc)$")) after importing the 're' module
2024-02-22 22:42:51,329 WARNING libqtile config.py:convert_deprecated_list():L824 Your Match with the wm_class property is using lists which are deprecated, replace Match(wm_class=['telegram-desktop']) with Match(wm_class=re.compile(r"^(telegram\-desktop)$")) after importing the 're' module
2024-02-22 22:42:51,715 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Right)>
2024-02-22 22:42:51,715 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Next)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Tab)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Left)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Prior)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4', 'shift'], Tab)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Right)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Next)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Tab)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Left)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Prior)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4', 'shift'], Tab)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Right)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Next)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Tab)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Left)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Prior)>
2024-02-22 22:42:51,716 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4', 'shift'], Tab)>
2024-02-22 22:42:51,717 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Right)>
2024-02-22 22:42:51,717 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Next)>
2024-02-22 22:42:51,717 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Tab)>
2024-02-22 22:42:51,717 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Left)>
2024-02-22 22:42:51,717 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Prior)>
2024-02-22 22:42:51,717 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4', 'shift'], Tab)>
2024-02-22 22:42:51,717 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Right)>
2024-02-22 22:42:51,717 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Next)>
2024-02-22 22:42:51,717 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Tab)>
2024-02-22 22:42:51,717 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Left)>
2024-02-22 22:42:51,717 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Prior)>
2024-02-22 22:42:51,717 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4', 'shift'], Tab)>
2024-02-22 22:42:51,717 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Right)>
2024-02-22 22:42:51,717 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Next)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Tab)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Left)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Prior)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4', 'shift'], Tab)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Right)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Next)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Tab)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Left)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Prior)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4', 'shift'], Tab)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Right)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Next)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Tab)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Left)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4'], Prior)>
2024-02-22 22:42:51,718 WARNING libqtile manager.py:grab_key():L478 Key spec duplicated, overriding previous: <Key (['mod4', 'shift'], Tab)>
2024-02-22 22:42:51,783 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Let's do the easy bit first, you're getting all those `Key spec duplicated` methods because you're defining those keys multiple times i.e. every time you loop through the groups. Move any binding that's not linked to `i.name` outside the loop.

As for the Azerty issue, this has been reported before. The issue, as I understand it, is that you need to press `shift` to access the numbers so you need to actually bind the base symbol for that key, rather than the number - see here: https://github.com/qtile/qtile/issues/3146#issuecomment-1008302093

**Comment by morgandavidson** [comment]
Hello @elParaguayo,

When I move bindings that are not linked to `i.name` outside of the loop (putting them inside of `key = []`), these bindings don't work anymore.

Regading the Azerty issue, when I put the solution proposed in #3146, qtile breaks:
```
keybindings = [
        "ampersand",
        "eacute",
        "quotedbl",
        "apostrophe",
        "parenleft",
    ]
    groups = [
        (str(name), {"label": str(label)})
        for label, name in enumerate(keybindings, start=1)
    ]
    return [Group(name=name, **kwargs) for name, kwargs in groups]
```

When I put `groups = [Group(i) for i in ["ampersand", "eacute", "quotedbl", "apostrophe", "parenleft"]`, I have two issues:
1. ampersand, eacute, etc. apear as group names instead of 1,2,etc.
2. numpad digits don't work

As I mainly use numpad for digits, I managed to keybind numpad with:
```
  groups = [
      Group("KP_End"), # 1
      Group("KP_Down", matches=[Match(wm_class=["emacs"])]), # 2
      Group("KP_Page_Down", matches=[Match(wm_class=["chromium"])]), # 3
      Group("KP_Left", matches=[Match(wm_class=["keepassxc"])]), # 4
      Group("KP_Begin", matches=[Match(wm_class=["telegram-desktop"])]), #5
      Group("KP_Right"), #6
      Group("KP_Home"), #4
      Group("KP_Up"),      # 8
      Group("KP_Page_Up"), # 9
  ]
```
  But I still have the issue of the group names. KP_End, KP_Down, etc appear instead of 1,2,etc.

**Comment by elParaguayo** [comment]
Do something like this then:
```python
bindings = ["KP_End", "KP_Down", "KP_Page_Down" etc etc]
  
groups = [
    Group("1"), # 1
    Group("2", matches=[Match(wm_class=["emacs"])]), # 2
    Group("3", matches=[Match(wm_class=["chromium"])]), # 3
    Group("4", matches=[Match(wm_class=["keepassxc"])]), # 4
    Group("5", matches=[Match(wm_class=["telegram-desktop"])]), # 5
    Group("6"), # 6
    Group("7"), # 7
    Group("8"),      # 8
    Group("9"), # 9
]

for i, group in enumerate(groups):
  keys.extend([
      Key([mod],
          bindings[i],
          lazy.group[group.name].toscreen()),

      Key([mod, "shift"],
          bindings[i]
          lazy.window.togroup(group.name, switch_group=True))
    ])
```

**Comment by elParaguayo** [comment]
> When I move bindings that are not linked to i.name outside of the loop (putting them inside of keys = []), these bindings don't work anymore.

That makes no sense. They only need to be bound once so should not be part of the groups loop.

**Comment by morgandavidson** [comment]
When group.py is:
```
from libqtile.config import Key, Group, Match
from libqtile.command import lazy
from .keys import keys, mod

# Keybinding configuration

bindings = ["KP_End", "KP_Down", "KP_Page_Down", "KP_Left", "KP_Begin", "KP_Right", "KP_Home", "KP_Up", "KP_Page_Up"]
groups = [
    Group("1"), # 1
    Group("2", matches=[Match(wm_class=["emacs"])]), # 2
    Group("3", matches=[Match(wm_class=["chromium"])]), # 3
    Group("4", matches=[Match(wm_class=["keepassxc"])]), # 4
    Group("5", matches=[Match(wm_class=["telegram-desktop"])]), # 5
    Group("6"), # 6
    Group("7"), # 7
    Group("8"),      # 8
    Group("9"), # 9
]

for i, group in enumerate(groups):
  keys.extend([
      Key([mod],
          bindings[i],
          lazy.group[group.name].toscreen()),

      Key([mod, "shift"],
          bindings[i]
          lazy.window.togroup(group.name, switch_group=True))
    ])
```
Qtile breaks. I'm using Qtile under [EOS](https://endeavouros.com/).

**Comment by elParaguayo** [comment]
You're going to need to give me more than "Qtile breaks". Error messages? What happens if you run `python config.py` etc etc?

**Comment by morgandavidson** [comment]
1. I replace group.py content by the content mentioned above
2. `rm  ~/.local/share/qtile/qtile.log`
3. logout
4. login
5. Qtile becomes unusable.

~/.local/share/qtile/qtile.log: 
```
2024-02-25 16:44:01,390 ERROR libqtile manager.py:load_config():L117 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 114, in load_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/crocefisso/.config/qtile/config.py", line 2, in <module>
    from modules.groups import groups
  File "/home/crocefisso/.config/qtile/modules/groups.py", line 32
    bindings[i]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
2024-02-25 16:44:01,391 WARNING libqtile utils.py:send_notification():L296 dbus-next is not installed. Unable to send notifications.
2024-02-25 16:44:01,450 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
```

**Comment by elParaguayo** [comment]
Yes, there's a typo.
```python
      Key([mod, "shift"],
          bindings[i]
          lazy.window.togroup(group.name, switch_group=True))
    ])
```
is missing a comma after `bindings[i]`.

**Comment by morgandavidson** [comment]
Thank you it works perfectly! Now I just have to find out how to add `lazy.screen.prev_group()` and `lazy.screen.next_group()`.

**Comment by elParaguayo** [comment]
Just add them wherever you define `keys`.

**Comment by morgandavidson** [comment]
```
keys = [
      Key([mod], "Left",
	  lazy.screen.prev_group(),
	  desc="Switch to previous group"),

      Key([mod], "Right",
	  lazy.screen.next_group(),
	  desc="Switch to next group"),
]
```
Doesn't work for me. 

So even if I know it's not the proper way, I have to put them inside the loop for them to work...

**Comment by elParaguayo** [comment]
My guess is you're not adding them to the main `keys` variable. You can't define a new list called `keys`. If you're trying to do this in a separate module to where the main `keys` variable is defined then you need to import that list and add these keys to it.

**Comment by marcoderer** [comment]
Hi @morgandavidson 
Maybe not relevant for you anymore, but just in case (maybe for others with the same problem): I got the keybindings for the azerty number row keys (ampersand, eacute a.s.o) to work for me. Easier than reaching for the numpad...

`g_bindings= [
    "ampersand", 
    "eacute", 
    "quotedbl", 
    "apostrophe", 
    "parenleft", 
    "paragraph", 
    "grave", 
    "exclam", 
    "cedilla",
]

groups = [
    Group("1", label="HOME", layout="monadtall"),
    Group("2", matches=[Match(wm_class=["firefox"])], label="globe", layout="monadtall"),
    Group("3", matches=[Match(title=["nvim"])], label="code", layout="monadtall"),
    Group("4", matches=[Match(wm_class=["thunar"])], label="terminal", layout="monadtall"),
    Group("5", matches=[Match(wm_class=["thunderbird"])], label="folder-open", layout="monadtall"),
    Group("6", matches=[Match(wm_class=["kitty"])], label="cubes", layout="monadtall"),
    Group("7", matches=[Match(wm_class=["virtualbox"])], label="comments", layout="monadtall"),
    Group("8", matches=[Match(wm_class=["whatsapp"])], label="envelope", layout="monadtall"),
    Group("9", matches=[Match(wm_class=["chromium"])], label="music", layout="monadtall"),
]

for i, group in enumerate(groups):
  keys.extend([
      # switch to group  
      Key([mod],
          g_bindings[i],
          lazy.group[group.name].toscreen()),
      # switch to & move focused window to group
      Key([mod, "shift"],
          g_bindings[i],
          lazy.window.togroup(group.name, switch_group=True))
    ])
`
