### ISSUE TITLE
has no attribute current_window

### ISSUE THREAD

**Issue by nazar-pc** [qtile/qtile#4755]
### Issue description

I'm getting "has no attribute current_window" in logs and not sure why

### Version

0.25.0

### Backend

X11 (default)

### Logs

```text
2024-04-06 20:40:51,224 ERROR libqtile core.py:_xpoll():L372 Got an exception in poll loop
Traceback (most recent call last):
  File "/home/nazar-pc/.local/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 347, in _xpoll
    self.handle_event(event)
  File "/home/nazar-pc/.local/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 314, in handle_event
    ret = target(event)
  File "/home/nazar-pc/.local/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 781, in handle_DestroyNotify
    if self.qtile.current_window is None:
  File "/home/nazar-pc/.local/lib/python3.10/site-packages/libqtile/command/base.py", line 281, in __getattr__
    raise AttributeError(f"{self.__class__} has no attribute {name}")
AttributeError: <class 'libqtile.core.manager.Qtile'> has no attribute current_window
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tych0** [comment]
I noticed this today as well. For me, it only happened after restart, is the same true for you?

**Comment by nazar-pc** [comment]
Happens after restart and then I think during runtime as well. Nothing seems to be visually broken though.

**Comment by tych0** [comment]
Yeah, I have the same experience. It would be good to clean up the logs, I'll look into it if nobody else has any ideas.
