### ISSUE TITLE
Dialogs are rendered behind apps sometimes

### ISSUE THREAD

**Issue by nazar-pc** [qtile/qtile#4805]
### Issue description

Reproduction:
1) Open one project in IDE (IntelliJ)
2) Open another project in IDE in a separate window
3) Open search dialog in a second window

Expected:
Search dialog window opens above other windows

Actual:
Search dialog opens above second window, but behind the first window somehow. Clicking or re-focusing on it fixes the issue for that particular instance.

This wasn't the case in older verison of Qtile (0.21 at least). This also happens with other apps like Geany for example. In some cases the dialog is completely hidden, which is hard to work with.

### Version

0.25.0

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Can you see if #4583 fixes this?

**Comment by nazar-pc** [comment]
Could you rebase it on latest `master`, please?

**Comment by elParaguayo** [comment]
Done.

**Comment by nazar-pc** [comment]
I'm getting some errors unfortunately:
<details>

```
2024-05-05 14:40:38,469 ERROR libqtile core.py:_xpoll():L372 Got an exception in poll loop
Traceback (most recent call last):
  File "/home/nazar-pc/.local/share/pipx/venvs/qtile/lib/python3.12/site-packages/libqtile/backend/x11/core.py", line 347, in _xpoll
    self.handle_event(event)
  File "/home/nazar-pc/.local/share/pipx/venvs/qtile/lib/python3.12/site-packages/libqtile/backend/x11/core.py", line 314, in handle_event
    ret = target(event)
          ^^^^^^^^^^^^^
  File "/home/nazar-pc/.local/share/pipx/venvs/qtile/lib/python3.12/site-packages/libqtile/backend/x11/core.py", line 781, in handle_DestroyNotify
    if self.qtile.current_window is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nazar-pc/.local/share/pipx/venvs/qtile/lib/python3.12/site-packages/libqtile/command/base.py", line 281, in __getattr__
    raise AttributeError(f"{self.__class__} has no attribute {name}")
AttributeError: <class 'libqtile.core.manager.Qtile'> has no attribute current_window
```

</details>

I then tried main and my config failed to load:
<details>

```
2024-05-05 15:13:16,615 ERROR libqtile manager.py:reload_config():L290 Configuration error:
Traceback (most recent call last):
  File "/home/nazar-pc/.local/share/pipx/venvs/qtile/lib/python3.12/site-packages/libqtile/core/manager.py", line 288, in reload_config
    self.config.load()
  File "/home/nazar-pc/.local/share/pipx/venvs/qtile/lib/python3.12/site-packages/libqtile/confreader.py", line 132, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/nazar-pc/.config/qtile/config.py", line 1, in <module>
    from libqtile.command import lazy
ImportError: cannot import name 'lazy' from 'libqtile.command' (/home/nazar-pc/.local/share/pipx/venvs/qtile/lib/python3.12/site-packages/libqtile/command/__init__.py)
```

<details>

I didn't see anything in changelog saying that `from libqtile.command import lazy` should break.

**Comment by elParaguayo** [comment]
Are you sure you've loaded that PR? The line number for the `current_window` error doesn't match the code in PR.

**Comment by nazar-pc** [comment]
Right, I just placed updated files on top of 0.25.0 and it broke. Now pulled the whole branch and unfortunately it didn't help with this issue.

**Comment by elParaguayo** [comment]
Cool. Thanks for testing. Will need to add to the "to do" list...

**Comment by elParaguayo** [comment]
Any chance you can take a video of this behaviour. I've just tried it and search dialog appears in the right place but I'm not convinced I'm doing this the same way as you.

**Comment by nazar-pc** [comment]
Sure: https://youtu.be/n95NR_2lWoY

**Comment by nazar-pc** [comment]
Were you able to reproduce it in the end? Issue is still labeled as unconfirmed.

**Comment by elParaguayo** [comment]
No. No luck recreating. I'll try again later but am very busy this weekend.

**Comment by nazar-pc** [comment]
Either https://github.com/qtile/qtile/pull/4583 was helping or something has changed between 0.25.0 and 0.26.0 (I also switched from old Plasma layout to upstreamed one). Now I'm sometimes getting dialog windows showing up above current window, but below basically all other windows somehow, which I have not seen before.

**Comment by elParaguayo** [comment]
Ok. Can you give me some steps to recreate please?

Have you patched #4583 to 0.26.0 to see if it helps?

**Comment by nazar-pc** [comment]
I have ScreenSplit like this:

```
|   | b |   |
| a |---| d |
|   | c |   |
|   |   |   |
```

All 4 are using Plasma and have Windows opened. `c` only had IDE, then I opened another project in IDE and noticed that search in the first project is now behind all windows on the screen except its parent.

> Have you patched https://github.com/qtile/qtile/pull/4583 to 0.26.0 to see if it helps?

Not yet, could you rebase it on `main` so I can just install it from your branch directly?

**Comment by elParaguayo** [comment]
Sure. I'll have to do that after work later today though.

**Comment by elParaguayo** [comment]
OK - it's rebased.

**Comment by nazar-pc** [comment]
Nope, #4583 didn't help with either of these issues unfortunately

**Comment by nazar-pc** [comment]
Definitely still an issue and a very annoying one at that

**Comment by nazar-pc** [comment]
I'd love if someone knowledgeable could finally fix this :pray:

**Comment by elParaguayo** [comment]
If someone can give me a reliable way to recreate this, I can take another look.

**Comment by saviola777** [comment]
I was able to reproduce it with the steps in the original post. On the Tile layout

1. Open IntelliJ (or any other JetBrains IDE)
2. Open some project
3. Open another project in a new window
4. In the new window, open the global search (Ctrl+Shift+f)

Also works on a floating layout.

I thought maybe tych0@0c7f945 would fix this (since the search window is a transient window), but it doesn't.

**Comment by nazar-pc** [comment]
A potentially related issue:
1) Have full-screen SMPlayer playing (with MPV backend)
2) Right click, select "Subtitles > Set delay ..."
3) Not only corresponding dialog appears, but also qBittorrent becomes visible above full-screen video player :confused: 
4) Closing "Set delay" dialog results in qBittorrent hiding behind full-screen video player again :thinking:

**Comment by nazar-pc** [comment]
This is still a very annoying issue

**Comment by elParaguayo** [comment]
@nazar-pc I'm currently rewriting the stacking logic for x11. If you're still using qtile, could you try the code in https://github.com/qtile/qtile/pull/5397 and see if this is any better.

**Comment by nazar-pc** [comment]
Running it now.

It does seem to work well where 0.33.0 didn't in some cases (like search window in Geany, search/action dialogs in IntelliJ IDEA), but `ulauncher` is now rendering behind other windows one some groups (specifically the one I was on before Qtile restart) for some reason, even though previously it always properly showed up above all other windows.

Here is Ulauncher's `xprop` from a screen where I can see it:

<details>

```
_NET_WM_DESKTOP(CARDINAL) = 2
_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_FOCUSED
_NET_WM_USER_TIME(CARDINAL) = 1915625319
_NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 1, 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x1c0844f
		bitmap id # of mask for icon: 0x1c08455
		window id # of group leader: 0x1c00001
_GTK_THEME_VARIANT(UTF8_STRING) = "dark"
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) = 	Icon (48 x 48):
...
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x21, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 29360156, 29360157
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1c0001b
WM_CLIENT_LEADER(WINDOW): window id # 0x1c00001
_NET_WM_PID(CARDINAL) = 3488
WM_LOCALE_NAME(STRING) = "uk_UA.UTF-8"
WM_CLIENT_MACHINE(STRING) = "nazar-pc"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 606 by 115
		program specified maximum size: 606 by 115
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "ulauncher", "Ulauncher"
WM_ICON_NAME(STRING) = "Ulauncher - Application Launcher"
_NET_WM_ICON_NAME(UTF8_STRING) = "Ulauncher - Application Launcher"
WM_NAME(STRING) = "Ulauncher - Application Launcher"
_NET_WM_NAME(UTF8_STRING) = "Ulauncher - Application Launcher"
```

</details>

**Comment by elParaguayo** [comment]
Thank you so much for testing. 

Looking at that xprop, it has the `_NET_WM_STATE_ABOVE` atom set so this should put it above tiled windows and in the same layer group as floating windows (assuming `floats_kept_above` is `True` in the config).

I can see there would be an issue in the current stacking code if a window changes group as there may be other windows in that group which are stacked higher. We might want to `move_to_top` when windows move group so that they're put at the top of their current layer group.

Are there any specific steps you can give me to recreate this?

**Comment by nazar-pc** [comment]
I do not have `floats_kept_above` in my config at all, so it should be `True` (the default).

> Are there any specific steps you can give me to recreate this?

Looks like Ulaucher is shown behind any window that was opened after it, so should be trivial to reproduce.

Basically start Ulauncher first and then open any other app. Invoking Ulauncher after this will make it show up behind new app.

**Comment by elParaguayo** [comment]
Ok - I suspect this is what's happening:
1) There's no current logic in the PR to raise windows when they're focused
2) When ulauncher is hidden, it's not closed and so it's not removed from the stack. When it's unhidden, it's just shown in it's old place in the stack.

You could verify this by doing `qtile cmd-obj -o core -f eval -a "self.zmanager.layers"` when ulauncher is hidden and see if the window is still shown in the list.

**Comment by nazar-pc** [comment]
When hidden it is not in the list

**Comment by elParaguayo** [comment]
Wasn't expecting that. When it's open, is it in the list?

**Comment by nazar-pc** [comment]
Yes, it appears in the list when shown and disappears when hidden

**Comment by elParaguayo** [comment]
OK - can you paste the output when it is in the list but shown behind other windows?

**Comment by nazar-pc** [comment]
Locked the machine with i3lock for 30 minutes. After unlock it works fine everywhere, with windows old and new. I am very confused right now, can't reproduce the issue anymore 🤷 

UPD: Tried restarting Qtile, but no, it still works fine.

**Comment by elParaguayo** [comment]
That's great to hear. I'll give it another test tonight but it sounds like the PR is an improvement on the current code.

**Comment by nazar-pc** [comment]
Okay, I think there are some glitches that do not persist over time. Just full-screened a video in Firefox and somehow one of the existing windows remained above the full-screen video. I then switched it back and forth again and everything went back to normal.

No idea how to reproduce, but this is a second glitch since I switched to that branch, so something to be aware of.

**Comment by elParaguayo** [comment]
Thanks. I'm not going to rush into merging this branch so fine for bug reports as you run into them.

**Comment by nazar-pc** [comment]
Okay, found reproduction for the last issue.

Switching one of the windows to floating and back (using `lazy.window.toggle_floating()`) does something to the window, which makes it stay above full-screen video right after that.

**Comment by elParaguayo** [comment]
I've pushed a commit which should force floating windows back into the layout layer when they've been toggled. Not sure if that solves this issue but worth a try.

Can you also bind a key to `lazy.core.show_stacking_order()`. If you get the wrong behaviour, can you press that key combo and paste the log lines here?

Thanks.

**Comment by nazar-pc** [comment]
That worked, thanks @elParaguayo ❤️

**Comment by nazar-pc** [comment]
Just had Geany's dialog (confirmation about what to do with a modified file) rendered behind the app. Happened a few times, but then was unable to reproduce on purpose. Other than that, works great so far.

**Comment by elParaguayo** [comment]
Thanks. Will try to test a bit when I can.

**Comment by nazar-pc** [comment]
Found another issue:
* Open GNOME Disks
* Switch it to floating mode (I have a shortcut for this)
* Open one of the built-in dialogs (like disk formatting, same effect with all of them)
* dialog opens behind the floating main window instead of in front of it

**Comment by nazar-pc** [comment]
Can confirm, last issue is fixed in updated https://github.com/qtile/qtile/pull/5397

**Comment by nazar-pc** [comment]
Well, Geany's search dialog is now above Geany, but below many other apps:
```
2025-09-01 05:18:22,798 WARNING libqtile core.py:show_stacking_order():L958 <ZManager Tree Root>
  <ZManager: LayerGroup.BACKGROUND>
  <ZManager: LayerGroup.BOTTOM>
  <ZManager: LayerGroup.KEEP_BELOW>
  <ZManager: LayerGroup.INTERNAL>
  <ZManager: LayerGroup.LAYOUT>
    <ZManager: Window(name='-', wid=25165831)>
    <ZManager: Window(name='/w/g/a/c/s/-', wid=83886083)>
    <ZManager: Window(name='-', wid=98566278)>
    <ZManager: Window(name='qtile.log - /home/nazar-pc/.local/share/qtile - Geany', wid=132120583)>
      <ZManager: Window(name='Search', wid=132126256)>
    <ZManager: Window(name='*file - Geany', wid=109051911)>
    <ZManager: Window(name='-', wid=65011796)>
    <ZManager: Window(name='-', wid=54525959)>
    <ZManager: Window(name='-', wid=16777220)>
    <ZManager: Window(name='Chromium', wid=79691780)>
    <ZManager: Window(name='-', wid=60817430)>
    <ZManager: Window(name='Strawberry)>
    <ZManager: Window(name='Mozilla Thunderbird Beta', wid=48234499)>
    <ZManager: Window(name='Dialogs are rendered behind apps sometimes · Issue #4805 · qtile/qtile', wid=62914563)>
    <ZManager: Window(name='~', wid=67108867)>
    <ZManager: Window(name='qtile', wid=106954795)>
  <ZManager: LayerGroup.KEEP_ABOVE>
  <ZManager: LayerGroup.MAX>
  <ZManager: LayerGroup.FULLSCREEN>
  <ZManager: LayerGroup.BRING_TO_FRONT>
  <ZManager: LayerGroup.TOP>
  <ZManager: LayerGroup.OVERLAY>
  <ZManager: LayerGroup.SYSTEM>
```

Window `132120583` is Geany instance I'm talking about, `132126256` is the search dialog.

Using ccdb49de21163c6dac7b1e7eef1c733de4a3b370, the current tip of https://github.com/qtile/qtile/pull/5397.

**Comment by elParaguayo** [comment]
Yes. That is how it's (currently) designed to work. The search window is a transient window for its parent and so it's displayed immediately above it.

Are all those other windows tiled but still covering it? Can you share a screenshot?

**Comment by nazar-pc** [comment]
Geany window is tiled and located in the far left split (I use ScreenSplit), while Geany's search window likes to remember its absolute position, so it often appears in the area of other splits, where other tiled windows are located. And if those windows often happen to be above Geany, so in the end I don't see the search window at all. It even sometimes appears below windows in the same split. So it only works fine if the floating window is physically above its parent, and not really guaranteed to work properly otherwise.

**Comment by nazar-pc** [comment]
One solution might be to move parent above all other windows when that happens, but then windows like this Geany search dialog will end up behind another windows, who just had it child window opened.

I don't think stacking child windows under parents works all that well in the end.

**Comment by elParaguayo** [comment]
> One solution might be to move parent above all other windows when that happens, but then windows like this Geany search dialog will end up behind another windows, who just had it child window opened.
> 
> I don't think stacking child windows under parents works all that well in the end.

Not sure I quite follow. The dialog is doing exactly what it's meant to do which is open directly above its parent. The issues are that its x, y coordinates aren't necessarily above the window so it ends up behind other tiled windows, particularly when the parent is low in the stack.

With ScreenSplit, we could move the active layout's windows to the top of the stack.

Or we could have a rule where a transient window is opened, we move it and it's parent to the top (ie we just treat it like a new window opening)

**Comment by nazar-pc** [comment]
Okay, now imagine there were two parent windows A and B, each with a single child window Ac and Bc. If Ac happens to be above B and Bc happens to be above A, it is currently impossible to have both Ac and Bc visible at the same time. Even though I'd expect that after opening Ac and then Bc, I'd see both.

**Comment by elParaguayo** [comment]
Sure. But are A and B tiled or overlapping? If they're tiled and their children opened above them then there wouldn't be an issue. So is the issue more about position than stacking height?

**Comment by nazar-pc** [comment]
That is my point exactly, child windows are not always opening above their parents. They most often do, but not always, not at all. I have a bunch of apps with dialogs I open hundreds of times, which have this behavior. It'll be really frustrating when I open a child window of an app and child window of a different app disappears all of a sudden because parent moved in the stack.

**Comment by elParaguayo** [comment]
Yes, so my question is, should we fix the position the child opens in instead? If not, and we choose to honour its requested position, we should probably just elevate the window and its parent.

**Comment by nazar-pc** [comment]
Elevating a parent is the source of the problems. As to not honoring requests of child windows, it feels like a slippery slope that will cause new edge-cases not being handled properly.

I think simply adding new windows to the top of the stack would solve this, which is at odds with child windows being stacked under/over their parents. I'm not sure what scenarios this doesn't cover, you have clearly though about this much more than I did.

**Comment by elParaguayo** [comment]
I'm just trying to honour the spec. Moving transients with their parent makes sense to me.

Pinging @tych0 for his opinion.

**Comment by tych0** [comment]
Just so I understand:

1. A is mapped
2. B is mapped
3. Ac is mapped
4. Bc is mapped

and the question is, what order should these stack in? IMO, it would be, from top to bottom,

Bc
Ac
B
A

because that's the order they were created and mapped in. If someone does something else (override-redirect, manual placement via StackAbove or whatever), we should respect that, but I expect those to be the exception, not the rule.

**Comment by elParaguayo** [comment]
Ok. That's not how this is doing it at the moment. A transient is just placed immediately above its parent. When one is moved, the other also moves (ie the parent and child group is preserved).

**Comment by nazar-pc** [comment]
Still relevant

**Comment by nazar-pc** [comment]
Ubuntu 26.04 is out with a new Python version, meaning I'll likely need to re-install Qtile, but I'm stuck on an old patched version that is no longer even available in the PR after https://github.com/qtile/qtile/pull/5397 was rebased, so I'm either stuck on old Ubuntu version or will have to hack something together.

Please prioritize this if you can. I'm not sure how people using Qtile every day with stacking logic being so broken in last several releases (and it worked fine for years before that) 😕

**Comment by tych0** [comment]
Somehow I didn't realize this had ever worked well for you... is there a particular commit that breaks things?

**Comment by tych0** [comment]
also, you should be able to work around the python version incompatibility matrix with uv, e.g.:

```
uv tool install --python 3.11 'qtile @ git+https://github.com/qtile/qtile.git@v0.23.0'
```

**Comment by nazar-pc** [comment]
As mentioned in the first message, it worked correctly in 0.21 and older versions (I've been using Qtile since 2018), but then broke at some point between that and 0.25.

The problem is that I only have a Qtile installed from unknown revision (one of the older versions of https://github.com/qtile/qtile/pull/5397, but not sure which one and probably with cherry-picked manually applied patches on top at this point) using pipx. I'm kind of stuck with it now until something less broken exists. It is too disruptive otherwise.

**Comment by tych0** [comment]
Yeah, I was wondering if you could bisect to a specific commit.

**Comment by nazar-pc** [comment]
It is kind of difficult to test when the config changes (mine is very far from default) and this is my primary session. Maybe one day I'll set up a machine to test this on. If you have a way to do this efficiently, it is trivially reproducible.

**Comment by nazar-pc** [comment]
Found what older version of the PR I'm still using to this day: https://github.com/qtile/qtile/pull/5397#issuecomment-4701536902

I didn't check when it regressed originally, not yet at least.
