### ISSUE TITLE
Config error lazy related

### ISSUE THREAD

**Issue by cr1ogen** [qtile/qtile#4807]
### Issue description

I have an error loading config.py
Use the same config for years

### Version

0.25.1.dev45+g53f37118

### Backend

Wayland (experimental) and X11

### Config

```python
from libqtile.config import Key, Group, Match
from libqtile.command import lazy
from .keys import mod, keys

groups = [
    Group(name='1', label="", matches=[
        Match(wm_class='firefox')], layout="monadtall"),
    Group(name='2', label="", layout="monadtall"),
    Group(name='3', label="", layout="monadtall"),
    Group(name='4', label="", matches=[
          Match(wm_class='Telegram'), Match(wm_class='discord')], layout='max'),
    Group(name='5', label="", matches=[
        Match(wm_class='pw-jack ardour')], layout='max'),
    Group(name='6', label="", matches=[
        Match(wm_class='iniciar sesión en steam'), Match(wm_class='steam'), Match(wm_class='r2modman'), Match(wm_class='heroic')], layout='monadtall'),

]

for i in groups:
    keys.extend(
        [
            # mod1 + letter of group = switch to group
            Key(
                [mod],
                i.name,
                lazy.group[i.name].toscreen(),
                desc="Switch to group {}".format(i.name),
            ),
            # mod1 + shift + letter of group = switch to & move focused window to group
            Key(
                [mod, "shift"],
                i.name,
                lazy.window.togroup(i.name, switch_group=True),
                desc="Switch to & move focused window to group {}".format(i.name),
            ),
        ]
    )
```

### Logs

```text
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/libqtile/core/manager.py", line 288, in reload_config
    self.config.load()
  File "/usr/local/lib/python3.11/dist-packages/libqtile/confreader.py", line 132, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/cr1ogen/.config/qtile/config.py", line 22, in <module>
    from modules.groups import groups
  File "/home/cr1ogen/.config/qtile/modules/groups.py", line 2, in <module>
    from libqtile.command import lazy
ImportError: cannot import name 'lazy' from 'libqtile.command' (/usr/local/lib/python3.11/dist-packages/libqtile/command/__init__.py)



### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
It should be `from libqtile.lazy import lazy`

**Comment by elParaguayo** [comment]
There was a change recently. The code you were using was deprecated in v0.15 I think.

**Comment by cr1ogen** [comment]
> There was a change recently. The code you were using was deprecated in v0.15 I think.

Works! Thank you. With your permission I close the issue
