### ISSUE TITLE
drop silly hack in x11's `get_screen_info()`

### ISSUE THREAD

**Issue by tych0** [qtile/qtile#4818]
### Issue description

We have the following code in `get_screen_info()`:

```
         if self.qtile:
             self._xpoll()
```

This is a pretty odd place to put this code, and it would be nice to get rid of it. Unfortunately, when we drop it, some tests fail. This is because it has the effect of swallowing the initial ScreenChangeNotify events from the x server, which some of our tests depend on.

### Version

git master

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tych0** [comment]
it turns out this can also generate spurious missing attribute errors:
```
2024-05-19 13:48:35,401 ERROR libqtile core.py:_xpoll():L359 Got an exception in poll loop
Traceback (most recent call last):
  File "/home/tycho/.local/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 334, in _xpoll
    self.handle_event(event)
  File "/home/tycho/.local/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 301, in handle_event
    ret = target(event)
  File "/home/tycho/.local/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 768, in handle_DestroyNotify
    if self.qtile.current_window is None:
  File "/home/tycho/.local/lib/python3.10/site-packages/libqtile/command/base.py", line 281, in __getattr__
    raise AttributeError(f"{self.__class__} has no attribute {name}")
AttributeError: <class 'libqtile.core.manager.Qtile'> has no attribute current_window
```

like I tried to fix in f987f5fc31972ff0e29678bea53d0f65d42d3506 since if there are pending events, they will be handled by that _xpoll() call before the qtile object is fully initialized.
