### ISSUE TITLE
Non-letters in keybinds break config. 

### ISSUE THREAD

**Issue by IgorSlonka** [qtile/qtile#4834]
### Issue description

I wanted to rebind kill qtile  to some rarely used keys, so I swapped "q" to " | ", later to " = ". After saving and reloading my groups merged together showing same windows on all of them, windows worked but were not focused, and icons on the bar (using default bar config) went from white to gray. 

Qtile worked, I could spawn another terminal which opened in fulscreen despite previous aplications in the background, clicking on the bar itself worked. However reloading with Mod + Ctrl + r did not. Changing settings back to to default ones required reboot to solve the issue. Logging out to other WM or to reload Qtile did not allow me to log back into Qtile. 

I believe this is not a correct behaviour. 
Trying to run Qtile Start resulted in Error - Qtile(LG3D) was alredy running, Qtile check helped me to find the issue with non letters. 

### Version

0.25.1.dev0+g005da458.d20240413

### Backend

X11 (default)

### Config

```python
Key([mod, "control"], "q", lazy.shutdown(), desc="Shutdown Qtile"),
Key([mod, "control"], "|", lazy.shutdown(), desc="Shutdown Qtile"),
Key([mod, "control"], "=", lazy.shutdown(), desc="Shutdown Qtile"),    
```

### Logs

```text
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/libqtile/scripts/start.py", line 109, in start
    q.loop()
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 202, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 227, in async_loop
    self.load_config(initial=True)
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 143, in load_config
    self.grab_key(key)
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 476, in grab_key
    syms = self.core.grab_key(key)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/x11/core.py", line 505, in grab_key
    keysym, modmask = self.lookup_key(key)
                      ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/x11/core.py", line 499, in lookup_key
    raise utils.QtileError(err)
libqtile.utils.QtileError: Unknown key: |
2024-05-24 02:01:20,515 ERROR libqtile core.py:__init__():L104 not starting; existing window manager awesome
2024-05-24 02:02:22,467 ERROR libqtile manager.py:load_config():L115 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 113, in load_config
    self.config.validate()
  File "/usr/lib/python3.12/site-packages/libqtile/confreader.py", line 152, in validate
    raise ConfigError("No such key: %s" % k.key)
libqtile.confreader.ConfigError: No such key: =
2024-05-24 02:02:22,468 WARNING libqtile utils.py:send_notification():L298 dbus-next is not installed. Unable to send notifications.
2024-05-24 02:02:22,521 ERROR libqtile start.py:start():L111 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/libqtile/backend/x11/core.py", line 496, in lookup_key
    keysym = xcbq.get_keysym(key.key)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/x11/xcbq.py", line 765, in get_keysym
    raise XCBQError("Unknown key: %s" % key)
libqtile.backend.x11.xcbq.XCBQError: Unknown key: =

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/libqtile/scripts/start.py", line 109, in start
    q.loop()
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 202, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 227, in async_loop
    self.load_config(initial=True)
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 143, in load_config
    self.grab_key(key)
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 476, in grab_key
    syms = self.core.grab_key(key)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/x11/core.py", line 505, in grab_key
    keysym, modmask = self.lookup_key(key)
                      ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/x11/core.py", line 499, in lookup_key
    raise utils.QtileError(err)
libqtile.utils.QtileError: Unknown key: =
2024-05-24 02:03:31,491 WARNING libqtile manager.py:grab_key():L481 Key spec duplicated, overriding previous: <Key (['mod4'], f)>
2024-05-24 02:03:31,492 WARNING libqtile manager.py:grab_key():L481 Key spec duplicated, overriding previous: <Key (['mod4'], 0)>
2024-05-24 02:03:31,492 WARNING libqtile manager.py:grab_key():L481 Key spec duplicated, overriding previous: <Key (['mod4'], 0)>
2024-05-24 02:03:31,492 WARNING libqtile manager.py:grab_key():L481 Key spec duplicated, overriding previous: <Key (['mod4'], 0)>
2024-05-24 02:03:31,492 WARNING libqtile manager.py:grab_key():L481 Key spec duplicated, overriding previous: <Key (['mod4'], 0)>
2024-05-24 02:03:31,492 WARNING libqtile manager.py:grab_key():L481 Key spec duplicated, overriding previous: <Key (['mod4'], 0)>
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by IgorSlonka** [comment]
Each line in config is a separate instance of me trying to change something.

**Comment by tych0** [comment]
You need to use "equals" instead. Maybe we should add some aliases here: https://github.com/qtile/qtile/blob/1c3ddd5e175bcf665f22c97782701b111db54f84/libqtile/backend/x11/xkeysyms.py#L568 ?

**Comment by IgorSlonka** [comment]
Thanks, I think it closes the ticket.
I'd say that aliases should be prepped at least for all keys on 'normal' 100% keyboard

**Comment by elParaguayo** [comment]
`|` is also an invalid name. That would be `"bar"`.
