### ISSUE TITLE
OSError: cannot load library 'libpango-1.0.so.0'

### ISSUE THREAD

**Issue by iribirii** [qtile/qtile#4863]
### Issue description

I keep getting this error whenever I try to load my qtile configuration. 
This has been working fine until today since I rebooted my computer after updating all the packages. 
Any idea of what could have gone wrong?

`OSError: cannot load library 'libpango-1.0.so.0': /usr/lib/libpango-1.0.so.0: undefined symbol: g_once_init_leave_pointer.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libpango-1.0.so.0'`

I update pango and this keeps happening 

### Version

0.26.1.dev21+g1cd2e6fe

### Backend

X11 (default)

### Logs

```text
I] ➜ qtile start                                                                                                                                                                                         (postdoc)
Traceback (most recent call last):
  File "/home/iribirii/anaconda3/envs/postdoc/bin/qtile", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/iribirii/anaconda3/envs/postdoc/lib/python3.12/site-packages/libqtile/scripts/main.py", line 79, in main
    func(options)
  File "/home/iribirii/anaconda3/envs/postdoc/lib/python3.12/site-packages/libqtile/scripts/start.py", line 103, in start
    q = make_qtile(options)
        ^^^^^^^^^^^^^^^^^^^
  File "/home/iribirii/anaconda3/envs/postdoc/lib/python3.12/site-packages/libqtile/scripts/start.py", line 66, in make_qtile
    kore = libqtile.backend.get_core(options.backend)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iribirii/anaconda3/envs/postdoc/lib/python3.12/site-packages/libqtile/backend/__init__.py", line 46, in get_core
    return importlib.import_module(f"libqtile.backend.{backend}.core").Core(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iribirii/anaconda3/envs/postdoc/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/iribirii/anaconda3/envs/postdoc/lib/python3.12/site-packages/libqtile/backend/x11/core.py", line 38, in <module>
    from libqtile.backend import base
  File "/home/iribirii/anaconda3/envs/postdoc/lib/python3.12/site-packages/libqtile/backend/base/__init__.py", line 2, in <module>
    from libqtile.backend.base.drawer import Drawer  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iribirii/anaconda3/envs/postdoc/lib/python3.12/site-packages/libqtile/backend/base/drawer.py", line 40, in <module>
    from libqtile import pangocffi, utils
  File "/home/iribirii/anaconda3/envs/postdoc/lib/python3.12/site-packages/libqtile/pangocffi.py", line 53, in <module>
    pango = ffi.dlopen("libpango-1.0.so.0")  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iribirii/anaconda3/envs/postdoc/lib/python3.12/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iribirii/anaconda3/envs/postdoc/lib/python3.12/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iribirii/anaconda3/envs/postdoc/lib/python3.12/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libpango-1.0.so.0': /usr/lib/libpango-1.0.so.0: undefined symbol: g_once_init_leave_pointer.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libpango-1.0.so.0'
```
```


### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tych0** [comment]
What distro are you on? It sounds like the packaging for pango is broken somehow.

**Comment by tych0** [comment]
I would ask in their support area, but my guess is if you reinstall/rebuild some packages (specifically, glib and pango), it might get fixed.

**Comment by iribirii** [comment]
well, it works today :man_shrugging:  I re-started like 3 times yesterday and nothing worked. and today magically does... thanks anyway!
