### ISSUE TITLE
A bug when combining ScreenSplit and Plasma

### ISSUE THREAD

**Issue by nazar-pc** [qtile/qtile#4915]
Finally tested and it is reproducible with Plasma layout, but not Tile for example.
Now that both are upstream it makes sense to create a proper issue.

Here is relevant part of the config:
<details>

```python
primary_match = [
    Match(wm_class='firefox'),
]

main_layout = ScreenSplit(
    name="Main",
    splits=[
        {
            "name": "left",
            "rect": (0, 0, 0.15, 1),
            "layout": Plasma(
                insert_position=1,
            ),
        },
        {
            "name": "top",
            "rect": (0.15, 0, 0.6, 0.4),
            "layout": Plasma(
                insert_position=1,
            ),
        },
        {
            "name": "bottom",
            "rect": (0.15, 0.4, 0.6, 0.6),
            "layout": Plasma(
                insert_position=1,
            ),
            "matches": primary_match,
        },
        {
            "name": "right",
            "rect": (0.75, 0, 0.25, 1),
            "layout": Plasma(
                insert_position=1,
            ),
        },
    ],
)

layouts = [
    main_layout,
]
```

</details>

Reproduction steps:
* Open Firefox
    * Opens in `bottom` split
    * Make sure this is the only app in this split
* Open anonymous window in Firefox
* Move main Firefox window to a different split (for example `top`)
    * Anonymous window remains in `bottom` and is the only window there
* Close anonymous window

Observe layout being broken:
1) I can no longer move Firefox window between splits, it doesn't get activated
2) 50% of `bottom` split is occupied by "nothing" like if there is an app there, but there isn't (even though private window before that occupied 100% of the split)

_Originally posted by @nazar-pc in https://github.com/qtile/qtile/issues/3793#issuecomment-1272122365_

**Comment by elParaguayo** [comment]
Thanks. I'll take a look when I can but life is going to be pretty manic this month so won't have a lot of time for qtile.

**Comment by elParaguayo** [comment]
Life still busy!

**Comment by nazar-pc** [comment]
Certainly still the case and not only with Firefox. I kind of learned to avoid it, but it is still actively annoying alongside with even more annoying https://github.com/qtile/qtile/issues/4805

**Comment by nazar-pc** [comment]
Unfortunately still happening

**Comment by elParaguayo** [comment]
Sorry @nazar-pc I had forgotten about this one. I'll see if I can remember to look at it soon.

EDIT: is this with `Plasma` in all splits? Or does it happen if `Plasma` is in just one split?

**Comment by elParaguayo** [comment]
So, this is the error message that is triggered when I follow your steps:
```
2025-06-21 07:10:30,619 libqtile manager.py:process_key_event():L485  KB command error move_window_to_next_split: Traceback (most recent call last):
  File "/home/elp/Documents/scripts/github/qtile-dev/qtile/libqtile/command/interface.py", line 431, in call
    return SUCCESS, cmd(*args, **kwargs)
                    ~~~^^^^^^^^^^^^^^^^^
  File "/home/elp/Documents/scripts/github/qtile-dev/qtile/libqtile/layout/screensplit.py", line 315, in move_window_to_next_split
    self._move_win_to_split()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/elp/Documents/scripts/github/qtile-dev/qtile/libqtile/layout/screensplit.py", line 258, in _move_win_to_split
    self.group.add(self._move_win)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/elp/Documents/scripts/github/qtile-dev/qtile/libqtile/group.py", line 268, in add
    i.add_client(win)
    ~~~~~~~~~~~~^^^^^
  File "/home/elp/Documents/scripts/github/qtile-dev/qtile/libqtile/layout/screensplit.py", line 222, in add_client
    self.active_layout.add_client(win)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/elp/Documents/scripts/github/qtile-dev/qtile/libqtile/layout/plasma.py", line 952, in add_client
    self.root.restore(new)
    ~~~~~~~~~~~~~~~~~^^^^^
  File "/home/elp/Documents/scripts/github/qtile-dev/qtile/libqtile/layout/plasma.py", line 634, in restore
    node.siblings[0].size = sizes[1]
    ~~~~~~~~~~~~~^^^
IndexError: list index out of range

2025-06-21 07:10:36,578 libqtile manager.py:process_key_event():L485  KB command error move_window_to_next_split: Traceback (most recent call last):
  File "/home/elp/Documents/scripts/github/qtile-dev/qtile/libqtile/command/interface.py", line 431, in call
    return SUCCESS, cmd(*args, **kwargs)
                    ~~~^^^^^^^^^^^^^^^^^
  File "/home/elp/Documents/scripts/github/qtile-dev/qtile/libqtile/layout/screensplit.py", line 315, in move_window_to_next_split
    self._move_win_to_split()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/elp/Documents/scripts/github/qtile-dev/qtile/libqtile/layout/screensplit.py", line 256, in _move_win_to_split
    self.group.remove(self._move_win)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/elp/Documents/scripts/github/qtile-dev/qtile/libqtile/group.py", line 309, in remove
    self.focus(nextfocus, warp=True, force=force)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elp/Documents/scripts/github/qtile-dev/qtile/libqtile/group.py", line 234, in focus
    layout.focus(win)
    ~~~~~~~~~~~~^^^^^
  File "/home/elp/Documents/scripts/github/qtile-dev/qtile/libqtile/layout/base.py", line 491, in focus
    self.clients.current_client = client
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elp/Documents/scripts/github/qtile-dev/qtile/libqtile/layout/base.py", line 261, in current_client
    self._current_idx = self.clients.index(client)
                        ~~~~~~~~~~~~~~~~~~^^^^^^^^
ValueError: Window(name='A bug when combining ScreenSplit and Plasma · Issue #4915 · qtile/qtile — Mozilla Firefox', wid=14680107) is not in list
```
Now just need to work out why that's happening...

**Comment by elParaguayo** [comment]
OK - so the issue is caused by the `restore` functionality of the `Plasma` layout. If I disable that then this issue disappears.

**Comment by elParaguayo** [comment]
Can you try #5297 please.
