### ISSUE TITLE
Wlan widget crashes if ESSID contains markup

### ISSUE THREAD

**Issue by andreashug** [qtile/qtile#4943]
### Issue description

The `Wlan` widget crashes if the ESSID contains characters considered as markup by `pango`, e.g. "A&B"

It's easy to reproduce by running
```
>>> from libqtile.pangocffi import parse_markup
>>> parse_markup("A&B")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/lib/python3.12/site-packages/libqtile/pangocffi.py", line 182, in parse_markup
    raise Exception("parse_markup() failed for %s" % value)
```

I'm happy to provide a pull request if you can confirm this as an actual bug. My suggested approach would be to use `libqtile.pangocffi.markup_escape_text` in `Wlan.poll()` immediately before calling `self.format.format`.

https://github.com/qtile/qtile/blob/ff90e5cfae7418ad62d0accc3cb38757fca2cdb9/libqtile/widget/wlan.py#L102

### Version

0.26.0

### Backend

X11 (default)

### Logs

```text
2024-08-01 09:19:11,384 ERROR libqtile bar.py:_configure_widget():L388 Wlan widget crashed during _configure with error:
Traceback (most recent call last):
  File "/opt/qtile/venv/lib/python3.12/site-packages/libqtile/bar.py", line 379, in _configure_widget
    widget._configure(self.qtile, self)
  File "/opt/qtile/venv/lib/python3.12/site-packages/libqtile/widget/base.py", line 800, in _configure
    _TextBox._configure(self, qtile, bar)
  File "/opt/qtile/venv/lib/python3.12/site-packages/libqtile/widget/base.py", line 573, in _configure
    self.layout = self.drawer.textlayout(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/qtile/venv/lib/python3.12/site-packages/libqtile/backend/base/drawer.py", line 322, in textlayout
    textlayout = TextLayout(
                 ^^^^^^^^^^^
  File "/opt/qtile/venv/lib/python3.12/site-packages/libqtile/backend/base/drawer.py", line 393, in __init__
    self.text = text
    ^^^^^^^^^
  File "/opt/qtile/venv/lib/python3.12/site-packages/libqtile/backend/base/drawer.py", line 412, in text
    attrlist, value, accel_char = pangocffi.parse_markup(value)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/qtile/venv/lib/python3.12/site-packages/libqtile/pangocffi.py", line 182, in parse_markup
    raise Exception("parse_markup() failed for %s" % value)
Exception: parse_markup() failed for b'A&V'
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by saviola777** [comment]
I think I would call `libqtile.pangocffi.markup_escape_text` on the result of `self.format.format`, but maybe that's what you meant.

**Comment by andreashug** [comment]
Actually, I thought to only escape the ESSID. Wouldn't escaping the result of `self.format.format` prevent any markup in the format string? To my understanding, this would render the `markup` flag in the widget config useless.

**Comment by elParaguayo** [comment]
Yes. We should escape text before it's formatted.

**Comment by saviola777** [comment]
I see, I thought the `markup` flag was mainly for the `fmt` parameter. I looked at the [cmus widget](https://github.com/qtile/qtile/blob/master/libqtile/widget/cmus.py#L215) where everything is escaped.

**Comment by elParaguayo** [comment]
If we escape text that includes pango markup then the markup won't work.

**Comment by elParaguayo** [comment]
@andreashug will you submit a PR for this?

**Comment by andreashug** [comment]
Yes, sorry about the delay.

I'm not so happy with monkeypatching `MockIwlib` in the test, but making it configurable would have required to refactor the other tests. Do you have a better idea?
