### ISSUE TITLE
Prompt stop working when config reloaded on wayland

### ISSUE THREAD

**Issue by Jeff-WuYo** [qtile/qtile#4952]
### Issue description

I use the default prompt, as the title, it stops working when config reloaded on wayland

### Version

0.27.1.dev0+g17cc04b3.d20240714

### Backend

Wayland (experimental)

### Config

[My config on github](https://github.com/Jeff-WuYo/Dot_file/blob/main/dot_config/qtile/config.py)

### Logs

```text
2024-08-09 02:01:10,438 ERROR libqtile manager.py:process_key_event():L474 KB command error spawncmd: Traceback (most recent call last):
   File "/usr/lib/python3.12/site-packages/libqtile/command/interface.py", line 431, in call
     return SUCCESS, cmd(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^
   File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 1638, in spawncmd
     mb.start_input(prompt, f, complete, aliases=aliases)
   File "/usr/lib/python3.12/site-packages/libqtile/widget/prompt.py", line 497, in start_input
     self._update()
   File "/usr/lib/python3.12/site-packages/libqtile/widget/prompt.py", line 525, in _update
     self.text = self.archived_input or self.user_input
     ^^^^^^^^^
   File "/usr/lib/python3.12/site-packages/libqtile/widget/base.py", line 523, in text
     self.layout.text = self.formatted_text
     ^^^^^^^^^^^^^^^^
   File "/usr/lib/python3.12/site-packages/libqtile/backend/base/drawer.py", line 421, in text
     self.layout.set_attributes(attrlist)
   File "/usr/lib/python3.12/site-packages/libqtile/pangocffi.py", line 114, in set_attributes
     pango.pango_layout_set_attributes(self._pointer, attrs)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Thanks. This Pango error pops up everywhere. It's incredibly annoying! I still haven't got to the bottom of it but it's definitely linked to reloading the config.

**Comment by Jeff-WuYo** [comment]
After 63ce551, the issue is gone, there are no error relate to this, closing.
