### ISSUE TITLE
Bar iteration when config reload on wayland

### ISSUE THREAD

**Issue by Jeff-WuYo** [qtile/qtile#4954]
### Issue description

When I reload the config, the bar iterate on top of each other. I've translucent bar, it's easier to find out. There's also visual glitch on previous bar. 
When it happened, it also breaks prompt widget, see #4952 .

### Version

0.27.1.dev0+g17cc04b3.d20240714

### Backend

Wayland (experimental)

### Config

[My config on github](https://github.com/Jeff-WuYo/Dot_file/blob/main/dot_config/qtile/config.py)

### Logs

```text
2024-08-09 20:23:50,232 ERROR libqtile manager.py:_finalize_configurables():L327 exception during finalize          
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 315, in _finalize_configurables
    widget.finalize()
  File "/usr/lib/python3.12/site-packages/libqtile/widget/statusnotifier.py", line 159, in finalize
    host.unregister_callbacks(
  File "/usr/lib/python3.12/site-packages/libqtile/widget/helpers/status_notifier/statusnotifier.py", line 670, in unregister_callbacks
    self._on_item_added.remove(on_item_added)
ValueError: list.remove(x): x not in list
2024-08-09 20:23:50,248 WARNING libqtile prompt.py:_configure():L440 Prompt widget only supports audible bell under X11
2024-08-09 20:23:54,264 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 973, in f
    func(*args)
  File "/usr/lib/python3.12/site-packages/libqtile/bar.py", line 620, in _actual_draw
    self._resize(self._length, self.widgets)
  File "/usr/lib/python3.12/site-packages/libqtile/bar.py", line 463, in _resize
    stretchspace = length - sum(i.length for i in widgets if i.length_type != STRETCH)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/bar.py", line 463, in <genexpr>
    stretchspace = length - sum(i.length for i in widgets if i.length_type != STRETCH)
                                ^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/command/base.py", line 281, in __getattr__
    raise AttributeError(f"{self.__class__} has no attribute {name}")
AttributeError: <class 'libqtile.widget.groupbox.GroupBox'> has no attribute length. Did you mean: '_length'?
2024-08-09 20:23:54,755 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 973, in f
    func(*args)
  File "/usr/lib/python3.12/site-packages/libqtile/bar.py", line 620, in _actual_draw
    self._resize(self._length, self.widgets)
  File "/usr/lib/python3.12/site-packages/libqtile/bar.py", line 463, in _resize
    stretchspace = length - sum(i.length for i in widgets if i.length_type != STRETCH)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/bar.py", line 463, in <genexpr>
    stretchspace = length - sum(i.length for i in widgets if i.length_type != STRETCH)
                                ^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/command/base.py", line 281, in __getattr__
    raise AttributeError(f"{self.__class__} has no attribute {name}")
AttributeError: <class 'libqtile.widget.groupbox.GroupBox'> has no attribute length. Did you mean: '_length'?
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by rmcmilli** [comment]
I had this issue when using [StatusNotifier on 0.27.0](https://github.com/elParaguayo/qtile-extras/issues/369). The update to 0.28.1 fixed it for me.

**Comment by Jeff-WuYo** [comment]
After 63ce551, the issue is gone, there are no error relate to this, closing.
