### ISSUE TITLE
Issue using lazy.group[].dropdown_toggle()

### ISSUE THREAD

**Issue by tpaniaki** [qtile/qtile#4964]
### Issue description

```
from libqtile import bar, layout, qtile, widget, hook
from libqtile.config import Click, Drag, Group, Key, Match, Screen, ScratchPad, DropDown
from libqtile.lazy import lazy

keys = [
 Key([mod], "a", lazy.group['scratchpad'].dropdown_toggle('thunar')),
 Key([mod], "d", lazy.group['scratchpad'].dropdown_toggle('thunar_download')),
]

groups = [Group(i) for i in "12"]

groups.append(
    ScratchPad("scratchpad", [
        DropDown("thunar", "thunar /home/USER", width=0.7, height=0.7, x=0.15, y=0.15, on_focus_lost_hide=False, opacity=1.0),
        DropDown("thunar_download", "thunar /home/USER/Téléchargements", width=0.7, height=0.7, x=0.15, y=0.15, on_focus_lost_hide=False, opacity=1.0),
    ])
)
```
If I close "thunar" and then open "thunar_download", scratchpads work. But if I toggle up/down "thunar" and then toggle "thunar_download" two random behaviors happen: 1. Nothing or 2. "thunar_download" opens maximized. 

### Version

0.27.1.dev0+g17cc04b3.d20240714

### Backend

Wayland (experimental)

### Logs

```text
libqtile.confreader.ConfigError: No such key: scratchpad
2024-08-15 20:04:19,395 WARNING libqtile utils.py:send_notification():L297 dbus-next is not installed. Unable to send notifications.
2024-08-15 20:04:20,630 ERROR libqtile manager.py:load_config():L117 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 115, in load_config
    self.config.validate()
  File "/usr/lib/python3.12/site-packages/libqtile/confreader.py", line 154, in validate
    raise ConfigError("No such key: %s" % k.key)
libqtile.confreader.ConfigError: No such key: scratchpad
2024-08-15 20:04:20,630 WARNING libqtile utils.py:send_notification():L297 dbus-next is not installed. Unable to send notifications.
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tpaniaki** [comment]
Solved by `dbus-launch thunar path` to generate a separate thunar instance.
