### ISSUE TITLE
default prompt can't type capital letter

### ISSUE THREAD

**Issue by Jeff-WuYo** [qtile/qtile#4983]
### Issue description

I use default prompt. I can't enter capital letter or column, or anything need shift key. On xorg, it works ok. \
It output error when I launch the prompt, and any subsequences input. I use `tail -f .local/share/qtile/qtile.log` to check.

### Version

0.28.2.dev0+gf1ed49bc.d20240813

### Backend

Wayland (experimental)

### Config

[My config on github](https://github.com/Jeff-WuYo/Dot_file/blob/main/dot_config/qtile/config.py)

### Logs

```text
2024-08-30 15:22:53,705 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.12/site-packages/libqtile/backend/wayland/inputs.py", line 311, in _on_key
    self.core.focused_internal.process_key_press(keysym)
                                                 ^^^^^^
UnboundLocalError: cannot access local variable 'keysym' where it is not associated with a value
2024-08-30 15:22:53,759 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.12/site-packages/libqtile/backend/wayland/inputs.py", line 311, in _on_key
    self.core.focused_internal.process_key_press(keysym)
                                                 ^^^^^^
UnboundLocalError: cannot access local variable 'keysym' where it is not associated with a value
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by tych0** [comment]
thanks for the report, can you try the above patch/PR?

**Comment by Jeff-WuYo** [comment]
I've tried, it behave extreme weird. I couldn't type any letter properly, just ::::.,.[[   ...,;; or some sort.
