### ISSUE TITLE
Pywayland UTF-8 error

### ISSUE THREAD

**Issue by NeoFax75** [qtile/qtile#4995]
### Issue description

My bar does not display properly and my log file is spammed every like 2 seconds.

```2024-09-07 19:21:07,433 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.12/site-packages/libqtile/backend/wayland/core.py", line 760, in _on_cursor_motion
    self._process_cursor_motion(event.time_msec, self.cursor.x, self.cursor.y)
  File "/usr/lib/python3.12/site-packages/libqtile/backend/wayland/core.py", line 1067, in _process_cursor_motion
    self._focus_pointer(cx_int, cy_int, motion=time_msec)
  File "/usr/lib/python3.12/site-packages/libqtile/backend/wayland/core.py", line 1113, in _focus_pointer
    win.process_pointer_enter(cx, cy)
  File "/usr/lib/python3.12/site-packages/libqtile/bar.py", line 553, in process_pointer_enter
    widget = self.get_widget_in_position(x, y)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/bar.py", line 517, in get_widget_in_position
    if x < i.offsetx + i.length:
                       ^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qtile_extras/widget/decorations.py", line 975, in length_get
    length = int(self.calculate_length())
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/widget/groupbox.py", line 344, in calculate_length
    width += self.box_width([g])
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/widget/groupbox.py", line 55, in box_width
    width, _ = self.drawer.max_layout_size(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/base/drawer.py", line 339, in max_layout_size
    sizelayout.text = i
    ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/base/drawer.py", line 422, in text
    self.layout.set_text(utils.scrub_to_utf8(value))
  File "/usr/lib/python3.12/site-packages/libqtile/pangocffi.py", line 117, in set_text
    text = text.encode("utf-8")
           ^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-1: surrogates not allowed```

### Version

0.28.2.dev0+gf1ed49bc.d20240813

### Backend

Wayland (experimental)

### Config

```python
#!/bin/python3
#  ____     ____
# / ___|   |  _ \
# \___ \   | | | |
#  ___) |  | |_| |
# |____(_) |____(_)
#
# Qtile imports
import os, subprocess
from libqtile import bar, layout, hook, widget, qtile
from libqtile.config import Screen, Match
from libqtile.lazy import lazy
from libqtile.utils import guess_terminal
from libqtile.dgroups import simple_key_binder

from keys import keys, home, mod1, mod2, mod3, mod, groups, mouse
from themes import Dracula, Midnight, Monokai, Tomorrow, One_dark, Nordic, Catppuccin, Tokyo_Night_Storm

#from qtile_extras import widget
from qtile_extras.widget import WiFiIcon
from qtile_extras.widget.decorations import PowerLineDecoration

@hook.subscribe.startup_once
def start_once():
    home = os.path.expanduser('~/.config/qtile/autostart.sh')
    subprocess.Popen([home])




theme = Tokyo_Night_Storm

accent_color=theme["blue"]

# Define the layout options
layout_defaults = {
    "border_width": 3,
    "border_focus": accent_color,
    "border_normal": theme["black"],
}
layout_mine = {
    "border_width": 3,
    "border_focus": accent_color,
    "border_normal": theme["background"],
    "margin": 12,
}
layout_mine2 = {
    "border_width": 3,
    "border_focus": accent_color,
    "border_normal": theme["background"],
}
layouts = [
    layout.MonadTall(**layout_mine, name="Tiled"),
    layout.Spiral(**layout_mine),
    layout.Bsp(
        **layout_mine,
        border_on_single=False,
        fair=True,
        grow_amount=10,
        lower_right=True,
        margin_on_single=None,
        ratio=1.6,
        wrap_clients=False
    ),
    layout.Max(name="  Fill "),
    layout.Floating(name="Float"),
    layout.Zoomy(**layout_mine, name="MStack"),
]

widget_defaults = dict(
    font="FiraCode Nerd Font Mono Regular",
    fontsize=12,
    padding=6,
)
extension_defaults = widget_defaults.copy()

icon = lambda char, foreground, background, fontsize: widget.TextBox(
    font="FiraCode Nerd Font Mono Regular",
    text=char,
    padding=1,
    margin=0,
    fontsize=fontsize,
    background=background,
    foreground=foreground,
    center_aligned=True,
)

# Works only with qtile-extras, add **powerline in all widgets

powerline = {
    "decorations": [
        PowerLineDecoration(path='forward_slash')
    ]
}


screens = [
    Screen(
        top=bar.Bar(

            [
                widget.Sep(
                    background=theme["background"],
                    foreground=theme["foreground"],
                    padding=1,
                ),
                # ------
                widget.TextBox(
                    font="FiraCode Nerd Font Mono Regular",
                    text=" ",
                    fontsize=20,
                    background=theme["background"],
                    foreground=theme["foreground"],
                    margin=10,
                    padding=2,
                    mouse_callbacks={
                        'Button1': lazy.spawn([home + '/bin/sidebar'])
                        },

                ),
                # ------
                widget.CurrentLayout(
                    use_mask=True,
                    font="FiraCode Nerd Font Mono Regular",
                     # scale=0.7,
                    padding=5,
                    background=theme["background"],
                    foreground=theme["foreground"],
                    fontsize=11,
                    **powerline
                ),
                # -----
                widget.GroupBox(
                    font="FiraCode Nerd Font Mono Regular",
                    highlight_method="block",
                    fmt="{}",
                    this_current_screen_border=theme["on"],
                    #this_other_screen_border=theme["blue"],
                    #this_current_screen=theme["background"],
                    block_highlight_text_color=theme["foreground"],
                    inactive=theme["blue"],
                    background=theme["BG1"],
                    borderwidth=1,
                    rounded=True,
                    padding_x=10,
                    padding_y=8,
                    margin_x=2,
                    disable_drag=True,
                    center_aligned=True,
                    hide_unused=True,
                    # visible_groups=['1', '2', '3'],
                    **powerline,
                    #margin=0
                ),
                # ------
                widget.WindowName(
                    format= '{name}',
                    font="FiraCode Nerd Font Mono Regular",
                    fontsize=13,
                    background=theme["BG1"],
                    foreground=theme["blue"],
                    center_aligned=True,
                    max_chars=40,
                ),
                # ------
                widget.Systray(
                    fontsize=12,
                    background=theme["BG1"],
                    center_aligned=True,
                    **powerline
                ),
                # ------
                icon("\uf021", foreground=theme["magenta"], background=theme["BG1"], fontsize=14,),
                widget.CheckUpdates(
                    distro="Arch",
                    font="FiraCode Nerd Font Mono",
                    fontsize=14,
                    dislpay_format = '{updates}',
                    no_update_string="Updates:0",
                    colour_no_updates=theme["blue"],
                    colour_have_updates=theme["magenta"],
                    background=theme["BG1"],
                    foreground=theme["magenta"],
                    update_interval=10,
                    padding=5,
                    **powerline,
                    mouse_callbacks={
                        'Button1': lazy.spawn(f"kitty -e sudo pacman -Syu")
                        },
                ),
                # -----
                widget.TextBox(
                    font="FiraCode Nerd Font Mono Regular",
                    text=" ",
                    fontsize=16,
                    foreground=theme["orange"],
                    background=theme["BG1"],
                    margin=3,
                    padding=2,
                    center_aligned=True,
                    mouse_callbacks={
                        'Button1': lazy.spawn("nitrogen --set-zoom-fill --random"),
                        'Button3': lazy.spawn([home + '/bin/ngen']),
                        },
                **powerline
                ),
                # ------
                widget.Net(
                    interface="wlan0",
                    format=" {down}",
                    background=theme["BG1"],
                    prefix="k",
                    foreground=theme["cyan"],
                    font="FiraCode Nerd Font Mono",
                    fontsize=14,
                    padding=5,  # Adjust the padding as needed
                    mouse_callbacks={'Button1': lazy.spawn(f"networkmanager_dmenu")},
                    **powerline
                ),

                # widget.WiFiIcon(
                #     interface="wlan0",
                #     active_colour=theme["cyan"],
                #     inactive_colour=theme["BG"],
                #     foreground=theme["cyan"],
                #     background = theme["BG3"],
                #     font="FiraCode Nerd Font Mono",
                #     fontsize=14,
                #     wifi_arc=100,
                #     expanded_timeout=None,
                #     update_interval=1,
                #     **powerline,
                #     mouse_callbacks={
                #         'Button1': lazy.spawn(f"networkmanager_dmenu")
                #         },
                #     ),
                # ------
                widget.BatteryIcon(
                    scale=1,
                    theme_path='/home/neofax/.local/share/icons/Panel/',
                    update_interval=3,
                    foreground=theme["green"],
                    background=theme["BG1"],
                    **powerline,
                    ),

                # ------
                icon("\uf017", foreground=theme["red"], background=theme["BG1"], fontsize=15,),
                widget.Clock(
                    font="FiraCode Nerd Font Mono",
                    format="%I:%M %p",
                    background=theme["BG1"],
                    foreground=theme["blue"],
                    fontsize= 16,
                    center_aligned=True
                ),
                widget.TextBox(
                    background=theme["BG1"],
                    padding=5,
                    text=" ",
                    fontsize=20,
                    mouse_callbacks={
                        "Button1": lazy.spawn(home + "/.config/qtile/scripts/powermenu.sh")
                    },
                ),
            ],
            24,
            background=theme["background"],
            # margin=[8,8,0,8],
            # border_width=[5, 5, 0, 5],  # Draw top and bottom borders
            # border_color=["ff00ff", "000000", "ff00ff", "000000"]  # Borders are magenta
        ),
    ),
]


dgroups_key_binder = None
dgroups_app_rules = []  # type: list
follow_mouse_focus = True
bring_front_click = False
cursor_warp = False
floating_layout = layout.Floating(
    float_rules=[
        # Run the utility of `xprop` to see the wm class and name of an X client.
        # *layout.Floating.default_float_rules,
        Match(title='Quit and close tabs?'),
        Match(wm_type='utility'),
        Match(wm_type='notification'),
        Match(wm_type='toolbar'),
        Match(wm_type='splash'),
        Match(wm_type='dialog'),
        Match(wm_class='gimp-2.99'),
        # Match(wm_class='Firefox'),
        Match(wm_class='file_progress'),
        Match(wm_class='confirm'),
        Match(wm_class='dialog'),
        Match(wm_class='download'),
        Match(wm_class='error'),
        Match(wm_class='notification'),
        Match(wm_class='splash'),
        Match(wm_class='toolbar'),
        Match(title='About LibreOffice'),
        Match(wm_class='confirmreset'),  # gitk
        Match(wm_class='makebranch'),  # gitk
        Match(wm_class='maketag'),  # gitk
        Match(wm_class='ssh-askpass'),  # ssh-askpass
        Match(title='branchdialog'),  # gitk
        Match(wm_class='pinentry-qt'),  # GPG key password entry
        Match(wm_class="pinentry-gtk-2"),
        Match(wm_class="zoom"),
        Match(func=lambda c: c.is_transient_for()),  # automatically float a window if it has a parent
    ]
)
auto_fullscreen = True
focus_on_window_activation = "smart"
reconfigure_screens = True

# If things like steam games want to auto-minimize themselves when losing
# focus, should we respect this or not?
auto_minimize = True

# When using the Wayland backend, this can be used to configure input devices.
wl_input_rules = None

# XXX: Gasp! We're lying here. In fact, nobody really uses or cares about this
# string besides java UI toolkits; you can see several discussions on the
# mailing lists, GitHub issues, and other WM documentation that suggest setting
# this string if your java app doesn't work correctly. We may as well just lie
# and say that we're a working one by default.
#
# We choose LG3D to maximize irony: it is a 3D non-reparenting WM written in
# java that happens to be on java's whitelist.
#wmname = "LG3D"
wmname = "Elysium/Q-tile"
```

### Logs

```text
2024-09-07 19:21:07,433 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.12/site-packages/libqtile/backend/wayland/core.py", line 760, in _on_cursor_motion
    self._process_cursor_motion(event.time_msec, self.cursor.x, self.cursor.y)
  File "/usr/lib/python3.12/site-packages/libqtile/backend/wayland/core.py", line 1067, in _process_cursor_motion
    self._focus_pointer(cx_int, cy_int, motion=time_msec)
  File "/usr/lib/python3.12/site-packages/libqtile/backend/wayland/core.py", line 1113, in _focus_pointer
    win.process_pointer_enter(cx, cy)
  File "/usr/lib/python3.12/site-packages/libqtile/bar.py", line 553, in process_pointer_enter
    widget = self.get_widget_in_position(x, y)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/bar.py", line 517, in get_widget_in_position
    if x < i.offsetx + i.length:
                       ^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qtile_extras/widget/decorations.py", line 975, in length_get
    length = int(self.calculate_length())
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/widget/groupbox.py", line 344, in calculate_length
    width += self.box_width([g])
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/widget/groupbox.py", line 55, in box_width
    width, _ = self.drawer.max_layout_size(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/base/drawer.py", line 339, in max_layout_size
    sizelayout.text = i
    ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/base/drawer.py", line 422, in text
    self.layout.set_text(utils.scrub_to_utf8(value))
  File "/usr/lib/python3.12/site-packages/libqtile/pangocffi.py", line 117, in set_text
    text = text.encode("utf-8")
           ^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-1: surrogates not allowed
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Can you post your `groups` definition too? The error seems to be because the groupbox widget can't display the group names.

**Comment by ervinpopescu** [comment]
Also there should be a `Logs` section in the issue template that you can use for better formatting and an easier to see stacktrace :) It's quite a struggle but luckily it's a short(er) stacktrace than some other ones.

**Comment by NeoFax75** [comment]
`groups = [
    Group('1', label='\ue007', layout='  Fill ',
          matches=[Match(wm_class=my_browser)]),
    Group('2', label='\uf120', layout='Tiled',
          matches=[Match(wm_class=my_terminal)]),
    Group('3', label='\uf121', layout='Tiled',
          matches=[Match(wm_class=my_editor)]),
    Group('4', label='\uf115', layout='Tiled',
          matches=[Match(wm_class=my_filemanager)]),
    Group('5', label='\uf001', layout='Tiled',
          matches=[Match(wm_class=my_musicplayer)]),
    Group('6', label='\uf167', layout='Tiled',
          matches=[
                    Match(wm_class="mpv"),
                    Match(wm_class="zoom"),
                    Match(wm_class="vlc")
                  ]),
    Group('7', label='\uf086', layout='Tiled',
          matches=[Match(wm_class=my_messaging)]),
    Group('8', label='\uf1d3', layout='Tiled'
          ),
    Group('9', label='\uec17', layout='Tiled',
          matches=[
                    Match(wm_class="Steam"),
                    Match(wm_class="lutris")
                ],),
    Group('0', label='\udb80\uddee', layout='Tiled',
          matches=[
                    Match(wm_class=my_email),
                ],),
]`

**Comment by NeoFax75** [comment]
> Also there should be a `Logs` section in the issue template that you can use for better formatting and an easier to see stacktrace :) It's quite a struggle but luckily it's a short(er) stacktrace than some other ones.

I added a small portion of the log before I saw the log section.  This snippet repeats over and over for 2 files of data (over 200kb of logs).

**Comment by ervinpopescu** [comment]
Oh well, you can also try formatting logs like so:
\```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac ante ipsum. Curabitur dui urna, facilisis at cursus vitae, porttitor vel sem. Fusce egestas tempus odio, eu rutrum justo fringilla sed. Nunc diam ligula, ornare nec risus vel, pharetra faucibus elit. Nullam vestibulum dolor vitae purus lobortis, sed eleifend justo imperdiet. Fusce mollis tincidunt metus ut vehicula. Suspendisse dignissim ut mi sed consequat. Fusce mollis, sem in dapibus vestibulum, tellus lectus sagittis magna, vulputate rutrum ipsum tellus at urna. Cras in lacinia mauris. 
\```
which will render better like so:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac ante ipsum. Curabitur dui urna, facilisis at cursus vitae, porttitor vel sem. Fusce egestas tempus odio, eu rutrum justo fringilla sed. Nunc diam ligula, ornare nec risus vel, pharetra faucibus elit. Nullam vestibulum dolor vitae purus lobortis, sed eleifend justo imperdiet. Fusce mollis tincidunt metus ut vehicula. Suspendisse dignissim ut mi sed consequat. Fusce mollis, sem in dapibus vestibulum, tellus lectus sagittis magna, vulputate rutrum ipsum tellus at urna. Cras in lacinia mauris. 
```

**Comment by ervinpopescu** [comment]
`\udb80\uddee` is the issue, you can't have 2 UTF-8 characters in the labels:

```
$ python
Python 3.12.6 (main, Sep  8 2024, 13:18:56) [GCC 14.2.1 20240805] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> "\udb80\uddee".encode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-1: surrogates not allowed
>>> "\udb80\uddee".encode("utf16", errors="surrogatepass").decode("utf16")
'\U000f01ee'
>>> Group(
...         "0",
...         label="\U000f01ee",
...         layout="Tiled",
...     )
<config.Group '0' (layout=Tiled, persist=True, init=True)>
```

Try `\U000f01ee` instead. If your font supports it, I think it might work.

Also, `layout="Tiled"` won't work. See https://docs.qtile.org/en/latest/manual/ref/layouts.html,https://docs.qtile.org/en/latest/manual/config/index.html and https://docs.qtile.org/en/latest/manual/config/groups.html for more details

**Comment by NeoFax75** [comment]
> `\udb80\uddee` is the issue, you can't have 2 UTF-8 characters in the labels (or rather [a surrogate pair with some specific rules not met](https://python-list.python.narkive.com/aKjK4Jje/encoding-of-surrogate-code-points-to-utf-8)):
> 
> ```
> $ python
> Python 3.12.6 (main, Sep  8 2024, 13:18:56) [GCC 14.2.1 20240805] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> "\udb80\uddee".encode()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-1: surrogates not allowed
> >>> "\udb80\uddee".encode("utf16", errors="surrogatepass").decode("utf16")
> '\U000f01ee'
> >>> Group(
> ...         "0",
> ...         label="\U000f01ee",
> ...         layout="Tiled",
> ...     )
> <config.Group '0' (layout=Tiled, persist=True, init=True)>
> ```
> 
> ~Try `\U000f01ee` instead. If your font supports it, I think it might work~, my font (`Font Awesome 6 Free Solid`) doesn't so this is the result:
> 
> ![image](https://private-user-images.githubusercontent.com/84532402/365537636-086365fc-4b65-443c-b70f-694aaa797ba8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MjA1NTMsIm5iZiI6MTcyNTkyMDI1MywicGF0aCI6Ii84NDUzMjQwMi8zNjU1Mzc2MzYtMDg2MzY1ZmMtNGI2NS00NDNjLWI3MGYtNjk0YWFhNzk3YmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDIyMTczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExODI1OGZhNzk2NTBhOGJiYTgwZWMyNjI0YmVkN2YzOWRmMjNmNDg5MzZkNWFjNjNlNjFjZDgxNmJmZGFhMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BH1tCkTJn-FV4Q_3ubzm7arq7rBQ1oRs21Hez-3c0Xw)
> 
> Scratch that, it won't. https://www.fileformat.info/info/unicode/char/f01ee/index.htm
> 
> I think you are trying to use invalid(Private Use Area) Unicode characters:
> 
> https://www.fileformat.info/info/unicode/char/db80/index.htm https://www.fileformat.info/info/unicode/char/ddee/index.htm
> 
> Some more context is needed.
> 
> Moreover, `layout="Tiled"` won't work. See https://docs.qtile.org/en/latest/manual/ref/layouts.html, https://docs.qtile.org/en/latest/manual/config/index.html and https://docs.qtile.org/en/latest/manual/config/groups.html for more details (you need to set a layout object, not a string).

Thanks, that fixed it and I was able to fix my battery icon problem as well.  Now, to find a systray (that works in wayland) and to figure out how to properly set the XDG_CURRENT_ENVIRONMENT so flameshot gui and obs works.

**Comment by ervinpopescu** [comment]
> Now, to find a systray (that works in wayland) 

Well you can't really have the `Systray` functionality in Wayland, `StatusNotifier` widget is pretty barebones and even with [the tweaks from `qtile-extras` ](https://qtile-extras.readthedocs.io/en/latest/manual/ref/widgets.html#statusnotifier) (support for rendering context menus by right-clicking on the icon) I don't think it's on the same level. 

> how to properly set the XDG_CURRENT_ENVIRONMENT so flameshot gui and obs works

@jwijenbergh might be able to help a bit more with his knowledge here (if he wants to :)). Did you check https://github.com/qtile/qtile/discussions/3979?

**Comment by elParaguayo** [comment]
What's missing in StatusNotifier? We're trying to implement the spec.

**Comment by ervinpopescu** [comment]
Well it does look like I'm talking out of my butt here (and I am, since I haven't even looked at the new spec), but the new `StatusNotifierItem` spec is not yet adopted by the majority of apps (it's getting there, I think), so that's why I said it's not there yet. Do correct me if I'm wrong @elParaguayo. Sorry for the misunderstanding, lemme edit my comment.

**Comment by NeoFax75** [comment]
> > Now, to find a systray (that works in wayland)
> 
> Well you can't really have the `Systray` functionality in Wayland, `StatusNotifier` widget's spec [`StatusNotifierItem`](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/) is not adopted by most apps and even with [the tweaks from `qtile-extras` ](https://qtile-extras.readthedocs.io/en/latest/manual/ref/widgets.html#statusnotifier) (support for rendering context menus by right-clicking on the icon) I don't think it's on the same level (yet).
> 
> > how to properly set the XDG_CURRENT_ENVIRONMENT so flameshot gui and obs works
> 
> @jwijenbergh might be able to help a bit more with his knowledge here (if he wants to :)). Did you check #3979?

I am now using StatusNotifier, but when I click on my tray items the menu doesn't show.  I used the advice in 3979 previously, but for whatever reason flameshot still does not see qtile being set as the desktop.  I will just use a different screen capture software.

**Comment by elParaguayo** [comment]
Are you using StatusNotifier from qtile-extras? You won't get menus if you import the widget from qtile.

**Comment by NeoFax75** [comment]
I added this to my config:
```from qtile_extras.widget import StatusNotifier```
```widget.StatusNotifier(
                    icon_size=20,
                    background=theme["BG1"],
                    highlight_colour=theme["on"],
                    menu_background=theme["blue"],
                    **powerline
                ),```

**Comment by elParaguayo** [comment]
That's not using the qtile-extras as you're calling `widget.StatusNotifier`. The easiest thing to do is just `from qtile_extras import widget` and don't import `widget` from `libqtile`.
