### ISSUE TITLE
TaskList stretch=False errors out

### ISSUE THREAD

**Issue by rmcmilli** [qtile/qtile#4996]
### Issue description

I enabled `stretch = False` in `widget.TaskList()` and it mangles my bar errors the following

```
struct.error: 'H' format requires 0 <= number <= 65535
2024-09-10 14:47:40,897 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib64/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ronmcmilli/.local/lib/python3.12/site-packages/libqtile/core/manager.py", line 973, in f
    func(*args)
  File "/home/ronmcmilli/.local/lib/python3.12/site-packages/libqtile/bar.py", line 669, in _actual_draw
    i.draw()
  File "/home/ronmcmilli/.local/lib/python3.12/site-packages/libqtile/widget/tasklist.py", line 615, in draw
    self.drawer.draw(offsetx=self.offset, offsety=self.offsety, width=self.width)
  File "/home/ronmcmilli/.local/lib/python3.12/site-packages/libqtile/backend/base/drawer.py", line 224, in draw
    self._draw(
  File "/home/ronmcmilli/.local/lib/python3.12/site-packages/libqtile/backend/x11/drawer.py", line 194, in _draw
    self.qtile.core.conn.conn.core.CopyArea(
  File "/usr/lib/python3.12/site-packages/xcffib/xproto.py", line 3151, in CopyArea
    buf.write(struct.pack("=xx2xIIIhhhhHH", src_drawable, dst_drawable, gc, src_x, src_y, dst_x, dst_y, width, height))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Version

0.28.1.dev2+g34c6191e

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
Can you share your config so I can see if I can recreate this?

**Comment by rmcmilli** [comment]
Updated issue with config.

**Comment by rmcmilli** [comment]
I've tried removing all decorations and transparency, tried removing all widgets except for groupbox to no avail. 

My next try is to reorder the widgets, maybe it has something to do with the spacers and centered groupbox?

**Comment by tych0** [comment]
Interesting, it looks like either the length or heigh tis not getting set correctly on tasklist. Does this fix it?

```
~/packages/qtile/test master git diff
diff --git a/libqtile/widget/tasklist.py b/libqtile/widget/tasklist.py
index 650ec16b..cfeff76a 100644
--- a/libqtile/widget/tasklist.py
+++ b/libqtile/widget/tasklist.py
@@ -366,6 +366,7 @@ class TaskList(base._Widget, base.PaddingMixin, base.MarginMixin):

         if not self.stretch:
             self.length_type = libqtile.bar.CALCULATED
+            self.length = self.calculate_length()

         if not has_xdg and self.theme_mode is not None:
             logger.warning("You must install pyxdg to use theme icons.")
```

If you can figure out what values length and height are, that would be useful.

We do have a test for this (`test_tasklist_no_stretch`) and it is passing in CI, so you are clearly doing something more advanced, although it's unclear what.

**Comment by rmcmilli** [comment]
No change in behavior, log as follows, looks the same: 

```
struct.error: 'H' format requires 0 <= number <= 65535
2024-09-22 13:41:36,306 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib64/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ronmcmilli/.local/lib/python3.12/site-packages/libqtile/core/manager.py", line 973, in f
    func(*args)
  File "/home/ronmcmilli/.local/lib/python3.12/site-packages/libqtile/bar.py", line 669, in _actual_draw
    i.draw()
  File "/home/ronmcmilli/.local/lib/python3.12/site-packages/libqtile/widget/tasklist.py", line 617, in draw
    self.drawer.draw(offsetx=self.offset, offsety=self.offsety, width=self.width)
  File "/home/ronmcmilli/.local/lib/python3.12/site-packages/libqtile/backend/base/drawer.py", line 224, in draw
    self._draw(
  File "/home/ronmcmilli/.local/lib/python3.12/site-packages/libqtile/backend/x11/drawer.py", line 194, in _draw
    self.qtile.core.conn.conn.core.CopyArea(
  File "/usr/lib/python3.12/site-packages/xcffib/xproto.py", line 3151, in CopyArea
    buf.write(struct.pack("=xx2xIIIhhhhHH", src_drawable, dst_drawable, gc, src_x, src_y, dst_x, dst_y, width, height))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: 'H' format requires 0 <= number <= 65535

```

**Comment by tych0** [comment]
Thanks, can you get the values of `length` and `width` there?

**Comment by rmcmilli** [comment]
Sorry, I'm not sure how to do that. The height of my bar here is `30`

**Comment by rmcmilli** [comment]
Thanks to @elParaguayo for the tip!

```
❯ qtile cmd-obj -o widget tasklist -f eval -a self.length
(True, '1346')

qtile on  tasklist-test [$?] via 🐍 v3.12.6
❯ qtile cmd-obj -o widget tasklist -f eval -a self.width
(True, '1346')
```

**Comment by rmcmilli** [comment]
Okay so in the bugged state: 

```
❯ qtile cmd-obj -o widget tasklist -f eval -a self.length
(True, '-235')
```

**Comment by elParaguayo** [comment]
How on earth do you get a negative number?

Can you try `qtile cmd-obj -o widget tasklist -f eval -a self.calc_box_widths()` in the bugged state?

**Comment by rmcmilli** [comment]
Not sure :). 

Am I messing something up here?

```
qtile on  tasklist-test [$?] via 🐍 v3.12.6
❯ qtile cmd-obj -o widget tasklist -f eval -a self.width
(True, '-291')

qtile on  tasklist-test [$?] via 🐍 v3.12.6
❯ qtile cmd-obj -o widget tasklist -f eval -a self.calc_box_widths()
-bash: syntax error near unexpected token `('

qtile on  tasklist-test [$?] via 🐍 v3.12.6
❯ qtile cmd-obj -o widget tasklist -f eval -a self.calc_box_widths
(True,
 '<bound method TaskList.calc_box_widths of <libqtile.widget.tasklist.TaskList '
 'object at 0x7feb3a06fcb0>>')
```

**Comment by elParaguayo** [comment]
Try:  `qtile cmd-obj -o widget tasklist -f eval -a "self.calc_box_widths()"`

**Comment by rmcmilli** [comment]
Hrm: 

```

qtile on  tasklist-test [$?] via 🐍 v3.12.6
❯ qtile cmd-obj -o widget tasklist -f eval -a "self.calc_box_widths()"
(True, '<zip object at 0x7feb39f1af00>')
```

**Comment by elParaguayo** [comment]
Sigh... `qtile cmd-obj -o widget tasklist -f eval -a "list(self.calc_box_widths())"`

**Comment by rmcmilli** [comment]
Better

```

qtile on  tasklist-test [$?] via 🐍 v3.12.6
❯ qtile cmd-obj -o widget tasklist -f eval -a "list(self.calc_box_widths())"
(True,
 "[(Window(name='TaskList stretch=False errors out · Issue #4996 · qtile/qtile "
 "- Brave', wid=18874390), <cairocffi.patterns.SurfacePattern object at "
 "0x7feb39f50bc0>, 'TaskList stretch=False errors out · Issue #4996 · "
 "qtile/qtile - Brave', -141.0), (Window(name='config.py - qtile - Visual "
 "Studio Code', wid=56623108), <cairocffi.patterns.SurfacePattern object at "
 "0x7feb3a007860>, 'config.py - qtile - Visual Studio Code', -141.0), "
 "(Window(name='tasklist.py - git [Dev Container: RM-Network-Dev-Container] - "
 "Visual Studio Code', wid=56623110), <cairocffi.patterns.SurfacePattern "
 "object at 0x7feb3a50b170>, 'tasklist.py - git [Dev Container: "
 "RM-Network-Dev-Container] - Visual Studio Code', -141.0)]")
```

**Comment by elParaguayo** [comment]
Does it start ok and then get buggy when you open more windows?

**Comment by rmcmilli** [comment]
Actually, yeah. If I open a new group the bar looks fine but gets mangled once I open a window. I hadn't tried that.

**Comment by elParaguayo** [comment]
OK - will need to take a look later to see why we're getting negative values. Very odd indeed.

**Comment by rmcmilli** [comment]
Okay, happy to provide more information as needed.

**Comment by elParaguayo** [comment]
Have found the source of the problem. Will now look for the fix...

**Comment by rmcmilli** [comment]
Looks good!
