### ISSUE TITLE
CurrentLayoutIcons widget is broken.

### ISSUE THREAD

**Issue by misumisumi** [qtile/qtile#5015]
### Issue description

`CurrentLayoutIcons` widget breaks with a type error.

### Version

0.28.1

### Backend

X11 (default)

### Config

```python
...
    base += [
        widget.Volume(
            fmt=" {}",
            get_volume_command="if [ -z $(pactl get-sink-mute $(pactl get-default-sink) | sed -e 's/Mute: no//g') ]; then echo \[$(pactl get-sink-volume $(pactl get-default-sink) | awk -F'/' '{print $2}' | sed -e 's/\s//g')\]; else echo M; fi",
            mute_command=["pactl set-source-mute @DEFAULT_SOURCE@ toggle"],
            volume_up_command=["pactl set-sink-volume @DEFAULT_SINK@ +5%"],
            volume_down_command=["pactl set-sink-volume @DEFAULT_SINK@ -5%"],
            **fc,
            **left_corner,
        ),
        widget.CurrentLayoutIcon(),
    ]

...
```

### Logs

```text
2024-10-01 15:00:21,855 ERROR libqtile bar.py:_configure_widget():L391 CurrentLayoutIcon widget crashed during _configure with error:
Traceback (most recent call last):
  File "/nix/store/058nqi30dgdshwb936clbl4vcc92wxsa-python3.12-qtile-0.28.1/lib/python3.12/site-packages/libqtile/bar.py", line 382, in _configure_widget
    widget._configure(self.qtile, self)
  File "/nix/store/sbjgbbxpj815cinj85jmcp564way2fhw-python3.12-qtile-extras-0.28.1/lib/python3.12/site-packages/qtile_extras/widget/decorations.py", line 869, in new_configure
    self.old_configure(qtile, bar)
  File "/nix/store/058nqi30dgdshwb936clbl4vcc92wxsa-python3.12-qtile-0.28.1/lib/python3.12/site-packages/libqtile/widget/currentlayout.py", line 127, in _configure
    self._setup_images()
  File "/nix/store/sbjgbbxpj815cinj85jmcp564way2fhw-python3.12-qtile-extras-0.28.1/lib/python3.12/site-packages/qtile_extras/widget/currentlayout.py", line 63, in _setup_images
    LayoutIcon._setup_images(self)
  File "/nix/store/058nqi30dgdshwb936clbl4vcc92wxsa-python3.12-qtile-0.28.1/lib/python3.12/site-packages/libqtile/widget/currentlayout.py", line 217, in _setup_images
    for names in self._get_layout_names():
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/058nqi30dgdshwb936clbl4vcc92wxsa-python3.12-qtile-0.28.1/lib/python3.12/site-packages/libqtile/widget/currentlayout.py", line 187, in _get_layout_names
    return set((layout.name, layout.__class__.__name__.lower()) for layout in layouts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/058nqi30dgdshwb936clbl4vcc92wxsa-python3.12-qtile-0.28.1/lib/python3.12/site-packages/libqtile/widget/currentlayout.py", line 187, in <genexpr>
    return set((layout.name, layout.__class__.__name__.lower()) for layout in layouts)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not iterable
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by misumisumi** [comment]
There were some errors in my config.
I apologize for not noticing before posting.
The errors were:

1. In `config.py`, I was importing a module with the same name as the layouts variable: `from my_modules import layouts`. This was the direct cause of the issue above.

2. After fixing that, I encountered `struct.error: required argument is not an integer`, which seems to be the issue raised in #1291.

**Comment by saviola777** [comment]
If you still encounter issues with your config feel free to join our IRC/Discord. If you're willing to post your (full) config I'm sure we'll figure it out together.

**Comment by misumisumi** [comment]
It seems to work perfectly.
Thank you!
