### ISSUE TITLE
test: test failure for `test_net_wm_icon_change`

### ISSUE THREAD

**Issue by uncomfyhalomacro** [qtile/qtile#5091]
Hello there again Qtile team. I tried to update Qtile 0.29.0 in openSUSE. But one test failed named `test_net_wm_icon_change`.

Here are the logs.

[test_net_wm_icon_change-failed-test.log](https://github.com/user-attachments/files/17816820/test_net_wm_icon_change-failed-test.log)

Currently, I am skipping the test for now so that the next openSUSE Tumbleweed snapshot will get the latest version of Qtile. https://build.opensuse.org/package/show/X11:windowmanagers/qtile

**Comment by tych0** [comment]
Thanks for the report, full error message is:
```
[ 1321s]             try:
[ 1321s]                 return fn(*args, **kwargs)
[ 1321s]             except ignore_exceptions:
[ 1321s]                 pass
[ 1321s]             except AssertionError:
[ 1321s]                 break
[ 1321s]             time.sleep(dt)
[ 1321s]             dt *= 1.5
[ 1321s]         if self.return_on_fail:
[ 1321s]             return False
[ 1321s]         else:
[ 1321s] >           raise AssertionError(self.fail_msg)
[ 1321s] E           AssertionError: retry failed!
[ 1321s]
[ 1321s] test/helpers.py:72: AssertionError
[ 1321s] ----------------------------- Captured stdout call -----------------------------
[ 1321s] ^[[0m^[[31m2024-11-17 15:08:05,975 ^[[1m^[[31mlibqtile loop.py:_handle_exception():L62 ^[[0m Exception in event loop:
[ 1321s] Traceback (most recent call last):
[ 1321s]   File "/home/abuild/rpmbuild/BUILD/qtile-0.29.0/libqtile/resources/sleep.py", line 100, in _start
[ 1321s]     self.bus = await MessageBus(bus_type=BusType.SYSTEM, negotiate_unix_fd=True).connect()
[ 1321s]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ 1321s]   File "/usr/lib/python3.11/site-packages/dbus_next/aio/message_bus.py", line 122, in __init__
[ 1321s]     super().__init__(bus_address, bus_type, ProxyObject)
[ 1321s]   File "/usr/lib/python3.11/site-packages/dbus_next/message_bus.py", line 85, in __init__
[ 1321s]     self._setup_socket()
[ 1321s]   File "/usr/lib/python3.11/site-packages/dbus_next/message_bus.py", line 575, in _setup_socket
[ 1321s]     raise err
[ 1321s]   File "/usr/lib/python3.11/site-packages/dbus_next/message_bus.py", line 548, in _setup_socket
[ 1321s]     self._sock.connect(filename)
[ 1321s] FileNotFoundError: [Errno 2] No such file or directory^[[0m
[ 1321s] =========================== short test summary info ============================
```

Seems like we should skip this test in environments where dbus doesn't exist, given that it requires it?

**Comment by tych0** [comment]
Hmm, actually I don't understand why only *this* test failed... the functionality it's invoking seems unrelated. But it does seem like we shouldn't fail here... does https://github.com/qtile/qtile/commit/ea3f30b80c848659ba331c43d683125e588af095 fix it?
