### ISSUE TITLE
Running reload_config command from bash script consistently fails

### ISSUE THREAD

**Issue by theincompletedetective** [qtile/qtile#5121]
### Issue description

I use pywal, and have a `bash` script that changes the wallpaper, updates the Qtile configuration with the new colors, and reloads it. After the script tries to run `wal -i /path/to/wallpaper && qtile cmd-obj -o cmd -f reload_config`, I often (but not always) see the error message show below, and have to manually restart Qtile from a tty or already-open terminal. If I run `wal -i /path/to/wallpaper && qtile cmd-obj -o cmd -f reload_config` directly from the terminal, it works as expected.

### Version

0.29.1.dev0+geed1e03c.d20241021

### Backend

X11 (default)

### Config

```python
# This is the code that sets the config colors using pywal, which is contained within its own file
def get_colors():
    pywal_colors = []

    cache = f'{home}/.cache/wal/colors'

    with open(cache, 'r') as file:
        for _ in range(8):
            pywal_colors.append(file.readline().strip())
            
    return pywal_colors


colors = get_colors()
```

### Logs

```text
error: Sorry cannot run function 'reload_config' with arguments []: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/libqtile/command/interface.py", line 431, in call
    return SUCCESS, cmd(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 310, in reload_config
    self.load_config()
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 141, in load_config
    self._process_screens(reloading=not initial)
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 415, in _process_screens
    scr._configure(
  File "/usr/lib/python3.12/site-packages/libqtile/config.py", line 484, in _configure
    self.paint(self.wallpaper, self.wallpaper_mode)
  File "/usr/lib/python3.12/site-packages/libqtile/config.py", line 490, in paint
    self.qtile.paint_screen(self, path, mode)
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 456, in paint_screen
    self.core.painter.paint(screen, image_path, mode)
  File "/usr/lib/python3.12/site-packages/libqtile/backend/x11/xcbq.py", line 730, in paint
    root_pixmap, surface = self._get_root_pixmap_and_surface(screen)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/x11/xcbq.py", line 651, in _get_root_pixmap_and_surface
    root_pixmap = self.default_screen.root.get_property(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/x11/window.py", line 376, in get_property
    r = self.conn.conn.core.GetProperty(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/xcffib/xproto.py", line 2836, in GetProperty
    return self.send_request(20, buf, GetPropertyCookie, is_checked=is_checked)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/xcffib/__init__.py", line 389, in send_request
    seq = self.conn.send_request(flags, xcb_parts + 2, xcb_req)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/xcffib/__init__.py", line 577, in wrapper
    self.invalid()
  File "/usr/lib/python3.12/site-packages/xcffib/__init__.py", line 567, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
How is that bash script being triggered?

**Comment by theincompletedetective** [comment]
The script is currently on my `PATH`, and it's triggered with a keybinding: `Key([mod, control], w, lazy.spawn("wallpaper"), desc="Change wallpaper")`.
