### ISSUE TITLE
Unexpected keyword argument 'is_checked' at startup

### ISSUE THREAD

**Issue by Sbach** [qtile/qtile#551]
As an ArchLinux user, I installed qtile from Git. During startup I have the following error:
```
2014-12-01 16:59:01,587 ERROR make_qtile:123 Qtile crashed during startup
Traceback (most recent call last):
  File "/usr/bin/qtile", line 120, in make_qtile
    state=options.state,
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 155, in __init__
    self._process_screens()
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 283, in _process_screens
    self.groups[i],
  File "/usr/lib/python2.7/site-packages/libqtile/config.py", line 169, in _configure
    i._configure(qtile, self)
  File "/usr/lib/python2.7/site-packages/libqtile/bar.py", line 166, in _configure
    self.opacity
  File "/usr/lib/python2.7/site-packages/libqtile/window.py", line 593, in create
    i.place(x, y, width, height, 0, None)
  File "/usr/lib/python2.7/site-packages/libqtile/window.py", line 432, in place
    self.window.configure(**kwarg)
  File "/usr/lib/python2.7/site-packages/libqtile/xcbq.py", line 562, in configure
    return self.conn.conn.core.ConfigureWindowChecked(self.wid, mask, values).check()
TypeError: ConfigureWindow() got an unexpected keyword argument 'is_checked'
```

If we take a look at the test code of xcffib we have:
```
def CreateWindow(self, depth, wid, parent, x, y, width, height, border_width, _class, visual, value_mask, value_list, is_checked=False):
    [...]
    return self.send_request(1, buf, is_checked=is_checked)
```
and in libqtile/xcbq.py:
```
def ConfigureWindow(self, window, value_mask, value_list):
    [...]
    return self.send_request(12, buf) 
````
Adding 'is_checked' in xcbq.py to match xcffib fixes the problem.

Can anyone reproduce this problem ?

**Comment by tych0** [comment]
Closing this, as svig's patch was merged as e798eada47c3806c9cd7b5b9d8f522a3db0025f2.
