### ISSUE TITLE
uncontrolled window, qtile.log shouts

### ISSUE THREAD

**Issue by atommixz** [qtile/qtile#561]
Sometimes the window becomes not controlled. It can not be done float / unfloat, you can not change the order. Also it is shows in all groups. Found .qtile.log, who shouts.
In the last qtile update, terminal - Sakura window is bugs all time.

Config almost standard http://ix.io/16m/
.qtile.log (cut) http://ix.io/1F9

**Comment by zordsdavini** [comment]
problem still exist

**Comment by zordsdavini** [comment]
Qtile doesn't crash totally it just becomes unresponsible. My qtile log shows same thing:
```
2015-02-10 16:15:03,018 ERROR _xpoll:668 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/libqtile/manager.py", line 657, in _xpoll
    r = h(e)
  File "/usr/lib/python3.4/site-packages/libqtile/manager.py", line 1018, in handle_UnmapNotify
    self.unmanage(e.window)
  File "/usr/lib/python3.4/site-packages/libqtile/manager.py", line 482, in unmanage
    c.group.remove(c)
  File "/usr/lib/python3.4/site-packages/libqtile/group.py", line 215, in remove
    nextfocus = i.remove(win)
  File "/usr/lib/python3.4/site-packages/libqtile/layout/zoomy.py", line 61, in remove
    self.cmd_previous()
  File "/usr/lib/python3.4/site-packages/libqtile/layout/zoomy.py", line 138, in cmd_previous
    self.group.focus(client, False)
  File "/usr/lib/python3.4/site-packages/libqtile/group.py", line 161, in focus
    l.focus(win)
  File "/usr/lib/python3.4/site-packages/libqtile/layout/zoomy.py", line 118, in focus
    format=8
  File "/usr/lib/python3.4/site-packages/libqtile/xcbq.py", line 606, in set_property
    ).check()
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 305, in check
    self.conn.request_check(self.sequence)
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 517, in wrapper
    return f(*args)
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 610, in request_check
    self._process_error(err)
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 581, in _process_error
    raise error(buf)
xcffib.xproto.WindowError
2015-02-10 16:15:05,771 ERROR _xpoll:668 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/libqtile/manager.py", line 657, in _xpoll
    r = h(e)
  File "/usr/lib/python3.4/site-packages/libqtile/window.py", line 997, in handle_EnterNotify
    self.group.focus(self, False)
  File "/usr/lib/python3.4/site-packages/libqtile/group.py", line 161, in focus
    l.focus(win)
  File "/usr/lib/python3.4/site-packages/libqtile/layout/zoomy.py", line 118, in focus
    format=8
  File "/usr/lib/python3.4/site-packages/libqtile/xcbq.py", line 606, in set_property
    ).check()
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 305, in check
    self.conn.request_check(self.sequence)
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 517, in wrapper
    return f(*args)
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 610, in request_check
    self._process_error(err)
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 581, in _process_error
    raise error(buf)
xcffib.xproto.WindowError
```
