### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by metaswirl** [qtile/qtile#666]
Qtile crashes with "ConnectionException" when changing windows on a 3 screen setup.

Distribution: Archlinux
Qtile Version: "dev" directly from git, "2124.c793a3a-1-any"

```
2015-05-11 13:16:29,496 ERROR <lambda>:698 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/trollius/events.py", line 138, in _run
    self._callback(*self._args)
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 664, in _xpoll
    error_code = self.conn.conn.has_error()
  File "/usr/lib/python2.7/site-packages/xcffib/__init__.py", line 518, in wrapper
    self.invalid()
  File "/usr/lib/python2.7/site-packages/xcffib/__init__.py", line 508, in invalid
    raise ConnectionException(err)
ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2015-05-11 13:16:29,537 ERROR <lambda>:698 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/trollius/events.py", line 138, in _run
    self._callback(*self._args)
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 664, in _xpoll
    error_code = self.conn.conn.has_error()
  File "/usr/lib/python2.7/site-packages/xcffib/__init__.py", line 518, in wrapper
    self.invalid()
  File "/usr/lib/python2.7/site-packages/xcffib/__init__.py", line 508, in invalid
    raise ConnectionException(err)
ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
2015-05-11 13:16:29,567 ERROR <lambda>:698 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/trollius/events.py", line 138, in _run
    self._callback(*self._args)
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 1117, in f
    self.conn.flush()
  File "/usr/lib/python2.7/site-packages/libqtile/xcbq.py", line 902, in flush
    return self.conn.flush()
  File "/usr/lib/python2.7/site-packages/xcffib/__init__.py", line 518, in wrapper
    self.invalid()
  File "/usr/lib/python2.7/site-packages/xcffib/__init__.py", line 508, in invalid
    raise ConnectionException(err)
ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
 ```

**Comment by sammanthp007** [comment]
It probably means that you are lacking some dependencies. Have you installed all the requirements?

**Comment by flacjacket** [comment]
Hmm, does it work ok if you only use 2 monitors?
