### ISSUE TITLE
Got an exception in poll loop

### ISSUE THREAD

**Issue by arthur-yaal** [qtile/qtile#667]
Hi,

When opening a pdf attachment with zathura from thunderbird, I got an error in log and strange comportment in the UI.

```
2015-05-11 16:20:00,438 ERROR _xpoll:668 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/libqtile/manager.py", line 657, in _xpoll
    r = h(e)
  File "/usr/lib/python3.4/site-packages/libqtile/manager.py", line 999, in handle_MapRequest
    c = self.manage(w)
  File "/usr/lib/python3.4/site-packages/libqtile/manager.py", line 549, in manage
    self.currentScreen.group.add(c, focus=c.can_steal_focus())
  File "/usr/lib/python3.4/site-packages/libqtile/group.py", line 210, in add
    win.group = self
  File "/usr/lib/python3.4/site-packages/libqtile/window.py", line 713, in group
    self.qtile.groups.index(group)
  File "/usr/lib/python3.4/site-packages/libqtile/xcbq.py", line 637, in set_property
    value
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 306, in check
    self.conn.request_check(self.sequence)
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 520, in wrapper
    return f(*args)
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 627, in request_check
    self._process_error(err)
  File "/usr/lib/python3.4/site-packages/xcffib/__init__.py", line 598, in _process_error
    raise error(buf)
xcffib.xproto.WindowError
```

**Comment by flacjacket** [comment]
Hi, any chance you can xtrace this? http://qtile.readthedocs.org/en/latest/manual/hacking.html#capturing-an-xtrace

**Comment by arthur-yaal** [comment]
Oups, I didn't answer...
It is no longer a problem.
