### ISSUE TITLE
VerticalLayout: mix of float and int values

### ISSUE THREAD

**Issue by sbach** [qtile/qtile#675]
After trying to use the vertical layout for my new screen, I got the following error.
```
2015-06-10 05:45:01,319 ERROR layoutAll:158 Exception in layout vertical
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qtile-0.9.1-py3.4.egg/libqtile/group.py", line 155, in layoutAll
    self.layout.layout(normal, screen)
  File "/usr/lib/python3.4/site-packages/qtile-0.9.1-py3.4.egg/libqtile/layout/base.py", line 58, in layout
    self.configure(i, screen)
  File "/usr/lib/python3.4/site-packages/qtile-0.9.1-py3.4.egg/libqtile/layout/verticaltile.py", line 196, in configure
    border_color, margin=self.margin)
  File "/usr/lib/python3.4/site-packages/qtile-0.9.1-py3.4.egg/libqtile/window.py", line 442, in place
    self.window.configure(**kwarg)
  File "/usr/lib/python3.4/site-packages/qtile-0.9.1-py3.4.egg/libqtile/xcbq.py", line 572, in configure
    values = [i & 0xffffffff for i in values]
  File "/usr/lib/python3.4/site-packages/qtile-0.9.1-py3.4.egg/libqtile/xcbq.py", line 572, in <listcomp>
    values = [i & 0xffffffff for i in values]
TypeError: unsupported operand type(s) for &: 'float' and 'int'
```
After a quick look it looks like an int() conversion is needed at the following lines:
```
libqtile/layout/verticaltile.py:
168    sec_pane_height = sec_area_height / (n - 1) - border_width * 2
169    normal_pane_height = (screen.height / n) - (border_width * 2)
```
Can someone reproduce this?

Note: I am using the develop branch 6a473e5

**Comment by flacjacket** [comment]
Can you see if https://github.com/flacjacket/qtile/tree/fix_vertical_layout fixes this for you? In definitely looks like a bug, if you can't check it I will try to get a test up for it when I have time.

**Comment by sbach** [comment]
I checked it with some different values, the vertical layout works perfectly with the new division operation. Thanks!

**Comment by flacjacket** [comment]
Just pushed that change, thanks for the report!
