### ISSUE TITLE
After I update Arch qtile is refuse to start

### ISSUE THREAD

**Issue by vslinko** [qtile/qtile#681]
```
2015-06-22 15:27:15,291 WARNING init_log:93 Starting Qtile
2015-06-22 15:27:15,537 WARNING safe_import:49 Can't Import Widget: '.mpriswidget.Mpris', No module named 'dbus'
2015-06-22 15:27:15,538 WARNING safe_import:49 Can't Import Widget: '.mpris2widget.Mpris2', No module named 'dbus'
2015-06-22 15:27:15,538 WARNING safe_import:49 Can't Import Widget: '.mpdwidget.Mpd', No module named 'mpd'
2015-06-22 15:27:15,542 WARNING safe_import:49 Can't Import Widget: '.wlan.Wlan', No module named 'pythonwifi'
2015-06-22 15:27:15,543 WARNING safe_import:49 Can't Import Widget: '.google_calendar.GoogleCalendar', No module named 'httplib2'
2015-06-22 15:27:15,544 WARNING safe_import:49 Can't Import Widget: '.imapwidget.ImapWidget', No module named 'keyring'
2015-06-22 15:27:15,546 WARNING register:102 Registering update without any dbus connection existing
2015-06-22 15:27:15,602 ERROR make_qtile:124 Qtile crashed during startup
Traceback (most recent call last):
  File "/usr/sbin/qtile", line 121, in make_qtile
    state=options.state,
  File "/usr/lib/python3.4/site-packages/libqtile/manager.py", line 156, in __init__
    self._process_screens()
  File "/usr/lib/python3.4/site-packages/libqtile/manager.py", line 312, in _process_screens
    self.groups[i],
  File "/usr/lib/python3.4/site-packages/libqtile/config.py", line 196, in _configure
    i._configure(qtile, self)
  File "/usr/lib/python3.4/site-packages/libqtile/bar.py", line 173, in _configure
    self.height
  File "/usr/lib/python3.4/site-packages/libqtile/drawer.py", line 227, in __init__
    self.height,
  File "/usr/lib/python3.4/site-packages/cairocffi/xcb.py", line 37, in __init__
    p = cairo.cairo_xcb_surface_create(
  File "/usr/lib/python3.4/site-packages/cffi/api.py", line 629, in __getattr__
    make_accessor(name)
  File "/usr/lib/python3.4/site-packages/cffi/api.py", line 625, in make_accessor
    make_accessor_locked(name)
  File "/usr/lib/python3.4/site-packages/cffi/api.py", line 619, in make_accessor_locked
    raise AttributeError(name)
AttributeError: cairo_xcb_surface_create
```

**Comment by vslinko** [comment]
I don't know how to fix it.

**Comment by zordsdavini** [comment]
Please look at https://github.com/qtile/qtile/issues/680
Close this as duplicate

**Comment by vslinko** [comment]
Thank you
