### ISSUE TITLE
import error when installing with yaourt

### ISSUE THREAD

**Issue by andrewyoung1991** [qtile/qtile#683]
looks like the latest version of xcffib has changed the namespace for ffi

```python
Traceback (most recent call last):
  File "setup.py", line 146, in <module>
    **cffi_args
  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.4/site-packages/setuptools/dist.py", line 272, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__
    self.finalize_options()
  File "/usr/lib/python3.4/site-packages/setuptools/dist.py", line 327, in finalize_options
    ep.load()(self, ep.name, value)
  File "/usr/lib/python3.4/site-packages/cffi/setuptools_ext.py", line 154, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/usr/lib/python3.4/site-packages/cffi/setuptools_ext.py", line 48, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/usr/lib/python3.4/site-packages/cffi/setuptools_ext.py", line 24, in execfile
    exec(code, glob, glob)
  File "libqtile/ffi_build.py", line 25, in <module>
    from xcffib.ffi_build import ffi as xcffib_ffi
ImportError: No module named 'xcffib.ffi_build'
```

**Comment by andrewyoung1991** [comment]
_fixed_ by adding community-testing repository to my /etc/pacman.conf mirror list and re-running the install.
it would be good to add this to the docs!

**Comment by Roger** [comment]
qitle git packages should work now on arch.. stable ones won't until a new release of qtile

**Comment by flacjacket** [comment]
This looks fixed, please re-open if it's still an issue
