### ISSUE TITLE
When I startup, qtile is crashed.

### ISSUE THREAD

**Issue by himaaaatti** [qtile/qtile#687]
```
2015-06-29 10:30:24,889 qtile init_log:105  Starting Qtile
2015-06-29 10:30:25,117 qtile safe_import:49  Can't Import Widget: '.launchbar.LaunchBar', No module named xdg.IconTheme
2015-06-29 10:30:25,118 qtile safe_import:49  Can't Import Widget: '.mpdwidget.Mpd', No module named mpd
2015-06-29 10:30:25,120 qtile safe_import:49  Can't Import Widget: '.wlan.Wlan', No module named pythonwifi.iwlibs
2015-06-29 10:30:25,120 qtile safe_import:49  Can't Import Widget: '.google_calendar.GoogleCalendar', No module named httplib2
2015-06-29 10:30:25,121 qtile safe_import:49  Can't Import Widget: '.imapwidget.ImapWidget', No module named keyring
2015-06-29 10:30:25,127 qtile make_qtile:124  Qtile crashed during startup
Traceback (most recent call last):
  File "bin/qtile", line 121, in make_qtile
    state=options.state,
  File "/home/hima/src/qtile/bin/libqtile/manager.py", line 88, in __init__
    self.conn = xcbq.Connection(displayName)
  File "/home/hima/src/qtile/bin/libqtile/xcbq.py", line 793, in __init__
    self.cursors = Cursors(self)
  File "/home/hima/src/qtile/bin/libqtile/xcursors.py", line 100, in __init__
    self.xcursor = self._setup_xcursor_binding()
  File "/home/hima/src/qtile/bin/libqtile/xcursors.py", line 119, in _setup_xcursor_binding
    self._cursor_ctx)
TypeError: initializer for ctype 'xcb_connection_t *' must be a pointer to same type, not cdata 'xcb_connection_t *'
Traceback (most recent call last):
  File "bin/qtile", line 130, in <module>
    q = make_qtile()
  File "bin/qtile", line 121, in make_qtile
    state=options.state,
  File "/home/hima/src/qtile/bin/libqtile/manager.py", line 88, in __init__
    self.conn = xcbq.Connection(displayName)
  File "/home/hima/src/qtile/bin/libqtile/xcbq.py", line 793, in __init__
    self.cursors = Cursors(self)
  File "/home/hima/src/qtile/bin/libqtile/xcursors.py", line 100, in __init__
    self.xcursor = self._setup_xcursor_binding()
  File "/home/hima/src/qtile/bin/libqtile/xcursors.py", line 119, in _setup_xcursor_binding
    self._cursor_ctx)
TypeError: initializer for ctype 'xcb_connection_t *' must be a pointer to same type, not cdata 'xcb_connection_t *'
```

Error occurred in Arch Linux.
Please tell me how to fix.

**Comment by himaaaatti** [comment]
I'm sorry. I solved this problem.
When i did't install xcffib complete, Python printed above error message.

**Comment by jhaubrich** [comment]
This was a dependency version problem for me. Fixed it by downgrading xcffib, cffi, and cairocffi.
