### ISSUE TITLE
UnicodeEncodeError when launching kcolorchooser

### ISSUE THREAD

**Issue by aartur** [qtile/qtile#714]
I'm using latest QTile from develop branch, running on PyPy 2.6. When launching `kcolorchooser` program QTile becomes broken with the following error in logs:

```
2015-07-22 21:03:56,666 INFO fire:270 Internal event: window_name_change((), {})
2015-07-22 21:03:56,681 INFO fire:270 Internal event: float_change((), {})
2015-07-22 21:03:56,681 INFO fire:270 Internal event: setgroup((), {})
2015-07-22 21:03:56,682 INFO fire:270 Internal event: group_window_add((), {})
2015-07-22 21:03:56,683 ERROR _xpoll:736 Got an exception in poll loop
Traceback (most recent call last):
  File "/pyenv/qtile-pypy/site-packages/qtile-0.10.1-py2.7.egg/libqtile/manager.py", line 713, in _xpoll
    r = h(e)
  File "/pyenv/qtile-pypy/site-packages/qtile-0.10.1-py2.7.egg/libqtile/manager.py", line 1035, in handle_MapRequest
    c = self.manage(w)
  File "/pyenv/qtile-pypy/site-packages/qtile-0.10.1-py2.7.egg/libqtile/manager.py", line 605, in manage
    self.currentScreen.group.add(c, focus=c.can_steal_focus())
  File "/pyenv/qtile-pypy/site-packages/qtile-0.10.1-py2.7.egg/libqtile/group.py", line 270, in add
    self.focus(win, True)
  File "/pyenv/qtile-pypy/site-packages/qtile-0.10.1-py2.7.egg/libqtile/group.py", line 213, in focus
    self.currentWindow = win
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 20: ordinal not in range(128)

```

As a quick fix I applied the following to `libqtile/window.py`, although it's probably not a proper solution:

```
@@ -210,6 +210,7 @@
     def updateName(self):
         try:
             self.name = self.window.get_name()
+            self.name = self.name.encode('utf8')
         except (xcffib.xproto.WindowError, xcffib.xproto.AccessError):
             return
         hook.fire("window_name_change")

```

**Comment by flacjacket** [comment]
I wonder if this isn't related to #737... I'll see if I can't reproduce this later today

**Comment by ramnes** [comment]
Can't reproduce this with Qtile 0.10.7 and kcolorchooser v2.0.0, but I'm not running them under PyPy.

Is the bug still there for you @aartur?
