### ISSUE TITLE
restarting qtile sometimes leaves a "frozen" desktop

### ISSUE THREAD

**Issue by ff2000** [qtile/qtile#735]
I can see it updating (e.g. CPU-widget) but neither mouse-clicks go through to the windows nor do key-presses - it feels like frozen. I have to hit `<CTRL><Alt><Backspace>` to kill my X-session.
Here is the qtile.log after such an issue:

```
2015-08-04 08:31:19,026 ERROR fire:275 Error in hook startup
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/libqtile/hook.py", line 273, in fire
    i(*args, **kwargs)
  File "/home/franz/.config/qtile/config.py", line 268, in startup
    execute_once("fbsetbg /home/franz/artwork/wallpaper/current.jpg")
  File "/home/franz/.config/qtile/config.py", line 259, in execute_once
    if not is_running(process):
  File "/home/franz/.config/qtile/config.py", line 254, in is_running
    if re.search(process, x):
  File "/usr/lib64/python3.4/re.py", line 166, in search
    return _compile(pattern, flags).search(string)
TypeError: can't use a string pattern on a bytes-like object
2015-08-04 08:31:20,102 WARNING __init__:754 /usr/lib64/python3.4/subprocess.py:754: ResourceWarnin
  _cleanup()

2015-08-04 08:31:39,167 ERROR _xpoll:753 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/libqtile/manager.py", line 730, in _xpoll
    r = h(e)
  File "/usr/lib64/python3.4/site-packages/libqtile/manager.py", line 949, in handle_ButtonPress
    self.cmd_focus_by_click(e)
  File "/usr/lib64/python3.4/site-packages/libqtile/manager.py", line 924, in cmd_focus_by_click
    self.currentGroup.focus(self.windowMap.get(wnd), False)
  File "/usr/lib64/python3.4/site-packages/libqtile/group.py", line 221, in focus
    l.focus(win)
  File "/usr/lib64/python3.4/site-packages/libqtile/layout/xmonad.py", line 203, in focus
    self.focused = self.clients.index(client)
ValueError: Window(qtile/qtile - Vimperator) is not in list
```

This is with recent develop-branch on python-3.4.1.

**Comment by aniruddhkanojia** [comment]
Hi

It seems unclear to me as to why such a problem would arise. 
Can you briefly describe how to reproduce the bug.
Also if you could post your config file here, it might be of help.

**Comment by ff2000** [comment]
It is basically qtile-examples/arkchar.py with some added widgets (cpu-/memory-/network-graph, mpd, notify) some keybindings changed (e.g. Mod4+m set to window.toggle_maximize()) and some stuff in startup() got removed. But I think I got this already with the default_config.
I had running a maximized firefox on workspace 1 (I think there was a terminal in the background) + 2 terminals side by side on workspace 2. I hit Mod4+Shift+r to restart qtile and hit this issue.

**Comment by aniruddhkanojia** [comment]
Hi

I wasn't able to reproduce your bug on my machine.
I did what you did and it worked fine on my machine.

**Comment by flacjacket** [comment]
The first error is a Python 3 string/bytes error, I'm not sure if that has something to do with the freezing bug. I can look at that example and try to give you a change for it.

**Comment by Nebucatnetzer** [comment]
I was experiencing a similar problem.
It happened when I added all the layouts to my config to try them out.
With trial and error I found that Slice, Tile and Zoomy were causing my setup to crash.

I've attached a log file and my config.
I hope the log file is not too large, it's getting late here.
If you need a more focused log file I'll create it on a another day.
[qtile_config_and_log.zip](https://github.com/qtile/qtile/files/3366058/qtile_config_and_log.zip)
