### ISSUE TITLE
restart is broken?

### ISSUE THREAD

**Issue by tych0** [qtile/qtile#739]
on current develop with python3, when I do a restart qtile starts eating 100% CPU and gives me a bunch of this:

```
2015-08-08 12:46:32,712 ERROR <lambda>:264 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 673, in _read_ready
    keep_open = self._protocol.eof_received()
  File "/usr/local/lib/python3.4/dist-packages/qtile-0.10.1-py3.4.egg/libqtile/ipc.py", line 172, in eof_received
    req = self._unpack(self.data)
  File "/usr/local/lib/python3.4/dist-packages/qtile-0.10.1-py3.4.egg/libqtile/ipc.py", line 46, in _unpack
    assert len(data) >= HDRLEN
TypeError: object of type 'NoneType' has no len()
2015-08-08 12:46:32,712 ERROR <lambda>:264 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 673, in _read_ready
    keep_open = self._protocol.eof_received()
  File "/usr/local/lib/python3.4/dist-packages/qtile-0.10.1-py3.4.egg/libqtile/ipc.py", line 172, in eof_received
    req = self._unpack(self.data)
  File "/usr/local/lib/python3.4/dist-packages/qtile-0.10.1-py3.4.egg/libqtile/ipc.py", line 46, in _unpack
    assert len(data) >= HDRLEN
TypeError: object of type 'NoneType' has no len()
2015-08-08 12:46:32,713 ERROR <lambda>:264 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 673, in _read_ready
    keep_open = self._protocol.eof_received()
  File "/usr/local/lib/python3.4/dist-packages/qtile-0.10.1-py3.4.egg/libqtile/ipc.py", line 172, in eof_received
    req = self._unpack(self.data)
  File "/usr/local/lib/python3.4/dist-packages/qtile-0.10.1-py3.4.egg/libqtile/ipc.py", line 46, in _unpack
    assert len(data) >= HDRLEN
TypeError: object of type 'NoneType' has no len()
```

**Comment by flacjacket** [comment]
I'm running 3.4 and haven't seen this, is your qtile-examples config up to date?

@aniruddhkanojia any idea if this is layout related?

**Comment by tych0** [comment]
On Sat, Aug 08, 2015 at 10:18:57AM -0700, Sean Vig wrote:
> I'm running 3.4 and haven't seen this, is your qtile-examples config up to date?

It's not, but I'll PR it shortly if you want to test.

**Comment by tych0** [comment]
On Sat, Aug 08, 2015 at 10:18:57AM -0700, Sean Vig wrote:
> I'm running 3.4 and haven't seen this, is your qtile-examples config up to date?

Ok, I've just pushed my updated config. If you've not seen it, perhaps
it's something funky with my local install, I'll do some more digging.
I'm also on 3.4.

**Comment by flacjacket** [comment]
Thanks, I'll check if it trips for me too

**Comment by aniruddhkanojia** [comment]
I found the source of the bug .
Your slice layout('gimp') has a slice layout as a fallback which in turn has a stack as a fallback layout.
I didn't cater to this extreme case.

**Comment by tych0** [comment]
On Aug 8, 2015 1:52 PM, "Aniruddh Kanojia" <notifications@github.com> wrote:
>
> I found the source of the bug .
> Your slice layout('gimp') has a slice layout as a fallback which in turn
has a stack as a fallback layout.
> I didn't cater to this extreme case.

Ok, (thanks Sean for fixing this, I don't think it's all that extreme), but
can we have a more graceful failure mode? Locking up isn't very nice, it
would be better to emit a log message and refuse to restart.

**Comment by ff2000** [comment]
Tycho Andersen wrote:
> On Aug 8, 2015 1:52 PM, "Aniruddh Kanojia" <notifications@github.com> wrote:
> >
> > I found the source of the bug .
> > Your slice layout('gimp') has a slice layout as a fallback which in turn
> has a stack as a fallback layout.
> > I didn't cater to this extreme case.
> 
> Ok, (thanks Sean for fixing this, I don't think it's all that extreme), but
> can we have a more graceful failure mode? Locking up isn't very nice, it
> would be better to emit a log message and refuse to restart.

In such cases (errors) awesomeWM generates a stack trace, starts the default config
and pops up a notification with the stack trace. I think that is quite good, as the
user gets a usable envronment, can see what went wrong and immediately try to fix
it.

**Comment by flacjacket** [comment]
That's probably a good idea, I think if we can catch when serializing fails
and have a fallback, that should save us from this in the future.
@aniruddhkanojia do you think you can look into this? That would be a good
final part of your project

**Comment by aniruddhkanojia** [comment]
At present, on a failure qtile will restart without using the state.
Should I also switch to a `fallback` config.

**Comment by flacjacket** [comment]
Alright, it looks like #740 will fix that, now when state generation fails it will fallback to running without a previous state and emit something like:
```
2015-08-16 19:47:51,644 qtile cmd_restart:1322  Unpickleable objects present, proceeding without state
2015-08-16 19:47:51,645 qtile cmd_restart:1323  Can't pickle <function CairoContext.<locals>.show_layout at 0x7fa9e66cc9d8>: attribute lookup show_layout on libqtile.pangocffi failed
```
in the log
