### ISSUE TITLE
xcursors.py:_setup_xcursor_binding causing crash after startup

### ISSUE THREAD

**Issue by TPHRyan** [qtile/qtile#766]
Hello, please note that I am new to qtile, and unfamiliar with the codebase / the system libraries involved. I was planning on getting acquainted / contributing, but I can't do that until the development branch will actually work for me!

I am using Arch Linux. 
This issue is persistent using both Xephyr and a separate TTY. 
It does not show up using the 0.10.0-1 version of qtile found in the Arch AUR. I am told this is out of date by yaourt but am at this point not going to try updating unless you think it's a good idea.

Whenever I startup an instance of qtile, the default instance is shown for a brief instant, complete with xterm (using the Xephyr script). After this time, the session crashes with this error message:

    Can't Import Widget: '.mpdwidget.Mpd', No module named 'mpd'
    Can't Import Widget: '.wlan.Wlan', No module named 'pythonwifi'
    Can't Import Widget: '.google_calendar.GoogleCalendar', No module named 'httplib2'
    Can't Import Widget: '.imapwidget.ImapWidget', No module named 'keyring'
    2015-09-28 11:31:18,726 qtile init_log:107  Starting Qtile
    2015-09-28 11:31:18,735 qtile make_qtile:129  Qtile crashed during startup
    Traceback (most recent call last):
      File "/home/ryan/code/python/qtile/scripts/../bin/qtile", line 126, in make_qtile
        state=options.state,
      File "/home/ryan/code/python/qtile/bin/libqtile/manager.py", line 110, in __init__
        self.conn = xcbq.Connection(displayName)
      File "/home/ryan/code/python/qtile/bin/libqtile/xcbq.py", line 803, in __init__
        self.cursors = Cursors(self)
      File "/home/ryan/code/python/qtile/bin/libqtile/xcursors.py", line 100, in __init__
        self.xcursor = self._setup_xcursor_binding()
      File "/home/ryan/code/python/qtile/bin/libqtile/xcursors.py", line 122, in _setup_xcursor_binding
        self._cursor_ctx)
    TypeError: initializer for ctype 'xcb_connection_t *' appears indeed to be 'xcb_connection_t *', but the types are different (check that you are not e.g. mixing up different ffi instances)
    Traceback (most recent call last):
      File "/home/ryan/code/python/qtile/scripts/../bin/qtile", line 135, in <module>
        q = make_qtile()
      File "/home/ryan/code/python/qtile/scripts/../bin/qtile", line 126, in make_qtile
        state=options.state,
      File "/home/ryan/code/python/qtile/bin/libqtile/manager.py", line 110, in __init__
        self.conn = xcbq.Connection(displayName)
      File "/home/ryan/code/python/qtile/bin/libqtile/xcbq.py", line 803, in __init__
        self.cursors = Cursors(self)
      File "/home/ryan/code/python/qtile/bin/libqtile/xcursors.py", line 100, in __init__
        self.xcursor = self._setup_xcursor_binding()
      File "/home/ryan/code/python/qtile/bin/libqtile/xcursors.py", line 122, in _setup_xcursor_binding
        self._cursor_ctx)
    TypeError: initializer for ctype 'xcb_connection_t *' appears indeed to be 'xcb_connection_t *', but the types are different (check that you are not e.g. mixing up different ffi instances)
    xterm: fatal IO error 11 (Resource temporarily unavailable) or KillClient on X server ":1"

I made a brief attempt to fix this issue myself but didn't really get anywhere as I'm new to qtile and don't really know how these xcursor bindings are supposed to work normally. Googling the TypeError message didn't really get me anywhere.

I suppose at this point I'm just looking for suggestions, if this isn't actually a fault of qtile itself.

**Comment by flacjacket** [comment]
You may not have built the ffi modules for qtile. How did you install qtile? If you use the setup.py script, it should do it for you, but if you just copy qtile somewhere (which it looks like you might have done), you need to run the build script yourself. To do this, you can do `python ./libqtile/ffi_build.py` from the qtile directory.

**Comment by TPHRyan** [comment]
Thank you - dumb oversight on my part. It seems setup.py was not generating the _ffi files, I had to manually run ffi_build.py as you said.

Should setup.py have built it for me in all cases? I was just getting a warning (found after redirecting stdout) about no matching files found.

**Comment by flacjacket** [comment]
What setup.py command did you run? It should build the files when you do a `setup.py install`.

**Comment by flacjacket** [comment]
This seems closed, if you have any other questions, feel free to ask here or on the mailing list, if you continue to have problems with this, feel free to re-open
