### ISSUE TITLE
Key when changing window to another group after python 3.5 migration in archlinux

### ISSUE THREAD

**Issue by ThomasChiroux** [qtile/qtile#776]
After upgrading arch to last python (3.5.0) and upgrading qtile to lastest git (e71a127511c9b6bda5e6a3376a7606c9f110f839), I get traceback when moving a window to another group:

ex:

2015-10-06 16:53:47,205 ERROR handle_KeyPress:912 KB command error togroup: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/libqtile/command.py", line 94, in call
    return (SUCCESS, cmd(*args, **kwargs))
  File "/usr/lib/python3.5/site-packages/libqtile/window.py", line 1222, in cmd_togroup
    self.togroup(groupName)
  File "/usr/lib/python3.5/site-packages/libqtile/window.py", line 986, in togroup
    self.group.remove(self)
  File "/usr/lib/python3.5/site-packages/libqtile/group.py", line 283, in remove
    i.remove(win)
  File "/usr/lib/python3.5/site-packages/libqtile/layout/tree.py", line 358, in remove
    self._nodes[win.window.wid].remove()
KeyError: 10635015

**Comment by tych0** [comment]
On Tue, Oct 06, 2015 at 08:09:39AM -0700, Thomas Chiroux wrote:
> After upgrading arch to last python (3.5.0) and upgrading qtile to lastest git (e71a127511c9b6bda5e6a3376a7606c9f110f839), I get traceback when moving a window to another group:
> 
> ex:
> 
> 2015-10-06 16:53:47,205 ERROR handle_KeyPress:912 KB command error togroup: Traceback (most recent call last):
>   File "/usr/lib/python3.5/site-packages/libqtile/command.py", line 94, in call
>     return (SUCCESS, cmd(*args, **kwargs))
>   File "/usr/lib/python3.5/site-packages/libqtile/window.py", line 1222, in cmd_togroup
>     self.togroup(groupName)
>   File "/usr/lib/python3.5/site-packages/libqtile/window.py", line 986, in togroup
>     self.group.remove(self)
>   File "/usr/lib/python3.5/site-packages/libqtile/group.py", line 283, in remove
>     i.remove(win)
>   File "/usr/lib/python3.5/site-packages/libqtile/layout/tree.py", line 358, in remove
>     self._nodes[win.window.wid].remove()
> KeyError: 10635015

Is this reliably reproducible? Is the wid in qtile.windowMap?

**Comment by ThomasChiroux** [comment]
yes, i've just tested it on another machine, same behaviour.

Here is another example with the output of qtile.windowMap:

2015-10-06 17:15:04,895 ERROR handle_KeyPress:912 KB command error togroup: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/libqtile/command.py", line 94, in call
    return (SUCCESS, cmd(*args, **kwargs))
  File "/usr/lib/python3.5/site-packages/libqtile/window.py", line 1222, in cmd_togroup
    self.togroup(groupName)
  File "/usr/lib/python3.5/site-packages/libqtile/window.py", line 986, in togroup
    self.group.remove(self)
  File "/usr/lib/python3.5/site-packages/libqtile/group.py", line 283, in remove
    i.remove(win)
  File "/usr/lib/python3.5/site-packages/libqtile/layout/tree.py", line 358, in remove
    self._nodes[win.window.wid].remove()
KeyError: 12582967


{4194459: Internal('<no name>', 4194459),
 4194475: <libqtile.widget.systray.Systray object at 0x7f9732d58860>,
 8388697: Window('Firefox Update'),
 10485761: Window('Nouvel onglet â Chromium'),
 12582922: Window('tail -f .qtile.log'),
 12582967: Window('tchiroux@mbptch2: ~'),
 12582999: Window('tchiroux@mbptch2: ~'),
 12583069: Window('less')}

**Comment by flacjacket** [comment]
This looks like I might have missed some things in #765, it shouldn't be indexed by the wid.

**Comment by flacjacket** [comment]
I just pushed a change up that should fix this, let us know if this is still a problem. Thanks!

**Comment by ThomasChiroux** [comment]
Yes it corrected the problem. Thanks !
