### ISSUE TITLE
GroupBox 'line' highlighting issue with multimonitor

### ISSUE THREAD

**Issue by flacjacket** [qtile/qtile#790]
So running multiple monitors, `highlight_color` does not get a value for the other screen's label (I think), and the log will start dumping this:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib64/python3.4/site-packages/libqtile/manager.py", line 1156, in f
    func(*args)
  File "/usr/lib64/python3.4/site-packages/libqtile/bar.py", line 288, in _actual_draw
    i.draw()
  File "/usr/lib64/python3.4/site-packages/libqtile/widget/groupbox.py", line 318, in draw
    highlight_color,
UnboundLocalError: local variable 'highlight_color' referenced before assignment
```
@flix477 if you want to take a crack at this, you're welcome to, otherwise I can try to fix it.

**Comment by flix477** [comment]
I'd like to fix the bug but it's hard without being able to test possible solutions. Is there a way to emulate a multi-monitor setup with xephyr?

**Comment by flacjacket** [comment]
Yeah, should be something like `Xephyr :1 -screen WxH -origin W,0 -screen WxH`
