### ISSUE TITLE
Slice layout broken (fallback)

### ISSUE THREAD

**Issue by rxcomm** [qtile/qtile#845]
It looks like commit da7a28fc839ab5f6c6cd001fbc1a17a598e0d0d2 broke the slice layout fallback.
For this layout:

     border_args = dict(
         border_width=1,
         border_focus='#0000FF'
     )

    layouts = [
    layout.Max(),
    layout.Stack(num_stacks=2, **border_args),

    # a layout just for gimp
    layout.Slice('left', 192, name='gimp', role='gimp-toolbox',
         fallback=layout.Slice('right', 256, role='gimp-dock',
         fallback=layout.Stack(num_stacks=1, **border_args))),

    # a layout for pidgin
    layout.Slice('right', 256, name='pidgin', role='buddy_list',
         fallback=layout.Stack(num_stacks=1, **border_args)),

    layout.MonadTall(ratio=0.65, **border_args),
    ]

I get the following stacktrace:

     2016-01-08 16:34:23,621 WARNING init_log:107 Starting Qtile
     2016-01-08 16:34:23,621 ERROR make_qtile:109 Traceback (most recent call last):
       File "/usr/local/lib/python3.4/dist-packages/qtile-0.10.3-py3.4.egg/libqtile/confreader.py", line 54, in __init__
         config = __import__(os.path.basename(fname)[:-3])
       File "/home/k0rx/.config/qtile/config.py", line 215, in <module>
         fallback=layout.Stack(num_stacks=1, **border_args))),
     TypeError: __init__() takes 1 positional argument but 3 were given

     Error while reading config file
     Traceback (most recent call last):
       File "/usr/local/lib/python3.4/dist-packages/qtile-0.10.3-py3.4.egg/libqtile/confreader.py", line 54, in __init__
         config = __import__(os.path.basename(fname)[:-3])
       File "/home/k0rx/.config/qtile/config.py", line 215, in <module>
         fallback=layout.Stack(num_stacks=1, **border_args))),
     TypeError: __init__() takes 1 positional argument but 3 were given

     During handling of the above exception, another exception occurred:

     Traceback (most recent call last):
       File "/usr/local/lib/python3.4/dist-packages/qtile-0.10.3-py3.4.egg/EGG-INFO/scripts/qtile", line 106, in make_qtile
         c = confreader.File(options.configfile, is_restart=options.no_spawn)
       File "/usr/local/lib/python3.4/dist-packages/qtile-0.10.3-py3.4.egg/libqtile/confreader.py", line 70, in __init__
         raise ConfigError(tb)
     libqtile.confreader.ConfigError: Traceback (most recent call last):
       File "/usr/local/lib/python3.4/dist-packages/qtile-0.10.3-py3.4.egg/libqtile/confreader.py", line 54, in __init__
         config = __import__(os.path.basename(fname)[:-3])
       File "/home/k0rx/.config/qtile/config.py", line 215, in <module>
         fallback=layout.Stack(num_stacks=1, **border_args))),
     TypeError: __init__() takes 1 positional argument but 3 were given

Reverting that commit makes things work as they should.

**Comment by flacjacket** [comment]
It looks like it might just be that the Slice layout no longer takes positional arguments, and you need to adapt your configuration.

What if try adding the kwarg names to your config? e.g. change:
```
layout.Slice('left', 192, name='gimp', role='gimp-toolbox',
     fallback=layout.Slice('right', 256, role='gimp-dock',
     fallback=layout.Stack(num_stacks=1, **border_args))),
```
to
```
layout.Slice(side='left', width=192, name='gimp', role='gimp-toolbox',
     fallback=layout.Slice(side='right', width=256, role='gimp-dock',
     fallback=layout.Stack(num_stacks=1, **border_args))),
```

**Comment by rxcomm** [comment]
OK, this works. Thanks!

**Comment by flacjacket** [comment]
Great! Thanks for the report, I'll be sure to make a note of this in the release notes on our next release.
