### ISSUE TITLE
cannot import name 'asyncio'

### ISSUE THREAD

**Issue by DirkHeinke** [qtile/qtile#849]
Hi,

I updated my ArchLinux yesterday and today qtile does not longer start. Any idea which package update could break qtile?

```
2016-01-17 11:15:57,311 qtile init_log:107  Starting Qtile
2016-01-17 11:15:57,311 qtile make_qtile:109  cannot import name 'asyncio'

Error while reading config file
Traceback (most recent call last):
  File "/usr/bin/qtile", line 106, in make_qtile
    c = confreader.File(options.configfile, is_restart=options.no_spawn)
  File "/usr/lib/python3.5/site-packages/libqtile/confreader.py", line 47, in __init__
    from .resources import default_config
  File "/usr/lib/python3.5/site-packages/libqtile/resources/default_config.py", line 27, in <module>
    from libqtile.config import Key, Screen, Group, Drag, Click
  File "/usr/lib/python3.5/site-packages/libqtile/config.py", line 28, in <module>
    from . import command
  File "/usr/lib/python3.5/site-packages/libqtile/command.py", line 26, in <module>
    from . import ipc
  File "/usr/lib/python3.5/site-packages/libqtile/ipc.py", line 34, in <module>
    from six.moves import asyncio
ImportError: cannot import name 'asyncio'
Traceback (most recent call last):
  File "/usr/bin/qtile", line 135, in <module>
    q = make_qtile()
  File "/usr/bin/qtile", line 106, in make_qtile
    c = confreader.File(options.configfile, is_restart=options.no_spawn)
  File "/usr/lib/python3.5/site-packages/libqtile/confreader.py", line 47, in __init__
    from .resources import default_config
  File "/usr/lib/python3.5/site-packages/libqtile/resources/default_config.py", line 27, in <module>
    from libqtile.config import Key, Screen, Group, Drag, Click
  File "/usr/lib/python3.5/site-packages/libqtile/config.py", line 28, in <module>
    from . import command
  File "/usr/lib/python3.5/site-packages/libqtile/command.py", line 26, in <module>
    from . import ipc
  File "/usr/lib/python3.5/site-packages/libqtile/ipc.py", line 34, in <module>
    from six.moves import asyncio
ImportError: cannot import name 'asyncio'
```

```
[2016-01-16 12:28] [ALPM] upgraded sqlite (3.9.2-1 -> 3.10.0-1)
[2016-01-16 12:28] [ALPM] upgraded python2-setuptools (1:19.2-1 -> 1:19.3-2)
[2016-01-16 12:28] [ALPM] upgraded ansible (1.9.4-1 -> 2.0.0.1-1)
[2016-01-16 12:28] [ALPM] upgraded bluez-libs (5.37-1 -> 5.37-2)
[2016-01-16 12:28] [ALPM] upgraded cpupower (4.3-1 -> 4.4-1)
[2016-01-16 12:28] [ALPM] upgraded dcadec (0.1.0-3 -> 0.2.0-1)
[2016-01-16 12:28] [ALPM] upgraded libelf (0.164-2 -> 0.165-1)
[2016-01-16 12:28] [ALPM] upgraded device-mapper (2.02.137-1 -> 2.02.138-1)
[2016-01-16 12:28] [ALPM] upgraded dhcpcd (6.9.4-1 -> 6.10.0-1)
[2016-01-16 12:28] [ALPM] upgraded elfutils (0.164-2 -> 0.165-1)
[2016-01-16 12:28] [ALPM] upgraded gnutls (3.4.7-2 -> 3.4.8-1)
[2016-01-16 12:28] [ALPM] upgraded harfbuzz (1.1.2-3 -> 1.1.3-1)
[2016-01-16 12:28] [ALPM] upgraded libass (0.13.0-1 -> 0.13.1-1)
[2016-01-16 12:28] [ALPM] upgraded opus (1.1.1-1 -> 1.1.2-1)
[2016-01-16 12:28] [ALPM] upgraded mesa (11.1.0-2 -> 11.1.1-1)
[2016-01-16 12:28] [ALPM] upgraded mesa-libgl (11.1.0-2 -> 11.1.1-1)
[2016-01-16 12:28] [ALPM] upgraded ffmpeg (1:2.8.4-2 -> 1:2.8.4-4)
[2016-01-16 12:28] [ALPM] upgraded gtk-update-icon-cache (3.18.6-1 -> 3.18.6-2)
[2016-01-16 12:28] [ALPM] upgraded gtk3 (3.18.6-1 -> 3.18.6-2)
[2016-01-16 12:28] [ALPM] upgraded firefox (43.0.1-2 -> 43.0.4-1)
[2016-01-16 12:28] [ALPM] upgraded freerdp (1:1.2.0_beta1+android9-1 -> 1:1.2.0_20160107-2)
[2016-01-16 12:28] [ALPM] upgraded geoip-database (20151201-1 -> 20160105-1)
[2016-01-16 12:28] [ALPM] upgraded ghostscript (9.18-4 -> 9.18-6)
[2016-01-16 12:28] [ALPM] upgraded git (2.6.4-1 -> 2.7.0-1)
[2016-01-16 12:28] [ALPM] upgraded go (2:1.5.2-1 -> 2:1.5.3-1)
[2016-01-16 12:28] [ALPM] upgraded harfbuzz-icu (1.1.2-3 -> 1.1.3-1)
[2016-01-16 12:28] [ALPM] upgraded imagemagick (6.9.2.10-1 -> 6.9.3.0-1)
[2016-01-16 12:28] [ALPM] upgraded python-setuptools (1:19.2-1 -> 1:19.3-2)
[2016-01-16 12:28] [ALPM] upgraded ipython (4.0.0-4 -> 4.0.1-1)
[2016-01-16 12:28] [ALPM] upgraded jupyter (4.0.6-3 -> 4.0.6-4)
[2016-01-16 12:28] [ALPM] upgraded libxslt (1.1.28-3 -> 1.1.28-4)
[2016-01-16 12:28] [ALPM] upgraded kdelibs (4.14.15-2 -> 4.14.16-1)
[2016-01-16 12:28] [ALPM] upgraded lib32-mesa (11.1.0-1 -> 11.1.1-1)
[2016-01-16 12:28] [ALPM] upgraded lib32-mesa-libgl (11.1.0-1 -> 11.1.1-1)
[2016-01-16 12:28] [ALPM] upgraded lib32-pam (1.2.1-1 -> 1.2.1-2)
[2016-01-16 12:28] [ALPM] upgraded libbsd (0.8.0-1 -> 0.8.1-1)
[2016-01-16 12:28] [ALPM] upgraded libdvdcss (1.3.0-1 -> 1.4.0-1)
[2016-01-16 12:28] [ALPM] upgraded libebml (1.3.1-2 -> 1.3.3-2)
[2016-01-16 12:28] [ALPM] upgraded libevdev (1.4.5-1 -> 1.4.6-1)
[2016-01-16 12:28] [ALPM] upgraded libmatroska (1.4.2-2 -> 1.4.4-1)
[2016-01-16 12:28] [ALPM] upgraded libnm-glib (1.0.10-1 -> 1.0.10-2)
[2016-01-16 12:28] [ALPM] upgraded libwbclient (4.3.3-1 -> 4.3.4-1)
[2016-01-16 12:28] [ALPM] upgraded lvm2 (2.02.137-1 -> 2.02.138-1)
[2016-01-16 12:28] [ALPM] upgraded man-pages (4.03-1 -> 4.04-1)
[2016-01-16 12:28] [ALPM] upgraded mumble (1.2.12-1 -> 1.2.13-1)
[2016-01-16 12:28] [ALPM] upgraded nano (2.5.0-1 -> 2.5.1-1)
[2016-01-16 12:28] [ALPM] upgraded openssh (7.1p1-1 -> 7.1p2-1)
[2016-01-16 12:28] [ALPM] upgraded openttd-opengfx (0.5.3-1 -> 0.5.4-1)
[2016-01-16 12:28] [ALPM] upgraded oxygen-icons (1:5.17.0-1 -> 1:5.18.0-1)
[2016-01-16 12:28] [ALPM] warning: /etc/pacman.d/mirrorlist installed as /etc/pacman.d/mirrorlist.pacnew
[2016-01-16 12:28] [ALPM] upgraded pacman-mirrorlist (20151215-1 -> 20160110-1)
[2016-01-16 12:28] [ALPM] upgraded perl-uri (1.69-1 -> 1.71-1)
[2016-01-16 12:28] [ALPM] upgraded perl-lwp-protocol-https (6.06-1 -> 6.06-2)
[2016-01-16 12:28] [ALPM] upgraded wine (1.9.0-1 -> 1.9.1-1)
[2016-01-16 12:28] [ALPM] upgraded playonlinux (4.2.9-1 -> 4.2.10-1)
[2016-01-16 12:28] [ALPM] upgraded python-numpy (1.10.2-1 -> 1.10.4-1)
[2016-01-16 12:28] [ALPM] upgraded qt5-base (5.5.1-7 -> 5.5.1-8)
[2016-01-16 12:28] [ALPM] upgraded python-matplotlib (1.5.0-2 -> 1.5.1-1)
[2016-01-16 12:28] [ALPM] upgraded python2-numpy (1.10.2-1 -> 1.10.4-1)
[2016-01-16 12:28] [ALPM] upgraded qt5-xmlpatterns (5.5.1-7 -> 5.5.1-8)
[2016-01-16 12:28] [ALPM] upgraded qt5-declarative (5.5.1-7 -> 5.5.1-8)
[2016-01-16 12:28] [ALPM] upgraded qt5-location (5.5.1-7 -> 5.5.1-8)
[2016-01-16 12:28] [ALPM] upgraded qt5-sensors (5.5.1-7 -> 5.5.1-8)
[2016-01-16 12:28] [ALPM] upgraded qt5-svg (5.5.1-7 -> 5.5.1-8)
[2016-01-16 12:28] [ALPM] upgraded qt5-webchannel (5.5.1-7 -> 5.5.1-8)
[2016-01-16 12:28] [ALPM] upgraded qt5-webkit (5.5.1-7 -> 5.5.1-8)
[2016-01-16 12:28] [ALPM] upgraded qt5-translations (5.5.1-7 -> 5.5.1-8)
[2016-01-16 12:28] [ALPM] upgraded qt5-tools (5.5.1-7 -> 5.5.1-8)
[2016-01-16 12:28] [ALPM] upgraded qt5-x11extras (5.5.1-7 -> 5.5.1-8)
[2016-01-16 12:28] [ALPM] upgraded smbclient (4.3.3-1 -> 4.3.4-1)
[2016-01-16 12:28] [ALPM] upgraded thunderbird (38.5.0-1 -> 38.5.1-1)
[2016-01-16 12:28] [ALPM] upgraded vte-common (0.42.1-1 -> 0.42.1-2)
[2016-01-16 12:28] [ALPM] upgraded vte3 (0.42.1-1 -> 0.42.1-2)
[2016-01-16 12:28] [ALPM] upgraded vinagre (3.18.2-1 -> 3.19.2-1)
[2016-01-16 12:28] [ALPM] upgraded virt-install (1.3.1-2 -> 1.3.2-1)
[2016-01-16 12:28] [ALPM] upgraded virt-manager (1.3.1-2 -> 1.3.2-1)
[2016-01-16 12:28] [ALPM] upgraded xf86-input-evdev (2.10.0-3 -> 2.10.1-3)
[2016-01-16 12:28] [ALPM] upgraded xmobar (0.23.1-6 -> 0.23.1-7)
[2016-01-16 12:28] [ALPM] upgraded xorg-server-common (1.18.0-3 -> 1.18.0-4)
[2016-01-16 12:28] [ALPM] upgraded xorg-server (1.18.0-3 -> 1.18.0-4)
[2016-01-16 12:28] [ALPM] upgraded xorg-server-devel (1.18.0-3 -> 1.18.0-4)
[2016-01-16 12:28] [ALPM] upgraded zip (3.0-6 -> 3.0-7)
```

**Comment by tych0** [comment]
On Sun, Jan 17, 2016 at 02:20:50AM -0800, Dirk Heinke wrote:
> Hi,
> 
> I updated my ArchLinux yesterday and today qtile does not longer start Any idea which package update could break qtile?

:( maybe six.moves no longer allows direct assignment? Not sure. Does
this patch work for you?

https://github.com/tych0/qtile/commit/be74bf3f747c1ef132f50eb5d16c6bb492d0bbb2

**Comment by DirkHeinke** [comment]
Hi, yeah it works. Also found this: https://aur.archlinux.org/packages/qtile/
```
In case anyone else needs a fix, I managed to get qtile back by editing the two scripts ipc.py and manager.py under /usr/lib/python3.5/site-packages/libqtile/, commenting out 

# from six.moves import asyncio

and adding

import asyncio
```

**Comment by tych0** [comment]
On Sun, Jan 17, 2016 at 02:53:05AM -0800, Dirk Heinke wrote:
> Hi, yeah it works. Also found this: https://aur.archlinux.org/packages/qtile/

Cool, thanks. I have to run now, but I suspect that six.moves has
stopped letting other people write to its namespace (probably by
failing silently or some other impolite crap :). @flacjacket if you
have time to figure out what the real issue is before I get back, feel
free to disregard or cherry pick the above as necessary :)

**Comment by tych0** [comment]
On Sun, Jan 17, 2016 at 02:53:05AM -0800, Dirk Heinke wrote:
> Hi, yeah it works. Also found this: https://aur.archlinux.org/packages/qtile/
> ```
> In case anyone else needs a fix, I managed to get qtile back by editing the two scripts ipc.py and manager.py under /usr/lib/python3.5/site-packages/libqtile/, commenting out 
> 
> # from six.moves import asyncio
> 
> and adding
> 
> import asyncio
> ```

I guess the other option would be to just import asyncio directly and
drop support for 3.3; seems pretty easy to support it though, so it
seems reasonable to try and keep it.

**Comment by jhdulaney** [comment]
try:
    from six.moves import asyncio
except ImportError:
    import asyncio

**Comment by jhdulaney** [comment]
Well, that removed my tabbing, but it gets the idea.

**Comment by flacjacket** [comment]
What's odd is nothing Python or qtile related looks like it got updated for you. The current version of six is 3 months old, the Python package on Arch is a month old, the only package updated that seems relevant to us is setuptools. I do see Arch quickly bumped 1.19.3 to 1.19.4, I honestly don't know how setuptools would spoil us, but updating that is worth a shot.

**Comment by flacjacket** [comment]
Alright, I updated setuptools from 1.19.2 to 1.19.4 and it looks like that is the problem. It seems like moving 1.19.2 to 1.19.3 they started using six, but I'm still not sure how setuptools would interfere with us.

**Comment by flacjacket** [comment]
Alright, I can't figure out what setuptools is doing to us. @jhdulaney I'm not sure that will necessarily work, if Python 2 has this same problem, it would fail there since it can't `import asyncio`. I'll cherry pick the fix @tych0 posted.

**Comment by zordsdavini** [comment]
it would be great to have it in stable and bump version

**Comment by flacjacket** [comment]
@zordsdavini I can get a minor version bump out today

**Comment by zordsdavini** [comment]
It would be great
2016 Saus. 18 20:46 "Sean Vig" <notifications@github.com> rašė:

**Comment by flacjacket** [comment]
Done!
