### ISSUE TITLE
Bug in qsh

### ISSUE THREAD

**Issue by flacjacket** [qtile/qtile#861]
From voldial on IRC:

```
 $ qsh
> ?
No such command: 
> ls
layout/  widget/  screen/  bar/     window/  group/ 
> tree screen
No such command: tree
> ls screen
layout/  widget/  screen/  bar/     window/  group/ 
> cd screen
screen> ls
layout/  window/  bar/     0/     
screen> cd 0
screen[0]> ls
layout/  window/  bar/   
screen[0]> cd window
screen[0].window> ls
group/   screen/  layout/
screen[0].window> cd screen
screen[0].window.screen> ls
Traceback (most recent call last):
  File "/usr/bin/qsh", line 4, in <module>
    __import__('pkg_resources').run_script('qtile==0.10.4', 'qsh')
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib64/python3.4/site-packages/qtile-0.10.4-py3.4.egg/EGG-INFO/scripts/qsh", line 62, in <module>
    main()
  File "/usr/lib64/python3.4/site-packages/qtile-0.10.4-py3.4.egg/EGG-INFO/scripts/qsh", line 56, in main
    qsh.loop()
  File "/usr/lib64/python3.4/site-packages/qtile-0.10.4-py3.4.egg/libqtile/sh.py", line 299, in loop
    self.process_command(line)
  File "/usr/lib64/python3.4/site-packages/qtile-0.10.4-py3.4.egg/libqtile/sh.py", line 281, in process_command
    val = builtin(args)
  File "/usr/lib64/python3.4/site-packages/qtile-0.10.4-py3.4.egg/libqtile/sh.py", line 192, in do_ls
    l = self._ls(self.current)
  File "/usr/lib64/python3.4/site-packages/qtile-0.10.4-py3.4.egg/libqtile/sh.py", line 123, in _ls
    attrs, itms = self._inspect(obj)
  File "/usr/lib64/python3.4/site-packages/qtile-0.10.4-py3.4.egg/libqtile/sh.py", line 116, in _inspect
    t, itms = obj.parent.items(obj.name)
  File "/usr/lib64/python3.4/site-packages/qtile-0.10.4-py3.4.egg/libqtile/command.py", line 116, in __call__
    return self.call(self.selectors, self.name, *args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/qtile-0.10.4-py3.4.egg/libqtile/command.py", line 244, in call
    raise CommandError(val)
libqtile.command.CommandError: No object window in path 'screen[0].window'
```

a better traceback:

```
In [13]: qsh.process_command('ls')
---------------------------------------------------------------------------
CommandError                              Traceback (most recent call last)
<ipython-input-13-a41cfe6e1d75> in <module>()
----> 1 qsh.process_command('ls')

/usr/lib64/python3.4/site-packages/qtile-0.10.4-py3.4.egg/libqtile/sh.py in process_command(self, line)
    279         builtin = getattr(self, "do_" + cmd, None)
    280         if builtin:
--> 281             val = builtin(args)
    282         else:
    283             val = self._call(cmd, args)

/usr/lib64/python3.4/site-packages/qtile-0.10.4-py3.4.egg/libqtile/sh.py in do_ls(self, arg)
    190                 ls ../layout
    191         """
--> 192         l = self._ls(self.current)
    193         l = ["%s/" % i for i in l]
    194         return self.columnize(l)

/usr/lib64/python3.4/site-packages/qtile-0.10.4-py3.4.egg/libqtile/sh.py in _ls(self, obj)
    121 
    122     def _ls(self, obj):
--> 123         attrs, itms = self._inspect(obj)
    124         all = []
    125         if attrs:

/usr/lib64/python3.4/site-packages/qtile-0.10.4-py3.4.egg/libqtile/sh.py in _inspect(self, obj)
    114         """
    115         if obj.parent and obj.myselector is None:
--> 116             t, itms = obj.parent.items(obj.name)
    117             attrs = obj._contains if t else None
    118             return (attrs, itms)

/usr/lib64/python3.4/site-packages/qtile-0.10.4-py3.4.egg/libqtile/command.py in __call__(self, *args, **kwargs)
    114 
    115     def __call__(self, *args, **kwargs):
--> 116         return self.call(self.selectors, self.name, *args, **kwargs)
    117 
    118 

/usr/lib64/python3.4/site-packages/qtile-0.10.4-py3.4.egg/libqtile/command.py in call(self, selectors, name, *args, **kwargs)
    242             return val
    243         elif state == ERROR:
--> 244             raise CommandError(val)
    245         else:
    246             raise CommandException(val)

CommandError: No object window in path 'screen[0].window'
```

**Comment by AlexTalker** [comment]
Seems not reproducible on `master` or `develop` branches, why this issue still opened?
