### ISSUE TITLE
traceback when dealing with floating

### ISSUE THREAD

**Issue by tych0** [qtile/qtile#893]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/qtile-0.10.5-py3.5.egg/libqtile/command.py", line 469, in cmd_function
    function(self, *args, **kwargs)
  File "/home/tycho/.qtile/config.py", line 106, in f
    qtile.groupMap[group].cmd_toscreen()
  File "/usr/local/lib/python3.5/dist-packages/qtile-0.10.5-py3.5.egg/libqtile/group.py", line 376, in cmd_toscreen
    screen.setGroup(self)
  File "/usr/local/lib/python3.5/dist-packages/qtile-0.10.5-py3.5.egg/libqtile/config.py", line 334, in setGroup
    new_group._setScreen(self)
  File "/usr/local/lib/python3.5/dist-packages/qtile-0.10.5-py3.5.egg/libqtile/group.py", line 174, in _setScreen
    self.floating_layout.to_screen(self, self.screen)
  File "/usr/local/lib/python3.5/dist-packages/qtile-0.10.5-py3.5.egg/libqtile/layout/floating.py", line 110, in to_screen
    new_x = new_screen.x + win.float_x
  File "/usr/local/lib/python3.5/dist-packages/qtile-0.10.5-py3.5.egg/libqtile/window.py", line 147, in getter
    raise AttributeError("Floating not yet configured yet")
AttributeError: Floating not yet configured yet
```

My config is some mods on the one seen here: https://github.com/qtile/qtile-examples/blob/master/tych0/config.py

I haven't looked at this very closely, but basically it seems like what's happening is that it doesn't like  switching to groups which have floating windows on them that haven't been drawn before.

**Comment by flacjacket** [comment]
Yep, I can confirm the same thing. I could have sworn I tried this, but maybe not after the second floating patch.

**Comment by Roger** [comment]
I have this issue when the floating window starts on a hidden group

**Comment by flacjacket** [comment]
I think I was able to fix this, at least it works for me now

**Comment by tjarvstrand** [comment]
When starting up, I get the below:
```
2016-04-02 13:17:31,000 ERROR libqtile manager.py:__init__():L226 failed restoring state
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libqtile/manager.py", line 224, in __init__
    st.apply(self)
  File "/usr/local/lib/python2.7/dist-packages/libqtile/state.py", line 57, in apply
    qtile.screens[screen].setGroup(group)
  File "/usr/local/lib/python2.7/dist-packages/libqtile/config.py", line 334, in setGroup
    new_group._setScreen(self)
  File "/usr/local/lib/python2.7/dist-packages/libqtile/group.py", line 174, in _setScreen
    self.floating_layout.to_screen(self, self.screen)
  File "/usr/local/lib/python2.7/dist-packages/libqtile/layout/floating.py", line 110, in to_screen
    new_x = new_screen.x + win.float_x
  File "/usr/local/lib/python2.7/dist-packages/libqtile/window.py", line 147, in getter
    raise AttributeError("Floating not yet configured yet")
AttributeError: Floating not yet configured yet
```

**Comment by tjarvstrand** [comment]
Nevermind, it seems to work now. Not sure what fixed it.
