### ISSUE TITLE
Notifications  widget does  not work

### ISSUE THREAD

**Issue by tollerm** [qtile/qtile#904]
Notification widget does not show notifications. Log file is filled with the following messages, which started to appear 2 weeks ago:

```
2016-04-13 16:13:23,852 ERROR libqtile notify.py:service():L94 Dbus connection failed
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qtile-0.10.5-py3.5.egg/libqtile/notify.py", line 92, in service
    self._service = NotificationService(self)
  File "/usr/lib/python3.5/site-packages/qtile-0.10.5-py3.5.egg/libqtile/notify.py", line 45, in __init__
    service.Object.__init__(self, bus_name, SERVICE_PATH)
  File "/usr/lib/python3.5/site-packages/dbus/service.py", line 485, in __init__
    self.add_to_connection(conn, object_path)
  File "/usr/lib/python3.5/site-packages/dbus/service.py", line 576, in add_to_connection
    self._fallback)
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
2016-04-13 16:13:23,853 WARNING libqtile notify.py:register():L102 Registering update without any dbus connection existing
```

Best regards,
Toller

**Comment by flacjacket** [comment]
So it looks like dbus-python has received 2 update since February, which are the only updates in almost 3 year. What version of dbus-python are you using?

**Comment by tollerm** [comment]
I am using ver. 1.2.4 of dbus-python

**Comment by flacjacket** [comment]
@tollerm see if you can fix your problem by doing this: https://github.com/qtile/qtile/issues/813#issuecomment-210001200

**Comment by tollerm** [comment]
It seems that the problems are not related. DBUS_SESSION_BUS_ADDRESS is set correctly on my system. Furthermore, for testing purposes I've installed dunst and it catch notifications without any problem

**Comment by dvzrv** [comment]
Running into the same error here.
It seems the way qtile is registering with dbus is somehow not right.

Searching along, I found these two links, that might hold some useful information.
https://stackoverflow.com/questions/34482691/register-a-hello-world-dbus-service-object-and-method-using-python
https://lists.freedesktop.org/archives/dbus/2013-March/015513.html

**Comment by flacjacket** [comment]
Well, we run `DBusGMainLoop(set_as_default=True)`, which should setup the main loop correctly. But maybe try https://github.com/flacjacket/qtile/tree/dbus_fix

**Comment by andering** [comment]
@dvzrv any progress or way i can simulate it ?

**Comment by rocha** [comment]
I tried @flacjacket patch and it worked flawlessly. Thanks @flacjacket!

**Comment by flacjacket** [comment]
@rocha Thanks for the update, I pushed that commit for the fix, @tollerm let us know if this is still a problem on your end

**Comment by tollerm** [comment]
yes, it solved my problems as well. Thanks.
T.

**Comment by dvzrv** [comment]
Sorry to jump on the sailed ship here, but it still doesn't work for me!

I'm on Arch Linux:
qtile 0.10.7
python-dbus 1.2.4

```
2017-04-12 11:15:46,540 ERROR libqtile notify.py:service():L94 Dbus connection failed
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/libqtile/notify.py", line 92, in service
    self._service = NotificationService(self, dbus_loop)
  File "/usr/lib/python3.6/site-packages/libqtile/notify.py", line 45, in __init__
    service.Object.__init__(self, bus_name, SERVICE_PATH)
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 485, in __init__
    self.add_to_connection(conn, object_path)
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 576, in add_to_connection
    self._fallback)
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
2017-04-12 11:15:46,541 WARNING libqtile notify.py:register():L102 Registering update without any dbus connection existing
2017-04-12 11:15:46,543 ERROR libqtile notify.py:service():L94 Dbus connection failed
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/libqtile/notify.py", line 92, in service
    self._service = NotificationService(self, dbus_loop)
  File "/usr/lib/python3.6/site-packages/libqtile/notify.py", line 45, in __init__
    service.Object.__init__(self, bus_name, SERVICE_PATH)
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 485, in __init__
    self.add_to_connection(conn, object_path)
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 576, in add_to_connection
    self._fallback)
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
2017-04-12 11:15:46,544 WARNING libqtile notify.py:register():L102 Registering update without any dbus connection existing

```
I see this every time I try to setup an external monitor, which then fails and leaves qtile completely deranged, as only the window of the internal monitor (Lenovo x220 here) is shown correctly (sort of) on the external monitor, but within a frame and the rest is broken (also a qtile restart doesn't fix this).
I'll create a new bug report for that though.

My `$DBUS_SESSION_BUS_ADDRESS` is exported to

`unix:path=/run/user/1000/bus
`

@flacjacket the fix is committed before 0.10.7, right?

I'm just wondering, what is wrong here and I can't seem to figure it out correctly

**Comment by flacjacket** [comment]
Yes, this should be in 0.10.7, that is odd since we do set `mainloop=` as noted in that error message.

Is this only when you have an external monitor? If you start qtile with just an internal monitor, is it fine?

**Comment by rocha** [comment]
Here is what ended up working for me: https://github.com/qtile/qtile/compare/develop...rocha:notify

I am not sure why this works. I simply followed other examples of `pydbus` usage.

**Comment by dvzrv** [comment]
@flacjacket nope this happens when starting only with the internal screen:

```
2017-04-18 14:03:10,056 WARNING libqtile log_utils.py:init_log():L118 Starting logging for Qtile
2017-04-18 14:03:10,641 ERROR libqtile notify.py:service():L94 Dbus connection failed
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/libqtile/notify.py", line 92, in service
    self._service = NotificationService(self, dbus_loop)
  File "/usr/lib/python3.6/site-packages/libqtile/notify.py", line 45, in __init__
    service.Object.__init__(self, bus_name, SERVICE_PATH)
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 485, in __init__
    self.add_to_connection(conn, object_path)
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 576, in add_to_connection
    self._fallback)
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
2017-04-18 14:03:10,644 WARNING libqtile notify.py:register():L102 Registering update without any dbus connection existing
2017-04-18 14:03:10,645 ERROR libqtile notify.py:service():L94 Dbus connection failed
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/libqtile/notify.py", line 92, in service
    self._service = NotificationService(self, dbus_loop)
  File "/usr/lib/python3.6/site-packages/libqtile/notify.py", line 45, in __init__
    service.Object.__init__(self, bus_name, SERVICE_PATH)
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 485, in __init__
    self.add_to_connection(conn, object_path)
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 576, in add_to_connection
    self._fallback)
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
2017-04-18 14:03:10,646 WARNING libqtile notify.py:register():L102 Registering update without any dbus connection existing
2017-04-18 14:03:10,698 WARNING libqtile manager.py:cmd_warning():L1193 Switching to WARNING threshold

```

**Comment by dvzrv** [comment]
@rocha is that a change, that can/should be committed to this repo?

**Comment by rocha** [comment]
@dvzrv I am not sure if it works for anyone else. Also my understanding of DBus is pretty poor to know why this works. However, I can make a pull request if it fixes the problem for different people.

**Comment by pauldub** [comment]
I recently started having this issue, I'm not sure why but @rocha patch fixed it.

**Comment by flacjacket** [comment]
I've pushed @rocha's fix to the develop branch, thanks for that! If any new problems come up, please comment.
