### ISSUE TITLE
Cannot set initial layout for Group

### ISSUE THREAD

**Issue by emesik** [qtile/qtile#971]
I have config file where `Group` gets a layout assigned on the start:

```
g = Group('a', layout='VerticalTile')
groups.append(g)
```

qtile crashes on start with exception:

```
Traceback (most recent call last):
  File "/usr/bin/qtile", line 9, in <module>
    load_entry_point('qtile==0.10.6', 'console_scripts', 'qtile')()
  File "/usr/lib/python2.7/site-packages/libqtile/scripts/qtile.py", line 125, in main
    q = make_qtile()
  File "/usr/lib/python2.7/site-packages/libqtile/scripts/qtile.py", line 116, in make_qtile
    state=options.state,
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 160, in __init__
    self.dgroups = DGroups(self, self.config.groups, key_binder)
  File "/usr/lib/python2.7/site-packages/libqtile/dgroups.py", line 94, in __init__
    self._setup_groups()
  File "/usr/lib/python2.7/site-packages/libqtile/dgroups.py", line 127, in _setup_groups
    self.add_dgroup(group, group.init)
  File "/usr/lib/python2.7/site-packages/libqtile/dgroups.py", line 123, in add_dgroup
    self.qtile.addGroup(group.name, group.layout, group.layouts)
  File "/usr/lib/python2.7/site-packages/libqtile/manager.py", line 466, in addGroup
    g._configure(layouts, self.config.floating_layout, self)
  File "/usr/lib/python2.7/site-packages/libqtile/group.py", line 71, in _configure
    self.layout = self.customLayout
  File "/usr/lib/python2.7/site-packages/libqtile/group.py", line 124, in layout
    raise ValueError("No such layout: %s" % layout)
ValueError: No such layout: VerticalTile
```

The same happens when I use `xmonad-tall` or any other layout name.

BTW, perhaps it would be better to pass a `Layout` object here than a name which is hard to find anywhere in the docs.

**Comment by and3rson** [comment]
@emesik You can still check out the source of `VerticalTile` and use the `name` attribute of the class. Another way to do this is to set custom name for a layout in `layouts=[]` definition and use it in your group config.

**Comment by dhannes** [comment]
The default name of layouts is always the class name in lower case.
see:  qtile/libqtile/layout/base.py (Layout.__init__, line 44ff)

You need to either specify a name for the Layout or use the class name in lower case.

By the way, it is possible to pass Layout objects to a Group, by using the `layouts` argument to specify a list of layouts for a group, instead of using the `layout` argument to specify the name of default layout.
`Group( 'a', layouts=[layout.VerticalTile()] )` 
Thus you get a Group with a single layout, which is -by definition- the default.

I add PR #1042 for a minor docu upgrade and suggest to close this issue.
