### ISSUE TITLE
Qtile crashed after installing python 3.6

### ISSUE THREAD

**Issue by zordsdavini** [qtile/qtile#994]
Sadly I never learn lesson not to be quick with updates :( 

> 2017-01-06 13:05:31,930 libqtile qtile.py:make_qtile():L119  Qtile crashed during startup Traceback (most recent call last):
>   File "/home/arnas/Skleps/qtile/libqtile/scripts/qtile.py", line 116, in make_qtiled
>     state=options.state,
>   File "/home/arnas/Skleps/qtile/libqtile/manager.py", line 175, in __init__
>     self._process_screens()
>   File "/home/arnas/Skleps/qtile/libqtile/manager.py", line 383, in _process_screens
>     self.groups[i],
>   File "/home/arnas/Skleps/qtile/libqtile/config.py", line 268, in _configure
>     i._configure(qtile, self)
>   File "/home/arnas/Skleps/qtile/libqtile/bar.py", line 193, in _configure
>     self.height
>   File "/home/arnas/Skleps/qtile/libqtile/drawer.py", line 244, in __init__
>     self.height,
>   File "/usr/lib/python3.6/site-packages/cairocffi/xcb.py", line 37, in __init__
>     p = cairo.cairo_xcb_surface_create(
> AttributeError: cffi library 'libcairo.so.2' has no function, constant or global variable named 'cairo_xcb_surface_create'
> Traceback (most recent call last):
>   File "/home/arnas/Skleps/qtile/scripts/../bin/qtile", line 33, in <module>
>     qtile.main()
>   File "/home/arnas/Skleps/qtile/libqtile/scripts/qtile.py", line 125, in main
>     q = make_qtile()
>   File "/home/arnas/Skleps/qtile/libqtile/scripts/qtile.py", line 116, in make_qtile
>     state=options.state,
>   File "/home/arnas/Skleps/qtile/libqtile/manager.py", line 175, in __init__
>     self._process_screens()
>   File "/home/arnas/Skleps/qtile/libqtile/manager.py", line 383, in _process_screens
>     self.groups[i],
>   File "/home/arnas/Skleps/qtile/libqtile/config.py", line 268, in _configure
>     i._configure(qtile, self)
>   File "/home/arnas/Skleps/qtile/libqtile/bar.py", line 193, in _configure
>     self.height
>   File "/home/arnas/Skleps/qtile/libqtile/drawer.py", line 244, in __init__
>     self.height,
>   File "/usr/lib/python3.6/site-packages/cairocffi/xcb.py", line 37, in __init__
>     p = cairo.cairo_xcb_surface_create(
> AttributeError: cffi library 'libcairo.so.2' has no function, constant or global variable named 'cairo_xcb_surface_create'

**Comment by ramnes** [comment]
It doesn't seem related to Python 3.6 to me, but rather to an incompatible version of libcairo. What OS are you using, and what's libcairo version?

**Comment by zordsdavini** [comment]
I tried python2 - it doesn't work, too. 
Archlinux:
- cairo 1.14.8-1
- python-cairo 1.10.0-7
- python-cairocffi 0.7.2-3

**Comment by zordsdavini** [comment]
python-cairo 1.10.0-7 was today updated

**Comment by zordsdavini** [comment]
I don't want to build qtile but I trying to add all information (during reinstalling):
==> Running setup.py
running install

It looks like your cairocffi was not built with xcffib support.  To fix this:
  - Ensure a recent xcffib is installed (pip install 'xcffib>=0.3.2')
  - The pip cache is cleared (remove ~/.cache/pip, if it exists)
  - Reinstall cairocffi, either:
      pip install --no-deps --ignore-installed cairocffi
    or
      pip uninstall cairocffi && pip install cairocffi

**Comment by ramnes** [comment]
Just got hit by this error while trying to run the tests in a virtualenv. I'm not sure why it happens, but a hack is to run `pip install -I --no-cache-dir pycairo -r requirements.txt`: we don't use pycairo anymore but as far as I understand, it bundles a proper version of cairo and makes everything work.

**Comment by ramnes** [comment]
Better explanation now:
- [ cairocffi needs to be installed **after** xcffib](https://github.com/Kozea/cairocffi/issues/100)
- [pip doesn't care in which order it install packages](https://github.com/pypa/pip/issues/4182)
- you can try `pip install cairocffi[xcb]` to make sure that cairocffi pulls xcffib, but still, pip will install cairocffi first (there is no such thing as conditional `install_requires` based on `extras_requires`)
- thus, the solution is to sequentially install xcffib, then cairocffi, ensuring that no cache is used when cairocffi is built (`pip install --no-cache-dir cairocffi`)

What a mess. :tada:
